"""
Constants for Offer Routing System
"""

# Cache keys
CACHE_PREFIX = 'offer_routing'
ROUTING_CACHE_KEY = f'{CACHE_PREFIX}:routing:{{user_id}}:{{context_hash}}'
SCORE_CACHE_KEY = f'{CACHE_PREFIX}:score:{{offer_id}}:{{user_id}}'
ROUTE_CACHE_KEY = f'{CACHE_PREFIX}:route:{{route_id}}:{{user_id}}'
CAP_CACHE_KEY = f'{CACHE_PREFIX}:cap:{{offer_id}}:{{user_id}}'
AFFINITY_CACHE_KEY = f'{CACHE_PREFIX}:affinity:{{user_id}}:{{category}}'

# Cache timeouts (in seconds)
ROUTING_CACHE_TIMEOUT = 300  # 5 minutes
SCORE_CACHE_TIMEOUT = 1800  # 30 minutes
ROUTE_CACHE_TIMEOUT = 3600  # 1 hour
CAP_CACHE_TIMEOUT = 86400  # 24 hours
AFFINITY_CACHE_TIMEOUT = 7200  # 2 hours

# Routing performance targets
MAX_ROUTING_TIME_MS = 50
MAX_CONDITION_EVAL_TIME_MS = 10
MAX_SCORING_TIME_MS = 20
MAX_RANKING_TIME_MS = 15
MAX_PERSONALIZATION_TIME_MS = 5

# Default values
DEFAULT_ROUTE_PRIORITY = 3
DEFAULT_OFFER_PRIORITY = 100
DEFAULT_CAP_DAILY = 100
DEFAULT_AB_TEST_SPLIT_PERCENTAGE = 50
DEFAULT_MIN_AB_TEST_SAMPLE_SIZE = 1000

# Scoring weights
DEFAULT_EPC_WEIGHT = 0.4
DEFAULT_CR_WEIGHT = 0.3
DEFAULT_RELEVANCE_WEIGHT = 0.2
DEFAULT_FRESHNESS_WEIGHT = 0.1

# Personalization thresholds
MIN_COLLABORATIVE_SCORE = 0.1
MIN_CONTENT_BASED_SCORE = 0.1
MIN_HYBRID_SCORE = 0.2
MAX_PREFERENCE_VECTOR_SIZE = 100

# Behavioral targeting windows
DEFAULT_BEHAVIOR_WINDOW_DAYS = 30
DEFAULT_CLICK_THRESHOLD = 3
DEFAULT_PURCHASE_THRESHOLD = 1
DEFAULT_SESSION_THRESHOLD = 5

# Geographic targeting
MAX_GEO_RULES_PER_ROUTE = 50
DEFAULT_COUNTRY_BLACKLIST = ['KP', 'IR', 'SY', 'CU']
DEFAULT_COUNTRY_WHITELIST = ['US', 'CA', 'GB', 'DE', 'FR']

# Device targeting
SUPPORTED_DEVICES = ['mobile', 'desktop', 'tablet', 'smart_tv']
SUPPORTED_OS = ['ios', 'android', 'windows', 'macos', 'linux']
SUPPORTED_BROWSERS = ['chrome', 'safari', 'firefox', 'edge', 'opera']

# A/B testing
MIN_AB_TEST_DURATION_HOURS = 24
MAX_AB_TEST_DURATION_DAYS = 30
STATISTICAL_SIGNIFICANCE_THRESHOLD = 0.95
MIN_CONVERSION_RATE_DIFFERENCE = 0.02

# Fallback rules
MAX_FALLBACK_RULES_PER_TENANT = 10
DEFAULT_FALLBACK_TIMEOUT_SECONDS = 2
MIN_FALLBACK_POOL_SIZE = 5

# Analytics and logging
DECISION_LOG_RETENTION_DAYS = 30
INSIGHT_AGGREGATION_HOURS = 1
PERFORMANCE_STATS_RETENTION_DAYS = 90
MAX_DECISION_LOGS_PER_BATCH = 1000

# Rate limiting
MAX_ROUTING_REQUESTS_PER_MINUTE = 1000
MAX_OFFER_EXPOSURES_PER_USER_PER_HOUR = 50
MAX_API_REQUESTS_PER_TENANT_PER_MINUTE = 500

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
MIN_PAGE_SIZE = 1

# File upload limits
MAX_OFFER_IMAGE_SIZE_MB = 5
MAX_CSV_IMPORT_SIZE_MB = 10
SUPPORTED_IMAGE_FORMATS = ['jpg', 'jpeg', 'png', 'gif', 'webp']

# API response formats
API_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
API_DATE_FORMAT = '%Y-%m-%d'
API_TIME_FORMAT = '%H:%M:%S'

# Error messages
ERROR_ROUTE_NOT_FOUND = 'Route not found'
ERROR_OFFER_NOT_FOUND = 'Offer not found'
ERROR_CONDITION_EVALUATION_FAILED = 'Condition evaluation failed'
ERROR_SCORING_FAILED = 'Offer scoring failed'
ERROR_CAP_EXCEEDED = 'Offer cap exceeded'
ERROR_PERSONALIZATION_FAILED = 'Personalization failed'
ERROR_FALLBACK_FAILED = 'Fallback routing failed'

# Success messages
SUCCESS_ROUTING_COMPLETED = 'Routing completed successfully'
SUCCESS_CACHE_WARMED = 'Cache warmed successfully'
SUCCESS_AB_TEST_STARTED = 'A/B test started successfully'
SUCCESS_CAP_RESET = 'Offer caps reset successfully'

# Logging levels
ROUTING_LOG_LEVEL = 'INFO'
PERFORMANCE_LOG_LEVEL = 'DEBUG'
ERROR_LOG_LEVEL = 'ERROR'

# Feature flags
ENABLE_COLLABORATIVE_FILTERING = True
ENABLE_CONTENT_BASED_PERSONALIZATION = True
ENABLE_HYBRID_PERSONALIZATION = True
ENABLE_BEHAVIORAL_TARGETING = True
ENABLE_GEOGRAPHIC_TARGETING = True
ENABLE_DEVICE_TARGETING = True
ENABLE_TIME_BASED_TARGETING = True
ENABLE_A_B_TESTING = True
ENABLE_REAL_TIME_PERSONALIZATION = True

# Database connection settings
ROUTING_DB_CONNECTION_POOL_SIZE = 20
ROUTING_DB_CONNECTION_TIMEOUT = 30
ROUTING_DB_MAX_RETRIES = 3

# Redis settings
ROUTING_REDIS_DB = 0
ROUTING_REDIS_CONNECTION_POOL_SIZE = 10
ROUTING_REDIS_SOCKET_TIMEOUT = 5
ROUTING_REDIS_SOCKET_CONNECT_TIMEOUT = 5

# Celery task settings
ROUTING_TASK_QUEUE = 'offer_routing'
ROUTING_TASK_PRIORITY = 5
ROUTING_TASK_SOFT_TIME_LIMIT = 60
ROUTING_TASK_HARD_TIME_LIMIT = 120

# Monitoring and alerting
ROUTING_SLOW_QUERY_THRESHOLD_MS = 100
ROUTING_ERROR_RATE_THRESHOLD = 0.05
ROUTING_CACHE_HIT_RATE_THRESHOLD = 0.8

# Security settings
MAX_CONCURRENT_ROUTING_REQUESTS_PER_USER = 10
ROUTING_REQUEST_TIMEOUT_SECONDS = 30
ENABLE_ROUTING_RATE_LIMITING = True

# Business logic
MAX_OFFERS_PER_ROUTE = 100
MAX_CONDITIONS_PER_ROUTE = 20
MAX_ACTIONS_PER_ROUTE = 10
MAX_CAPS_PER_OFFER = 5
MAX_AB_TESTS_PER_TENANT = 10

# Data validation
MIN_ROUTE_NAME_LENGTH = 3
MAX_ROUTE_NAME_LENGTH = 100
MIN_OFFER_NAME_LENGTH = 3
MAX_OFFER_NAME_LENGTH = 200
MAX_DESCRIPTION_LENGTH = 1000

# External service timeouts
EXTERNAL_API_TIMEOUT_SECONDS = 10
EXTERNAL_SERVICE_RETRY_ATTEMPTS = 3
EXTERNAL_SERVICE_RETRY_DELAY_SECONDS = 1

PREFERENCE_VECTOR_CACHE_TIMEOUT = 3600  # 1 hour
PERFORMANCE_ALERT_THRESHOLD = 80.0  # Alert when routing time exceeds 80ms
