# Generated by Django
# Initial migration for postback_engine app

from django.conf import settings
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdNetworkConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='network name')),
                ('network_key', models.CharField(db_index=True, help_text='URL-safe slug: /api/postback_engine/{network_key}/', max_length=64, unique=True, verbose_name='network key')),
                ('network_type', models.CharField(choices=[('cpa', 'CPA Network'), ('cpl', 'CPL Network'), ('cpi', 'CPI (Mobile Install)'), ('cpm', 'CPM Network'), ('cpc', 'CPC Network'), ('affiliate', 'Affiliate Network'), ('offerwall', 'Offerwall'), ('direct', 'Direct Advertiser'), ('internal', 'Internal System'), ('s2s', 'Server-to-Server')], default='cpa', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing Mode'), ('suspended', 'Suspended'), ('deprecated', 'Deprecated')], db_index=True, default='testing', max_length=20, verbose_name='status')),
                ('logo_url', models.URLField(blank=True, verbose_name='logo URL')),
                ('secret_key', models.CharField(help_text='HMAC secret.', max_length=512, verbose_name='secret key')),
                ('api_key', models.CharField(blank=True, max_length=512, verbose_name='API key')),
                ('signature_algorithm', models.CharField(choices=[('hmac_sha256', 'HMAC-SHA256'), ('hmac_sha512', 'HMAC-SHA512'), ('hmac_md5', 'HMAC-MD5 (Legacy)'), ('md5', 'MD5 (Legacy)'), ('none', 'No Signature (IP-only)')], default='hmac_sha256', max_length=20, verbose_name='signature algorithm')),
                ('require_nonce', models.BooleanField(default=True, verbose_name='require nonce')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, verbose_name='IP whitelist')),
                ('trust_x_forwarded_for', models.BooleanField(default=False, verbose_name='trust X-Forwarded-For')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='field mapping')),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='required fields')),
                ('postback_url_template', models.TextField(blank=True, verbose_name='postback URL template')),
                ('reward_rules', models.JSONField(blank=True, default=dict, verbose_name='reward rules')),
                ('default_reward_points', models.PositiveIntegerField(default=0, verbose_name='default reward points')),
                ('default_reward_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='default reward USD')),
                ('dedup_window', models.CharField(choices=[('1h', '1 Hour'), ('1d', '1 Day'), ('7d', '7 Days'), ('30d', '30 Days'), ('forever', 'Forever (No Repeat)')], default='forever', max_length=10, verbose_name='dedup window')),
                ('attribution_model', models.CharField(choices=[('last_click', 'Last Click'), ('first_click', 'First Click'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('position_based', 'Position Based (U-Shape)'), ('data_driven', 'Data Driven')], default='last_click', max_length=20, verbose_name='attribution model')),
                ('conversion_window_hours', models.PositiveIntegerField(default=720, verbose_name='conversion window (hours)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=1000, verbose_name='rate limit / minute')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='test mode')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_engine_adnetworkconfig_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ad network config',
                'verbose_name_plural': 'ad network configs',
                'ordering': ['name'],
            },
        ),
        # Additional models would be added by subsequent migrations
        # Run: python manage.py makemigrations postback_engine
        # to auto-generate full migrations from the models.
    ]
