# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postback_engine', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_logs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='click_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='postback_engine.clicklog', verbose_name='click log'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postback_engine_conversions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='conversiondeduplication',
            name='conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_record', to='postback_engine.conversion', verbose_name='conversion'),
        ),
        migrations.AddField(
            model_name='conversiondeduplication',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_records', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='conversiondeduplication',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='click_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_attempts', to='postback_engine.clicklog', verbose_name='click log'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_attempts', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_attempts', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_fraud_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='hourlystat',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='hourlystat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='impression',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='impression',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_blacklists', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='fraud_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to='postback_engine.fraudattemptlog', verbose_name='fraud attempt'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='networkadaptermapping',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_mappings', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='networkadaptermapping',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='networkperformance',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='networkperformance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerpostback',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_postbacks', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='offerpostback',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='postbackqueue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='postbackrawlog',
            name='click_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_postback_logs', to='postback_engine.clicklog', verbose_name='click log'),
        ),
        migrations.AddField(
            model_name='postbackrawlog',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_logs', to='postback_engine.adnetworkconfig', verbose_name='network'),
        ),
        migrations.AddField(
            model_name='postbackrawlog',
            name='resolved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_postback_logs', to=settings.AUTH_USER_MODEL, verbose_name='resolved user'),
        ),
        migrations.AddField(
            model_name='postbackrawlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='postbackqueue',
            name='raw_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='postback_engine.postbackrawlog', verbose_name='raw postback log'),
        ),
        migrations.AddField(
            model_name='fraudattemptlog',
            name='raw_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_attempts', to='postback_engine.postbackrawlog', verbose_name='raw postback log'),
        ),
        migrations.AddField(
            model_name='conversiondeduplication',
            name='raw_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_record', to='postback_engine.postbackrawlog', verbose_name='original postback log'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='raw_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversion', to='postback_engine.postbackrawlog', verbose_name='raw postback log'),
        ),
        migrations.AddField(
            model_name='retrylog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='adnetworkconfig',
            index=models.Index(fields=['network_key', 'status'], name='postback_en_network_aa8029_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['user', 'offer_id', 'clicked_at'], name='postback_en_user_id_b71013_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['network', 'clicked_at'], name='postback_en_network_613c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['ip_address', 'clicked_at'], name='postback_en_ip_addr_8d7aca_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['device_fingerprint', 'clicked_at'], name='postback_en_device__b739ff_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['country', 'clicked_at'], name='postback_en_country_ef2e17_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['status', 'clicked_at'], name='postback_en_status_81d3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['converted', 'expires_at'], name='postback_en_convert_e28461_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlystat',
            index=models.Index(fields=['date', 'hour', 'network'], name='postback_en_date_cfb831_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlystat',
            unique_together={('network', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['network', 'impressed_at'], name='postback_en_network_855870_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['user', 'offer_id'], name='postback_en_user_id_c5c9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['ip_address', 'impressed_at'], name='postback_en_ip_addr_1da6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['blacklist_type', 'is_active'], name='postback_en_blackli_a12014_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['value', 'blacklist_type'], name='postback_en_value_b81d62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipblacklist',
            unique_together={('blacklist_type', 'value', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='networkadaptermapping',
            unique_together={('network', 'standard_name')},
        ),
        migrations.AddIndex(
            model_name='networkperformance',
            index=models.Index(fields=['date', 'network'], name='postback_en_date_82067d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkperformance',
            unique_together={('network', 'date')},
        ),
        migrations.AddIndex(
            model_name='offerpostback',
            index=models.Index(fields=['network', 'offer_id', 'is_active'], name='postback_en_network_62fa14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerpostback',
            unique_together={('network', 'offer_id')},
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['network', 'status', 'received_at'], name='postback_en_network_e83968_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['lead_id', 'network'], name='postback_en_lead_id_9f4e06_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['click_id', 'network'], name='postback_en_click_i_b2bf24_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='postback_en_status_fcb9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['source_ip', 'received_at'], name='postback_en_source__358059_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackrawlog',
            index=models.Index(fields=['transaction_id'], name='postback_en_transac_468488_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackqueue',
            index=models.Index(fields=['status', 'priority', 'process_after'], name='postback_en_status_a0908f_idx'),
        ),
        migrations.AddIndex(
            model_name='postbackqueue',
            index=models.Index(fields=['status', 'enqueued_at'], name='postback_en_status_4a781e_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattemptlog',
            index=models.Index(fields=['fraud_type', 'detected_at'], name='postback_en_fraud_t_f256c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattemptlog',
            index=models.Index(fields=['source_ip', 'detected_at'], name='postback_en_source__e6a6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattemptlog',
            index=models.Index(fields=['user', 'detected_at'], name='postback_en_user_id_6f33ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattemptlog',
            index=models.Index(fields=['fraud_score', 'is_auto_blocked'], name='postback_en_fraud_s_250d74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversiondeduplication',
            index=models.Index(fields=['network', 'lead_id'], name='postback_en_network_edd020_idx'),
        ),
        migrations.AddIndex(
            model_name='conversiondeduplication',
            index=models.Index(fields=['transaction_id'], name='postback_en_transac_ca92c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversiondeduplication',
            unique_together={('network', 'lead_id')},
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user', 'status', 'converted_at'], name='postback_en_user_id_ba003e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['network', 'status', 'converted_at'], name='postback_en_network_be8c88_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['offer_id', 'status'], name='postback_en_offer_i_8713f2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['country', 'converted_at'], name='postback_en_country_6f34dc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['wallet_credited', 'converted_at'], name='postback_en_wallet__7b36cc_idx'),
        ),
        migrations.AddIndex(
            model_name='retrylog',
            index=models.Index(fields=['retry_type', 'object_id'], name='postback_en_retry_t_772286_idx'),
        ),
        migrations.AddIndex(
            model_name='retrylog',
            index=models.Index(fields=['succeeded', 'attempted_at'], name='postback_en_succeed_46fc3e_idx'),
        ),
    ]
