# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postback_engine', '0003_rename_postback_en_network_aa8029_idx_idx_network_key_status_1368_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clicklog',
            new_name='idx_user_offer_id_clicked__b46',
            old_name='idx_user_offer_id_clicked_at_1370',
        ),
        migrations.RenameIndex(
            model_name='clicklog',
            new_name='idx_device_fingerprint_cli_bd2',
            old_name='idx_device_fingerprint_clicked_at_1373',
        ),
        migrations.RenameIndex(
            model_name='conversion',
            new_name='idx_user_status_converted__8ca',
            old_name='idx_user_status_converted_at_1383',
        ),
        migrations.RenameIndex(
            model_name='conversion',
            new_name='idx_network_status_convert_21d',
            old_name='idx_network_status_converted_at_1384',
        ),
        migrations.RenameIndex(
            model_name='conversion',
            new_name='idx_wallet_credited_conver_927',
            old_name='idx_wallet_credited_converted_at_1387',
        ),
        migrations.RenameIndex(
            model_name='fraudattemptlog',
            new_name='idx_fraud_type_detected_at_81e',
            old_name='idx_fraud_type_detected_at_1391',
        ),
        migrations.RenameIndex(
            model_name='fraudattemptlog',
            new_name='idx_fraud_score_is_auto_bl_d87',
            old_name='idx_fraud_score_is_auto_blocked_1394',
        ),
        migrations.RenameIndex(
            model_name='impression',
            new_name='idx_ip_address_impressed_a_d3f',
            old_name='idx_ip_address_impressed_at_1390',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_blacklist_type_is_acti_621',
            old_name='idx_blacklist_type_is_active_1395',
        ),
        migrations.RenameIndex(
            model_name='offerpostback',
            new_name='idx_network_offer_id_is_ac_265',
            old_name='idx_network_offer_id_is_active_1369',
        ),
        migrations.RenameIndex(
            model_name='postbackqueue',
            new_name='idx_status_priority_proces_46c',
            old_name='idx_status_priority_process_after_1399',
        ),
        migrations.RenameIndex(
            model_name='postbackrawlog',
            new_name='idx_network_status_receive_18b',
            old_name='idx_network_status_received_at_1377',
        ),
        migrations.RenameIndex(
            model_name='retrylog',
            new_name='idx_succeeded_attempted_at_bb4',
            old_name='idx_succeeded_attempted_at_1402',
        ),
    ]
