# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('offerwall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='offerwall.offer'),
        ),
    ]
