# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('offerwall', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannerimpression',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.banner'),
        ),
        migrations.AddField(
            model_name='bannerimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannerreward',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cms.banner'),
        ),
        migrations.AddField(
            model_name='bannerreward',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cms.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cms.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.contentcategory'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms.contentcategory'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='original_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='related_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pages', to='offerwall.offer'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pages', to='tasks.mastertask'),
        ),
        migrations.AddField(
            model_name='banner',
            name='internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentpermission',
            name='content',
            field=models.ForeignKey(help_text='Content this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentpermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentpermission',
            name='parent_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_permissions', to='cms.contentpermission'),
        ),
        migrations.AddField(
            model_name='contentshare',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentviewlog',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='contentviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='related_offers',
            field=models.ManyToManyField(blank=True, related_name='related_faqs', to='offerwall.offer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='related_pages',
            field=models.ManyToManyField(blank=True, related_name='related_faqs', to='cms.contentpage'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['slug', 'is_active'], name='cms_faqcate_slug_0c92fb_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['faq_type', 'order'], name='cms_faqcate_faq_typ_e5cfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['uuid'], name='cms_faqcate_uuid_1e4ba2_idx'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='cms.faqcategory'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='cms.faq'),
        ),
        migrations.AddField(
            model_name='faqfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.contentcategory'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.contentcategory'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.imagegallery'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['permission_id', 'action'], name='cms_permiss_permiss_e41119_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['user_id', '-created_at'], name='cms_permiss_user_id_672af1_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['content_id', '-created_at'], name='cms_permiss_content_166c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionstats',
            index=models.Index(fields=['date', '-check_count'], name='cms_permiss_date_3bd15b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionstats',
            unique_together={('date', 'content_id')},
        ),
        migrations.AddIndex(
            model_name='siteanalytics',
            index=models.Index(fields=['date'], name='cms_siteana_date_a4d46f_idx'),
        ),
        migrations.AddIndex(
            model_name='siteanalytics',
            index=models.Index(fields=['uuid'], name='cms_siteana_uuid_48d512_idx'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['banner', 'created_at'], name='cms_bannerc_banner__a7930c_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['user', 'click_type'], name='cms_bannerc_user_id_2a7ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['created_at', 'banner'], name='cms_bannerc_created_454798_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['uuid'], name='cms_bannerc_uuid_94be1b_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['banner', 'created_at'], name='cms_banneri_banner__3b64e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['user', 'impression_type'], name='cms_banneri_user_id_972365_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['created_at', 'banner'], name='cms_banneri_created_2b9742_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['ip_address', 'created_at'], name='cms_banneri_ip_addr_5e8165_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerimpression',
            index=models.Index(fields=['uuid'], name='cms_banneri_uuid_70ba1f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', 'is_approved'], name='cms_comment_content_5fb6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'comment_type'], name='cms_comment_user_id_ca8f65_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at', 'content_type', 'object_id'], name='cms_comment_created_066ead_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['uuid'], name='cms_comment_uuid_85afb8_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'is_active'], name='cms_comment_parent__9d9afc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved', 'is_flagged'], name='cms_comment_is_appr_adc809_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'user'], name='cms_comment_comment_43b36c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['uuid'], name='cms_comment_uuid_ef5323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['slug', 'is_active'], name='cms_content_slug_be705c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['parent', 'category_type'], name='cms_content_parent__72ca67_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['show_in_menu', 'is_active'], name='cms_content_show_in_0d2b07_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['show_in_app', 'category_type'], name='cms_content_show_in_673946_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['is_active', 'order', 'parent'], name='cms_content_is_acti_12a23b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcategory',
            index=models.Index(fields=['category_type', 'show_in_menu'], name='cms_content_categor_bf39ac_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['slug', 'status'], name='cms_content_slug_69dd41_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['category', 'page_type', 'is_active'], name='cms_content_categor_94fd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['published_date', 'status'], name='cms_content_publish_a83416_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['is_featured', 'is_active'], name='cms_content_is_feat_a05360_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['language', 'status'], name='cms_content_languag_8e6da5_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['status', 'published_date', 'category'], name='cms_content_status_a00614_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['is_active', 'is_featured', 'page_type'], name='cms_content_is_acti_761357_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['author', 'status', 'created_at'], name='cms_content_author__2ae406_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpage',
            index=models.Index(fields=['uuid', 'is_active'], name='cms_content_uuid_6ae41b_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['banner_type', 'is_active'], name='cms_banner_banner__f0f6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['start_date', 'end_date'], name='cms_banner_start_d_e7c916_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['position', 'target_device'], name='cms_banner_positio_22dfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['uuid', 'is_active'], name='cms_banner_uuid_f96e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['priority', 'start_date', 'end_date'], name='cms_banner_priorit_b64a36_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['tenant_id', 'content', 'is_active'], name='cms_content_tenant__50c71b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['tenant_id', 'permission_type', 'target_id'], name='cms_content_tenant__05a78d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['tenant_id', 'priority'], name='cms_content_tenant__10c880_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['tenant_id', 'expires_at'], name='cms_content_tenant__33dfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['uuid'], name='cms_content_uuid_dd8ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpermission',
            index=models.Index(fields=['created_at'], name='cms_content_created_9e426b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentpermission',
            unique_together={('tenant_id', 'content', 'permission_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='contentshare',
            index=models.Index(fields=['content', 'share_platform'], name='cms_content_content_7efd27_idx'),
        ),
        migrations.AddIndex(
            model_name='contentshare',
            index=models.Index(fields=['created_at', 'content'], name='cms_content_created_4c6a71_idx'),
        ),
        migrations.AddIndex(
            model_name='contentshare',
            index=models.Index(fields=['uuid'], name='cms_content_uuid_3a9962_idx'),
        ),
        migrations.AddIndex(
            model_name='contentviewlog',
            index=models.Index(fields=['content', 'created_at'], name='cms_content_content_dcf005_idx'),
        ),
        migrations.AddIndex(
            model_name='contentviewlog',
            index=models.Index(fields=['user', 'is_completed'], name='cms_content_user_id_770bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='contentviewlog',
            index=models.Index(fields=['created_at', 'content'], name='cms_content_created_7648ef_idx'),
        ),
        migrations.AddIndex(
            model_name='contentviewlog',
            index=models.Index(fields=['uuid'], name='cms_content_uuid_b730e2_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active'], name='cms_faq_categor_d1f6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_featured', 'is_pinned'], name='cms_faq_is_feat_b71190_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['tags', 'is_active'], name='cms_faq_tags_776872_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['uuid', 'is_active'], name='cms_faq_uuid_c5d6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['priority', 'view_count'], name='cms_faq_priorit_526c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['slug', 'is_active'], name='cms_faq_slug_39ccd3_idx'),
        ),
        migrations.AddIndex(
            model_name='faqfeedback',
            index=models.Index(fields=['faq', 'is_helpful'], name='cms_faqfeed_faq_id_3ee496_idx'),
        ),
        migrations.AddIndex(
            model_name='faqfeedback',
            index=models.Index(fields=['user', 'created_at'], name='cms_faqfeed_user_id_993238_idx'),
        ),
        migrations.AddIndex(
            model_name='faqfeedback',
            index=models.Index(fields=['uuid'], name='cms_faqfeed_uuid_a16512_idx'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['file_type', 'is_public'], name='cms_fileman_file_ty_61170a_idx'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['category', 'is_public'], name='cms_fileman_categor_ea476f_idx'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['uuid'], name='cms_fileman_uuid_0660f4_idx'),
        ),
        migrations.AddIndex(
            model_name='filemanager',
            index=models.Index(fields=['is_active', 'file_type'], name='cms_fileman_is_acti_c5c25c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['slug', 'is_active'], name='cms_imagega_slug_f5d5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['category', 'is_featured'], name='cms_imagega_categor_5bf1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['uuid'], name='cms_imagega_uuid_95c3df_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'order'], name='cms_gallery_gallery_c95859_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_active', 'gallery'], name='cms_gallery_is_acti_431bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['uuid'], name='cms_gallery_uuid_9a3589_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['key', 'category'], name='cms_siteset_key_7000ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['category', 'is_public'], name='cms_siteset_categor_a27a04_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['uuid'], name='cms_siteset_uuid_133200_idx'),
        ),
    ]
