# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_cms_banner_banner__f0f6bb_idx_idx_banner_type_is_active_900_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='idx_priority_start_date_en_32e',
            old_name='idx_priority_start_date_end_date_904',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='idx_content_type_object_id_d58',
            old_name='idx_content_type_object_id_is_appr_946',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='idx_created_at_content_typ_a82',
            old_name='idx_created_at_content_type_object_948',
        ),
        migrations.RenameIndex(
            model_name='contentcategory',
            new_name='idx_show_in_app_category_t_19d',
            old_name='idx_show_in_app_category_type_888',
        ),
        migrations.RenameIndex(
            model_name='contentcategory',
            new_name='idx_category_type_show_in__d66',
            old_name='idx_category_type_show_in_menu_890',
        ),
        migrations.RenameIndex(
            model_name='contentpage',
            new_name='idx_category_page_type_is__322',
            old_name='idx_category_page_type_is_active_892',
        ),
        migrations.RenameIndex(
            model_name='contentpage',
            new_name='idx_status_published_date__6ff',
            old_name='idx_status_published_date_category_896',
        ),
        migrations.RenameIndex(
            model_name='contentpage',
            new_name='idx_is_active_is_featured__560',
            old_name='idx_is_active_is_featured_page_typ_897',
        ),
        migrations.RenameIndex(
            model_name='contentpage',
            new_name='idx_author_status_created__6ac',
            old_name='idx_author_status_created_at_898',
        ),
        migrations.RenameIndex(
            model_name='contentpermission',
            new_name='idx_tenant_id_content_is_a_d63',
            old_name='idx_tenant_id_content_is_active_959',
        ),
        migrations.RenameIndex(
            model_name='contentpermission',
            new_name='idx_tenant_id_permission_t_def',
            old_name='idx_tenant_id_permission_type_targ_960',
        ),
    ]
