# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djoyalty', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked auth user (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coalitionearn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coalition_earns', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='campaignparticipant',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='bonusevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_events', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_dailystreak_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='earnrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_earnrule_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='earnrulecondition',
            name='earn_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='djoyalty.earnrule'),
        ),
        migrations.AddField(
            model_name='earnrulelog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_rule_logs', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='earnrulelog',
            name='earn_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='djoyalty.earnrule'),
        ),
        migrations.AddField(
            model_name='earnruletiermultiplier',
            name='earn_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_multipliers', to='djoyalty.earnrule'),
        ),
        migrations.AddField(
            model_name='earntransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_transactions', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='earntransaction',
            name='earn_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earn_transactions', to='djoyalty.earnrule'),
        ),
        migrations.AddField(
            model_name='earntransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_earntransaction_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_event_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_giftcard_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltycampaign',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltycampaign_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignsegment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='djoyalty.loyaltycampaign'),
        ),
        migrations.AddField(
            model_name='campaignparticipant',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participants', to='djoyalty.loyaltycampaign'),
        ),
        migrations.AddField(
            model_name='loyaltyfraudrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltyfraudrule_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltyinsight',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltyinsight_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltynotification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_notifications', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='loyaltynotification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltynotification_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltypoints_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltysubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_subscriptions', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='loyaltysubscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltysubscription_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_loyaltytier_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='earnruletiermultiplier',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_multipliers', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_milestone_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='partnermerchant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_partnermerchant_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coalitionearn',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coalition_earns', to='djoyalty.partnermerchant'),
        ),
        migrations.AddField(
            model_name='pointsabuselog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_logs', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsabuselog',
            name='fraud_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_logs', to='djoyalty.loyaltyfraudrule'),
        ),
        migrations.AddField(
            model_name='pointsabuselog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsabuselog_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsadjustment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_adjustments', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsadjustment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsadjustment_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsalert',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_alerts', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsconversion',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_conversions', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsconversion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsconversion_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsexpiry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_expiries', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsexpiry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsexpiry_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsledger',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsledger_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsexpiry',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expiry_records', to='djoyalty.pointsledger'),
        ),
        migrations.AddField(
            model_name='pointsrate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsrate_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointsreservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_reservations', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointsreservation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointsreservation_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='from_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transfers_sent', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_pointstransfer_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='to_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transfers_received', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_redemptionrequest_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='redemptionhistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='djoyalty.redemptionrequest'),
        ),
        migrations.AddField(
            model_name='redemptionrule',
            name='min_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='redemptionrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_redemptionrule_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='djoyalty.redemptionrule'),
        ),
        migrations.AddField(
            model_name='referralpointsrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_referralpointsrule_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='streakreward',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_rewards', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='streakreward',
            name='streak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='djoyalty.dailystreak'),
        ),
        migrations.AddField(
            model_name='tierbenefit',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='tierconfig',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djoyalty_tier_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tierhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='tierhistory',
            name='from_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='tierhistory',
            name='to_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='txn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='txn',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_txn_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='earntransaction',
            name='txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earn_transactions', to='djoyalty.txn'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='djoyalty.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='usermilestone',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones', to='djoyalty.milestone'),
        ),
        migrations.AddField(
            model_name='usertier',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tiers', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='usertier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_usertier_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usertier',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tiers', to='djoyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='redemption_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='djoyalty.redemptionrequest'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_voucher_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='voucherredemption',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemptions', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='voucherredemption',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='djoyalty.voucher'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'code'], name='djoyalty_cu_tenant__79b383_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='djoyalty_cu_tenant__daecfe_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='djoyalty_cu_is_acti_1909f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('challenge', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='dailystreak',
            unique_together={('tenant', 'customer')},
        ),
        migrations.AddIndex(
            model_name='earnrule',
            index=models.Index(fields=['is_active', 'trigger'], name='djoyalty_ea_is_acti_5d1c88_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_ev_tenant__bdc468_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['action'], name='djoyalty_ev_action_87e63f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='djoyalty_ev_timesta_69ead7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipant',
            unique_together={('campaign', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyinsight',
            unique_together={('tenant', 'report_date', 'period')},
        ),
        migrations.AddIndex(
            model_name='loyaltynotification',
            index=models.Index(fields=['customer', 'is_read'], name='djoyalty_lo_custome_30c70e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypoints',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_lo_tenant__4b293c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltypoints',
            unique_together={('tenant', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='loyaltytier',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='earnruletiermultiplier',
            unique_together={('earn_rule', 'tier')},
        ),
        migrations.AddIndex(
            model_name='pointsabuselog',
            index=models.Index(fields=['risk_level', 'is_resolved'], name='djoyalty_po_risk_le_e24bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_po_tenant__da8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['txn_type', 'source'], name='djoyalty_po_txn_typ_c80be4_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['expires_at'], name='djoyalty_po_expires_13a112_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['created_at'], name='djoyalty_po_created_9563b1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsexpiry',
            index=models.Index(fields=['expires_at', 'is_processed'], name='djoyalty_po_expires_89e114_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsexpiry',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_po_tenant__50ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsreservation',
            index=models.Index(fields=['reference'], name='djoyalty_po_referen_2b990b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsreservation',
            index=models.Index(fields=['expires_at'], name='djoyalty_po_expires_e48933_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransfer',
            index=models.Index(fields=['status'], name='djoyalty_po_status_5a7423_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransfer',
            index=models.Index(fields=['tenant'], name='djoyalty_po_tenant__05c2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['status', 'tenant'], name='djoyalty_re_status_ff64fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streakreward',
            unique_together={('customer', 'milestone_days')},
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_tx_tenant__950158_idx'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['timestamp'], name='djoyalty_tx_timesta_b4f2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['is_discount'], name='djoyalty_tx_is_disc_e3b25e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('customer', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='usermilestone',
            unique_together={('customer', 'milestone')},
        ),
        migrations.AddIndex(
            model_name='usertier',
            index=models.Index(fields=['customer', 'is_current'], name='djoyalty_us_custome_848f35_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='djoyalty_vo_code_e088ab_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='djoyalty_vo_status_0db916_idx'),
        ),
    ]
