# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djoyalty', '0003_rename_djoyalty_cu_tenant__79b383_idx_idx_tenant_code_968_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pointsexpiry',
            new_name='idx_expires_at_is_processe_538',
            old_name='idx_expires_at_is_processed_983',
        ),
    ]
