# Generated by Django 5.0.11 on 2026-04-10 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoyalty', '0006_campaigns_advanced'),
        ('tenants', '0003_alter_tenant_max_users_tenantbilling_tenantinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='djoyalty.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked auth user (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='txn',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='txn',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_unique',
            field=models.BooleanField(default=True, help_text='Only awarded once per customer'),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Active'), ('completed', '✅ Completed'), ('failed', '❌ Failed'), ('upcoming', '📅 Upcoming'), ('expired', '⌛ Expired')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_customer_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='earnrule',
            name='applicable_tiers',
            field=models.JSONField(blank=True, help_text='List of tier names, null=all tiers', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='djoyalty.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_event_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='loyaltynotification',
            name='channel',
            field=models.CharField(choices=[('email', '📧 Email'), ('sms', '📱 SMS'), ('push', '🔔 Push Notification'), ('in_app', '💬 In-App')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='loyaltynotification',
            name='notification_type',
            field=models.CharField(choices=[('points_expiry', '⌛ Points Expiry Warning'), ('tier_change', '🏆 Tier Change'), ('badge_unlock', '🎖️ Badge Unlocked'), ('campaign', '📣 Campaign'), ('redemption', '🎁 Redemption Update'), ('general', '📢 General')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pointsabuselog',
            name='action_taken',
            field=models.CharField(choices=[('flag', '⚑ Flag'), ('suspend', '⏸️ Suspend'), ('block', '🚫 Block'), ('notify', '🔔 Notify Admin')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pointsabuselog',
            name='risk_level',
            field=models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('critical', '🔴 Critical')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='pointsalert',
            name='channel',
            field=models.CharField(choices=[('email', '📧 Email'), ('sms', '📱 SMS'), ('push', '🔔 Push Notification'), ('in_app', '💬 In-App')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('admin', 'Admin Adjustment'), ('expiry', 'Points Expiry'), ('redemption', 'Redemption'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('streak', 'Daily Streak'), ('badge', 'Badge Unlock'), ('challenge', 'Challenge Completion'), ('milestone', 'Milestone')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pointstransfer',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('completed', '✅ Completed'), ('failed', '❌ Failed'), ('cancelled', '🚫 Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='redemption_type',
            field=models.CharField(choices=[('voucher', '🎫 Voucher'), ('cashback', '💵 Cashback'), ('product', '📦 Product'), ('giftcard', '🎁 Gift Card'), ('donation', '❤️ Donation')], max_length=32),
        ),
        migrations.AlterField(
            model_name='txn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='djoyalty.customer'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djoyalty_txn_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='txn',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'code'], name='djoyalty_cu_tenant__79b383_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='djoyalty_cu_tenant__daecfe_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='djoyalty_cu_is_acti_1909f8_idx'),
        ),
        migrations.AddIndex(
            model_name='earnrule',
            index=models.Index(fields=['is_active', 'trigger'], name='djoyalty_ea_is_acti_5d1c88_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_ev_tenant__bdc468_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['action'], name='djoyalty_ev_action_87e63f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='djoyalty_ev_timesta_69ead7_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltynotification',
            index=models.Index(fields=['customer', 'is_read'], name='djoyalty_lo_custome_30c70e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypoints',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_lo_tenant__4b293c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsabuselog',
            index=models.Index(fields=['risk_level', 'is_resolved'], name='djoyalty_po_risk_le_e24bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsexpiry',
            index=models.Index(fields=['expires_at', 'is_processed'], name='djoyalty_po_expires_89e114_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsexpiry',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_po_tenant__50ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_po_tenant__da8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['txn_type', 'source'], name='djoyalty_po_txn_typ_c80be4_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['expires_at'], name='djoyalty_po_expires_13a112_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsledger',
            index=models.Index(fields=['created_at'], name='djoyalty_po_created_9563b1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsreservation',
            index=models.Index(fields=['reference'], name='djoyalty_po_referen_2b990b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsreservation',
            index=models.Index(fields=['expires_at'], name='djoyalty_po_expires_e48933_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransfer',
            index=models.Index(fields=['status'], name='djoyalty_po_status_5a7423_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransfer',
            index=models.Index(fields=['tenant'], name='djoyalty_po_tenant__05c2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['status', 'tenant'], name='djoyalty_re_status_ff64fa_idx'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['tenant', 'customer'], name='djoyalty_tx_tenant__950158_idx'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['timestamp'], name='djoyalty_tx_timesta_b4f2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['is_discount'], name='djoyalty_tx_is_disc_e3b25e_idx'),
        ),
        migrations.AddIndex(
            model_name='usertier',
            index=models.Index(fields=['customer', 'is_current'], name='djoyalty_us_custome_848f35_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='djoyalty_vo_code_e088ab_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='djoyalty_vo_status_0db916_idx'),
        ),
    ]
