# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='notice',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='notifications.notice', verbose_name='Previous Version'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users to show notice', related_name='targeted_notices', to=settings.AUTH_USER_MODEL, verbose_name='Target Users'),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notices', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='notification',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='notification',
            name='parent_notification',
            field=models.ForeignKey(blank=True, help_text='Parent notification for threaded notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notifications.notification', verbose_name='Parent Notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='Previous version of notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='notifications.notification', verbose_name='Previous Version'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='api_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationanalytics',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationfeedback',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['device_type'], name='notificatio_device__289fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform'], name='notificatio_platfor_0d3ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['last_active'], name='notificatio_last_ac_441a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'token')},
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status', 'is_published'], name='notificatio_status_eb3fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['notice_type'], name='notificatio_notice__43dfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='notificatio_priorit_2accad_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['start_date', 'end_date'], name='notificatio_start_d_2fb93c_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_pinned'], name='notificatio_is_pinn_430e11_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at'], name='notificatio_created_270d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_d92267_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='notificatio_channel_1d6e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expire_date'], name='notificatio_expire__f24ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['batch_id'], name='notificatio_batch_i_f9a553_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['campaign_id'], name='notificatio_campaig_a65697_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_id'], name='notificatio_group_i_c7532d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_deleted'], name='notificatio_is_dele_13dd60_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['language'], name='notificatio_languag_6b763d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('progress_value__gte', 0.0), ('progress_value__lte', 100.0)), name='progress_value_range'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationfeedback',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification'], name='notificatio_notific_ca68c9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user'], name='notificatio_user_id_9c973b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['log_type'], name='notificatio_log_typ_2dd728_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['log_level'], name='notificatio_log_lev_001c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['name'], name='notificatio_name_05069a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type'], name='notificatio_templat_5e0a58_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['category'], name='notificatio_categor_7eadfe_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx'),
        ),
    ]
