# Generated by Django 5.0.11 on 2026-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='progress_value_range',
        ),
    ]
