# Generated by Django 5.0.11 on 2026-04-25 13:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_new_split_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newnotificationcampaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newnotificationcampaign',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='newnotificationcampaign',
            name='template',
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignresult DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignabtest DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='campaignsegment',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Leave null to use the segment across multiple campaigns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='notifications.notificationcampaign'),
        ),
        migrations.AlterField(
            model_name='campaignresult',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='notifications.notificationcampaign'),
        ),
        migrations.AlterField(
            model_name='campaignabtest',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test', to='notifications.notificationcampaign'),
        ),
        migrations.AlterModelOptions(
            name='notificationcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification Campaign (New)', 'verbose_name_plural': 'Notification Campaigns (New)'},
        ),
        migrations.RenameIndex(
            model_name='emaildeliverylog',
            new_name='notificatio_notific_03c0ea_idx',
            old_name='notif_emaildlog_notif_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildeliverylog',
            new_name='notificatio_message_223f4e_idx',
            old_name='notif_emaildlog_msgid_idx',
        ),
        migrations.RenameIndex(
            model_name='inappmessage',
            new_name='notificatio_user_id_f8157d_idx',
            old_name='notif_inapp_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationqueue',
            new_name='notificatio_status_7d5496_idx',
            old_name='notif_queue_status_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationretry',
            new_name='notificatio_status_dae9b9_idx',
            old_name='notif_retry_status_retrytime_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationschedule',
            new_name='notificatio_status_150fac_idx',
            old_name='notif_sched_status_sendat_idx',
        ),
        migrations.RenameIndex(
            model_name='optouttracking',
            new_name='notificatio_user_id_8ecec4_idx',
            old_name='notif_optout_user_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdeliverylog',
            new_name='notificatio_notific_11d204_idx',
            old_name='notif_pushdlog_notif_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='notificatio_user_id_fa4742_idx',
            old_name='notif_pushdevice_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='notificatio_device__da0339_idx',
            old_name='notif_pushdevice_dtype_idx',
        ),
        migrations.RenameIndex(
            model_name='smsdeliverylog',
            new_name='notificatio_notific_84258f_idx',
            old_name='notif_smsdlog_notif_status_idx',
        ),
        migrations.RenameIndex(
            model_name='smsdeliverylog',
            new_name='notificatio_gateway_cf6bf5_idx',
            old_name='notif_smsdlog_gateway_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='affiliate_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='conversion_value',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='ab_test_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='ab_test_variants',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='click_through_rate',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='delivery_rate',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='open_rate',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='send_limit',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='target_count',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='target_segment',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='title_template',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_clicked',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_delivered',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_failed',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_read',
        ),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='total_sent',
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_campaigns', to='notifications.campaignsegment'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='send_at',
            field=models.DateTimeField(blank=True, help_text='UTC time to start sending. Null = send immediately on launch.', null=True),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_campaigns', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignabtest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaignabtest',
            name='split_pct',
            field=models.PositiveSmallIntegerField(default=50, help_text='Percentage of users who receive variant A', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='campaignresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignresult DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignabtest DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='campaignsegment',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary filter conditions evaluated by SegmentService'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignresult DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignabtest DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='campaignsegment',
            name='estimated_size',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of users matching this segment'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE notifications_campaignsegment DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignresult DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignabtest DROP CONSTRAINT IF EXISTS notifications_campai_campaign_id_bbe32a56_fk_notificat',
                'ALTER TABLE notifications_campaignsegment ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignresult ALTER COLUMN campaign_id TYPE uuid USING NULL',
                'ALTER TABLE notifications_campaignabtest ALTER COLUMN campaign_id TYPE uuid USING NULL',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='campaignsegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('browser', 'Browser Push'), ('all', 'All Channels')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='click_pct',
            field=models.FloatField(default=0.0, help_text='Percentage of delivered notifications that were clicked'),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='delivery_pct',
            field=models.FloatField(default=0.0, help_text='Percentage of sent notifications that were delivered'),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='open_pct',
            field=models.FloatField(default=0.0, help_text='Percentage of delivered notifications that were opened'),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='message_id',
            field=models.CharField(blank=True, help_text='Provider-assigned message ID for webhook matching', max_length=255),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='provider',
            field=models.CharField(blank=True, help_text='sendgrid / smtp / ses', max_length=50),
        ),
        migrations.AlterField(
            model_name='inappmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000, null=True, blank=True)', max_length=20, null=True, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system_update', 'System Update'), ('maintenance', 'System Maintenance'), ('app_update', 'App Update'), ('new_feature', 'New Feature'), ('bug_fix', 'Bug Fix'), ('announcement', 'Announcement'), ('news', 'News'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('withdrawal_success', 'Withdrawal Success'), ('withdrawal_failed', 'Withdrawal Failed'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('deposit_success', 'Deposit Success'), ('deposit_failed', 'Deposit Failed'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_expired', 'Subscription Expired'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('low_balance', 'Low Balance'), ('bonus_added', 'Bonus Added'), ('cashback', 'Cashback'), ('reward_points', 'Reward Points'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_rejected', 'Task Rejected'), ('task_approved', 'Task Approved'), ('task_expired', 'Task Expired'), ('task_reminder', 'Task Reminder'), ('task_deadline', 'Task Deadline'), ('task_reward', 'Task Reward'), ('task_verification', 'Task Verification'), ('task_dispute', 'Task Dispute'), ('task_available', 'New Task Available'), ('task_limit_reached', 'Task Limit Reached'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_new_device', 'Login from New Device'), ('login_new_location', 'Login from New Location'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('two_factor_enabled', '2FA Enabled'), ('two_factor_disabled', '2FA Disabled'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_pending', 'KYC Pending'), ('kyc_submitted', 'KYC Submitted'), ('fraud_detected', 'Fraud Detected'), ('security_alert', 'Security Alert'), ('promotion', 'Promotion'), ('offer', 'Offer'), ('discount', 'Discount'), ('coupon', 'Coupon'), ('sale', 'Sale'), ('flash_sale', 'Flash Sale'), ('new_arrival', 'New Arrival'), ('restock', 'Restock'), ('price_drop', 'Price Drop'), ('abandoned_cart', 'Abandoned Cart'), ('wishlist', 'Wishlist'), ('product_review', 'Product Review'), ('survey', 'Survey'), ('feedback', 'Feedback'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('friend_rejected', 'Friend Rejected'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('message', 'Message'), ('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('mention', 'Mention'), ('tag', 'Tag'), ('invite', 'Invite'), ('group_invite', 'Group Invite'), ('group_join', 'Group Join'), ('group_leave', 'Group Leave'), ('event_invite', 'Event Invite'), ('event_reminder', 'Event Reminder'), ('referral_signup', 'Referral Signup'), ('referral_completed', 'Referral Completed'), ('referral_reward', 'Referral Reward'), ('referral_expired', 'Referral Expired'), ('offer_completed', 'Offer/Offerwall Completed'), ('offer_available', 'New Offer Available'), ('postback_received', 'Advertiser Postback Received'), ('postback_failed', 'Postback Failed'), ('ip_fraud_blocked', 'IP/Fraud Blocked'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated'), ('account_warning', 'Account Warning'), ('affiliate_commission', 'Affiliate Commission Earned'), ('sub_affiliate_earn', 'Sub-Affiliate Earning'), ('leaderboard_update', 'Leaderboard Position Update'), ('publisher_payout', 'Publisher Payout'), ('conversion_received', 'Conversion Received'), ('campaign_live', 'Campaign Went Live'), ('campaign_paused', 'Campaign Paused'), ('referral_bonus', 'Referral Bonus'), ('team_bonus', 'Team Bonus'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_reply', 'Ticket Reply'), ('ticket_escalated', 'Ticket Escalated'), ('live_chat', 'Live Chat'), ('chat_message', 'Chat Message'), ('chat_request', 'Chat Request'), ('faq_suggestion', 'FAQ Suggestion'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('achievement_unlocked', 'Achievement Unlocked'), ('milestone_reached', 'Milestone Reached'), ('rank_up', 'Rank Up'), ('streak', 'Streak'), ('daily_streak', 'Daily Streak'), ('weekly_streak', 'Weekly Streak'), ('monthly_streak', 'Monthly Streak'), ('challenge_completed', 'Challenge Completed'), ('contest_won', 'Contest Won'), ('contest_participation', 'Contest Participation'), ('daily_reward', 'Daily Reward'), ('streak_reward', 'Streak Reward'), ('weekly_reward', 'Weekly Reward'), ('monthly_reward', 'Monthly Reward'), ('spin_wheel', 'Spin Wheel'), ('scratch_card', 'Scratch Card'), ('lucky_draw', 'Lucky Draw'), ('quiz_completed', 'Quiz Completed'), ('trivia_winner', 'Trivia Winner'), ('mini_game', 'Mini Game'), ('user_registered', 'User Registered'), ('user_verified', 'User Verified'), ('user_blocked', 'User Blocked'), ('user_deleted', 'User Deleted'), ('content_reported', 'Content Reported'), ('content_removed', 'Content Removed'), ('content_approved', 'Content Approved'), ('moderation', 'Moderation'), ('admin_alert', 'Admin Alert'), ('system_error', 'System Error'), ('database_backup', 'Database Backup'), ('server_maintenance', 'Server Maintenance'), ('ad_viewed', 'Ad Viewed'), ('ad_clicked', 'Ad Clicked'), ('ad_completed', 'Ad Completed'), ('video_watched', 'Video Watched'), ('article_read', 'Article Read'), ('app_installed', 'App Installed'), ('app_reviewed', 'App Reviewed'), ('survey_completed', 'Survey Completed'), ('poll_voted', 'Poll Voted'), ('custom', 'Custom'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('warning', 'Warning'), ('info', 'Information'), ('success', 'Success'), ('error', 'Error'), ('general', 'General')], default='general', help_text='Type/category of notification', max_length=50, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Template context variables applied to every notification in the batch'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationfatigue',
            name='daily_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = use system default from settings'),
        ),
        migrations.AlterField(
            model_name='notificationfatigue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationfatigue',
            name='is_fatigued',
            field=models.BooleanField(db_index=True, default=False, help_text='True = suppress non-critical notifications for this user'),
        ),
        migrations.AlterField(
            model_name='notificationfatigue',
            name='weekly_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = use system default from settings'),
        ),
        migrations.AlterField(
            model_name='notificationinsight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='1 = lowest priority, 10 = highest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Earliest time this item should be processed'),
        ),
        migrations.AlterField(
            model_name='notificationretry',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-based retry attempt number'),
        ),
        migrations.AlterField(
            model_name='notificationretry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationretry',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of retry attempts before abandoning'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='send_at',
            field=models.DateTimeField(help_text='UTC datetime when the notification should be dispatched'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone name, e.g. "Asia/Dhaka"', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('system_update', 'System Update'), ('maintenance', 'System Maintenance'), ('app_update', 'App Update'), ('new_feature', 'New Feature'), ('bug_fix', 'Bug Fix'), ('announcement', 'Announcement'), ('news', 'News'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('withdrawal_success', 'Withdrawal Success'), ('withdrawal_failed', 'Withdrawal Failed'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('deposit_success', 'Deposit Success'), ('deposit_failed', 'Deposit Failed'), ('refund', 'Refund'), ('chargeback', 'Chargeback'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_expired', 'Subscription Expired'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('low_balance', 'Low Balance'), ('bonus_added', 'Bonus Added'), ('cashback', 'Cashback'), ('reward_points', 'Reward Points'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_rejected', 'Task Rejected'), ('task_approved', 'Task Approved'), ('task_expired', 'Task Expired'), ('task_reminder', 'Task Reminder'), ('task_deadline', 'Task Deadline'), ('task_reward', 'Task Reward'), ('task_verification', 'Task Verification'), ('task_dispute', 'Task Dispute'), ('task_available', 'New Task Available'), ('task_limit_reached', 'Task Limit Reached'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_new_device', 'Login from New Device'), ('login_new_location', 'Login from New Location'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('two_factor_enabled', '2FA Enabled'), ('two_factor_disabled', '2FA Disabled'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_pending', 'KYC Pending'), ('kyc_submitted', 'KYC Submitted'), ('fraud_detected', 'Fraud Detected'), ('security_alert', 'Security Alert'), ('promotion', 'Promotion'), ('offer', 'Offer'), ('discount', 'Discount'), ('coupon', 'Coupon'), ('sale', 'Sale'), ('flash_sale', 'Flash Sale'), ('new_arrival', 'New Arrival'), ('restock', 'Restock'), ('price_drop', 'Price Drop'), ('abandoned_cart', 'Abandoned Cart'), ('wishlist', 'Wishlist'), ('product_review', 'Product Review'), ('survey', 'Survey'), ('feedback', 'Feedback'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('friend_rejected', 'Friend Rejected'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('message', 'Message'), ('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('mention', 'Mention'), ('tag', 'Tag'), ('invite', 'Invite'), ('group_invite', 'Group Invite'), ('group_join', 'Group Join'), ('group_leave', 'Group Leave'), ('event_invite', 'Event Invite'), ('event_reminder', 'Event Reminder'), ('referral_signup', 'Referral Signup'), ('referral_completed', 'Referral Completed'), ('referral_reward', 'Referral Reward'), ('referral_expired', 'Referral Expired'), ('offer_completed', 'Offer/Offerwall Completed'), ('offer_available', 'New Offer Available'), ('postback_received', 'Advertiser Postback Received'), ('postback_failed', 'Postback Failed'), ('ip_fraud_blocked', 'IP/Fraud Blocked'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated'), ('account_warning', 'Account Warning'), ('affiliate_commission', 'Affiliate Commission Earned'), ('sub_affiliate_earn', 'Sub-Affiliate Earning'), ('leaderboard_update', 'Leaderboard Position Update'), ('publisher_payout', 'Publisher Payout'), ('conversion_received', 'Conversion Received'), ('campaign_live', 'Campaign Went Live'), ('campaign_paused', 'Campaign Paused'), ('referral_bonus', 'Referral Bonus'), ('team_bonus', 'Team Bonus'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_reply', 'Ticket Reply'), ('ticket_escalated', 'Ticket Escalated'), ('live_chat', 'Live Chat'), ('chat_message', 'Chat Message'), ('chat_request', 'Chat Request'), ('faq_suggestion', 'FAQ Suggestion'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('achievement_unlocked', 'Achievement Unlocked'), ('milestone_reached', 'Milestone Reached'), ('rank_up', 'Rank Up'), ('streak', 'Streak'), ('daily_streak', 'Daily Streak'), ('weekly_streak', 'Weekly Streak'), ('monthly_streak', 'Monthly Streak'), ('challenge_completed', 'Challenge Completed'), ('contest_won', 'Contest Won'), ('contest_participation', 'Contest Participation'), ('daily_reward', 'Daily Reward'), ('streak_reward', 'Streak Reward'), ('weekly_reward', 'Weekly Reward'), ('monthly_reward', 'Monthly Reward'), ('spin_wheel', 'Spin Wheel'), ('scratch_card', 'Scratch Card'), ('lucky_draw', 'Lucky Draw'), ('quiz_completed', 'Quiz Completed'), ('trivia_winner', 'Trivia Winner'), ('mini_game', 'Mini Game'), ('user_registered', 'User Registered'), ('user_verified', 'User Verified'), ('user_blocked', 'User Blocked'), ('user_deleted', 'User Deleted'), ('content_reported', 'Content Reported'), ('content_removed', 'Content Removed'), ('content_approved', 'Content Approved'), ('moderation', 'Moderation'), ('admin_alert', 'Admin Alert'), ('system_error', 'System Error'), ('database_backup', 'Database Backup'), ('server_maintenance', 'Server Maintenance'), ('ad_viewed', 'Ad Viewed'), ('ad_clicked', 'Ad Clicked'), ('ad_completed', 'Ad Completed'), ('video_watched', 'Video Watched'), ('article_read', 'Article Read'), ('app_installed', 'App Installed'), ('app_reviewed', 'App Reviewed'), ('survey_completed', 'Survey Completed'), ('poll_voted', 'Poll Voted'), ('custom', 'Custom'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('warning', 'Warning'), ('info', 'Information'), ('success', 'Success'), ('error', 'Error'), ('general', 'General')], default='general', max_length=50, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Bengali, null=True, blank=True)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title (English, null=True, blank=True)'),
        ),
        migrations.AlterField(
            model_name='optouttracking',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('browser', 'Browser Push'), ('all', 'All Channels')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='optouttracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optouttracking',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True = user is opted out; False = re-subscribed'),
        ),
        migrations.AlterField(
            model_name='optouttracking',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional free-text reason'),
        ),
        migrations.AlterField(
            model_name='optouttracking',
            name='opted_in_at',
            field=models.DateTimeField(blank=True, help_text='When the user re-subscribed (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='pushdeliverylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushdeliverylog',
            name='provider',
            field=models.CharField(blank=True, help_text='fcm / apns / web_push', max_length=50),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='apns_token',
            field=models.CharField(blank=True, help_text='Apple Push Notification service device token', max_length=500),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging registration token', max_length=500),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='web_push_subscription',
            field=models.JSONField(blank=True, default=dict, help_text='Web push subscription object (endpoint, p256dh, auth)'),
        ),
        migrations.AlterField(
            model_name='smsdeliverylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='campaignsegment',
            index=models.Index(fields=['segment_type'], name='notificatio_segment_eed1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsegment',
            index=models.Index(fields=['campaign'], name='notificatio_campaig_1913a1_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrate',
            index=models.Index(fields=['date', 'channel'], name='notificatio_date_a1bccb_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_1a5f25_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['created_at'], name='notificatio_created_1aea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='inappmessage',
            index=models.Index(fields=['user', 'expires_at'], name='notificatio_user_id_39cceb_idx'),
        ),
        migrations.AddIndex(
            model_name='inappmessage',
            index=models.Index(fields=['message_type'], name='notificatio_message_3cf97f_idx'),
        ),
        migrations.AddIndex(
            model_name='inappmessage',
            index=models.Index(fields=['created_at'], name='notificatio_created_5da395_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['status'], name='notificatio_status_431dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['created_at'], name='notificatio_created_0fbe0a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status'], name='notificatio_status_203ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['send_at'], name='notificatio_send_at_66b666_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['created_at'], name='notificatio_created_00d10b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationfatigue',
            index=models.Index(fields=['is_fatigued'], name='notificatio_is_fati_e7dfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationfatigue',
            index=models.Index(fields=['user'], name='notificatio_user_id_1426b4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinsight',
            index=models.Index(fields=['date', 'channel'], name='notificatio_date_fb8993_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_a6050c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationretry',
            index=models.Index(fields=['retry_at'], name='notificatio_retry_a_b22fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationschedule',
            index=models.Index(fields=['send_at'], name='notificatio_send_at_78b68a_idx'),
        ),
        migrations.AddIndex(
            model_name='optouttracking',
            index=models.Index(fields=['channel', 'is_active'], name='notificatio_channel_90b3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='optouttracking',
            index=models.Index(fields=['opted_out_at'], name='notificatio_opted_o_86898a_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdeliverylog',
            index=models.Index(fields=['device', 'status'], name='notificatio_device__908dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdeliverylog',
            index=models.Index(fields=['created_at'], name='notificatio_created_cb37b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['fcm_token'], name='notificatio_fcm_tok_564db9_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['apns_token'], name='notificatio_apns_to_91f33e_idx'),
        ),
        migrations.AddIndex(
            model_name='smsdeliverylog',
            index=models.Index(fields=['phone'], name='notificatio_phone_fedc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='smsdeliverylog',
            index=models.Index(fields=['created_at'], name='notificatio_created_4691e6_idx'),
        ),
        migrations.DeleteModel(
            name='NewNotificationCampaign',
        ),
    ]
