# Generated by Django 5.0.11 on 2026-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_newnotificationcampaign_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
