# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='backup',
            name='delta_base',
            field=models.ForeignKey(blank=True, help_text='Base backup for delta/incremental', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delta_children', to='backup.backup'),
        ),
        migrations.AddField(
            model_name='backup',
            name='parent_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_backups', to='backup.backup', verbose_name='Parent Backup'),
        ),
        migrations.AddField(
            model_name='backup',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_backups', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup.backup', verbose_name='Related Backup'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='backupnotificationconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='backup',
            name='notification_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backup.backupnotificationconfig', verbose_name='Notification Configuration'),
        ),
        migrations.AddField(
            model_name='backuprestoration',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restorations', to='backup.backup', verbose_name='Backup'),
        ),
        migrations.AddField(
            model_name='backuprestoration',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_restorations', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By'),
        ),
        migrations.AddField(
            model_name='backuprestoration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_restorations', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='backuprestoration',
            name='rollback_to_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_from', to='backup.backup', verbose_name='Rollback to Backup'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='restoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='backup.backuprestoration', verbose_name='Related Restoration'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='backup.backupschedule', verbose_name='Related Schedule'),
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backup.backupschedule', verbose_name='Backup Schedule'),
        ),
        migrations.AddField(
            model_name='backup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_backups', to='backup.backupschedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='backupstoragelocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='deltabackuptracker',
            name='child_backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_child', to='backup.backup', verbose_name='Child Backup'),
        ),
        migrations.AddField(
            model_name='deltabackuptracker',
            name='parent_backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_parent', to='backup.backup', verbose_name='Parent Backup'),
        ),
        migrations.AddField(
            model_name='retentionpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='backup',
            name='retention_policy_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backup.retentionpolicy', verbose_name='Retention Policy'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['frequency'], name='backup_sche_frequen_fed0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['is_active'], name='backup_sche_is_acti_0ae4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['next_run'], name='backup_sche_next_ru_d2af0c_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['last_run_status'], name='backup_sche_last_ru_0e2571_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['timestamp'], name='backup_logs_timesta_007b17_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['level'], name='backup_logs_level_950207_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['category'], name='backup_logs_categor_e35a09_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['action'], name='backup_logs_action_612971_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['source'], name='backup_logs_source_b48d74_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup'], name='backup_logs_backup__49c239_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['user'], name='backup_logs_user_id_b7bfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['is_processed'], name='backup_logs_is_proc_dd0ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['requires_attention'], name='backup_logs_require_e15be5_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['error_code'], name='backup_logs_error_c_24a007_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['storage_type'], name='backup_logs_storage_c7112a_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-timestamp', 'level'], name='backup_logs_timesta_fb80d2_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-timestamp', 'category'], name='backup_logs_timesta_4f7972_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-timestamp', 'backup'], name='backup_logs_timesta_a3ce9a_idx'),
        ),
        migrations.AddIndex(
            model_name='backupstoragelocation',
            index=models.Index(fields=['storage_type'], name='backup_stor_storage_3f6ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='backupstoragelocation',
            index=models.Index(fields=['status'], name='backup_stor_status_5c15dc_idx'),
        ),
        migrations.AddIndex(
            model_name='backupstoragelocation',
            index=models.Index(fields=['is_default'], name='backup_stor_is_defa_91c12b_idx'),
        ),
        migrations.AddIndex(
            model_name='backupstoragelocation',
            index=models.Index(fields=['priority'], name='backup_stor_priorit_dd8cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='deltabackuptracker',
            index=models.Index(fields=['parent_backup'], name='delta_backu_parent__fec837_idx'),
        ),
        migrations.AddIndex(
            model_name='deltabackuptracker',
            index=models.Index(fields=['child_backup'], name='delta_backu_child_b_351109_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deltabackuptracker',
            unique_together={('parent_backup', 'child_backup')},
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_id'], name='backup_hist_backup__1853eb_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status'], name='backup_hist_status_75c2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_type'], name='backup_hist_backup__0f7207_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_by'], name='backup_hist_created_8ac395_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['start_time'], name='backup_hist_start_t_8ef0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['database_name'], name='backup_hist_databas_a2a035_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['is_healthy'], name='backup_hist_is_heal_947203_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['retention_policy'], name='backup_hist_retenti_96fc58_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['health_score'], name='backup_hist_health__474b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['storage_type'], name='backup_hist_storage_59ccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_at'], name='backup_hist_created_67331f_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['expires_at'], name='backup_hist_expires_2da7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['verified'], name='backup_hist_verifie_089db3_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['encryption_enabled'], name='backup_hist_encrypt_c3fbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['compression_enabled'], name='backup_hist_compres_62d5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_schedule'], name='backup_hist_backup__9bd917_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['retention_policy_ref'], name='backup_hist_retenti_0a125a_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['parent_backup'], name='backup_hist_parent__836409_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['delta_base'], name='backup_hist_delta_b_ad1680_idx'),
        ),
        migrations.AddConstraint(
            model_name='backup',
            constraint=models.UniqueConstraint(fields=('name', 'database_name'), name='unique_backup_name_per_database'),
        ),
    ]
