# Generated by Django 5.0.11 on 2026-03-03 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backupnotificationconfig_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_backups', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
