# Generated by Django 5.0.11 on 2026-03-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_backup_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_backups', to='backup.backupschedule', verbose_name='Schedule'),
        ),
    ]
