# Generated by Django 5.0.11 on 2026-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_backup_schedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='backup',
            name='file_size_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='backup',
            name='health_score_range',
        ),
    ]
