# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dr_alert_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_name', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20, null=True)),
                ('message', models.TextField()),
                ('metric', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='DRBackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dr_job_id', models.CharField(blank=True, help_text='ID from DR system', max_length=100, null=True, unique=True)),
                ('backup_type', models.CharField(blank=True, choices=[('full', 'Full'), ('incremental', 'Incremental'), ('differential', 'Differential')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20, null=True)),
                ('source_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('compressed_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_path', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DRDrillRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dr_drill_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('scenario_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('achieved_rto_seconds', models.FloatField(blank=True, null=True)),
                ('target_rto_seconds', models.IntegerField(blank=True, null=True)),
                ('achieved_rpo_seconds', models.FloatField(blank=True, null=True)),
                ('target_rpo_seconds', models.IntegerField(blank=True, null=True)),
                ('participants', models.JSONField(default=list)),
                ('lessons_learned', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DRFailoverEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dr_failover_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('failover_type', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('drill', 'Drill')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], max_length=20, null=True)),
                ('primary_node', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_node', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_reason', models.TextField()),
                ('rto_achieved_seconds', models.FloatField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_drill', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DRRestoreRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dr_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('restore_type', models.CharField(blank=True, choices=[('full', 'Full'), ('partial', 'Partial'), ('table', 'Table'), ('point_in_time', 'Point In Time')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20, null=True)),
                ('target_database', models.CharField(blank=True, max_length=100, null=True)),
                ('point_in_time', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DRSystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_health', models.CharField(blank=True, default='unknown', max_length=20, null=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_failover_at', models.DateTimeField(blank=True, null=True)),
                ('replication_lag_seconds', models.FloatField(blank=True, null=True)),
                ('active_incidents', models.IntegerField(default=0)),
                ('active_alerts', models.IntegerField(default=0)),
                ('rto_achieved_seconds', models.FloatField(blank=True, null=True)),
                ('rpo_achieved_seconds', models.FloatField(blank=True, null=True)),
                ('raw_status', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DR System Status',
                'verbose_name_plural': 'DR System Status',
            },
        ),
    ]
