# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dr_integration', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dralert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dralert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='drbackuprecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='drbackuprecord',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drdrillrecord',
            name='planned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drfailoverevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='drfailoverevent',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drrestorerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr_restore_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drrestorerecord',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr_restore_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drrestorerecord',
            name='source_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr_integration.drbackuprecord'),
        ),
        migrations.AddField(
            model_name='drrestorerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='drbackuprecord',
            index=models.Index(fields=['status', 'created_at'], name='dr_integrat_status_300408_idx'),
        ),
        migrations.AddIndex(
            model_name='drbackuprecord',
            index=models.Index(fields=['tenant', 'status'], name='dr_integrat_tenant__e8ac0f_idx'),
        ),
    ]
