# Generated by Django 5.0.11 on 2026-04-09 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drsystemstatus',
            options={'verbose_name': 'DR System Status', 'verbose_name_plural': 'DR System Status'},
        ),
        migrations.RenameIndex(
            model_name='drbackuprecord',
            new_name='dr_integrat_status_300408_idx',
            old_name='dr_backup_status_idx',
        ),
        migrations.RenameIndex(
            model_name='drbackuprecord',
            new_name='dr_integrat_tenant__e8ac0f_idx',
            old_name='dr_backup_tenant_idx',
        ),
        migrations.AlterField(
            model_name='dralert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drbackuprecord',
            name='dr_job_id',
            field=models.CharField(help_text='ID from DR system', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='drbackuprecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drdrillrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drfailoverevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drrestorerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drsystemstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
