# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_integration', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drbackuprecord',
            new_name='idx_status_created_at_993',
            old_name='dr_integrat_status_300408_idx',
        ),
        migrations.RenameIndex(
            model_name='drbackuprecord',
            new_name='idx_tenant_status_994',
            old_name='dr_integrat_tenant__e8ac0f_idx',
        ),
    ]
