# Generated by Django 5.0.11 on 2026-03-16 03:10

import api.alerts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdashboardconfig',
            name='dashboard_layout',
            field=models.JSONField(default=api.alerts.models.get_default_dashboard_layout, help_text='Widget layout configuration'),
        ),
    ]
