# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertchannel_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertcorrelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertcorrelation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertcorrelation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertdashboardconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertdashboardconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_alertdashboardconfig_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertescalation',
            name='escalate_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertescalation_escalate_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertescalation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertgroup_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertlog_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertnoise',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertnoise_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertnoise',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertprediction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertprediction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertprediction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertrecipient_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_alertrecipient_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertreport_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertreport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertrule_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertprediction',
            name='target_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_target', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertnoise',
            name='target_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_target', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='rules',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertescalation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertcorrelation',
            name='primary_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_primary', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertcorrelation',
            name='secondary_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_secondary', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertrulehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertrulehistory_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrulehistory',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertrulehistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertschedule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alertsuppression',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alertsuppression_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertsuppression',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='alertsuppression',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_alerttemplate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_anomalydetectionmodel_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='target_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_target', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channelhealthlog',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertchannel'),
        ),
        migrations.AddField(
            model_name='channelhealthlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channelratelimit',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertchannel'),
        ),
        migrations.AddField(
            model_name='channelratelimit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channelroute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_channelroute_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelroute',
            name='destination_channels',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_destination', to='alerts.alertchannel'),
        ),
        migrations.AddField(
            model_name='channelroute',
            name='source_channels',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_source', to='alerts.alertchannel'),
        ),
        migrations.AddField(
            model_name='channelroute',
            name='source_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_source', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='channelroute',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incident_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incident_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_alerts',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertlog'),
        ),
        migrations.AddField(
            model_name='incident',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incident_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentpostmortem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incidentpostmortem_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentpostmortem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incidentpostmortem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentpostmortem',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.incident'),
        ),
        migrations.AddField(
            model_name='incidentpostmortem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incidentpostmortem_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentpostmortem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='incidentresponder',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.incident'),
        ),
        migrations.AddField(
            model_name='incidentresponder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='incidentresponder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_incidentresponder_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_incidenttimeline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.incident'),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mttdmetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mttrmetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='alert_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertlog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='backup_users',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_backup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_oncallschedule_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='escalation_users',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_escalation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='primary_users',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_rootcauseanalysis_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='related_alerts',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_alerts', to='alerts.alertlog'),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_rootcauseanalysis_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='slabreach',
            name='alert_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertlog'),
        ),
        migrations.AddField(
            model_name='slabreach',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_slabreach_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slabreach',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_slabreach_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slabreach',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='alert_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='systemhealthcheck',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='thresholdbreach',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_thresholdbreach_acknowledged_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thresholdbreach',
            name='alert_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertlog'),
        ),
        migrations.AddField(
            model_name='thresholdbreach',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_thresholdbreach_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thresholdbreach',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='alert_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_thresholdconfig_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='thresholdbreach',
            name='threshold_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.thresholdconfig'),
        ),
        migrations.AddField(
            model_name='adaptivethreshold',
            name='threshold_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.thresholdconfig'),
        ),
        migrations.AddField(
            model_name='thresholdhistory',
            name='adaptive_threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='alerts.adaptivethreshold'),
        ),
        migrations.AddField(
            model_name='thresholdhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_thresholdhistory_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thresholdhistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='thresholdprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_thresholdprofile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thresholdprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='alertanalytics',
            index=models.Index(fields=['date'], name='alerts_aler_date_834cea_idx'),
        ),
        migrations.AddIndex(
            model_name='alertanalytics',
            index=models.Index(fields=['resolution_rate'], name='alerts_aler_resolut_8f2567_idx'),
        ),
        migrations.AddIndex(
            model_name='alertanalytics',
            index=models.Index(fields=['total_notification_cost'], name='alerts_aler_total_n_9fab4d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertanalytics',
            index=models.Index(fields=['total_alerts', 'date'], name='alerts_aler_total_a_9b1ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='alertchannel',
            index=models.Index(fields=['channel_type', 'is_enabled'], name='alerts_aler_channel_18283a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertchannel',
            index=models.Index(fields=['status'], name='alerts_aler_status_d0121a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertchannel',
            index=models.Index(fields=['priority'], name='alerts_aler_priorit_132876_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['recipient_type', 'is_active'], name='alerts_aler_recipie_1c010b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['priority'], name='alerts_aler_priorit_55a924_idx'),
        ),
        migrations.AddIndex(
            model_name='alertreport',
            index=models.Index(fields=['report_type', 'status'], name='alerts_aler_report__ffbde1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertreport',
            index=models.Index(fields=['generated_at'], name='alerts_aler_generat_14e094_idx'),
        ),
        migrations.AddIndex(
            model_name='alertreport',
            index=models.Index(fields=['next_run'], name='alerts_aler_next_ru_c6fc19_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_active', 'alert_type'], name='alerts_aler_is_acti_53c8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['severity', 'last_triggered'], name='alerts_aler_severit_912ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['created_at'], name='alerts_aler_created_5cfb95_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='rule_name_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertprediction',
            index=models.Index(fields=['prediction_type', 'is_active'], name='alerts_aler_predict_560df3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertprediction',
            index=models.Index(fields=['training_status', 'last_trained'], name='alerts_aler_trainin_2a7be1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnoise',
            index=models.Index(fields=['noise_type', 'is_active'], name='alerts_aler_noise_t_831a79_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnoise',
            index=models.Index(fields=['action', 'is_active'], name='alerts_aler_action_7ffc95_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['triggered_at'], name='alerts_aler_trigger_8995e0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['is_resolved', 'triggered_at'], name='alerts_aler_is_reso_7b9f78_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['rule', 'triggered_at'], name='alerts_aler_rule_id_7f6d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['triggered_at'], name='triggered_at_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='details_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertgroup',
            index=models.Index(fields=['is_active'], name='alerts_aler_is_acti_475e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertgroup',
            index=models.Index(fields=['group_notification_enabled'], name='alerts_aler_group_n_598f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertgroup',
            index=models.Index(fields=['cached_alert_count'], name='alerts_aler_cached__05e94a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertescalation',
            index=models.Index(fields=['is_active', 'level'], name='alerts_aler_is_acti_1de330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertescalation',
            unique_together={('rule', 'level')},
        ),
        migrations.AddIndex(
            model_name='alertcorrelation',
            index=models.Index(fields=['correlation_type', 'status'], name='alerts_aler_correla_fbbc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcorrelation',
            index=models.Index(fields=['status', 'last_analyzed'], name='alerts_aler_status_673719_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrulehistory',
            index=models.Index(fields=['rule', 'changed_at'], name='alerts_aler_rule_id_fbd49c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrulehistory',
            index=models.Index(fields=['changed_by', 'changed_at'], name='alerts_aler_changed_fce86d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrulehistory',
            index=models.Index(fields=['action', 'changed_at'], name='alerts_aler_action_cb5c90_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrulehistory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['changed_fields'], name='changed_fields_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertschedule',
            index=models.Index(fields=['rule', 'is_active'], name='alerts_aler_rule_id_239bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='alertschedule',
            index=models.Index(fields=['is_active', 'timezone'], name='alerts_aler_is_acti_8f6ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertschedule',
            index=models.Index(fields=['is_active', 'days_of_week'], name='alerts_aler_is_acti_bb14ee_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsuppression',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='alerts_aler_is_acti_a05e36_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsuppression',
            index=models.Index(fields=['suppression_type'], name='alerts_aler_suppres_555f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsuppression',
            index=models.Index(fields=['rule', 'is_active'], name='alerts_aler_rule_id_bff0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['alert_type', 'severity'], name='alerts_aler_alert_t_567ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['is_default', 'language'], name='alerts_aler_is_defa_161af9_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['alert_type', 'is_default'], name='alerts_aler_alert_t_37e5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionmodel',
            index=models.Index(fields=['detection_method', 'is_active'], name='alerts_anom_detecti_01b073_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionmodel',
            index=models.Index(fields=['last_trained'], name='alerts_anom_last_tr_23eb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='channelhealthlog',
            index=models.Index(fields=['channel', 'checked_at'], name='alerts_chan_channel_520e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='channelhealthlog',
            index=models.Index(fields=['status', 'checked_at'], name='alerts_chan_status_aa3132_idx'),
        ),
        migrations.AddIndex(
            model_name='channelhealthlog',
            index=models.Index(fields=['check_type', 'checked_at'], name='alerts_chan_check_t_3424f0_idx'),
        ),
        migrations.AddIndex(
            model_name='channelratelimit',
            index=models.Index(fields=['channel', 'limit_type'], name='alerts_chan_channel_29c793_idx'),
        ),
        migrations.AddIndex(
            model_name='channelroute',
            index=models.Index(fields=['route_type', 'is_active'], name='alerts_chan_route_t_cdb03d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelroute',
            index=models.Index(fields=['priority'], name='alerts_chan_priorit_97d204_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'detected_at'], name='alerts_inci_status_b78ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'detected_at'], name='alerts_inci_severit_65f2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assigned_to', 'status'], name='alerts_inci_assigne_0cbeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['detected_at'], name='alerts_inci_detecte_1c2898_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentpostmortem',
            index=models.Index(fields=['incident'], name='alerts_inci_inciden_a480f4_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentpostmortem',
            index=models.Index(fields=['status', 'created_at'], name='alerts_inci_status_e1b167_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentpostmortem',
            index=models.Index(fields=['published_at'], name='alerts_inci_publish_05e2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentresponder',
            index=models.Index(fields=['incident', 'role'], name='alerts_inci_inciden_80f128_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentresponder',
            index=models.Index(fields=['user', 'status'], name='alerts_inci_user_id_39c0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentresponder',
            index=models.Index(fields=['status', 'assigned_at'], name='alerts_inci_status_27ba6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentresponder',
            unique_together={('incident', 'user')},
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['incident', 'timestamp'], name='alerts_inci_inciden_f3b420_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['event_type', 'timestamp'], name='alerts_inci_event_t_144e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='mttdmetric',
            index=models.Index(fields=['last_calculated'], name='alerts_mttd_last_ca_f6f226_idx'),
        ),
        migrations.AddIndex(
            model_name='mttrmetric',
            index=models.Index(fields=['last_calculated'], name='alerts_mttr_last_ca_419881_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='alerts_noti_status_5a4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='alerts_noti_notific_d1f017_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['alert_log', 'created_at'], name='alerts_noti_alert_l_98d947_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='alerts_noti_recipie_6c700f_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallschedule',
            index=models.Index(fields=['schedule_type', 'is_active'], name='alerts_onca_schedul_c85e92_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallschedule',
            index=models.Index(fields=['is_active'], name='alerts_onca_is_acti_f7f1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='rootcauseanalysis',
            index=models.Index(fields=['analysis_method', 'status'], name='alerts_root_analysi_9160fa_idx'),
        ),
        migrations.AddIndex(
            model_name='rootcauseanalysis',
            index=models.Index(fields=['completed_at'], name='alerts_root_complet_dfe4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['sla_type', 'status'], name='alerts_slab_sla_typ_c01fce_idx'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['severity', 'breach_time'], name='alerts_slab_severit_2f1c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['alert_log', 'breach_time'], name='alerts_slab_alert_l_2742f3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['check_type', 'status'], name='alerts_syst_check_t_20cf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['is_active', 'next_check'], name='alerts_syst_is_acti_2de4df_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['status', 'last_checked'], name='alerts_syst_status_80e02e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['priority', 'is_active'], name='alerts_syst_priorit_2c850b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['-timestamp'], name='alerts_syst_timesta_e5ae62_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['data_source', 'timestamp'], name='alerts_syst_data_so_f94083_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdconfig',
            index=models.Index(fields=['alert_rule', 'is_active'], name='alerts_thre_alert_r_3f82bd_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdconfig',
            index=models.Index(fields=['threshold_type', 'is_active'], name='alerts_thre_thresho_551b16_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdconfig',
            index=models.Index(fields=['last_calculated'], name='alerts_thre_last_ca_7a8e14_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['threshold_config', 'detected_at'], name='alerts_thre_thresho_ba35a6_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['severity', 'detected_at'], name='alerts_thre_severit_6f3153_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['resolved_at'], name='alerts_thre_resolve_4bb555_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['acknowledged_at'], name='alerts_thre_acknowl_7fb634_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivethreshold',
            index=models.Index(fields=['threshold_config'], name='alerts_adap_thresho_ee35c1_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivethreshold',
            index=models.Index(fields=['last_adaptation'], name='alerts_adap_last_ad_594c07_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivethreshold',
            index=models.Index(fields=['adaptation_method'], name='alerts_adap_adaptat_00c681_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdhistory',
            index=models.Index(fields=['adaptive_threshold', 'created_at'], name='alerts_thre_adaptiv_74b234_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdhistory',
            index=models.Index(fields=['change_type', 'created_at'], name='alerts_thre_change__21722b_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdprofile',
            index=models.Index(fields=['profile_type', 'is_active'], name='alerts_thre_profile_fdaf01_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdprofile',
            index=models.Index(fields=['is_default'], name='alerts_thre_is_defa_b81239_idx'),
        ),
    ]
