# Generated by Django 5.0.11 on 2026-03-18 05:34
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('alerts', '0002_alertdashboardconfig_dashboard_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.RemoveIndex(
            model_name='alertlog',
            name='details_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertrule',
            name='rule_name_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertrulehistory',
            name='changed_fields_gin_idx',
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='details_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['name'], name='rule_name_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrulehistory',
            index=models.Index(fields=['changed_fields'], name='changed_fields_gin_idx'),
        ),
    ]
