# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_rename_alerts_adap_thresho_ee35c1_idx_idx_threshold_config_778_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertanalytics',
            new_name='idx_total_notification_cos_779',
            old_name='idx_total_notification_cost_722',
        ),
        migrations.RenameIndex(
            model_name='alertchannel',
            new_name='idx_channel_type_is_enable_146',
            old_name='idx_channel_type_is_enabled_692',
        ),
        migrations.RenameIndex(
            model_name='alertcorrelation',
            new_name='idx_correlation_type_statu_37e',
            old_name='idx_correlation_type_status_753',
        ),
        migrations.RenameIndex(
            model_name='alertgroup',
            new_name='idx_group_notification_ena_34e',
            old_name='idx_group_notification_enabled_725',
        ),
        migrations.RenameIndex(
            model_name='alertlog',
            new_name='idx_is_resolved_triggered__2b2',
            old_name='idx_is_resolved_triggered_at_707',
        ),
        migrations.RenameIndex(
            model_name='alertprediction',
            new_name='idx_prediction_type_is_act_a12',
            old_name='idx_prediction_type_is_active_755',
        ),
        migrations.RenameIndex(
            model_name='alertprediction',
            new_name='idx_training_status_last_t_5ce',
            old_name='idx_training_status_last_trained_756',
        ),
        migrations.RenameIndex(
            model_name='alertrecipient',
            new_name='idx_recipient_type_is_acti_266',
            old_name='idx_recipient_type_is_active_701',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='idx_severity_last_triggere_51f',
            old_name='idx_severity_last_triggered_704',
        ),
        migrations.RenameIndex(
            model_name='alertsuppression',
            new_name='idx_is_active_start_time_e_f97',
            old_name='idx_is_active_start_time_end_time_727',
        ),
        migrations.RenameIndex(
            model_name='anomalydetectionmodel',
            new_name='idx_detection_method_is_ac_f7c',
            old_name='idx_detection_method_is_active_757',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='idx_notification_type_crea_6b0',
            old_name='idx_notification_type_created_at_710',
        ),
        migrations.RenameIndex(
            model_name='oncallschedule',
            new_name='idx_schedule_type_is_activ_172',
            old_name='idx_schedule_type_is_active_751',
        ),
        migrations.RenameIndex(
            model_name='thresholdbreach',
            new_name='idx_threshold_config_detec_ea1',
            old_name='idx_threshold_config_detected_at_774',
        ),
        migrations.RenameIndex(
            model_name='thresholdconfig',
            new_name='idx_threshold_type_is_acti_ccc',
            old_name='idx_threshold_type_is_active_772',
        ),
        migrations.RenameIndex(
            model_name='thresholdhistory',
            new_name='idx_adaptive_threshold_cre_3f8',
            old_name='idx_adaptive_threshold_created_at_781',
        ),
    ]
