"""
Constants for Disaster Recovery System
"""

# RTO/RPO defaults (in seconds)
DEFAULT_RTO_SECONDS = 3600       # 1 hour
DEFAULT_RPO_SECONDS = 900        # 15 minutes
CRITICAL_RTO_SECONDS = 300       # 5 minutes
CRITICAL_RPO_SECONDS = 60        # 1 minute

# Backup retention defaults
DEFAULT_FULL_BACKUP_RETENTION_DAYS = 30
DEFAULT_INCREMENTAL_BACKUP_RETENTION_DAYS = 7
DEFAULT_DIFFERENTIAL_BACKUP_RETENTION_DAYS = 14
ARCHIVE_RETENTION_DAYS = 2555    # 7 years for compliance

# Health check intervals (seconds)
HEALTH_CHECK_INTERVAL = 30
CRITICAL_HEALTH_CHECK_INTERVAL = 10
REPLICATION_LAG_THRESHOLD_SECONDS = 60

# Failover thresholds
FAILOVER_HEALTH_CHECK_FAILURES = 3
FAILOVER_TIMEOUT_SECONDS = 300
AUTO_FAILBACK_WAIT_SECONDS = 600

# Storage limits
MAX_BACKUP_SIZE_GB = 10240       # 10 TB
MIN_STORAGE_FREE_PERCENT = 20    # Trigger alert if < 20% free
COMPRESSION_RATIO_TARGET = 0.4   # Target 40% of original size

# Encryption
ENCRYPTION_ALGORITHM = "AES-256-GCM"
KEY_ROTATION_DAYS = 90

# Alert thresholds
CPU_ALERT_THRESHOLD = 85.0       # percent
MEMORY_ALERT_THRESHOLD = 90.0
DISK_ALERT_THRESHOLD = 85.0
NETWORK_LATENCY_THRESHOLD_MS = 200

# Retry settings
MAX_BACKUP_RETRY_ATTEMPTS = 3
BACKUP_RETRY_DELAY_SECONDS = 300
MAX_RESTORE_RETRY_ATTEMPTS = 2

# Pagination
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 500

# DR Drill
DRILL_MIN_INTERVAL_DAYS = 30
DRILL_TIMEOUT_HOURS = 4

# SLA defaults
DEFAULT_SLA_UPTIME_PERCENT = 99.9
HIGH_AVAILABILITY_SLA_PERCENT = 99.99

# API versioning
API_VERSION = "v1"
API_PREFIX = f"/api/{API_VERSION}"

# Audit
AUDIT_LOG_RETENTION_DAYS = 365 * 7   # 7 years

# Notification
ALERT_COOLDOWN_SECONDS = 300
ESCALATION_WAIT_MINUTES = 15
