# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_networks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconversion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adnetworkwebhooklog',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad_networks.offerconversion'),
        ),
        migrations.AddField(
            model_name='offerperformanceanalytics',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='offersynclog',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='ad_networks.adnetwork'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='ad_networks',
            field=models.ManyToManyField(related_name='offerwalls', to='ad_networks.adnetwork'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offerwalls', to='ad_networks.offercategory'),
        ),
        migrations.AddField(
            model_name='smartofferrecommendation',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='smartofferrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='engagement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='ad_networks.userofferengagement'),
        ),
        migrations.AddField(
            model_name='adnetworkwebhooklog',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad_networks.userofferengagement'),
        ),
        migrations.AddField(
            model_name='userofferlimit',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_limits', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='userofferlimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='networkstatistic',
            unique_together={('ad_network', 'date')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'is_featured'], name='ad_networks_status_0f5996_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['external_id'], name='ad_networks_externa_60ec3f_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['ad_network', 'status'], name='ad_networks_ad_netw_9c617f_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['category', 'status'], name='ad_networks_categor_a56842_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['reward_amount'], name='ad_networks_reward__2ffd77_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['expires_at'], name='ad_networks_expires_1eb6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwall',
            index=models.Index(fields=['wall_type', 'is_active'], name='ad_networks_wall_ty_554783_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwall',
            index=models.Index(fields=['slug'], name='ad_networks_slug_498097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smartofferrecommendation',
            unique_together={('user', 'offer')},
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['click_id'], name='ad_networks_click_i_26eb14_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['conversion_id'], name='ad_networks_convers_7ebbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['user', 'status'], name='ad_networks_user_id_61ec92_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['offer', 'status'], name='ad_networks_offer_i_4137ca_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['created_at'], name='ad_networks_created_2a019e_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferengagement',
            index=models.Index(fields=['status', 'created_at'], name='ad_networks_status_904e99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userofferengagement',
            unique_together={('user', 'offer', 'click_id')},
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['conversion_status'], name='ad_networks_convers_11feb2_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['fraud_score'], name='ad_networks_fraud_s_cca49c_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['chargeback_processed'], name='ad_networks_chargeb_215420_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['created_at'], name='ad_networks_created_87bb73_idx'),
        ),
        migrations.AddIndex(
            model_name='adnetworkwebhooklog',
            index=models.Index(fields=['ad_network', 'processed'], name='ad_networks_ad_netw_3ca788_idx'),
        ),
        migrations.AddIndex(
            model_name='adnetworkwebhooklog',
            index=models.Index(fields=['created_at'], name='ad_networks_created_92ed79_idx'),
        ),
        migrations.AddIndex(
            model_name='adnetworkwebhooklog',
            index=models.Index(fields=['event_type'], name='ad_networks_event_t_e36abf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userofferlimit',
            unique_together={('user', 'offer')},
        ),
    ]
