# Generated by Django 5.0.11 on 2026-02-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_networks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adnetworkwebhooklog',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='network_type',
            field=models.CharField(blank=True, choices=[('admob', 'Google AdMob'), ('unity', 'Unity Ads'), ('ironsource', 'IronSource'), ('applovin', 'AppLovin'), ('tapjoy', 'Tapjoy'), ('vungle', 'Vungle'), ('adscend', 'Adscend Media'), ('offertoro', 'OfferToro'), ('adgem', 'AdGem'), ('ayetstudios', 'Ayetstudios'), ('lootably', 'Lootably'), ('revenueuniverse', 'Revenue Universe'), ('adgate', 'AdGate Media'), ('cpalead', 'CPAlead'), ('adworkmedia', 'AdWork Media'), ('wannads', 'Wannads'), ('personaly', 'Persona.ly'), ('kiwiwall', 'KiwiWall'), ('monlix', 'Monlix'), ('notik', 'Notik'), ('offerdaddy', 'OfferDaddy'), ('offertown', 'OfferTown'), ('adlockmedia', 'AdLock Media'), ('offerwallpro', 'Offerwall.pro'), ('wallads', 'WallAds'), ('wallport', 'Wallport'), ('walltoro', 'WallToro'), ('pollfish', 'Pollfish'), ('cpxresearch', 'CPX Research'), ('bitlabs', 'BitLabs'), ('inbrain', 'InBrain.ai'), ('theoremreach', 'TheoremReach'), ('yoursurveys', 'YourSurveys'), ('surveysavvy', 'SurveySavvy'), ('opinionworld', 'OpinionWorld'), ('toluna', 'Toluna'), ('surveymonkey', 'SurveyMonkey'), ('swagbucks', 'Swagbucks'), ('prizerebel', 'PrizeRebel'), ('grabpoints', 'GrabPoints'), ('instagc', 'InstaGC'), ('points2shop', 'Points2Shop'), ('loottv', 'Loot.tv'), ('hideouttv', 'Hideout.tv'), ('rewardrack', 'RewardRack'), ('earnhoney', 'EarnHoney'), ('rewardxp', 'RewardXP'), ('idleempire', 'Idle-Empire'), ('gain', 'Gain.gg'), ('grindabuck', 'GrindaBuck'), ('timebucks', 'TimeBucks'), ('clixsense', 'ClixSense'), ('neobux', 'NeoBux'), ('probux', 'ProBux'), ('clixwall', 'ClixWall'), ('fyber', 'Fyber'), ('offerstation', 'OfferStation'), ('chartboost', 'Chartboost'), ('supersonic', 'Supersonic'), ('appnext', 'AppNext'), ('digitalturbine', 'Digital Turbine'), ('glispa', 'Glispa'), ('adcolony', 'AdColony'), ('inmobi', 'InMobi'), ('mopub', 'MoPub'), ('pangle', 'Pangle (by TikTok)'), ('mintegral', 'Mintegral'), ('ogury', 'Ogury'), ('verizonmedia', 'Verizon Media'), ('smaato', 'Smaato'), ('mobilefuse', 'MobileFuse'), ('leadbolt', 'Leadbolt'), ('startapp', 'StartApp'), ('mediabrix', 'Mediabrix'), ('nativex', 'NativeX'), ('heyzap', 'Heyzap'), ('kidoz', 'Kidoz'), ('pokkt', 'Pokkt'), ('youappi', 'YouAppi'), ('ampiri', 'Ampiri'), ('adincube', 'AdinCube'), ('custom1', 'Custom Network 1'), ('custom2', 'Custom Network 2'), ('custom3', 'Custom Network 3'), ('custom4', 'Custom Network 4'), ('custom5', 'Custom Network 5'), ('custom6', 'Custom Network 6'), ('custom7', 'Custom Network 7'), ('custom8', 'Custom Network 8'), ('custom9', 'Custom Network 9'), ('custom10', 'Custom Network 10')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_limits', to='ad_networks.offer'),
        ),
    ]
