# Generated by Django 5.0.11 on 2026-03-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_networks', '0003_adnetworkwebhooklog_is_processed_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedip',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='knownbadip',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.offercategory'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='engagement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.userofferengagement'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_networks_offerconversion_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerperformanceanalytics',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='offersynclog',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='ad_networks',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.adnetwork'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.offercategory'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_smartofferrecommendation_offer', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_smartofferrecommendation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_userofferengagement_offer', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_userofferengagement_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_networks_userofferengagement_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_userofferlimit_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
