# Generated by Django 5.0.11 on 2026-04-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_networks', '0003_rename_ad_networks_network_1b3b5e_idx_idx_network_type_569_and_more'),
        ('ad_networks', '0005_offerattachment_userwallet_and_more'),
    ]

    operations = [
    ]
