# Generated by Django 5.0.11 on 2026-04-22 01:11

import api.ad_networks.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_networks', '0006_merge_20260422_0657'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('request_data', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
                ('request_headers', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
                ('response_headers', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
                ('status_code', models.IntegerField()),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('timeout', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Network API Log',
                'verbose_name_plural': 'Network API Logs',
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint_checked', models.URLField(blank=True, null=True)),
                ('check_type', models.CharField(choices=[('ping', 'Ping'), ('api_call', 'API Call'), ('webhook', 'Webhook Test'), ('postback', 'Postback Test')], default='api_call', max_length=20)),
                ('uptime_percentage', models.FloatField(default=0, help_text='Uptime percentage')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Network Health Check',
                'verbose_name_plural': 'Network Health Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_fraudulent', models.BooleanField(default=False, help_text='Whether this record is flagged as fraudulent')),
                ('fraud_indicators', models.JSONField(blank=True, default=list, help_text='List of fraud indicators')),
                ('fraud_reviewed_at', models.DateTimeField(blank=True, help_text='Fraud review timestamp', null=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('is_unique', models.BooleanField(default=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('click_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device_info', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
                ('location_data', models.JSONField(blank=True, default=api.ad_networks.models.default_dict)),
            ],
            options={
                'verbose_name': 'Offer Click',
                'verbose_name_plural': 'Offer Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferDailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('count_today', models.IntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('reset_date', models.DateField(auto_now_add=True)),
                ('daily_limit', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offer Daily Limit',
                'verbose_name_plural': 'Offer Daily Limits',
            },
        ),
        migrations.CreateModel(
            name='OfferReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('fraud_score', models.FloatField(default=0.0, help_text='Fraud detection score (0-100)')),
                ('is_fraudulent', models.BooleanField(default=False, help_text='Whether this record is flagged as fraudulent')),
                ('fraud_indicators', models.JSONField(blank=True, default=list, help_text='List of fraud indicators')),
                ('fraud_reviewed_at', models.DateTimeField(blank=True, help_text='Fraud review timestamp', null=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Offer Reward',
                'verbose_name_plural': 'Offer Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Offer Tag',
                'verbose_name_plural': 'Offer Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfferTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('is_auto_tagged', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score for auto-tagging', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Offer Tagging',
                'verbose_name_plural': 'Offer Taggings',
            },
        ),
        migrations.RemoveIndex(
            model_name='offerattachment',
            name='adnet_auto_idx_001',
        ),
        migrations.RemoveIndex(
            model_name='offerattachment',
            name='adnet_auto_idx_002',
        ),
        migrations.RemoveIndex(
            model_name='userwallet',
            name='adnet_auto_idx_004',
        ),
        migrations.RemoveIndex(
            model_name='userwallet',
            name='adnet_auto_idx_005',
        ),
        migrations.RemoveIndex(
            model_name='userwallet',
            name='adnet_auto_idx_006',
        ),
        migrations.RemoveIndex(
            model_name='userwallet',
            name='adnet_auto_idx_007',
        ),
        migrations.RenameIndex(
            model_name='adnetwork',
            new_name='ad_networks_network_1b3b5e_idx',
            old_name='idx_network_type_569',
        ),
        migrations.RenameIndex(
            model_name='adnetwork',
            new_name='ad_networks_categor_202ff0_idx',
            old_name='idx_category_is_active_570',
        ),
        migrations.RenameIndex(
            model_name='adnetwork',
            new_name='ad_networks_country_bd1e2c_idx',
            old_name='idx_country_support_571',
        ),
        migrations.RenameIndex(
            model_name='adnetwork',
            new_name='ad_networks_trust_s_e096e8_idx',
            old_name='idx_trust_score_572',
        ),
        migrations.RenameIndex(
            model_name='adnetworkwebhooklog',
            new_name='ad_networks_ad_netw_3ca788_idx',
            old_name='idx_ad_network_processed_591',
        ),
        migrations.RenameIndex(
            model_name='adnetworkwebhooklog',
            new_name='ad_networks_created_92ed79_idx',
            old_name='idx_created_at_592',
        ),
        migrations.RenameIndex(
            model_name='adnetworkwebhooklog',
            new_name='ad_networks_event_t_e36abf_idx',
            old_name='idx_event_type_593',
        ),
        migrations.RenameIndex(
            model_name='blacklistedip',
            new_name='ad_networks_ip_addr_a3810a_idx',
            old_name='idx_ip_address_is_active_594',
        ),
        migrations.RenameIndex(
            model_name='blacklistedip',
            new_name='ad_networks_expiry__5dd59a_idx',
            old_name='idx_expiry_date_is_active_595',
        ),
        migrations.RenameIndex(
            model_name='blacklistedip',
            new_name='ad_networks_reason_8edd7a_idx',
            old_name='idx_reason_is_active_596',
        ),
        migrations.RenameIndex(
            model_name='blacklistedip',
            new_name='ad_networks_created_e9fd3b_idx',
            old_name='idx_created_at_597',
        ),
        migrations.RenameIndex(
            model_name='knownbadip',
            new_name='ad_networks_ip_addr_7b5fb2_idx',
            old_name='idx_ip_address_is_active_598',
        ),
        migrations.RenameIndex(
            model_name='knownbadip',
            new_name='ad_networks_threat__d43584_idx',
            old_name='idx_threat_type_is_active_599',
        ),
        migrations.RenameIndex(
            model_name='knownbadip',
            new_name='ad_networks_expires_63bf07_idx',
            old_name='idx_expires_at_600',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_status_0f5996_idx',
            old_name='idx_status_is_featured_573',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_externa_60ec3f_idx',
            old_name='idx_external_id_574',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_ad_netw_9c617f_idx',
            old_name='idx_ad_network_status_575',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_categor_a56842_idx',
            old_name='idx_category_status_576',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_reward__2ffd77_idx',
            old_name='idx_reward_amount_577',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='ad_networks_expires_1eb6c4_idx',
            old_name='idx_expires_at_578',
        ),
        migrations.RenameIndex(
            model_name='offerattachment',
            new_name='ad_networks_file_ha_08e35a_idx',
            old_name='adnet_auto_idx_003',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='ad_networks_convers_11feb2_idx',
            old_name='idx_conversion_status_585',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='ad_networks_fraud_s_cca49c_idx',
            old_name='idx_fraud_score_586',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='ad_networks_chargeb_215420_idx',
            old_name='idx_chargeback_processed_587',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='ad_networks_created_87bb73_idx',
            old_name='idx_created_at_588',
        ),
        migrations.RenameIndex(
            model_name='offerwall',
            new_name='ad_networks_wall_ty_554783_idx',
            old_name='idx_wall_type_is_active_589',
        ),
        migrations.RenameIndex(
            model_name='offerwall',
            new_name='ad_networks_slug_498097_idx',
            old_name='idx_slug_590',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_click_i_26eb14_idx',
            old_name='idx_click_id_579',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_convers_7ebbd6_idx',
            old_name='idx_conversion_id_580',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_user_id_61ec92_idx',
            old_name='idx_user_status_581',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_offer_i_4137ca_idx',
            old_name='idx_offer_status_582',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_created_2a019e_idx',
            old_name='idx_created_at_583',
        ),
        migrations.RenameIndex(
            model_name='userofferengagement',
            new_name='ad_networks_status_904e99_idx',
            old_name='idx_status_created_at_584',
        ),
        migrations.AlterUniqueTogether(
            name='networkstatistic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='smartofferrecommendation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userofferlimit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blacklistedip',
            unique_together={('ip_address', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='knownbadip',
            unique_together={('ip_address', 'tenant_id')},
        ),
        migrations.RemoveField(
            model_name='offerattachment',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='offerattachment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offerattachment',
            name='last_downloaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'tenant_id')},
        ),
        migrations.AddField(
            model_name='adnetwork',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='adnetworkwebhooklog',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='blacklistedip',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='Tenant identifier for multi-tenancy', max_length=50),
        ),
        migrations.AddField(
            model_name='frauddetectionrule',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='knownbadip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knownbadip',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='knownbadip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='networkstatistic',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='fraud_indicators',
            field=models.JSONField(blank=True, default=list, help_text='List of fraud indicators'),
        ),
        migrations.AddField(
            model_name='offer',
            name='fraud_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fraud review timestamp', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='fraud_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the fraud flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_fraudulent',
            field=models.BooleanField(default=False, help_text='Whether this record is flagged as fraudulent'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='fraud_indicators',
            field=models.JSONField(blank=True, default=list, help_text='List of fraud indicators'),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='fraud_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fraud review timestamp', null=True),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='fraud_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the fraud flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='offerperformanceanalytics',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='offersynclog',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='smartofferrecommendation',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='fraud_indicators',
            field=models.JSONField(blank=True, default=list, help_text='List of fraud indicators'),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='fraud_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fraud review timestamp', null=True),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='fraud_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the fraud flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='fraud_score',
            field=models.FloatField(default=0.0, help_text='Fraud detection score (0-100)'),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='is_fraudulent',
            field=models.BooleanField(default=False, help_text='Whether this record is flagged as fraudulent'),
        ),
        migrations.AddField(
            model_name='userofferengagement',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='userofferlimit',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='category',
            field=models.CharField(blank=True, choices=[('offerwall', 'Offerwall'), ('survey', 'Survey'), ('video', 'Video/Ads'), ('gaming', 'Gaming'), ('app_install', 'App Install'), ('cashback', 'Cashback'), ('cpi_cpa', 'CPI/CPA'), ('cpe', 'CPE (Cost Per Engagement)'), ('other', 'Other')], default='offerwall', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Your commission %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='country_support',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('tier1', 'Tier 1 (US, UK, CA, AU)'), ('tier2', 'Tier 2 (EU, Middle East)'), ('tier3', 'Tier 3 (Asia, Africa, South America)'), ('bd_only', 'Bangladesh Only'), ('indian_sub', 'Indian Subcontinent')], default='global', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='epc',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Earnings Per Click', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='min_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='total_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='adnetwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='request_method',
            field=models.CharField(blank=True, default='POST', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adnetworkwebhooklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='blacklistedip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='frauddetectionrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='frauddetectionrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='frauddetectionrule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frauddetectionrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='networkstatistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='age_group',
            field=models.CharField(blank=True, choices=[('13-17', 'Teen (13-17)'), ('18-24', 'Young Adult (18-24)'), ('25-34', 'Adult (25-34)'), ('35-44', 'Middle Age (35-44)'), ('45-54', 'Senior Adult (45-54)'), ('55+', 'Elderly (55+)'), ('any', 'Any Age')], default='any', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='click_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='device_type',
            field=models.CharField(blank=True, choices=[('any', 'Any Device'), ('mobile', 'Mobile Only'), ('tablet', 'Tablet Only'), ('desktop', 'Desktop Only'), ('android', 'Android Only'), ('ios', 'iOS Only')], default='any', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='easy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='gender_targeting',
            field=models.CharField(blank=True, choices=[('any', 'Any Gender'), ('male', 'Male Only'), ('female', 'Female Only')], default='any', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reward_currency',
            field=models.CharField(blank=True, default='BDT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='file',
            field=models.FileField(upload_to='offer_attachments/'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='file_size',
            field=models.IntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='offer_attachments/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offerattachment',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='avg_reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('survey', 'Survey'), ('offer', 'Offer'), ('video', 'Video'), ('game', 'Game'), ('app_install', 'App Install'), ('quiz', 'Quiz'), ('task', 'Task'), ('signup', 'Signup'), ('shopping', 'Shopping'), ('cashback', 'Cashback'), ('other', 'Other')], default='offer', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='color',
            field=models.CharField(blank=True, default='#3498db', help_text='Hex color code', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='conversion_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Verification'), ('verified', 'Verified by Network'), ('approved', 'Approved for Payment'), ('rejected', 'Rejected (Fraud)'), ('chargeback', 'Chargeback (Payment Cancelled)'), ('disputed', 'Disputed'), ('paid', 'Paid to User')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='network_currency',
            field=models.CharField(blank=True, default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offerperformanceanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offerperformanceanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerperformanceanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offersynclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offersynclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offersynclog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='background_color',
            field=models.CharField(blank=True, default='#f8f9fa', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='min_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='min_reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='theme_color',
            field=models.CharField(blank=True, default='#3498db', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('main', 'Main Offerwall'), ('survey', 'Survey Wall'), ('video', 'Video Wall'), ('game', 'Game Wall'), ('app', 'App Install Wall'), ('featured', 'Featured Offers'), ('trending', 'Trending Offers'), ('high_paying', 'High Paying Offers'), ('quick', 'Quick Offers')], default='main', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_smartofferrecommendation_offer', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='smartofferrecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_smartofferrecommendation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='click_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='commission_earned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='network_payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_userofferengagement_offer', to='ad_networks.offer'),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='reward_earned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='status',
            field=models.CharField(blank=True, choices=[('clicked', 'Clicked'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='clicked', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='userofferengagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_userofferengagement_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userofferlimit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='freeze_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_networks_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adnetwork',
            unique_together={('network_type', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='networkstatistic',
            unique_together={('ad_network', 'date', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='offerwall',
            unique_together={('slug', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='smartofferrecommendation',
            unique_together={('user', 'offer', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userofferlimit',
            unique_together={('user', 'offer', 'tenant_id')},
        ),
        migrations.AddIndex(
            model_name='adnetwork',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__c24021_idx'),
        ),
        migrations.AddIndex(
            model_name='adnetworkwebhooklog',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__307b90_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedip',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__d491d2_idx'),
        ),
        migrations.AddIndex(
            model_name='frauddetectionrule',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__f07cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='frauddetectionrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='ad_networks_rule_ty_0c481d_idx'),
        ),
        migrations.AddIndex(
            model_name='knownbadip',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__54d310_idx'),
        ),
        migrations.AddIndex(
            model_name='networkstatistic',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__b3c2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='networkstatistic',
            index=models.Index(fields=['date'], name='ad_networks_date_42e73f_idx'),
        ),
        migrations.AddIndex(
            model_name='offerattachment',
            index=models.Index(fields=['offer', 'file_type'], name='ad_networks_offer_i_6b725a_idx'),
        ),
        migrations.AddIndex(
            model_name='offerattachment',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__e5f001_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__a2d5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformanceanalytics',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__4517b7_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformanceanalytics',
            index=models.Index(fields=['offer'], name='ad_networks_offer_i_e1aa60_idx'),
        ),
        migrations.AddIndex(
            model_name='offersynclog',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__bf72ce_idx'),
        ),
        migrations.AddIndex(
            model_name='offersynclog',
            index=models.Index(fields=['ad_network', 'status'], name='ad_networks_ad_netw_0d6a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwall',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__4a95b5_idx'),
        ),
        migrations.AddIndex(
            model_name='smartofferrecommendation',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__57b0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='smartofferrecommendation',
            index=models.Index(fields=['score'], name='ad_networks_score_f058a1_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferlimit',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__e54912_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['user', 'tenant_id'], name='ad_networks_user_id_691178_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['is_active', 'is_frozen'], name='ad_networks_is_acti_804f89_idx'),
        ),
        migrations.AlterModelTable(
            name='offerattachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userwallet',
            table=None,
        ),
        migrations.AddField(
            model_name='networkapilog',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_network', to='ad_networks.adnetwork'),
        ),
        migrations.AddField(
            model_name='networkapilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkhealthcheck',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_network', to='ad_networks.adnetwork'),
        ),
        migrations.AddField(
            model_name='offerclick',
            name='fraud_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the fraud flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerclick',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='offerclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerdailylimit',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='offerdailylimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerreward',
            name='engagement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_engagement', to='ad_networks.userofferengagement'),
        ),
        migrations.AddField(
            model_name='offerreward',
            name='fraud_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the fraud flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerreward',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='offerreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerreward',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='offertag',
            index=models.Index(fields=['slug'], name='ad_networks_slug_294cae_idx'),
        ),
        migrations.AddIndex(
            model_name='offertag',
            index=models.Index(fields=['is_active', 'order'], name='ad_networks_is_acti_e0e982_idx'),
        ),
        migrations.AddIndex(
            model_name='offertag',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__d0659d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offertag',
            unique_together={('name', 'tenant_id'), ('slug', 'tenant_id')},
        ),
        migrations.AddField(
            model_name='offertagging',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offertagging',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='ad_networks.offer'),
        ),
        migrations.AddField(
            model_name='offertagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tag', to='ad_networks.offertag'),
        ),
        migrations.RemoveField(
            model_name='blacklistedip',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='knownbadip',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='last_transaction_at',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='unfrozen_at',
        ),
        migrations.AddIndex(
            model_name='networkapilog',
            index=models.Index(fields=['network', 'request_timestamp'], name='ad_networks_network_22a304_idx'),
        ),
        migrations.AddIndex(
            model_name='networkapilog',
            index=models.Index(fields=['endpoint', 'request_timestamp'], name='ad_networks_endpoin_53be67_idx'),
        ),
        migrations.AddIndex(
            model_name='networkapilog',
            index=models.Index(fields=['status_code', 'is_success'], name='ad_networks_status__d87114_idx'),
        ),
        migrations.AddIndex(
            model_name='networkapilog',
            index=models.Index(fields=['user', 'request_timestamp'], name='ad_networks_user_id_7f65a1_idx'),
        ),
        migrations.AddIndex(
            model_name='networkapilog',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__2d5085_idx'),
        ),
        migrations.AddIndex(
            model_name='networkhealthcheck',
            index=models.Index(fields=['network', 'checked_at'], name='ad_networks_network_f713cf_idx'),
        ),
        migrations.AddIndex(
            model_name='networkhealthcheck',
            index=models.Index(fields=['is_healthy', 'checked_at'], name='ad_networks_is_heal_ea1e40_idx'),
        ),
        migrations.AddIndex(
            model_name='networkhealthcheck',
            index=models.Index(fields=['check_type', 'checked_at'], name='ad_networks_check_t_1c9b44_idx'),
        ),
        migrations.AddIndex(
            model_name='networkhealthcheck',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__a87d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['user', 'clicked_at'], name='ad_networks_user_id_59c131_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['offer', 'clicked_at'], name='ad_networks_offer_i_95f574_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['ip_address', 'clicked_at'], name='ad_networks_ip_addr_f64e20_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['is_unique', 'is_fraud'], name='ad_networks_is_uniq_e0c1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['click_id'], name='ad_networks_click_i_738921_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__25f226_idx'),
        ),
        migrations.AddIndex(
            model_name='offerdailylimit',
            index=models.Index(fields=['user', 'reset_date'], name='ad_networks_user_id_5c586d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerdailylimit',
            index=models.Index(fields=['offer', 'reset_date'], name='ad_networks_offer_i_35dcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='offerdailylimit',
            index=models.Index(fields=['last_reset_at'], name='ad_networks_last_re_5baf87_idx'),
        ),
        migrations.AddIndex(
            model_name='offerdailylimit',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__49f16a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerdailylimit',
            unique_together={('user', 'offer', 'reset_date', 'tenant_id')},
        ),
        migrations.AddIndex(
            model_name='offerreward',
            index=models.Index(fields=['user', 'status'], name='ad_networks_user_id_1b371d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerreward',
            index=models.Index(fields=['offer', 'status'], name='ad_networks_offer_i_002a19_idx'),
        ),
        migrations.AddIndex(
            model_name='offerreward',
            index=models.Index(fields=['status', 'created_at'], name='ad_networks_status_bb3c94_idx'),
        ),
        migrations.AddIndex(
            model_name='offerreward',
            index=models.Index(fields=['payment_reference'], name='ad_networks_payment_2ae867_idx'),
        ),
        migrations.AddIndex(
            model_name='offerreward',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__5f68ef_idx'),
        ),
        migrations.AddIndex(
            model_name='offertagging',
            index=models.Index(fields=['offer', 'tag'], name='ad_networks_offer_i_ab3bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='offertagging',
            index=models.Index(fields=['tag', 'created_at'], name='ad_networks_tag_id_87b0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='offertagging',
            index=models.Index(fields=['is_auto_tagged'], name='ad_networks_is_auto_7e99ab_idx'),
        ),
        migrations.AddIndex(
            model_name='offertagging',
            index=models.Index(fields=['tenant_id'], name='ad_networks_tenant__ea5f7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offertagging',
            unique_together={('offer', 'tag')},
        ),
    ]
