# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('submission_type', models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Submission Type')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=50, help_text='Lower number = higher priority (evaluated first).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority')),
                ('conditions', models.JSONField(default=list, help_text='List of condition objects. All must match for the rule to fire.', verbose_name='Conditions')),
                ('action', models.CharField(choices=[('approve', 'Auto-Approve'), ('reject', 'Auto-Reject'), ('flag', 'Flag for Review'), ('escalate', 'Escalate'), ('request_proof', 'Request Additional Proof'), ('notify_admin', 'Notify Admin')], max_length=20, verbose_name='Action')),
                ('confidence_threshold', models.FloatField(default=0.9, help_text='AI confidence must be ≥ this value for the action to fire.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence Threshold')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System rules cannot be deleted via the API.', verbose_name='System Rule')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Auto-Approval Rule',
                'verbose_name_plural': 'Auto-Approval Rules',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofScanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_type', models.CharField(choices=[('image', 'Image Scan'), ('text', 'Text Analysis'), ('ocr', 'OCR Extraction'), ('combined', 'Combined (Image + Text)')], db_index=True, max_length=10, verbose_name='Scan Type')),
                ('file_url', models.URLField(blank=True, default='', help_text='URL of the file scanned (image/PDF). Empty for text scans.', max_length=2048, verbose_name='File URL')),
                ('input_text', models.TextField(blank=True, default='', help_text='Raw text sent for analysis (truncated if > MAX_SUBMISSION_TEXT_LENGTH).', verbose_name='Input Text')),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence')),
                ('is_flagged', models.BooleanField(blank=True, null=True, verbose_name='Flagged?')),
                ('labels', models.JSONField(blank=True, default=list, help_text='List of label strings returned by the AI model.', verbose_name='Detected Labels')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='OCR Extracted Text')),
                ('raw_result', models.JSONField(blank=True, default=dict, verbose_name='Raw Scanner Result')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Error Message')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scan Duration (ms)')),
                ('model_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Model Version')),
            ],
            options={
                'verbose_name': 'Proof Scanner',
                'verbose_name_plural': 'Proof Scanners',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspiciousSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(db_index=True, help_text="Model label, e.g. 'tasks.taskproof'", max_length=100, verbose_name='Content Type')),
                ('content_id', models.CharField(db_index=True, max_length=128, verbose_name='Content ID')),
                ('submission_type', models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Submission Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'AI Scanning'), ('auto_approved', 'Auto-Approved'), ('auto_rejected', 'Auto-Rejected'), ('human_review', 'Awaiting Human Review'), ('human_approved', 'Human-Approved'), ('human_rejected', 'Human-Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Moderation Status')),
                ('ai_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='AI Confidence')),
                ('risk_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Risk Score')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10, verbose_name='Risk Level')),
                ('flag_reason', models.CharField(choices=[('spam', 'Spam'), ('fake_proof', 'Fake Proof'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Submission'), ('policy_violation', 'Policy Violation'), ('suspicious_pattern', 'Suspicious Pattern'), ('low_quality', 'Low Quality'), ('other', 'Other')], default='other', max_length=25, verbose_name='Flag Reason')),
                ('ai_explanation', models.TextField(blank=True, default='', verbose_name='AI Explanation')),
                ('scan_metadata', models.JSONField(blank=True, default=dict, help_text='Raw JSON output from the AI scanner.', verbose_name='Scan Metadata')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewer_note', models.TextField(blank=True, default='', verbose_name='Reviewer Note')),
                ('final_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('scanning', 'AI Scanning'), ('auto_approved', 'Auto-Approved'), ('auto_rejected', 'Auto-Rejected'), ('human_review', 'Awaiting Human Review'), ('human_approved', 'Human-Approved'), ('human_rejected', 'Human-Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], default='', max_length=20, verbose_name='Final Status')),
            ],
            options={
                'verbose_name': 'Suspicious Submission',
                'verbose_name_plural': 'Suspicious Submissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Bot Name')),
                ('description', models.TextField(blank=True, default='')),
                ('submission_type', models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Target Submission Type')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, default='idle', max_length=12, verbose_name='Status')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Bot Configuration')),
                ('total_processed', models.PositiveIntegerField(default=0, verbose_name='Total Processed')),
                ('total_approved', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('total_escalated', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Current Retry Count')),
            ],
            options={
                'verbose_name': 'Task Bot',
                'verbose_name_plural': 'Task Bots',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
