# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_mod', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mod_rules', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='autoapprovalrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proofscanner',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Escalated To'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_submissions', to='auto_mod.autoapprovalrule', verbose_name='Matched Rule'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proofscanner',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='auto_mod.suspicioussubmission', verbose_name='Submission'),
        ),
        migrations.AddField(
            model_name='taskbot',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bots', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='taskbot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='autoapprovalrule',
            index=models.Index(fields=['submission_type', 'is_active', 'priority'], name='auto_mod_au_submiss_a13588_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapprovalrule',
            index=models.Index(fields=['action', 'is_active'], name='auto_mod_au_action_da9b03_idx'),
        ),
        migrations.AddIndex(
            model_name='suspicioussubmission',
            index=models.Index(fields=['status', 'risk_level', 'created_at'], name='auto_mod_su_status_48c4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='suspicioussubmission',
            index=models.Index(fields=['content_type', 'content_id'], name='auto_mod_su_content_4ffa15_idx'),
        ),
        migrations.AddIndex(
            model_name='suspicioussubmission',
            index=models.Index(fields=['submitted_by', 'status'], name='auto_mod_su_submitt_9b4e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='suspicioussubmission',
            index=models.Index(fields=['submission_type', 'status'], name='auto_mod_su_submiss_ffe056_idx'),
        ),
        migrations.AddConstraint(
            model_name='suspicioussubmission',
            constraint=models.UniqueConstraint(fields=('content_type', 'content_id'), name='unique_submission_per_content'),
        ),
        migrations.AddIndex(
            model_name='proofscanner',
            index=models.Index(fields=['submission', 'scan_type'], name='auto_mod_pr_submiss_62f0db_idx'),
        ),
        migrations.AddIndex(
            model_name='proofscanner',
            index=models.Index(fields=['is_flagged', 'created_at'], name='auto_mod_pr_is_flag_d4c47d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskbot',
            index=models.Index(fields=['status', 'submission_type'], name='auto_mod_ta_status_ad945a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskbot',
            index=models.Index(fields=['last_heartbeat'], name='auto_mod_ta_last_he_9048cd_idx'),
        ),
    ]
