# Generated by Django 5.0.11 on 2026-03-07 02:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mod', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoapprovalrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auto-Approval Rule', 'verbose_name_plural': 'Auto-Approval Rules'},
        ),
        migrations.AlterModelOptions(
            name='proofscanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proof Scanner', 'verbose_name_plural': 'Proof Scanners'},
        ),
        migrations.AlterModelOptions(
            name='suspicioussubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Suspicious Submission', 'verbose_name_plural': 'Suspicious Submissions'},
        ),
        migrations.AlterModelOptions(
            name='taskbot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task Bot', 'verbose_name_plural': 'Task Bots'},
        ),
        migrations.RenameIndex(
            model_name='autoapprovalrule',
            new_name='auto_mod_au_submiss_a13588_idx',
            old_name='am_aar_type_active_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='autoapprovalrule',
            new_name='auto_mod_au_action_da9b03_idx',
            old_name='am_aar_action_idx',
        ),
        migrations.RenameIndex(
            model_name='proofscanner',
            new_name='auto_mod_pr_submiss_62f0db_idx',
            old_name='am_ps_sub_type_idx',
        ),
        migrations.RenameIndex(
            model_name='proofscanner',
            new_name='auto_mod_pr_is_flag_d4c47d_idx',
            old_name='am_ps_flagged_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='auto_mod_su_status_48c4ee_idx',
            old_name='am_ss_status_risk_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='auto_mod_su_content_4ffa15_idx',
            old_name='am_ss_content_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='auto_mod_su_submitt_9b4e9d_idx',
            old_name='am_ss_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='taskbot',
            new_name='auto_mod_ta_status_ad945a_idx',
            old_name='am_tb_status_type_idx',
        ),
        migrations.RenameIndex(
            model_name='taskbot',
            new_name='auto_mod_ta_last_he_9048cd_idx',
            old_name='am_tb_heartbeat_idx',
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='action',
            field=models.CharField(choices=[('approve', 'Auto-Approve'), ('reject', 'Auto-Reject'), ('flag', 'Flag for Review'), ('escalate', 'Escalate'), ('request_proof', 'Request Additional Proof'), ('notify_admin', 'Notify Admin')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='conditions',
            field=models.JSONField(default=list, help_text='List of condition objects. All must match for the rule to fire.', verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='confidence_threshold',
            field=models.FloatField(default=0.9, help_text='AI confidence must be ≥ this value for the action to fire.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence Threshold'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mod_rules', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System rules cannot be deleted via the API.', verbose_name='System Rule'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Rule Name'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=50, help_text='Lower number = higher priority (evaluated first).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='submission_type',
            field=models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Scan Duration (ms)'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='file_url',
            field=models.URLField(blank=True, default='', help_text='URL of the file scanned (image/PDF). Empty for text scans.', max_length=2048, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='input_text',
            field=models.TextField(blank=True, default='', help_text='Raw text sent for analysis (truncated if > MAX_SUBMISSION_TEXT_LENGTH).', verbose_name='Input Text'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='is_flagged',
            field=models.BooleanField(blank=True, null=True, verbose_name='Flagged?'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='List of label strings returned by the AI model.', verbose_name='Detected Labels'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Model Version'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='ocr_text',
            field=models.TextField(blank=True, default='', verbose_name='OCR Extracted Text'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='raw_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw Scanner Result'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='scan_type',
            field=models.CharField(choices=[('image', 'Image Scan'), ('text', 'Text Analysis'), ('ocr', 'OCR Extraction'), ('combined', 'Combined (Image + Text)')], db_index=True, max_length=10, verbose_name='Scan Type'),
        ),
        migrations.AlterField(
            model_name='proofscanner',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='auto_mod.suspicioussubmission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='AI Confidence'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', verbose_name='AI Explanation'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='content_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='content_type',
            field=models.CharField(db_index=True, help_text="Model label, e.g. 'tasks.taskproof'", max_length=100, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Escalated To'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='final_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('scanning', 'AI Scanning'), ('auto_approved', 'Auto-Approved'), ('auto_rejected', 'Auto-Rejected'), ('human_review', 'Awaiting Human Review'), ('human_approved', 'Human-Approved'), ('human_rejected', 'Human-Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], default='', max_length=20, verbose_name='Final Status'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='flag_reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('fake_proof', 'Fake Proof'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Submission'), ('policy_violation', 'Policy Violation'), ('suspicious_pattern', 'Suspicious Pattern'), ('low_quality', 'Low Quality'), ('other', 'Other')], default='other', max_length=25, verbose_name='Flag Reason'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_submissions', to='auto_mod.autoapprovalrule', verbose_name='Matched Rule'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='reviewer_note',
            field=models.TextField(blank=True, default='', verbose_name='Reviewer Note'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='risk_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Risk Score'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='scan_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Raw JSON output from the AI scanner.', verbose_name='Scan Metadata'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scanning', 'AI Scanning'), ('auto_approved', 'Auto-Approved'), ('auto_rejected', 'Auto-Rejected'), ('human_review', 'Awaiting Human Review'), ('human_approved', 'Human-Approved'), ('human_rejected', 'Human-Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Moderation Status'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='submission_type',
            field=models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='suspicioussubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bots', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Bot Configuration'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Last Error'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Bot Name'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Current Retry Count'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, default='idle', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='submission_type',
            field=models.CharField(choices=[('task_proof', 'Task Proof'), ('user_content', 'User Content'), ('profile', 'Profile'), ('report', 'Report'), ('comment', 'Comment'), ('media', 'Media Upload')], db_index=True, max_length=20, verbose_name='Target Submission Type'),
        ),
        migrations.AlterField(
            model_name='taskbot',
            name='total_processed',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Processed'),
        ),
        migrations.AddIndex(
            model_name='suspicioussubmission',
            index=models.Index(fields=['submission_type', 'status'], name='auto_mod_su_submiss_ffe056_idx'),
        ),
    ]
