# Generated by Django 5.0.11 on 2026-03-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mod', '0002_alter_autoapprovalrule_options_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proofscanner',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='suspicioussubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taskbot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
    ]
