# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mod', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autoapprovalrule',
            new_name='idx_submission_type_is_active_prio_816',
            old_name='auto_mod_au_submiss_a13588_idx',
        ),
        migrations.RenameIndex(
            model_name='autoapprovalrule',
            new_name='idx_action_is_active_817',
            old_name='auto_mod_au_action_da9b03_idx',
        ),
        migrations.RenameIndex(
            model_name='proofscanner',
            new_name='idx_submission_scan_type_822',
            old_name='auto_mod_pr_submiss_62f0db_idx',
        ),
        migrations.RenameIndex(
            model_name='proofscanner',
            new_name='idx_is_flagged_created_at_823',
            old_name='auto_mod_pr_is_flag_d4c47d_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_status_risk_level_created_at_818',
            old_name='auto_mod_su_status_48c4ee_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_content_type_content_id_819',
            old_name='auto_mod_su_content_4ffa15_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_submitted_by_status_820',
            old_name='auto_mod_su_submitt_9b4e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_submission_type_status_821',
            old_name='auto_mod_su_submiss_ffe056_idx',
        ),
        migrations.RenameIndex(
            model_name='taskbot',
            new_name='idx_status_submission_type_824',
            old_name='auto_mod_ta_status_ad945a_idx',
        ),
        migrations.RenameIndex(
            model_name='taskbot',
            new_name='idx_last_heartbeat_825',
            old_name='auto_mod_ta_last_he_9048cd_idx',
        ),
    ]
