# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_mod', '0003_rename_auto_mod_au_submiss_a13588_idx_idx_submission_type_is_active_prio_816_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autoapprovalrule',
            new_name='idx_submission_type_is_act_f29',
            old_name='idx_submission_type_is_active_prio_816',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_status_risk_level_crea_b03',
            old_name='idx_status_risk_level_created_at_818',
        ),
        migrations.RenameIndex(
            model_name='suspicioussubmission',
            new_name='idx_content_type_content_i_9a3',
            old_name='idx_content_type_content_id_819',
        ),
    ]
