# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable unique name for this contest cycle.', max_length=255, unique=True, verbose_name='Contest Name')),
                ('slug', models.SlugField(blank=True, default='', help_text='URL-safe identifier derived from the contest name.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(default='', help_text='Optional contest description shown to participants.', max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Lifecycle state of the contest cycle.', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, help_text='Inclusive start of the contest window (UTC).', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='Exclusive end of the contest window (UTC).', verbose_name='End Date')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='All points earned during this cycle are multiplied by this factor. Must be between 0.01 and 100.00.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Points Multiplier')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured cycles are prominently displayed in the UI.', verbose_name='Is Featured')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Optional hard cap on participant count. NULL = unlimited.', null=True, verbose_name='Max Participants')),
                ('metadata', models.JSONField(default=dict, help_text='Arbitrary JSON configuration for this cycle (e.g. reward tiers, eligibility rules). Must not exceed 65536 bytes.', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Contest Cycle',
                'verbose_name_plural': 'Contest Cycles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('title', models.CharField(help_text="Short display title shown to the user (e.g. '1st Place Trophy').", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='Description')),
                ('reward_type', models.CharField(choices=[('POINTS', 'Points'), ('BADGE', 'Badge'), ('COUPON', 'Coupon'), ('PHYSICAL', 'Physical Prize'), ('CUSTOM', 'Custom')], help_text='Category of reward (POINTS, BADGE, COUPON, PHYSICAL, CUSTOM).', max_length=30, verbose_name='Reward Type')),
                ('reward_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Numeric value of the reward. Interpretation depends on reward_type (e.g. point amount, coupon discount percentage).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reward Value')),
                ('rank_from', models.PositiveIntegerField(blank=True, help_text='Inclusive lower bound of the rank window (1 = top).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Rank From')),
                ('rank_to', models.PositiveIntegerField(help_text='Inclusive upper bound of the rank window.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Rank To')),
                ('total_budget', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this reward can be issued. NULL = no cap (issue to all eligible participants).', null=True, verbose_name='Total Budget')),
                ('issued_count', models.PositiveIntegerField(default=0, help_text='Running total of how many times this reward has been issued.', verbose_name='Issued Count')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive rewards are not issued to new participants.', verbose_name='Is Active')),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional URL to a reward badge or trophy image.', max_length=500, verbose_name='Image URL')),
                ('metadata', models.JSONField(default=dict, help_text='Arbitrary extra data for the reward (e.g. coupon code, SKU).', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Contest Reward',
                'verbose_name_plural': 'Contest Rewards',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('REGIONAL', 'Regional'), ('CATEGORY', 'Category')], db_index=True, default='GLOBAL', help_text='GLOBAL = all participants; REGIONAL / CATEGORY may be added via scope_ref.', max_length=20, verbose_name='Scope')),
                ('scope_ref', models.CharField(blank=True, db_index=True, default='', help_text='Optional identifier qualifying the scope (e.g. region code, category slug).', max_length=100, verbose_name='Scope Reference')),
                ('snapshot_data', models.JSONField(default=list, help_text='Ordered list of leaderboard entries at snapshot time. See model docstring for entry schema.', verbose_name='Snapshot Data')),
                ('top_n', models.PositiveSmallIntegerField(default=100, help_text='Number of top entries captured in this snapshot.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Top N')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINALIZED', 'Finalized'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='PENDING = being built; FINALIZED = immutable; FAILED = error during generation.', max_length=20, verbose_name='Status')),
                ('generated_at', models.DateTimeField(blank=True, help_text='Timestamp when this snapshot was successfully finalized.', null=True, verbose_name='Generated At')),
                ('error_message', models.TextField(default='', help_text='Populated when status=FAILED; contains traceback or summary.', verbose_name='Error Message')),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 hex digest of the serialized snapshot_data. Used for integrity verification.', max_length=64, verbose_name='Checksum')),
            ],
            options={
                'verbose_name': 'Leaderboard Snapshot',
                'verbose_name_plural': 'Leaderboard Snapshots',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('achievement_type', models.CharField(choices=[('RANK_REWARD', 'Rank Reward'), ('MILESTONE', 'Milestone'), ('STREAK', 'Streak'), ('BADGE', 'Badge'), ('BONUS', 'Bonus'), ('CUSTOM', 'Custom')], db_index=True, help_text='Semantic category of the achievement.', max_length=50, verbose_name='Achievement Type')),
                ('title', models.CharField(blank=True, help_text="Display title for the achievement (e.g. 'Top 10 Finisher').", max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Description')),
                ('points_awarded', models.IntegerField(default=0, help_text="Points credited to the user's account for this achievement. May be 0 for badge-only achievements.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Points Awarded')),
                ('rank_at_award', models.PositiveIntegerField(blank=True, help_text="User's leaderboard rank at the time of award, if applicable.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Rank at Award')),
                ('is_awarded', models.BooleanField(db_index=True, default=False, help_text='True once the achievement has been formally granted and any associated points/rewards have been dispatched.', verbose_name='Is Awarded')),
                ('awarded_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when is_awarded was set to True.', null=True, verbose_name='Awarded At')),
                ('is_notified', models.BooleanField(default=False, help_text='True once the user has been notified of this achievement.', verbose_name='Is Notified')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified At')),
                ('metadata', models.JSONField(default=dict, help_text='Arbitrary context data at time of award (e.g. snapshot id, score).', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
