# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcycle',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who created this contest cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contest_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contestcycle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contestreward',
            name='contest_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='gamification.contestcycle', verbose_name='Contest Cycle'),
        ),
        migrations.AddField(
            model_name='contestreward',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaderboardsnapshot',
            name='contest_cycle',
            field=models.ForeignKey(blank=True, help_text='The contest cycle this snapshot belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaderboard_snapshots', to='gamification.contestcycle', verbose_name='Contest Cycle'),
        ),
        migrations.AddField(
            model_name='leaderboardsnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='contest_cycle',
            field=models.ForeignKey(blank=True, help_text='NULL for global/lifetime achievements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_achievements', to='gamification.contestcycle', verbose_name='Contest Cycle'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='contest_reward',
            field=models.ForeignKey(blank=True, help_text='The reward template that triggered this achievement, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_achievements', to='gamification.contestreward', verbose_name='Contest Reward'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='contestcycle',
            index=models.Index(fields=['status', 'start_date'], name='gamif_cc_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='contestcycle',
            index=models.Index(fields=['start_date', 'end_date'], name='gamif_cc_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='contestreward',
            index=models.Index(fields=['contest_cycle', 'rank_from', 'rank_to'], name='gamif_cr_cycle_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='contestreward',
            index=models.Index(fields=['reward_type', 'is_active'], name='gamif_cr_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['contest_cycle', 'scope', 'created_at'], name='gamif_ls_cyc_scope_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['status', 'created_at'], name='gamif_ls_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_awarded', 'created_at'], name='gamif_ua_user_awarded_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['contest_cycle', 'achievement_type'], name='gamif_ua_cycle_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement_type', 'awarded_at'], name='gamif_ua_type_awarded_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(condition=models.Q(('contest_cycle__isnull', False)), fields=('user', 'achievement_type', 'contest_cycle'), name='gamif_ua_uniq_usr_type_cyc'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(condition=models.Q(('contest_cycle__isnull', True)), fields=('user', 'achievement_type'), name='gamif_ua_uniq_usr_type_glb'),
        ),
    ]
