# api/wallet/migrations/0004_world_class_features.py
"""
World-class features migration:
  KYCVerification, VirtualAccount, SettlementBatch, InstantPayout,
  MassPayoutJob, MassPayoutItem, DisputeCase, WithdrawalWhitelist,
  SecurityEvent, RefundRequest, FraudScore, AMLFlag,
  EarningOffer, OfferConversion, WebhookEndpoint, TaxRecord
"""
import uuid
from decimal import Decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallet_fixes_and_cpalead"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(name="KYCVerification", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_kyc_tenant", to="tenants.tenant")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_kyc_user", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="kyc_verifications", to="wallet.wallet")),
            ("level", models.PositiveSmallIntegerField(choices=[(0,"Level 0"),(1,"Level 1"),(2,"Level 2"),(3,"Level 3")], default=0)),
            ("status", models.CharField(choices=[("pending","Pending"),("approved","Approved"),("rejected","Rejected"),("expired","Expired")], default="pending", max_length=10)),
            ("doc_type", models.CharField(blank=True, max_length=15)),
            ("doc_number", models.CharField(blank=True, max_length=50)),
            ("doc_front_url", models.URLField(blank=True)),
            ("doc_back_url", models.URLField(blank=True)),
            ("selfie_url", models.URLField(blank=True)),
            ("address_proof_url", models.URLField(blank=True)),
            ("daily_wd_limit", models.DecimalField(decimal_places=2, default=Decimal("500"), max_digits=20)),
            ("monthly_wd_limit", models.DecimalField(decimal_places=2, default=Decimal("5000"), max_digits=20)),
            ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_kyc_reviewed", to=settings.AUTH_USER_MODEL)),
            ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ("rejection_reason", models.TextField(blank=True)),
            ("expires_at", models.DateTimeField(blank=True, null=True)),
            ("risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_kyc_verification","app_label":"wallet"}),

        migrations.CreateModel(name="VirtualAccount", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_virtualaccount_tenant", to="tenants.tenant")),
            ("va_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="virtual_accounts", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="virtual_accounts", to="wallet.wallet")),
            ("account_type", models.CharField(default="bank", max_length=10)),
            ("status", models.CharField(default="active", max_length=6)),
            ("account_number", models.CharField(blank=True, max_length=30, unique=True)),
            ("ifsc_code", models.CharField(blank=True, max_length=15)),
            ("bank_name", models.CharField(blank=True, max_length=100)),
            ("vpa_address", models.CharField(blank=True, max_length=100)),
            ("expected_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ("amount_received", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("close_by", models.DateTimeField(blank=True, null=True)),
            ("description", models.TextField(blank=True)),
            ("metadata", models.JSONField(blank=True, default=dict)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("closed_at", models.DateTimeField(blank=True, null=True)),
        ], options={"db_table":"wallet_virtual_account","app_label":"wallet"}),

        migrations.CreateModel(name="SettlementBatch", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_settlementbatch_tenant", to="tenants.tenant")),
            ("settlement_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="settlements", to="wallet.wallet")),
            ("schedule", models.CharField(default="two_day", max_length=10)),
            ("status", models.CharField(default="pending", max_length=12)),
            ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("fee_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("net_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("transaction_count", models.PositiveIntegerField(default=0)),
            ("settlement_date", models.DateField()),
            ("settled_at", models.DateTimeField(blank=True, null=True)),
            ("utr_number", models.CharField(blank=True, max_length=100)),
            ("bank_reference", models.CharField(blank=True, max_length=200)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table":"wallet_settlement_batch","app_label":"wallet"}),

        migrations.CreateModel(name="InstantPayout", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_instantpayout_tenant", to="tenants.tenant")),
            ("payout_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="instant_payouts", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="instant_payouts", to="wallet.wallet")),
            ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("net_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("fee_percent", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=5)),
            ("min_fee", models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=8)),
            ("method", models.CharField(max_length=20)),
            ("destination", models.CharField(max_length=100)),
            ("status", models.CharField(default="pending", max_length=12)),
            ("arrival_time", models.DateTimeField(blank=True, null=True)),
            ("gateway_ref", models.CharField(blank=True, max_length=200)),
            ("failure_reason", models.TextField(blank=True)),
            ("withdrawal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="instant_payout", to="wallet.withdrawal")),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_instant_payout","app_label":"wallet"}),

        migrations.CreateModel(name="MassPayoutJob", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_masspayjob_tenant", to="tenants.tenant")),
            ("job_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("title", models.CharField(max_length=200)),
            ("status", models.CharField(default="draft", max_length=12)),
            ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("total_count", models.PositiveIntegerField(default=0)),
            ("success_count", models.PositiveIntegerField(default=0)),
            ("failed_count", models.PositiveIntegerField(default=0)),
            ("pending_count", models.PositiveIntegerField(default=0)),
            ("payout_type", models.CharField(blank=True, max_length=50)),
            ("method", models.CharField(default="bkash", max_length=20)),
            ("note", models.TextField(blank=True)),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mass_payout_jobs", to=settings.AUTH_USER_MODEL)),
            ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_mass_payouts", to=settings.AUTH_USER_MODEL)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("started_at", models.DateTimeField(blank=True, null=True)),
            ("completed_at", models.DateTimeField(blank=True, null=True)),
        ], options={"db_table":"wallet_mass_payout_job","app_label":"wallet"}),

        migrations.CreateModel(name="MassPayoutItem", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="wallet.masspayoutjob")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mass_payout_items", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mass_payout_items", to="wallet.wallet")),
            ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ("status", models.CharField(default="pending", max_length=8)),
            ("error", models.TextField(blank=True)),
            ("withdrawal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mass_payout_item", to="wallet.withdrawal")),
            ("processed_at", models.DateTimeField(blank=True, null=True)),
        ], options={"db_table":"wallet_mass_payout_item","app_label":"wallet"}),

        migrations.CreateModel(name="DisputeCase", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_dispute_tenant", to="tenants.tenant")),
            ("case_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_disputes", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="disputes", to="wallet.wallet")),
            ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="disputes", to="wallet.wallettransaction")),
            ("withdrawal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="disputes", to="wallet.withdrawal")),
            ("reason", models.CharField(max_length=20)),
            ("status", models.CharField(default="open", max_length=25)),
            ("outcome", models.CharField(blank=True, max_length=20)),
            ("disputed_amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ("refunded_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("description", models.TextField()),
            ("evidence", models.JSONField(blank=True, default=list)),
            ("internal_notes", models.TextField(blank=True)),
            ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_disputes", to=settings.AUTH_USER_MODEL)),
            ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_disputes", to=settings.AUTH_USER_MODEL)),
            ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ("due_by", models.DateTimeField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_dispute","app_label":"wallet"}),

        migrations.CreateModel(name="WithdrawalWhitelist", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_whitelist_tenant", to="tenants.tenant")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="withdrawal_whitelist", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whitelist", to="wallet.wallet")),
            ("method_type", models.CharField(max_length=10)),
            ("account", models.CharField(max_length=200)),
            ("label", models.CharField(blank=True, max_length=100)),
            ("is_active", models.BooleanField(default=False)),
            ("activated_at", models.DateTimeField(blank=True, null=True)),
            ("is_trusted", models.BooleanField(default=False)),
            ("added_ip", models.GenericIPAddressField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table":"wallet_withdrawal_whitelist","app_label":"wallet","unique_together":{("user","method_type","account")}}),

        migrations.CreateModel(name="SecurityEvent", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_securityevent_tenant", to="tenants.tenant")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_security_events", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="security_events", to="wallet.wallet")),
            ("event_type", models.CharField(max_length=25)),
            ("lock_hours", models.PositiveIntegerField(default=24)),
            ("lock_until", models.DateTimeField()),
            ("is_resolved", models.BooleanField(default=False)),
            ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ("device_info", models.JSONField(blank=True, default=dict)),
            ("notes", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table":"wallet_security_event","app_label":"wallet"}),

        migrations.CreateModel(name="RefundRequest", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_refund_tenant", to="tenants.tenant")),
            ("refund_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_refunds", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="wallet.wallet")),
            ("original_txn", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="refund_requests", to="wallet.wallettransaction")),
            ("reason", models.CharField(max_length=25)),
            ("status", models.CharField(default="pending", max_length=12)),
            ("requested_amount", models.DecimalField(decimal_places=2, max_digits=20)),
            ("approved_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("description", models.TextField(blank=True)),
            ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_refunds", to=settings.AUTH_USER_MODEL)),
            ("processed_at", models.DateTimeField(blank=True, null=True)),
            ("refund_txn", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refund_origin", to="wallet.wallettransaction")),
            ("rejection_reason", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_refund_request","app_label":"wallet"}),

        migrations.CreateModel(name="FraudScore", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_fraudscore_tenant", to="tenants.tenant")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_fraud_scores", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fraud_scores", to="wallet.wallet")),
            ("transaction", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fraud_score", to="wallet.wallettransaction")),
            ("withdrawal", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="fraud_score", to="wallet.withdrawal")),
            ("score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("risk_level", models.CharField(default="low", max_length=8)),
            ("is_blocked", models.BooleanField(default=False)),
            ("block_reason", models.TextField(blank=True)),
            ("velocity_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("ip_risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("device_risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("amount_risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("pattern_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("kyc_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ("signals", models.JSONField(blank=True, default=list)),
            ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_fraud_scores", to=settings.AUTH_USER_MODEL)),
            ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ("override_reason", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table":"wallet_fraud_score","app_label":"wallet"}),

        migrations.CreateModel(name="AMLFlag", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_amlflag_tenant", to="tenants.tenant")),
            ("flag_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aml_flags", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aml_flags", to="wallet.wallet")),
            ("flag_type", models.CharField(max_length=25)),
            ("status", models.CharField(default="flagged", max_length=15)),
            ("description", models.TextField()),
            ("suspicious_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("evidence", models.JSONField(blank=True, default=list)),
            ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_aml_cases", to=settings.AUTH_USER_MODEL)),
            ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_aml_cases", to=settings.AUTH_USER_MODEL)),
            ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ("reported_to", models.CharField(blank=True, max_length=200)),
            ("reported_at", models.DateTimeField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_aml_flag","app_label":"wallet"}),

        migrations.CreateModel(name="EarningOffer", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_earningoffer_tenant", to="tenants.tenant")),
            ("offer_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("title", models.CharField(max_length=200)),
            ("description", models.TextField(blank=True)),
            ("offer_type", models.CharField(max_length=15)),
            ("geo_tier", models.CharField(default="all", max_length=6)),
            ("target_countries", models.JSONField(blank=True, default=list)),
            ("payout", models.DecimalField(decimal_places=4, max_digits=10)),
            ("payout_currency", models.CharField(default="USD", max_length=5)),
            ("payout_bdt", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ("daily_cap", models.PositiveIntegerField(default=0)),
            ("total_cap", models.PositiveIntegerField(default=0)),
            ("conversions_today", models.PositiveIntegerField(default=0)),
            ("total_conversions", models.PositiveIntegerField(default=0)),
            ("is_active", models.BooleanField(default=True)),
            ("requires_kyc", models.BooleanField(default=False)),
            ("min_publisher_level", models.PositiveSmallIntegerField(default=1)),
            ("advertiser", models.CharField(blank=True, max_length=200)),
            ("offer_url", models.URLField(blank=True)),
            ("preview_url", models.URLField(blank=True)),
            ("icon_url", models.URLField(blank=True)),
            ("starts_at", models.DateTimeField(blank=True, null=True)),
            ("ends_at", models.DateTimeField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_earning_offer","app_label":"wallet"}),

        migrations.CreateModel(name="OfferConversion", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("offer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="conversions", to="wallet.earningoffer")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offer_conversions", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offer_conversions", to="wallet.wallet")),
            ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="offer_conversions", to="wallet.wallettransaction")),
            ("status", models.CharField(default="pending", max_length=12)),
            ("payout", models.DecimalField(decimal_places=4, max_digits=10)),
            ("click_id", models.CharField(blank=True, db_index=True, max_length=100)),
            ("sub_id", models.CharField(blank=True, max_length=100)),
            ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ("user_agent", models.TextField(blank=True)),
            ("country_code", models.CharField(blank=True, max_length=3)),
            ("device_type", models.CharField(blank=True, max_length=20)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("approved_at", models.DateTimeField(blank=True, null=True)),
        ], options={"db_table":"wallet_offer_conversion","app_label":"wallet"}),

        migrations.CreateModel(name="WebhookEndpoint", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_webhookendpoint_tenant", to="tenants.tenant")),
            ("endpoint_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_webhook_endpoints", to=settings.AUTH_USER_MODEL)),
            ("url", models.URLField()),
            ("secret", models.CharField(blank=True, max_length=256)),
            ("subscribed_events", models.JSONField(default=list)),
            ("is_active", models.BooleanField(default=True)),
            ("last_called_at", models.DateTimeField(blank=True, null=True)),
            ("last_status", models.PositiveIntegerField(blank=True, null=True)),
            ("failure_count", models.PositiveIntegerField(default=0)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
        ], options={"db_table":"wallet_webhook_endpoint","app_label":"wallet"}),

        migrations.CreateModel(name="TaxRecord", fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wallet_taxrecord_tenant", to="tenants.tenant")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_tax_records", to=settings.AUTH_USER_MODEL)),
            ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tax_records", to="wallet.wallet")),
            ("tax_year", models.PositiveSmallIntegerField()),
            ("status", models.CharField(default="pending", max_length=10)),
            ("total_income", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("total_withdrawn", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("total_fees", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("total_bonuses", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("total_referral", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ("transaction_count", models.PositiveIntegerField(default=0)),
            ("tin_number", models.CharField(blank=True, max_length=20)),
            ("pdf_url", models.URLField(blank=True)),
            ("generated_at", models.DateTimeField(blank=True, null=True)),
            ("sent_at", models.DateTimeField(blank=True, null=True)),
            ("notes", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ], options={"db_table":"wallet_tax_record","app_label":"wallet","unique_together":{("user","tax_year")}}),
    ]
