# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferralNetwork',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='api_userreferralnetwork_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('total_referrals', models.IntegerField(default=0, help_text='Direct + indirect referrals', verbose_name='Total Referrals')),
                ('active_referrals', models.IntegerField(default=0, verbose_name='Active Referrals')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Commission Earned')),
                ('level_1_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Level 1 Commission')),
                ('level_2_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Level 2 Commission')),
                ('level_3_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Level 3 Commission')),
                ('last_commission_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Last Commission Calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Referral Network',
                'verbose_name_plural': 'User Referral Networks',
                'db_table': 'user_referral_networks',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='api_userstreak_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('current_streak', models.IntegerField(default=0, help_text='Consecutive days of login', verbose_name='Current Streak')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Longest Streak')),
                ('last_login_date', models.DateField(blank=True, null=True, verbose_name='Last Login Date')),
                ('total_logins', models.IntegerField(default=0, verbose_name='Total Logins')),
                ('streak_start_date', models.DateField(blank=True, null=True, verbose_name='Streak Start Date')),
                ('today_logged_in', models.BooleanField(default=False, verbose_name='Today Logged In')),
                ('milestone_7_days', models.BooleanField(default=False, verbose_name='7 Days Milestone')),
                ('milestone_30_days', models.BooleanField(default=False, verbose_name='30 Days Milestone')),
                ('milestone_90_days', models.BooleanField(default=False, verbose_name='90 Days Milestone')),
                ('milestone_180_days', models.BooleanField(default=False, verbose_name='180 Days Milestone')),
                ('milestone_365_days', models.BooleanField(default=False, verbose_name='365 Days Milestone')),
                ('total_streak_rewards', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Streak Rewards')),
                ('last_reward_date', models.DateField(blank=True, null=True, verbose_name='Last Reward Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pending_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('lifetime_earnings', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_withdrawn', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('min_withdrawal', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('PAYPAL', 'PayPal'), ('BANK', 'Bank Transfer'), ('CRYPTO', 'Cryptocurrency'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, null=True)),
                ('payment_details', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True)),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='%(app_label)s_%(class)s_tenant', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_tenant', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_dailystats_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earningtask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='earningtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type'], name='notificatio_templat_b63ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='notificatio_is_acti_f33840_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'offer_type'], name='offers_status_7e7d52_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['featured'], name='offers_feature_45efa3_idx'),
        ),
        migrations.AddField(
            model_name='offerwalllog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_offerwalllog_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='offerwallnetwork',
            index=models.Index(fields=['network_code'], name='offerwall_n_network_8a2d00_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwallnetwork',
            index=models.Index(fields=['is_active'], name='offerwall_n_is_acti_77fbdc_idx'),
        ),
        migrations.AddField(
            model_name='offerwalloffer',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='api.offerwallnetwork', verbose_name='Network'),
        ),
        migrations.AddField(
            model_name='offerwalllog',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='api.offerwalloffer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_referral_referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_referral_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_referralcommission_referred_user', to=settings.AUTH_USER_MODEL, verbose_name='Referred User'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_referralcommission_referrer', to=settings.AUTH_USER_MODEL, verbose_name='Referrer'),
        ),
        migrations.AddIndex(
            model_name='referrallevel',
            index=models.Index(fields=['level_number'], name='referral_le_level_n_9738c6_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallevel',
            index=models.Index(fields=['is_active'], name='referral_le_is_acti_5cd2d6_idx'),
        ),
        migrations.AddField(
            model_name='streakreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_streakreward_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_transaction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_userdevice_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='deviceloginhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='api.userdevice', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_useroffer_offer', to='api.offer'),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_useroffer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreferralnetwork',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.referrallevel', verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='userreferralnetwork',
            name='direct_referrals',
            field=models.ManyToManyField(blank=True, related_name='api_userreferralnetwork_direct_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Direct Referrals'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['current_streak'], name='user_streak_current_328ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='userstreak',
            index=models.Index(fields=['last_login_date'], name='user_streak_last_lo_15afd5_idx'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_wallet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_withdrawal_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_withdrawal_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['user', '-date'], name='daily_stats_user_id_daf80f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='offerwalloffer',
            index=models.Index(fields=['offer_id'], name='offerwall_o_offer_i_0a36a1_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalloffer',
            index=models.Index(fields=['network', 'status'], name='offerwall_o_network_98def6_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalloffer',
            index=models.Index(fields=['offer_type'], name='offerwall_o_offer_t_708fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalloffer',
            index=models.Index(fields=['is_featured'], name='offerwall_o_is_feat_f7c4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalloffer',
            index=models.Index(fields=['expiry_date'], name='offerwall_o_expiry__950e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalllog',
            index=models.Index(fields=['transaction_id'], name='offerwall_l_transac_1c13c4_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalllog',
            index=models.Index(fields=['user', 'status'], name='offerwall_l_user_id_1af46c_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalllog',
            index=models.Index(fields=['status', 'created_at'], name='offerwall_l_status_8fe12e_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalllog',
            index=models.Index(fields=['offer', 'status'], name='offerwall_l_offer_i_4f0291_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwalllog',
            index=models.Index(fields=['fraud_score'], name='offerwall_l_fraud_s_a10f4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred')},
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referrer', 'level'], name='referral_co_referre_3895de_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['is_paid'], name='referral_co_is_paid_bd31a8_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['created_at'], name='referral_co_created_665788_idx'),
        ),
        migrations.AddIndex(
            model_name='streakreward',
            index=models.Index(fields=['user', 'awarded_at'], name='streak_rewa_user_id_440a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='streakreward',
            index=models.Index(fields=['reward_type'], name='streak_rewa_reward__0c376a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id'], name='user_device_device__945e98_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['ip_address'], name='user_device_ip_addr_6a6b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['fraud_score'], name='user_device_fraud_s_15ee86_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['is_vpn_detected'], name='user_device_is_vpn__0ef76d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='deviceloginhistory',
            index=models.Index(fields=['device', 'login_time'], name='device_logi_device__de6464_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceloginhistory',
            index=models.Index(fields=['is_successful'], name='device_logi_is_succ_cf47e1_idx'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['user', 'status'], name='user_offers_user_id_fe63e5_idx'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['offer', 'status'], name='user_offers_offer_i_6e1084_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useroffer',
            unique_together={('user', 'offer')},
        ),
        migrations.AddIndex(
            model_name='userreferralnetwork',
            index=models.Index(fields=['total_referrals'], name='user_referr_total_r_43bb48_idx'),
        ),
        migrations.AddIndex(
            model_name='userreferralnetwork',
            index=models.Index(fields=['total_commission_earned'], name='user_referr_total_c_0f4c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='withdrawals_user_id_38a9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'),
        ),
    ]
