# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_daily_stats_user_id_daf80f_idx_idx_user_date_043_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userreferralnetwork',
            new_name='idx_total_commission_earne_b69',
            old_name='idx_total_commission_earned_010',
        ),
    ]
