# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('signup_bonus_given', models.BooleanField(default=False)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='1=direct, 2=grandchild, 3=great-grandchild', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, help_text='1, 2, or 3')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_amount', models.DecimalField(decimal_places=2, default=0, help_text='referred_user এর মূল earning যার উপর commission হিসাব হয়েছে', max_digits=10)),
                ('source_type', models.CharField(default='task', help_text='task, offer, bonus, etc.', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=10, null=True)),
                ('rank', models.IntegerField()),
                ('total_referrals', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0)),
                ('total_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_signup_bonus', models.DecimalField(decimal_places=2, default=20, help_text='নতুন user যে bonus পাবে', max_digits=10)),
                ('referrer_signup_bonus', models.DecimalField(decimal_places=2, default=50, help_text='যে refer করেছে সে যে bonus পাবে', max_digits=10)),
                ('level1_commission_rate', models.DecimalField(decimal_places=2, default=10, help_text='Level 1 commission % (direct referral)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('level2_commission_rate', models.DecimalField(decimal_places=2, default=5, help_text='Level 2 commission % (referral এর referral)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('level3_commission_rate', models.DecimalField(decimal_places=2, default=2, help_text='Level 3 commission %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('team_bonus_enabled', models.BooleanField(default=False)),
                ('team_bonus_min_referrals', models.IntegerField(default=10)),
                ('team_bonus_rate', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_referral_depth', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'Referral Settings',
            },
        ),
    ]
