# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referral', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_referral_referred_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_referral_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_chain_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='earner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_chain_earner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral.referral'),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_referralearning_referred_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_referralearning_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.mastertask'),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralleaderboard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralleaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'created_at'], name='referral_re_referre_b9044b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred_user')},
        ),
        migrations.AddIndex(
            model_name='referralchain',
            index=models.Index(fields=['earner'], name='referral_re_earner__b55f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralchain',
            index=models.Index(fields=['beneficiary'], name='referral_re_benefic_961c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referralchain',
            unique_together={('beneficiary', 'earner', 'level')},
        ),
        migrations.AddIndex(
            model_name='referralearning',
            index=models.Index(fields=['referrer', '-created_at'], name='referral_re_referre_8a0bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='referralearning',
            index=models.Index(fields=['level'], name='referral_re_level_daf73c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referralleaderboard',
            unique_together={('user', 'period', 'period_start')},
        ),
    ]
