# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_from_referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.referral'),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='source_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.earningtask'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred_user')},
        ),
    ]
