# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='idx_referrer_created_at_1667',
            old_name='referral_re_referre_b9044b_idx',
        ),
        migrations.RenameIndex(
            model_name='referralchain',
            new_name='idx_earner_1668',
            old_name='referral_re_earner__b55f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='referralchain',
            new_name='idx_beneficiary_1669',
            old_name='referral_re_benefic_961c78_idx',
        ),
        migrations.RenameIndex(
            model_name='referralearning',
            new_name='idx_referrer_created_at_1670',
            old_name='referral_re_referre_8a0bcd_idx',
        ),
        migrations.RenameIndex(
            model_name='referralearning',
            new_name='idx_level_1671',
            old_name='referral_re_level_daf73c_idx',
        ),
    ]
