# Generated by Django 5.0.11 on 2026-04-01 10:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_referral_tenant_referralearning_tenant_and_more'),
        ('tasks', '0004_adminledger_tenant_mastertask_tenant_and_more'),
        ('tenants', '0003_alter_tenant_max_users_tenantbilling_tenantinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='1=direct, 2=grandchild, 3=great-grandchild', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=10)),
                ('rank', models.IntegerField()),
                ('total_referrals', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.RemoveField(
            model_name='referralsettings',
            name='lifetime_commission_rate',
        ),
        migrations.AddField(
            model_name='referral',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='suspicious_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='level',
            field=models.IntegerField(default=1, help_text='1, 2, or 3'),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='source_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='referred_user এর মূল earning যার উপর commission হিসাব হয়েছে', max_digits=10),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='source_type',
            field=models.CharField(default='task', help_text='task, offer, bonus, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='wallet_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='level1_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Level 1 commission % (direct referral)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='level2_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Level 2 commission % (referral এর referral)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='level3_commission_rate',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Level 3 commission %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='max_referral_depth',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='team_bonus_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='team_bonus_min_referrals',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='team_bonus_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='referralearning',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral.referral'),
        ),
        migrations.AlterField(
            model_name='referralearning',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.mastertask'),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='direct_signup_bonus',
            field=models.DecimalField(decimal_places=2, default=20, help_text='নতুন user যে bonus পাবে', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='referrer_signup_bonus',
            field=models.DecimalField(decimal_places=2, default=50, help_text='যে refer করেছে সে যে bonus পাবে', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'created_at'], name='referral_re_referre_b9044b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralearning',
            index=models.Index(fields=['referrer', '-created_at'], name='referral_re_referre_8a0bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='referralearning',
            index=models.Index(fields=['level'], name='referral_re_level_daf73c_idx'),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_chain_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='earner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_chain_earner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralchain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralleaderboard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralleaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referralchain',
            index=models.Index(fields=['earner'], name='referral_re_earner__b55f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralchain',
            index=models.Index(fields=['beneficiary'], name='referral_re_benefic_961c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referralchain',
            unique_together={('beneficiary', 'earner', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='referralleaderboard',
            unique_together={('user', 'period', 'period_start')},
        ),
    ]
