# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monetization_tools', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abtestassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adnetwork',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adnetworkdailystat',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='adnetworkdailystat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adperformancedaily',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='adperformancedaily',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_campaign', to='monetization_tools.adcampaign'),
        ),
        migrations.AddField(
            model_name='adperformancedaily',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adperformancehourly',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='adperformancehourly',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_campaign', to='monetization_tools.adcampaign'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='adperformancehourly',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='adperformancedaily',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversionlog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_campaign', to='monetization_tools.adcampaign'),
        ),
        migrations.AddField(
            model_name='conversionlog',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_click', to='monetization_tools.clicklog'),
        ),
        migrations.AddField(
            model_name='conversionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_coupon', to='monetization_tools.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='floorpriceconfig',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='floorpriceconfig',
            name='ad_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='floorpriceconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impressionlog',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='impressionlog',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='impressionlog',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_placement', to='monetization_tools.adplacement'),
        ),
        migrations.AddField(
            model_name='impressionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='impressionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='impression',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_impression', to='monetization_tools.impressionlog'),
        ),
        migrations.AddField(
            model_name='inapppurchase',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inapppurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardrank',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaderboardrank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monetizationconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='monetizationnotificationtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offer', to='monetization_tools.offer'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='offer_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_offer_completion', to='monetization_tools.offercompletion'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerwall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_offerwall', to='monetization_tools.offerwall'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_payout_method', to='monetization_tools.payoutmethod'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointledgersnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pointledgersnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='offer_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_offer_completion', to='monetization_tools.offercompletion'),
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='postback_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_postback_log', to='monetization_tools.postbacklog'),
        ),
        migrations.AddField(
            model_name='prizeconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_account_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisheraccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='recurringbilling',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_payment_transaction', to='monetization_tools.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='recurringbilling',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referral_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_referral_link', to='monetization_tools.referrallink'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_program', to='monetization_tools.referralprogram'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_program', to='monetization_tools.referralprogram'),
        ),
        migrations.AddField(
            model_name='revenuedailysummary',
            name='ad_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='revenuedailysummary',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_campaign', to='monetization_tools.adcampaign'),
        ),
        migrations.AddField(
            model_name='revenuedailysummary',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='revenuegoal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='offer_completion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_offer_completion', to='monetization_tools.offercompletion'),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spinwheelconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='prizeconfig',
            name='wheel_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_wheel_config', to='monetization_tools.spinwheelconfig'),
        ),
        migrations.AddField(
            model_name='spinwheellog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='spinwheellog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_target_plan', to='monetization_tools.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersegment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='target_segments',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_target_segments', to='monetization_tools.usersegment'),
        ),
        migrations.AddField(
            model_name='usersegmentmembership',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_segment', to='monetization_tools.usersegment'),
        ),
        migrations.AddField(
            model_name='usersegmentmembership',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usersegmentmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_plan', to='monetization_tools.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringbilling',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_subscription', to='monetization_tools.usersubscription'),
        ),
        migrations.AddField(
            model_name='waterfallconfig',
            name='ad_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_network', to='monetization_tools.adnetwork'),
        ),
        migrations.AddField(
            model_name='waterfallconfig',
            name='ad_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ad_unit', to='monetization_tools.adunit'),
        ),
        migrations.AddField(
            model_name='waterfallconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='abtest',
            index=models.Index(fields=['status'], name='mt_ab_status_idx'),
        ),
        migrations.AddIndex(
            model_name='abtestassignment',
            index=models.Index(fields=['test', 'variant_name'], name='mt_ab_assign_variant_idx'),
        ),
        migrations.AddConstraint(
            model_name='abtestassignment',
            constraint=models.UniqueConstraint(fields=('test', 'user'), name='mt_ab_assign_unique'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'category'], name='mt_ach_user_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement_key'), name='mt_ach_unique_per_user'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(check=models.Q(('coin_reward__gte', 0)), name='mt_ach_coin_non_neg'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='mt_camp_status_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['tenant', 'status'], name='mt_camp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['campaign_id'], name='mt_camp_uuid_idx'),
        ),
        migrations.AddConstraint(
            model_name='adcampaign',
            constraint=models.CheckConstraint(check=models.Q(('total_budget__gt', 0)), name='mt_campaign_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='adcampaign',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='mt_campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='adcampaign',
            constraint=models.CheckConstraint(check=models.Q(('daily_budget__isnull', True), ('daily_budget__lte', models.F('total_budget')), _connector='OR'), name='mt_campaign_daily_lte_total'),
        ),
        migrations.AddIndex(
            model_name='adnetwork',
            index=models.Index(fields=['network_type', 'is_active'], name='mt_an_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='adnetwork',
            index=models.Index(fields=['priority', 'is_active'], name='mt_an_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='adnetwork',
            constraint=models.UniqueConstraint(fields=('tenant', 'network_type'), name='mt_adnetwork_unique_type_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='adnetwork',
            constraint=models.CheckConstraint(check=models.Q(('floor_ecpm__gte', 0)), name='mt_adnetwork_floor_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='adnetwork',
            constraint=models.CheckConstraint(check=models.Q(('revenue_share__gte', 0), ('revenue_share__lte', 1)), name='mt_adnetwork_revshare_range'),
        ),
        migrations.AddConstraint(
            model_name='adnetworkdailystat',
            constraint=models.UniqueConstraint(fields=('ad_network', 'date'), name='mt_an_daily_stat_unique'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['campaign', 'ad_format', 'is_active'], name='mt_unit_camp_format_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['ad_network', 'ad_format'], name='mt_unit_network_format_idx'),
        ),
        migrations.AddConstraint(
            model_name='adunit',
            constraint=models.CheckConstraint(check=models.Q(('floor_ecpm__isnull', True), ('floor_ecpm__gte', 0), _connector='OR'), name='mt_adunit_floor_non_negative'),
        ),
        migrations.AddIndex(
            model_name='adplacement',
            index=models.Index(fields=['screen_name', 'position', 'is_active'], name='mt_place_screen_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='adplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('placement_key__isnull', False)), fields=('tenant', 'placement_key'), name='mt_placement_unique_key_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='adperformancehourly',
            index=models.Index(fields=['ad_unit', 'hour_bucket'], name='mt_ph_unit_hour_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancehourly',
            index=models.Index(fields=['ad_network', 'hour_bucket'], name='mt_ph_network_hour_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancehourly',
            index=models.Index(fields=['hour_bucket', 'country'], name='mt_ph_hour_country_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancehourly',
            index=models.Index(fields=['tenant', 'hour_bucket'], name='mt_ph_tenant_hour_idx'),
        ),
        migrations.AddConstraint(
            model_name='adperformancehourly',
            constraint=models.UniqueConstraint(fields=('tenant', 'ad_unit', 'ad_network', 'hour_bucket', 'country', 'device_type'), name='mt_perf_hourly_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='adperformancedaily',
            index=models.Index(fields=['date', 'total_revenue'], name='mt_pd_date_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancedaily',
            index=models.Index(fields=['ad_network', 'date'], name='mt_pd_network_date_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancedaily',
            index=models.Index(fields=['campaign', 'date'], name='mt_pd_camp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='adperformancedaily',
            index=models.Index(fields=['tenant', 'date'], name='mt_pd_tenant_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='adperformancedaily',
            constraint=models.UniqueConstraint(fields=('tenant', 'ad_unit', 'ad_network', 'campaign', 'date', 'country', 'device_type'), name='mt_perf_daily_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['ad_unit', 'status', 'is_active'], name='mt_creative_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['creative_type', 'status'], name='mt_creative_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionlog',
            index=models.Index(fields=['campaign', 'conversion_type'], name='mt_cnv_camp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionlog',
            index=models.Index(fields=['is_verified', 'converted_at'], name='mt_cnv_verified_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversionlog',
            constraint=models.CheckConstraint(check=models.Q(('payout__gte', 0)), name='mt_conv_payout_non_neg'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='mt_coup_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'used_at'], name='mt_coupon_usage_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('coupon', 'user'), name='mt_coupon_usage_uniq'),
        ),
        migrations.AddIndex(
            model_name='dailystreak',
            index=models.Index(fields=['current_streak'], name='mt_streak_current_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystreak',
            index=models.Index(fields=['last_login_date'], name='mt_streak_last_login_idx'),
        ),
        migrations.AddIndex(
            model_name='floorpriceconfig',
            index=models.Index(fields=['ad_network', 'country', 'is_active'], name='mt_fp_net_country_idx'),
        ),
        migrations.AddIndex(
            model_name='floorpriceconfig',
            index=models.Index(fields=['ad_unit', 'is_active'], name='mt_fp_unit_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorpriceconfig',
            constraint=models.CheckConstraint(check=models.Q(('floor_ecpm__gte', 0)), name='mt_floor_non_neg'),
        ),
        migrations.AddIndex(
            model_name='impressionlog',
            index=models.Index(fields=['ad_unit', 'logged_at'], name='mt_il_unit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='impressionlog',
            index=models.Index(fields=['ad_network', 'logged_at'], name='mt_il_net_time_idx'),
        ),
        migrations.AddIndex(
            model_name='impressionlog',
            index=models.Index(fields=['country', 'logged_at'], name='mt_il_country_time_idx'),
        ),
        migrations.AddIndex(
            model_name='impressionlog',
            index=models.Index(fields=['is_bot', 'logged_at'], name='mt_il_bot_time_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['ad_unit', 'clicked_at'], name='mt_cl_unit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['is_valid', 'clicked_at'], name='mt_cl_valid_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inapppurchase',
            index=models.Index(fields=['user', 'status'], name='mt_iap_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='inapppurchase',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='mt_iap_amount_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='inapppurchase',
            constraint=models.CheckConstraint(check=models.Q(('coins_granted__gte', 0)), name='mt_iap_coins_non_neg'),
        ),
        migrations.AddIndex(
            model_name='leaderboardrank',
            index=models.Index(fields=['scope', 'board_type', 'rank'], name='mt_lb_scope_type_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardrank',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'board_type', 'period_label'), name='mt_lb_unique_user_position'),
        ),
        migrations.AddConstraint(
            model_name='monetizationconfig',
            constraint=models.UniqueConstraint(fields=('tenant',), name='mt_config_one_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='monetizationnotificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_type', 'channel', 'language'), name='mt_notif_unique_per_event_channel_lang'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['transaction_id'], name='mt_oc_txn_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['user', 'status'], name='mt_oc_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['offer', 'status'], name='mt_oc_offer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['fraud_score', 'status'], name='mt_oc_fraud_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['ip_address', 'created_at'], name='mt_oc_ip_time_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['device_id', 'created_at'], name='mt_oc_device_time_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['clicked_at'], name='mt_oc_clicked_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['network_transaction_id'], name='mt_oc_net_txn_idx'),
        ),
        migrations.AddConstraint(
            model_name='offercompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('user', 'offer'), name='mt_completion_one_approval_per_user_offer'),
        ),
        migrations.AddConstraint(
            model_name='offercompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('network_transaction_id__isnull', False)), fields=('offer', 'network_transaction_id'), name='mt_completion_unique_network_txn'),
        ),
        migrations.AddConstraint(
            model_name='offercompletion',
            constraint=models.CheckConstraint(check=models.Q(('fraud_score__lte', 100)), name='mt_completion_fraud_max_100'),
        ),
        migrations.AddConstraint(
            model_name='offercompletion',
            constraint=models.CheckConstraint(check=models.Q(('reward_amount__gte', 0)), name='mt_completion_reward_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='offercompletion',
            constraint=models.CheckConstraint(check=models.Q(('payout_amount__gte', 0)), name='mt_completion_payout_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='offerwall',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mt_offerwall_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offerwall', 'status'], name='mt_off_wall_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'status'], name='mt_off_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['expiry_date', 'status'], name='mt_off_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured', 'is_hot'], name='mt_off_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(('payout_usd__gte', 0)), name='mt_offer_payout_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(('point_value__gte', 0)), name='mt_offer_points_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(('bonus_multiplier__gte', 1)), name='mt_offer_multiplier_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('offerwall', 'external_offer_id'), name='mt_offer_unique_external_per_wall'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='mt_pay_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'status'], name='mt_pay_gw_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='mt_pay_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_txn_id__isnull', False)), fields=('gateway', 'gateway_txn_id'), name='mt_pay_unique_gateway_txn'),
        ),
        migrations.AddIndex(
            model_name='payoutmethod',
            index=models.Index(fields=['user', 'method_type', 'is_active'], name='mt_pm_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='mt_payout_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'created_at'], name='mt_payout_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(check=models.Q(('coins_deducted__gt', 0)), name='mt_payout_coins_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(check=models.Q(('amount_usd__gt', 0)), name='mt_payout_usd_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', 0)), name='mt_payout_net_non_neg'),
        ),
        migrations.AddIndex(
            model_name='pointledgersnapshot',
            index=models.Index(fields=['user', 'snapshot_date'], name='mt_snap_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointledgersnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'snapshot_date'), name='mt_ledger_snap_unique'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['network_txn_id'], name='mt_pb_net_txn_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['status', 'received_at'], name='mt_pb_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['source_ip', 'received_at'], name='mt_pb_ip_time_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['ad_network', 'received_at'], name='mt_pb_net_time_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['user', 'severity', 'resolution'], name='mt_fraud_user_sev_res_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type', 'resolution'], name='mt_fraud_type_res_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['severity', 'resolution'], name='mt_fraud_sev_res_idx'),
        ),
        migrations.AddIndex(
            model_name='publisheraccount',
            index=models.Index(fields=['account_type', 'status'], name='mt_pub_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='publisheraccount',
            index=models.Index(fields=['email'], name='mt_pub_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='publisheraccount',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit_usd__gte', 0)), name='mt_pub_credit_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='publisheraccount',
            constraint=models.CheckConstraint(check=models.Q(('current_balance_usd__gte', 0)), name='mt_pub_balance_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='publisheraccount',
            constraint=models.CheckConstraint(check=models.Q(('custom_rev_share__isnull', True), models.Q(('custom_rev_share__gte', 0), ('custom_rev_share__lte', 1)), _connector='OR'), name='mt_pub_revshare_range'),
        ),
        migrations.AddConstraint(
            model_name='referralprogram',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mt_refprog_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='referralprogram',
            constraint=models.CheckConstraint(check=models.Q(('l1_commission_pct__gte', 0), ('l1_commission_pct__lte', 100)), name='mt_refprog_l1_range'),
        ),
        migrations.AddIndex(
            model_name='referrallink',
            index=models.Index(fields=['code'], name='mt_reflink_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='referrallink',
            constraint=models.UniqueConstraint(fields=('program', 'user'), name='mt_reflink_unique_per_user_prog'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referrer', 'is_paid'], name='mt_refcomm_referrer_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referee', 'level'], name='mt_refcomm_referee_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 5)), name='mt_refcomm_level_range'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.CheckConstraint(check=models.Q(('commission_coins__gte', 0)), name='mt_refcomm_coins_non_neg'),
        ),
        migrations.AddIndex(
            model_name='revenuedailysummary',
            index=models.Index(fields=['date', 'total_revenue'], name='mt_rds_date_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedailysummary',
            index=models.Index(fields=['tenant', 'date'], name='mt_rds_tenant_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenuedailysummary',
            constraint=models.UniqueConstraint(fields=('tenant', 'ad_network', 'campaign', 'date', 'country'), name='mt_rev_daily_unique'),
        ),
        migrations.AddConstraint(
            model_name='revenuegoal',
            constraint=models.CheckConstraint(check=models.Q(('target_value__gt', 0)), name='mt_goal_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='revenuegoal',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gt', models.F('period_start'))), name='mt_goal_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['transaction_id'], name='mt_rt_txn_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['user', '-created_at'], name='mt_rt_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['transaction_type'], name='mt_rt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['reference_id'], name='mt_rt_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardtransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '+', models.F('amount')))), name='mt_reward_txn_ledger_invariant'),
        ),
        migrations.AddConstraint(
            model_name='rewardtransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_before__gte', 0)), name='mt_reward_txn_balance_before_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='rewardtransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after__gte', 0)), name='mt_reward_txn_balance_after_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='spinwheelconfig',
            constraint=models.CheckConstraint(check=models.Q(('cost_per_spin__gte', 0)), name='mt_swconfig_cost_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='prizeconfig',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 1)), name='mt_prize_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='prizeconfig',
            constraint=models.CheckConstraint(check=models.Q(('prize_value__gte', 0)), name='mt_prize_value_non_neg'),
        ),
        migrations.AddIndex(
            model_name='spinwheellog',
            index=models.Index(fields=['user', 'log_type', 'played_at'], name='mt_spin_user_type_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='spinwheellog',
            constraint=models.CheckConstraint(check=models.Q(('prize_value__gte', 0)), name='mt_spin_prize_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mt_plan_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='mt_plan_price_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('coin_amount__gte', 0)), name='mt_coupon_coins_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_pct__gte', 0), ('discount_pct__lte', 100)), name='mt_coupon_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('multiplier__gte', 1)), name='mt_coupon_multiplier_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='usersegment',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mt_segment_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='mt_flash_active_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashsale',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='mt_flash_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='flashsale',
            constraint=models.CheckConstraint(check=models.Q(('multiplier__gte', 1)), name='mt_flash_multiplier_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='flashsale',
            constraint=models.CheckConstraint(check=models.Q(('discount_pct__gte', 0), ('discount_pct__lte', 100)), name='mt_flash_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='flashsale',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='mt_flash_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='usersegmentmembership',
            index=models.Index(fields=['user', 'segment'], name='mt_segmem_user_seg_idx'),
        ),
        migrations.AddIndex(
            model_name='usersegmentmembership',
            index=models.Index(fields=['segment', 'expires_at'], name='mt_segmem_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersegmentmembership',
            constraint=models.UniqueConstraint(fields=('segment', 'user'), name='mt_seg_membership_unique'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='mt_usub_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['current_period_end'], name='mt_usub_period_end_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'is_auto_renew'], name='mt_usub_renew_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbilling',
            index=models.Index(fields=['scheduled_at', 'status'], name='mt_bill_sched_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbilling',
            index=models.Index(fields=['status', 'next_attempt'], name='mt_bill_status_next_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringbilling',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='mt_bill_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='waterfallconfig',
            index=models.Index(fields=['ad_unit', 'priority', 'is_active'], name='mt_wf_unit_prio_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterfallconfig',
            constraint=models.UniqueConstraint(fields=('ad_unit', 'ad_network'), name='mt_wf_unique_unit_network'),
        ),
        migrations.AddConstraint(
            model_name='waterfallconfig',
            constraint=models.CheckConstraint(check=models.Q(('floor_ecpm__gte', 0)), name='mt_wf_floor_non_neg'),
        ),
    ]
