# Generated by Django 5.0.11 on 2026-03-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicefingerprint',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='fraudalert',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='fraudattempt',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='fraudrule',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='ipreputation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='userriskprofile',
            options={'ordering': ['-updated_at']},
        ),
    ]
