# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud_detection', '0002_initial'),
        ('offerwall', '0002_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudattempt',
            name='affected_transactions',
            field=models.ManyToManyField(blank=True, related_name='fraud_detection_attempts', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detection_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='fraud_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fraud_detection.fraudattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='fraudpattern',
            unique_together={('name', 'pattern_type')},
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='fraud_detec_rule_ty_28ca92_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['severity'], name='fraud_detec_severit_3ac147_idx'),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='fraud_rules',
            field=models.ManyToManyField(related_name='fraud_detection_attempts', to='fraud_detection.fraudrule'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='related_rules',
            field=models.ManyToManyField(blank=True, to='fraud_detection.fraudrule'),
        ),
        migrations.AddField(
            model_name='fraudsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ipreputation',
            index=models.Index(fields=['ip_address', 'is_blacklisted'], name='fraud_detec_ip_addr_7727b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ipreputation',
            index=models.Index(fields=['country', 'fraud_score'], name='fraud_detec_country_d796ea_idx'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='offerwall.offer', verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offer_completions', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_completions', to='wallet.wallettransaction', verbose_name='WalletTransaction'),
        ),
        migrations.AddField(
            model_name='offercompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_completions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userriskprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detection_risk_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['device_hash'], name='fraud_detec_device__45f678_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['user', 'last_seen'], name='fraud_detec_user_id_7ed638_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['ip_address', 'created_at'], name='fraud_detec_ip_addr_4cc1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattempt',
            index=models.Index(fields=['user', 'status'], name='fraud_detec_user_id_ff8d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattempt',
            index=models.Index(fields=['attempt_type', 'created_at'], name='fraud_detec_attempt_2beb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattempt',
            index=models.Index(fields=['fraud_score'], name='fraud_detec_fraud_s_b821da_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='fraud_detec_alert_t_fb3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['priority', 'created_at'], name='fraud_detec_priorit_da1e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['user', 'status'], name='fraud_detec_user_id_fcac76_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['offer', 'status'], name='fraud_detec_offer_i_d1f529_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['tracked_at'], name='fraud_detec_tracked_b5d8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='offercompletion',
            index=models.Index(fields=['is_fraud'], name='fraud_detec_is_frau_a1e8af_idx'),
        ),
        migrations.AddIndex(
            model_name='userriskprofile',
            index=models.Index(fields=['overall_risk_score'], name='fraud_detec_overall_4ddafa_idx'),
        ),
        migrations.AddIndex(
            model_name='userriskprofile',
            index=models.Index(fields=['is_flagged', 'is_restricted'], name='fraud_detec_is_flag_6807f6_idx'),
        ),
    ]
