# Generated by Django 5.0.11 on 2026-03-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_alter_devicefingerprint_options_and_more'),
        ('fraud_detection', '0002_fix_array_fields'),
    ]

    operations = [
    ]
