# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_device_hash_1002',
            old_name='fraud_detec_device__45f678_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_user_last_seen_1003',
            old_name='fraud_detec_user_id_7ed638_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_ip_address_created_at_1004',
            old_name='fraud_detec_ip_addr_4cc1c8_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudalert',
            new_name='idx_alert_type_is_resolved_1007',
            old_name='fraud_detec_alert_t_fb3ef8_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudalert',
            new_name='idx_priority_created_at_1008',
            old_name='fraud_detec_priorit_da1e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_user_status_997',
            old_name='fraud_detec_user_id_ff8d5d_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_attempt_type_created_at_998',
            old_name='fraud_detec_attempt_2beb6c_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_fraud_score_999',
            old_name='fraud_detec_fraud_s_b821da_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudrule',
            new_name='idx_rule_type_is_active_995',
            old_name='fraud_detec_rule_ty_28ca92_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudrule',
            new_name='idx_severity_996',
            old_name='fraud_detec_severit_3ac147_idx',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_ip_address_is_blacklisted_1005',
            old_name='fraud_detec_ip_addr_7727b7_idx',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_country_fraud_score_1006',
            old_name='fraud_detec_country_d796ea_idx',
        ),
        migrations.RenameIndex(
            model_name='offercompletion',
            new_name='idx_user_status_1009',
            old_name='fraud_detec_user_id_fcac76_idx',
        ),
        migrations.RenameIndex(
            model_name='offercompletion',
            new_name='idx_offer_status_1010',
            old_name='fraud_detec_offer_i_d1f529_idx',
        ),
        migrations.RenameIndex(
            model_name='offercompletion',
            new_name='idx_tracked_at_1011',
            old_name='fraud_detec_tracked_b5d8dd_idx',
        ),
        migrations.RenameIndex(
            model_name='offercompletion',
            new_name='idx_is_fraud_1012',
            old_name='fraud_detec_is_frau_a1e8af_idx',
        ),
        migrations.RenameIndex(
            model_name='userriskprofile',
            new_name='idx_overall_risk_score_1000',
            old_name='fraud_detec_overall_4ddafa_idx',
        ),
        migrations.RenameIndex(
            model_name='userriskprofile',
            new_name='idx_is_flagged_is_restricted_1001',
            old_name='fraud_detec_is_flag_6807f6_idx',
        ),
    ]
