# Generated by Django 5.0.11 on 2026-03-18 04:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_merge_20260318_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudpattern',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ipreputation',
            name='threat_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userriskprofile',
            name='warning_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
