# Generated by Django 5.0.11 on 2026-03-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0004_fix_array_default'),
        ('fraud_detection', '0004_fix_existing_array_data'),
    ]

    operations = [
    ]
