# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0004_rename_fraud_detec_device__45f678_idx_idx_device_hash_1002_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fraudalert',
            new_name='idx_alert_type_is_resolved_a40',
            old_name='idx_alert_type_is_resolved_1007',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_attempt_type_created_a_18d',
            old_name='idx_attempt_type_created_at_998',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_ip_address_is_blacklis_456',
            old_name='idx_ip_address_is_blacklisted_1005',
        ),
        migrations.RenameIndex(
            model_name='userriskprofile',
            new_name='idx_is_flagged_is_restrict_e85',
            old_name='idx_is_flagged_is_restricted_1001',
        ),
    ]
