# Generated by Django 5.0.11 on 2026-03-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0006_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudpattern',
            options={},
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='device_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
