# Generated by Django 5.0.11 on 2026-04-09 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0007_fix_device_fingerprint_null'),
        ('wallet', '0002_userpaymentmethod_tenant_wallet_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudattempt',
            name='affected_transactions',
            field=models.ManyToManyField(blank=True, related_name='fraud_detection_attempts', to='wallet.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='fraudattempt',
            name='fraud_rules',
            field=models.ManyToManyField(related_name='fraud_detection_attempts', to='fraud_detection.fraudrule'),
        ),
        migrations.AlterField(
            model_name='fraudattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detection_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userriskprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detection_risk_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
