# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertiser_portal', '0002_alter_click_coordinates_alter_conversion_coordinates_and_more'),
        ('offer_inventory', '0002_initial'),
        ('smartlink', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clickfraudflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clickmetadata',
            name='click',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='smartlink.click'),
        ),
        migrations.AddField(
            model_name='click',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='smartlink.clicksession'),
        ),
        migrations.AddField(
            model_name='offerblacklist',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerblacklist',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_from_smartlinks', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerperformancestat',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_performance_stats', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerpoolentry',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerpoolentry',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='smartlink.offerpool'),
        ),
        migrations.AddField(
            model_name='offercaptracker',
            name='pool_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_trackers', to='smartlink.offerpoolentry'),
        ),
        migrations.AddField(
            model_name='offerrotationlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerscorecache',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_caches', to='offer_inventory.offer'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['offer_id', 'created_at'], name='pb_offer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['click_id'], name='pb_click_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['transaction_id'], name='pb_txn_idx'),
        ),
        migrations.AddField(
            model_name='publisherallowlist',
            name='advertiser',
            field=models.ForeignKey(blank=True, help_text='Specific advertiser access grant. Null = all advertisers in category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_allowlists', to='advertiser_portal.advertiser'),
        ),
        migrations.AddField(
            model_name='publisherallowlist',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_allowlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherallowlist',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherblocklist',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_blocklists', to='advertiser_portal.advertiser'),
        ),
        migrations.AddField(
            model_name='publisherblocklist',
            name='blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherblocklist',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_advertisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherdomain',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publishersmartlink',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_smartlinks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publishersmartlink',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_smartlinks', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publishersubid',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_id_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redirectchain',
            name='click',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_chain', to='smartlink.click'),
        ),
        migrations.AddField(
            model_name='redirectlog',
            name='click',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_log', to='smartlink.click'),
        ),
        migrations.AddField(
            model_name='redirectlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlink_redirect_logs', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_smartlinks', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='redirectrule',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='redirectlog',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_redirect_logs', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='redirectchain',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_chains', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='publishersubid',
            name='smartlink',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all publisher SmartLinks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_id_definitions', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='publishersmartlink',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_assignments', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='prelander',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_landers', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='offerrotationlog',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_logs', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='offerpool',
            name='smartlink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_pool', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='offerperformancestat',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_performance_stats', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='offerblacklist',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_offers', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='geoperformancestat',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_performance_stats', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='deviceperformancestat',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_performance_stats', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='clicksession',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='clickheatmap',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='click',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='botclick',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_clicks', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='abtestresult',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_results', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinkdailystat',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinkdomain',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartlinkfallback',
            name='smartlink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fallback', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinkgroup',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_groups', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlink_smartlinks', to='smartlink.smartlinkgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='smartlinkrotation',
            name='smartlink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_config', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinkstat',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinktagging',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinktagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='smartlink.smartlinktag'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='smartlink_smartlinks', through='smartlink.SmartLinkTagging', to='smartlink.smartlinktag'),
        ),
        migrations.AddField(
            model_name='smartlinkversion',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='abtestresult',
            name='control_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_tests', to='smartlink.smartlinkversion'),
        ),
        migrations.AddField(
            model_name='abtestresult',
            name='winner_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tests', to='smartlink.smartlinkversion'),
        ),
        migrations.AddField(
            model_name='targetingrule',
            name='smartlink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rule', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='ostargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='os_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='languagetargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='isptargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isp_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='geotargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='devicetargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='browsertargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='browser_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='timetargeting',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_targeting', to='smartlink.targetingrule'),
        ),
        migrations.AddField(
            model_name='uniqueclick',
            name='first_click',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartlink.click'),
        ),
        migrations.AddField(
            model_name='uniqueclick',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_clicks', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='uniqueclick',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_clicks', to='smartlink.smartlink'),
        ),
        migrations.AddIndex(
            model_name='clickfraudflag',
            index=models.Index(fields=['score', 'action_taken'], name='fraud_score_action_idx'),
        ),
        migrations.AddIndex(
            model_name='clickfraudflag',
            index=models.Index(fields=['is_reviewed'], name='fraud_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='clickmetadata',
            index=models.Index(fields=['sub1'], name='meta_sub1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerpoolentry',
            unique_together={('pool', 'offer')},
        ),
        migrations.AddIndex(
            model_name='offercaptracker',
            index=models.Index(fields=['period_date', 'is_capped'], name='cap_date_capped_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offercaptracker',
            unique_together={('pool_entry', 'period', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='offerscorecache',
            index=models.Index(fields=['country', 'device_type', 'score'], name='score_geo_device_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerscorecache',
            unique_together={('offer', 'country', 'device_type')},
        ),
        migrations.AlterUniqueTogether(
            name='publisherallowlist',
            unique_together={('publisher', 'category', 'advertiser')},
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['smartlink', 'created_at'], name='rlog_sl_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['offer', 'created_at'], name='rlog_offer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['ip'], name='rlog_ip_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publishersmartlink',
            unique_together={('publisher', 'smartlink')},
        ),
        migrations.AddIndex(
            model_name='offerperformancestat',
            index=models.Index(fields=['offer', 'date'], name='opstat_offer_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerperformancestat',
            unique_together={('smartlink', 'offer', 'date', 'country', 'device_type')},
        ),
        migrations.AlterUniqueTogether(
            name='offerblacklist',
            unique_together={('smartlink', 'offer')},
        ),
        migrations.AddIndex(
            model_name='geoperformancestat',
            index=models.Index(fields=['country', 'date', 'epc'], name='geo_country_date_epc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geoperformancestat',
            unique_together={('smartlink', 'country', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceperformancestat',
            unique_together={('smartlink', 'device_type', 'date')},
        ),
        migrations.AddIndex(
            model_name='clicksession',
            index=models.Index(fields=['session_id'], name='session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='clicksession',
            index=models.Index(fields=['ip', 'smartlink'], name='session_ip_sl_idx'),
        ),
        migrations.AddIndex(
            model_name='clickheatmap',
            index=models.Index(fields=['date', 'country'], name='heatmap_date_country_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clickheatmap',
            unique_together={('smartlink', 'country', 'date')},
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['smartlink', 'created_at'], name='click_sl_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['offer', 'created_at'], name='click_offer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip', 'created_at'], name='click_ip_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['country', 'device_type'], name='click_geo_device_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['is_unique', 'is_fraud', 'is_bot'], name='click_flags_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkdailystat',
            index=models.Index(fields=['date', 'smartlink'], name='daily_date_sl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smartlinkdailystat',
            unique_together={('smartlink', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='smartlinkgroup',
            unique_together={('publisher', 'name')},
        ),
        migrations.AddIndex(
            model_name='smartlinkstat',
            index=models.Index(fields=['smartlink', 'hour'], name='stat_sl_hour_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkstat',
            index=models.Index(fields=['hour', 'country'], name='stat_hour_country_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smartlinkstat',
            unique_together={('smartlink', 'hour', 'country', 'device_type')},
        ),
        migrations.AlterUniqueTogether(
            name='smartlinktagging',
            unique_together={('smartlink', 'tag')},
        ),
        migrations.AddIndex(
            model_name='smartlink',
            index=models.Index(fields=['slug'], name='sl_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlink',
            index=models.Index(fields=['publisher', 'is_active'], name='sl_pub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlink',
            index=models.Index(fields=['created_at'], name='sl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='uniqueclick',
            index=models.Index(fields=['date', 'smartlink'], name='unique_date_sl_idx'),
        ),
    ]
