from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0003_offer_pool'),
        ('offer_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('click_count', models.PositiveSmallIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_click_session'},
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=10)),
                ('os', models.CharField(blank=True, max_length=10)),
                ('browser', models.CharField(blank=True, max_length=10)),
                ('is_unique', models.BooleanField(db_index=True, default=False)),
                ('is_fraud', models.BooleanField(db_index=True, default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('fraud_score', models.PositiveSmallIntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('smartlink', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='smartlink.smartlink')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.offer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartlink.clicksession')),
            ],
            options={'db_table': 'sl_click', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ClickMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('sub1', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sub2', models.CharField(blank=True, max_length=255)),
                ('sub3', models.CharField(blank=True, max_length=255)),
                ('sub4', models.CharField(blank=True, max_length=255)),
                ('sub5', models.CharField(blank=True, max_length=255)),
                ('custom_params', models.JSONField(blank=True, default=dict)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('landing_page_url', models.URLField(blank=True, max_length=2048)),
                ('offer_url_final', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='smartlink.click')),
            ],
            options={'db_table': 'sl_click_metadata'},
        ),
        migrations.CreateModel(
            name='UniqueClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateField(db_index=True)),
                ('click_count', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlink.smartlink')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer_inventory.offer')),
                ('first_click', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartlink.click')),
            ],
            options={'db_table': 'sl_unique_click'},
        ),
        migrations.CreateModel(
            name='ClickFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('signals', models.JSONField(default=list)),
                ('action_taken', models.CharField(max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='smartlink.click')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'sl_click_fraud_flag'},
        ),
        migrations.CreateModel(
            name='ClickHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('country', models.CharField(max_length=2)),
                ('date', models.DateField(db_index=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_click_heatmap', 'unique_together': {('smartlink', 'country', 'date')}},
        ),
        migrations.CreateModel(
            name='BotClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('bot_type', models.CharField(blank=True, max_length=50)),
                ('detection_method', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_clicks', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_bot_click', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RedirectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('redirect_type', models.CharField(default='302', max_length=5)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('destination_url', models.URLField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(default=302)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('was_cached', models.BooleanField(default=False)),
                ('was_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('smartlink', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_logs', to='smartlink.smartlink')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.offer')),
                ('click', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_log', to='smartlink.click')),
            ],
            options={'db_table': 'sl_redirect_log', 'ordering': ['-created_at']},
        ),
    ]
