from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ('smartlink', '0004_click_tracking'),
        ('offer_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLinkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('hour', models.DateTimeField(db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('bot_clicks', models.PositiveIntegerField(default=0)),
                ('fraud_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_smartlink_stat', 'unique_together': {('smartlink', 'hour', 'country', 'device_type')}},
        ),
        migrations.CreateModel(
            name='SmartLinkDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('date', models.DateField(db_index=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('bot_clicks', models.PositiveIntegerField(default=0)),
                ('fraud_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('top_country', models.CharField(blank=True, max_length=2)),
                ('top_device', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_smartlink_daily_stat', 'ordering': ['-date'], 'unique_together': {('smartlink', 'date')}},
        ),
        migrations.CreateModel(
            name='OfferPerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('date', models.DateField(db_index=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=10)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_performance_stats', to='smartlink.smartlink')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_performance_stats', to='offer_inventory.offer')),
            ],
            options={'db_table': 'sl_offer_performance_stat', 'unique_together': {('smartlink', 'offer', 'date', 'country', 'device_type')}},
        ),
        migrations.CreateModel(
            name='GeoPerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('date', models.DateField(db_index=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_performance_stats', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_geo_performance_stat', 'unique_together': {('smartlink', 'country', 'date')}},
        ),
        migrations.CreateModel(
            name='DevicePerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('device_type', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('epc', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_performance_stats', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_device_performance_stat', 'unique_together': {('smartlink', 'device_type', 'date')}},
        ),
        migrations.CreateModel(
            name='ABTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('status', models.CharField(choices=[('draft','Draft'),('running','Running'),('paused','Paused'),('completed','Completed'),('winner_found','Winner Found')], db_index=True, default='running', max_length=15)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('uplift_percent', models.FloatField(default=0.0)),
                ('control_cr', models.FloatField(default=0.0)),
                ('winner_cr', models.FloatField(default=0.0)),
                ('control_clicks', models.PositiveIntegerField(default=0)),
                ('winner_clicks', models.PositiveIntegerField(default=0)),
                ('p_value', models.FloatField(default=1.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_results', to='smartlink.smartlink')),
                ('winner_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tests', to='smartlink.smartlinkversion')),
                ('control_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_tests', to='smartlink.smartlinkversion')),
            ],
            options={'db_table': 'sl_ab_test_result', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PublisherDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('verification_status', models.CharField(choices=[('pending','Pending'),('verified','Verified'),('failed','Failed'),('expired','Expired')], db_index=True, default='pending', max_length=10)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'sl_publisher_domain', 'ordering': ['-is_primary', 'domain']},
        ),
        migrations.CreateModel(
            name='PublisherSmartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_edit_targeting', models.BooleanField(default=True)),
                ('can_edit_pool', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_smartlinks', to=settings.AUTH_USER_MODEL)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_assignments', to='smartlink.smartlink')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_smartlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'sl_publisher_smartlink', 'unique_together': {('publisher', 'smartlink')}},
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('traffic_split', models.PositiveSmallIntegerField(default=100)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('clicks_through', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_landing_page'},
        ),
        migrations.CreateModel(
            name='PreLander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=2048)),
                ('type', models.CharField(choices=[('survey','Survey'),('quiz','Quiz'),('video','Video'),('article','Article'),('custom','Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('pass_through_params', models.BooleanField(default=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('pass_through_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_landers', to='smartlink.smartlink')),
            ],
            options={'db_table': 'sl_pre_lander'},
        ),
        migrations.CreateModel(
            name='RedirectChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('chain', models.JSONField(default=list)),
                ('hop_count', models.PositiveSmallIntegerField(default=0)),
                ('total_time_ms', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smartlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_chains', to='smartlink.smartlink')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_chain', to='smartlink.click')),
            ],
            options={'db_table': 'sl_redirect_chain', 'ordering': ['-created_at']},
        ),
    ]
