# Generated by Django 5.0.11 on 2026-04-10 09:49

import api.smartlink.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_portal', '0002_alter_click_coordinates_alter_conversion_coordinates_and_more'),
        ('offer_inventory', '0002_alter_redirectlog_offer_alter_redirectlog_smart_link'),
        ('smartlink', '0008_postback_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('ip_range', 'IP Range'), ('country', 'Country'), ('ua_contains', 'User Agent Contains'), ('param_match', 'URL Parameter Match'), ('time_based', 'Time Based')], max_length=20)),
                ('condition_value', models.CharField(help_text='Value to match against.', max_length=500)),
                ('redirect_url', models.URLField(help_text='Override redirect URL when condition is matched.', max_length=2048, validators=[api.smartlink.validators.validate_redirect_url])),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher = evaluated first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect Rule',
                'db_table': 'sl_redirect_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmartLinkDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Domain')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SmartLink Domain',
                'db_table': 'smartlink_domain',
            },
        ),
        migrations.AlterModelOptions(
            name='abtestresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'A/B Test Result'},
        ),
        migrations.AlterModelOptions(
            name='botclick',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bot Click'},
        ),
        migrations.AlterModelOptions(
            name='browsertargeting',
            options={'verbose_name': 'Browser Targeting'},
        ),
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-created_at'], 'verbose_name': 'Click', 'verbose_name_plural': 'Clicks'},
        ),
        migrations.AlterModelOptions(
            name='clickfraudflag',
            options={'verbose_name': 'Click Fraud Flag'},
        ),
        migrations.AlterModelOptions(
            name='clickheatmap',
            options={'verbose_name': 'Click Heatmap'},
        ),
        migrations.AlterModelOptions(
            name='clickmetadata',
            options={'verbose_name': 'Click Metadata'},
        ),
        migrations.AlterModelOptions(
            name='clicksession',
            options={'verbose_name': 'Click Session'},
        ),
        migrations.AlterModelOptions(
            name='deviceperformancestat',
            options={'verbose_name': 'Device Performance Stat'},
        ),
        migrations.AlterModelOptions(
            name='devicetargeting',
            options={'verbose_name': 'Device Targeting'},
        ),
        migrations.AlterModelOptions(
            name='geoperformancestat',
            options={'verbose_name': 'Geo Performance Stat'},
        ),
        migrations.AlterModelOptions(
            name='geotargeting',
            options={'verbose_name': 'Geo Targeting'},
        ),
        migrations.AlterModelOptions(
            name='isptargeting',
            options={'verbose_name': 'ISP Targeting'},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Landing Page'},
        ),
        migrations.AlterModelOptions(
            name='languagetargeting',
            options={'verbose_name': 'Language Targeting'},
        ),
        migrations.AlterModelOptions(
            name='offerblacklist',
            options={'verbose_name': 'Offer Blacklist'},
        ),
        migrations.AlterModelOptions(
            name='offercaptracker',
            options={'verbose_name': 'Offer Cap Tracker'},
        ),
        migrations.AlterModelOptions(
            name='offerperformancestat',
            options={'verbose_name': 'Offer Performance Stat'},
        ),
        migrations.AlterModelOptions(
            name='offerpool',
            options={'verbose_name': 'Offer Pool'},
        ),
        migrations.AlterModelOptions(
            name='offerpoolentry',
            options={'ordering': ['-priority', '-weight'], 'verbose_name': 'Offer Pool Entry'},
        ),
        migrations.AlterModelOptions(
            name='offerrotationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer Rotation Log'},
        ),
        migrations.AlterModelOptions(
            name='offerscorecache',
            options={'verbose_name': 'Offer Score Cache'},
        ),
        migrations.AlterModelOptions(
            name='ostargeting',
            options={'verbose_name': 'OS Targeting'},
        ),
        migrations.AlterModelOptions(
            name='postbacklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postback Log'},
        ),
        migrations.AlterModelOptions(
            name='prelander',
            options={'ordering': ['name'], 'verbose_name': 'Pre-Lander'},
        ),
        migrations.AlterModelOptions(
            name='publisherallowlist',
            options={'verbose_name': 'Publisher Allow List'},
        ),
        migrations.AlterModelOptions(
            name='publisherblocklist',
            options={'verbose_name': 'Publisher Block List'},
        ),
        migrations.AlterModelOptions(
            name='publisherdomain',
            options={'ordering': ['-is_primary', 'domain'], 'verbose_name': 'Publisher Domain'},
        ),
        migrations.AlterModelOptions(
            name='publishersmartlink',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Publisher SmartLink'},
        ),
        migrations.AlterModelOptions(
            name='publishersubid',
            options={'verbose_name': 'Publisher Sub ID Definition'},
        ),
        migrations.AlterModelOptions(
            name='redirectchain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Redirect Chain'},
        ),
        migrations.AlterModelOptions(
            name='redirectlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Redirect Log'},
        ),
        migrations.AlterModelOptions(
            name='smartlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'SmartLink', 'verbose_name_plural': 'SmartLinks'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkdailystat',
            options={'ordering': ['-date'], 'verbose_name': 'SmartLink Daily Stat'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkfallback',
            options={'verbose_name': 'SmartLink Fallback'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkgroup',
            options={'ordering': ['name'], 'verbose_name': 'SmartLink Group', 'verbose_name_plural': 'SmartLink Groups'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkrotation',
            options={'verbose_name': 'SmartLink Rotation Config'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkstat',
            options={'verbose_name': 'SmartLink Hourly Stat'},
        ),
        migrations.AlterModelOptions(
            name='smartlinktag',
            options={'ordering': ['name'], 'verbose_name': 'SmartLink Tag'},
        ),
        migrations.AlterModelOptions(
            name='smartlinktagging',
            options={'verbose_name': 'SmartLink Tagging'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkversion',
            options={'ordering': ['-is_control', 'name'], 'verbose_name': 'SmartLink Version (A/B)'},
        ),
        migrations.AlterModelOptions(
            name='targetingrule',
            options={'verbose_name': 'Targeting Rule'},
        ),
        migrations.AlterModelOptions(
            name='timetargeting',
            options={'verbose_name': 'Time Targeting'},
        ),
        migrations.AlterModelOptions(
            name='uniqueclick',
            options={'verbose_name': 'Unique Click'},
        ),
        migrations.RemoveField(
            model_name='publisherdomain',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='publisherdomain',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='publisherallowlist',
            name='advertiser',
            field=models.ForeignKey(blank=True, help_text='Specific advertiser access grant. Null = all advertisers in category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_allowlists', to='advertiser_portal.advertiser'),
        ),
        migrations.AddField(
            model_name='publisherblocklist',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_blocklists', to='advertiser_portal.advertiser'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='smartlink_smartlinks', through='smartlink.SmartLinkTagging', to='smartlink.smartlinktag'),
        ),
        migrations.AlterField(
            model_name='abtestresult',
            name='auto_applied',
            field=models.BooleanField(default=False, help_text='Winner was automatically applied to SmartLink rotation.'),
        ),
        migrations.AlterField(
            model_name='abtestresult',
            name='confidence_level',
            field=models.FloatField(default=0.0, help_text='Statistical confidence (0.0 - 1.0). Significant at 0.95+.'),
        ),
        migrations.AlterField(
            model_name='abtestresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='abtestresult',
            name='p_value',
            field=models.FloatField(default=1.0, help_text='Statistical p-value. Significant at < 0.05.'),
        ),
        migrations.AlterField(
            model_name='abtestresult',
            name='uplift_percent',
            field=models.FloatField(default=0.0, help_text='Percentage improvement of winner vs control.'),
        ),
        migrations.AlterField(
            model_name='botclick',
            name='bot_type',
            field=models.CharField(blank=True, help_text='Googlebot, SEMrush, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='botclick',
            name='detection_method',
            field=models.CharField(help_text='ua_pattern, ip_list, behavior', max_length=30),
        ),
        migrations.AlterField(
            model_name='botclick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='browsertargeting',
            name='browsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('opera', 'Opera'), ('other', 'Other')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='browsertargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='browsertargeting',
            name='mode',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=10),
        ),
        migrations.AlterField(
            model_name='click',
            name='browser',
            field=models.CharField(blank=True, choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('opera', 'Opera'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='click',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='click',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlink_clicks', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='click',
            name='os',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='click',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='smartlink.clicksession'),
        ),
        migrations.AlterField(
            model_name='clickfraudflag',
            name='action_taken',
            field=models.CharField(help_text='allow/block/flag', max_length=20),
        ),
        migrations.AlterField(
            model_name='clickfraudflag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clickfraudflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clickfraudflag',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 fraud probability score.'),
        ),
        migrations.AlterField(
            model_name='clickfraudflag',
            name='signals',
            field=models.JSONField(default=list, help_text='List of fraud signal types detected.'),
        ),
        migrations.AlterField(
            model_name='clickheatmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clickmetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clicksession',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clicksession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceperformancestat',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceperformancestat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicetargeting',
            name='device_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], max_length=10), blank=True, default=list, help_text='e.g. ["mobile", "tablet"]', size=None),
        ),
        migrations.AlterField(
            model_name='devicetargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicetargeting',
            name='mode',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=10),
        ),
        migrations.AlterField(
            model_name='geoperformancestat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='ISO 3166-1 alpha-2 country codes. e.g. ["BD","US","GB"]', size=None),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geotargeting',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Region/state names.', size=None),
        ),
        migrations.AlterField(
            model_name='isptargeting',
            name='asns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='ASN numbers. e.g. ["AS24389", "AS17494"]', size=None),
        ),
        migrations.AlterField(
            model_name='isptargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='isptargeting',
            name='isps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='ISP/carrier names. e.g. ["Grameenphone","Robi","Banglalink"]', size=None),
        ),
        migrations.AlterField(
            model_name='isptargeting',
            name='mode',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='traffic_split',
            field=models.PositiveSmallIntegerField(default=100, help_text='Percentage of traffic to this landing page (0-100).'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='url',
            field=models.URLField(max_length=2048, validators=[api.smartlink.validators.validate_redirect_url]),
        ),
        migrations.AlterField(
            model_name='languagetargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='languagetargeting',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='ISO 639-1 language codes. e.g. ["en","bn","ar"]', size=None),
        ),
        migrations.AlterField(
            model_name='languagetargeting',
            name='mode',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=10),
        ),
        migrations.AlterField(
            model_name='offerblacklist',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerblacklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerblacklist',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_from_smartlinks', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='offercaptracker',
            name='cap_limit',
            field=models.PositiveIntegerField(help_text='Snapshot of cap at time of creation.'),
        ),
        migrations.AlterField(
            model_name='offercaptracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offercaptracker',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('total', 'Total (Lifetime)')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='offercaptracker',
            name='period_date',
            field=models.DateField(db_index=True, help_text='The date this tracker applies to (YYYY-MM-DD for daily).'),
        ),
        migrations.AlterField(
            model_name='offerperformancestat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='min_epc_threshold',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Minimum EPC required for an offer to be included in rotation.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='offerpoolentry',
            name='cap_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Max clicks per day for this offer in this pool.', null=True, validators=[api.smartlink.validators.validate_cap_value]),
        ),
        migrations.AlterField(
            model_name='offerpoolentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerpoolentry',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Priority order. Higher = evaluated first in priority mode.'),
        ),
        migrations.AlterField(
            model_name='offerpoolentry',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Rotation weight (1-1000). Higher = more traffic.', validators=[api.smartlink.validators.validate_weight]),
        ),
        migrations.AlterField(
            model_name='offerrotationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerrotationlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='offerrotationlog',
            name='selected_reason',
            field=models.CharField(help_text='e.g. weighted_random, epc_optimized', max_length=30),
        ),
        migrations.AlterField(
            model_name='offerscorecache',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offerscorecache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ostargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ostargeting',
            name='mode',
            field=models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], default='whitelist', max_length=10),
        ),
        migrations.AlterField(
            model_name='ostargeting',
            name='os_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux'), ('unknown', 'Unknown')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='postbacklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prelander',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prelander',
            name='pass_through_params',
            field=models.BooleanField(default=True, help_text='Pass sub1-sub5 params through the pre-lander URL.'),
        ),
        migrations.AlterField(
            model_name='prelander',
            name='url',
            field=models.URLField(max_length=2048, validators=[api.smartlink.validators.validate_redirect_url]),
        ),
        migrations.AlterField(
            model_name='publisherallowlist',
            name='category',
            field=models.CharField(help_text='Offer category/vertical name. e.g. "finance", "gaming", "health"', max_length=100),
        ),
        migrations.AlterField(
            model_name='publisherallowlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisherblocklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisherdomain',
            name='domain',
            field=models.CharField(max_length=253, unique=True, validators=[api.smartlink.validators.validate_custom_domain], verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='publisherdomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisherdomain',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary domain for this publisher.'),
        ),
        migrations.AlterField(
            model_name='publisherdomain',
            name='verification_token',
            field=models.CharField(blank=True, help_text='TXT record value for DNS verification.', max_length=64),
        ),
        migrations.AlterField(
            model_name='publishersmartlink',
            name='can_edit_pool',
            field=models.BooleanField(default=False, help_text='Allow publisher to add/remove offers from pool.'),
        ),
        migrations.AlterField(
            model_name='publishersmartlink',
            name='can_edit_targeting',
            field=models.BooleanField(default=True, help_text='Allow publisher to edit targeting rules.'),
        ),
        migrations.AlterField(
            model_name='publishersmartlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishersmartlink',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_smartlinks', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='publishersubid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishersubid',
            name='smartlink',
            field=models.ForeignKey(blank=True, help_text='If null, applies to all publisher SmartLinks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_id_definitions', to='smartlink.smartlink'),
        ),
        migrations.AlterField(
            model_name='redirectchain',
            name='chain',
            field=models.JSONField(default=list, help_text='Ordered list of hops. Each hop: {"step": 1, "type": "pre_lander", "url": "...", "ts": "..."}'),
        ),
        migrations.AlterField(
            model_name='redirectchain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redirectlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redirectlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlink_redirect_logs', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='redirectlog',
            name='redirect_type',
            field=models.CharField(choices=[('302', 'HTTP 302 (Temporary)'), ('301', 'HTTP 301 (Permanent)'), ('meta', 'Meta Refresh'), ('js', 'JavaScript Redirect')], default='302', max_length=5),
        ),
        migrations.AlterField(
            model_name='redirectlog',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_redirect_logs', to='smartlink.smartlink'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartlink_smartlinks', to='smartlink.smartlinkgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_smartlinks', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='redirect_type',
            field=models.CharField(choices=[('302', 'HTTP 302 (Temporary)'), ('301', 'HTTP 301 (Permanent)'), ('meta', 'Meta Refresh'), ('js', 'JavaScript Redirect')], default='302', max_length=5, verbose_name='Redirect Type'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='rotation_method',
            field=models.CharField(choices=[('weighted', 'Weighted Random'), ('round_robin', 'Round Robin'), ('epc_optimized', 'EPC Optimized'), ('priority', 'Priority Based')], default='weighted', max_length=20, verbose_name='Rotation Method'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='slug',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[api.smartlink.validators.validate_slug_format], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('geo_specific', 'Geo Specific'), ('device_specific', 'Device Specific'), ('offer_specific', 'Offer Specific'), ('ab_test', 'A/B Test'), ('campaign', 'Campaign')], default='general', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='smartlinkdailystat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkfallback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkfallback',
            name='url',
            field=models.URLField(max_length=2048, validators=[api.smartlink.validators.validate_redirect_url], verbose_name='Fallback URL'),
        ),
        migrations.AlterField(
            model_name='smartlinkgroup',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='smartlinkgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='smartlinkgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='smartlinkgroup',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_groups', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='smartlinkrotation',
            name='auto_optimize_epc',
            field=models.BooleanField(default=False, help_text='Automatically shift weight to higher-EPC offers.'),
        ),
        migrations.AlterField(
            model_name='smartlinkrotation',
            name='epc_min_clicks',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minimum clicks before offer is included in EPC optimization.'),
        ),
        migrations.AlterField(
            model_name='smartlinkrotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkrotation',
            name='method',
            field=models.CharField(choices=[('weighted', 'Weighted Random'), ('round_robin', 'Round Robin'), ('epc_optimized', 'EPC Optimized'), ('priority', 'Priority Based')], default='weighted', max_length=20),
        ),
        migrations.AlterField(
            model_name='smartlinkstat',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='CR = conversions / clicks', max_digits=6),
        ),
        migrations.AlterField(
            model_name='smartlinkstat',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='smartlinkstat',
            name='epc',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Earnings per click = revenue / clicks', max_digits=8),
        ),
        migrations.AlterField(
            model_name='smartlinkstat',
            name='hour',
            field=models.DateTimeField(db_index=True, help_text='Truncated to hour (YYYY-MM-DD HH:00:00).'),
        ),
        migrations.AlterField(
            model_name='smartlinkstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinktag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinktag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='smartlinktagging',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinktagging',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='smartlink.smartlink'),
        ),
        migrations.AlterField(
            model_name='smartlinktagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='smartlink.smartlinktag'),
        ),
        migrations.AlterField(
            model_name='smartlinkversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkversion',
            name='is_control',
            field=models.BooleanField(default=False, help_text='Is this the control variant?'),
        ),
        migrations.AlterField(
            model_name='smartlinkversion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Version Name'),
        ),
        migrations.AlterField(
            model_name='smartlinkversion',
            name='traffic_split',
            field=models.PositiveSmallIntegerField(default=50, help_text='Percentage of traffic for this variant (0-100).'),
        ),
        migrations.AlterField(
            model_name='targetingrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='targetingrule',
            name='logic',
            field=models.CharField(choices=[('AND', 'All rules must match'), ('OR', 'Any rule must match')], default='AND', max_length=3, verbose_name='Rule Logic'),
        ),
        migrations.AlterField(
            model_name='targetingrule',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher priority rules evaluated first.'),
        ),
        migrations.AlterField(
            model_name='timetargeting',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, default=list, help_text='0=Monday, 6=Sunday. Empty = all days.', size=None),
        ),
        migrations.AlterField(
            model_name='timetargeting',
            name='end_hour',
            field=models.PositiveSmallIntegerField(default=23, help_text='UTC hour to end (0-23).'),
        ),
        migrations.AlterField(
            model_name='timetargeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetargeting',
            name='start_hour',
            field=models.PositiveSmallIntegerField(default=0, help_text='UTC hour to start (0-23).'),
        ),
        migrations.AlterField(
            model_name='timetargeting',
            name='timezone_name',
            field=models.CharField(default='UTC', help_text='Timezone for day/hour evaluation.', max_length=50),
        ),
        migrations.AlterField(
            model_name='uniqueclick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uniqueclick',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_clicks', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='uniqueclick',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_clicks', to='smartlink.smartlink'),
        ),
        migrations.AlterUniqueTogether(
            name='publisherallowlist',
            unique_together={('publisher', 'category', 'advertiser')},
        ),
        migrations.AlterUniqueTogether(
            name='smartlinkgroup',
            unique_together={('publisher', 'name')},
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['smartlink', 'created_at'], name='click_sl_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['offer', 'created_at'], name='click_offer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip', 'created_at'], name='click_ip_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['country', 'device_type'], name='click_geo_device_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['is_unique', 'is_fraud', 'is_bot'], name='click_flags_idx'),
        ),
        migrations.AddIndex(
            model_name='clickfraudflag',
            index=models.Index(fields=['score', 'action_taken'], name='fraud_score_action_idx'),
        ),
        migrations.AddIndex(
            model_name='clickfraudflag',
            index=models.Index(fields=['is_reviewed'], name='fraud_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='clickheatmap',
            index=models.Index(fields=['date', 'country'], name='heatmap_date_country_idx'),
        ),
        migrations.AddIndex(
            model_name='clickmetadata',
            index=models.Index(fields=['sub1'], name='meta_sub1_idx'),
        ),
        migrations.AddIndex(
            model_name='clicksession',
            index=models.Index(fields=['session_id'], name='session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='clicksession',
            index=models.Index(fields=['ip', 'smartlink'], name='session_ip_sl_idx'),
        ),
        migrations.AddIndex(
            model_name='geoperformancestat',
            index=models.Index(fields=['country', 'date', 'epc'], name='geo_country_date_epc_idx'),
        ),
        migrations.AddIndex(
            model_name='offercaptracker',
            index=models.Index(fields=['period_date', 'is_capped'], name='cap_date_capped_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformancestat',
            index=models.Index(fields=['offer', 'date'], name='opstat_offer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='offerscorecache',
            index=models.Index(fields=['country', 'device_type', 'score'], name='score_geo_device_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['smartlink', 'created_at'], name='rlog_sl_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['offer', 'created_at'], name='rlog_offer_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectlog',
            index=models.Index(fields=['ip'], name='rlog_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlink',
            index=models.Index(fields=['created_at'], name='sl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkdailystat',
            index=models.Index(fields=['date', 'smartlink'], name='daily_date_sl_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkstat',
            index=models.Index(fields=['smartlink', 'hour'], name='stat_sl_hour_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkstat',
            index=models.Index(fields=['hour', 'country'], name='stat_hour_country_idx'),
        ),
        migrations.AddIndex(
            model_name='uniqueclick',
            index=models.Index(fields=['date', 'smartlink'], name='unique_date_sl_idx'),
        ),
        migrations.AddField(
            model_name='redirectrule',
            name='smartlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='smartlink.smartlink'),
        ),
        migrations.AddField(
            model_name='smartlinkdomain',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlink_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
