# Generated by Django 5.0.14 on 2026-02-17 09:53
# FIXED: ForeignKey default ছিল timezone.now, UUID field এ কাজ করে না

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimittracker',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratelimittracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratelimittracker',
            name='endpoint',
            field=models.CharField(default='', max_length=255),  # [OK] timezone.now → ''
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratelimittracker',
            name='user',
            field=models.ForeignKey(
                null=True,                          # [OK] null=True যোগ করা হয়েছে
                blank=True,                         # [OK] blank=True যোগ করা হয়েছে
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskscorehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountlink',
            name='linked_account',
            field=models.CharField(default='', max_length=255),  # [OK] timezone.now → ''
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='action_type',
            field=models.CharField(default='', max_length=100),  # [OK] timezone.now → ''
            preserve_default=False,
        ),
    ]