# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_fingerprint_hash_1863',
            old_name='device_fing_fingerp_25f02a_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_is_suspicious_1864',
            old_name='device_fing_is_susp_a66d98_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_is_blocked_1865',
            old_name='device_fing_is_bloc_b588ff_idx',
        ),
        migrations.RenameIndex(
            model_name='frauddetectionlog',
            new_name='idx_event_type_1872',
            old_name='fraud_detec_event_t_6cd581_idx',
        ),
        migrations.RenameIndex(
            model_name='frauddetectionlog',
            new_name='idx_severity_1873',
            old_name='fraud_detec_severit_7ae879_idx',
        ),
        migrations.RenameIndex(
            model_name='frauddetectionlog',
            new_name='idx_ip_address_1874',
            old_name='fraud_detec_ip_addr_361323_idx',
        ),
        migrations.RenameIndex(
            model_name='frauddetectionlog',
            new_name='idx_detected_at_1875',
            old_name='fraud_detec_detecte_f16760_idx',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_ip_address_1866',
            old_name='ip_reputati_ip_addr_26e481_idx',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_reputation_1867',
            old_name='ip_reputati_reputat_625b85_idx',
        ),
        migrations.RenameIndex(
            model_name='ipreputation',
            new_name='idx_is_blacklisted_1868',
            old_name='ip_reputati_is_blac_f59001_idx',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='idx_code_is_used_1860',
            old_name='users_otp_code_fa06ee_idx',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='idx_expires_at_1861',
            old_name='users_otp_expires_8f43b7_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimittracker',
            new_name='idx_identifier_limit_type_1877',
            old_name='rate_limit__identif_86ebe1_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimittracker',
            new_name='idx_is_blocked_1878',
            old_name='rate_limit__is_bloc_202775_idx',
        ),
        migrations.RenameIndex(
            model_name='riskscorehistory',
            new_name='idx_user_calculated_at_1876',
            old_name='risk_score__user_id_c33498_idx',
        ),
        migrations.RenameIndex(
            model_name='useraccountlink',
            new_name='idx_registration_ip_1869',
            old_name='user_accoun_registr_eb41ed_idx',
        ),
        migrations.RenameIndex(
            model_name='useraccountlink',
            new_name='idx_registration_date_1870',
            old_name='user_accoun_registr_91a812_idx',
        ),
        migrations.RenameIndex(
            model_name='useraccountlink',
            new_name='idx_is_flagged_1871',
            old_name='user_accoun_is_flag_21313f_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='idx_timestamp_1862',
            old_name='users_usera_timesta_b616d0_idx',
        ),
        migrations.RenameIndex(
            model_name='userstatistics',
            new_name='idx_user_total_earned_1879',
            old_name='user_statis_user_id_ca5f00_idx',
        ),
        migrations.RenameIndex(
            model_name='userstatistics',
            new_name='idx_user_current_streak_1880',
            old_name='user_statis_user_id_2d90c5_idx',
        ),
    ]
