# Generated by Django 5.0.11 on 2026-02-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ratelimittracker_count_ratelimittracker_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
