# Generated by Django 5.0.11 on 2026-03-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vpn_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccountlink',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
