# Generated by Django 5.0.11 on 2026-03-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_frauddetectionlog_resolved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
