# Generated by Django 5.0.11 on 2026-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Geographic coordinates as {lat, lng}', null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Geographic coordinates as {lat, lng}', null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Geographic coordinates as {lat, lng}', null=True),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='geo_coordinates',
            field=models.JSONField(blank=True, help_text='Geographic coordinates as {lat, lng}', null=True),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='geo_shapes',
            field=models.JSONField(blank=True, help_text='Geographic shapes as GeoJSON', null=True),
        ),
    ]
