# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_portal', '0003_remove_blacklistappeal_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advertiserverification',
            new_name='idx_advertiser_verificatio_11f',
            old_name='idx_advertiser_verification_type_066',
        ),
        migrations.RenameIndex(
            model_name='audiencesegment',
            new_name='idx_advertiser_segment_typ_82a',
            old_name='idx_advertiser_segment_type_359',
        ),
        migrations.RenameIndex(
            model_name='integrationcredential',
            new_name='idx_integration_credential_ced',
            old_name='idx_integration_credential_type_319',
        ),
        migrations.RenameIndex(
            model_name='integrationmapping',
            new_name='idx_integration_source_ent_d9e',
            old_name='idx_integration_source_entity_317',
        ),
        migrations.RenameIndex(
            model_name='integrationmapping',
            new_name='idx_integration_target_ent_319',
            old_name='idx_integration_target_entity_318',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='idx_notification_event_typ_6d2',
            old_name='idx_notification_event_type_335',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='idx_external_transaction_i_8c4',
            old_name='idx_external_transaction_id_132',
        ),
    ]
