# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, help_text='Unique ledger entry ID (format: PREFIX-YYYYMMDDHHMMSS-XXXXXXXX)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (always positive for profit)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0')])),
                ('source', models.CharField(db_index=True, help_text='Source of profit (task, withdrawal_fee, etc.)', max_length=50)),
                ('source_type', models.CharField(choices=[('task', 'Task Revenue'), ('withdrawal_fee', 'Withdrawal Fee'), ('referral_unclaimed', 'Unclaimed Referral'), ('adjustment', 'Manual Adjustment'), ('other', 'Other')], db_index=True, default='task', help_text='Category of profit source', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this profit entry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this entry was last updated')),
            ],
            options={
                'verbose_name': 'Admin Ledger',
                'verbose_name_plural': 'Admin Ledger',
                'ordering': ['-created_at'],
                'permissions': [('view_profit_reports', 'Can view profit reports'), ('export_ledger', 'Can export ledger data')],
            },
        ),
        migrations.CreateModel(
            name='MasterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('system_type', models.CharField(choices=[('click_visit', 'Click & Visit System'), ('gamified', 'Gamified System'), ('data_input', 'Data Input System'), ('guide_signup', 'Guide/Signup System'), ('external_wall', 'External Wall System')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('daily_retention', 'Daily & Retention'), ('gamified', 'Gamified'), ('ads_multimedia', 'Ads & Multimedia'), ('app_social', 'App & Social'), ('web_content', 'Web & Content'), ('refer_team', 'Refer & Team'), ('advanced_api', 'Advanced & API')], db_index=True, max_length=20)),
                ('task_metadata', models.JSONField(blank=True, default=dict)),
                ('rewards', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('ui_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('target_user_segments', models.JSONField(blank=True, default=list)),
                ('min_user_level', models.IntegerField(default=1)),
                ('max_user_level', models.IntegerField(blank=True, null=True)),
                ('total_completions', models.IntegerField(default=0)),
                ('unique_users_completed', models.IntegerField(default=0)),
                ('daily_completion_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('verified', 'Verified')], db_index=True, default='started', max_length=20)),
                ('proof_data', models.JSONField(blank=True, default=dict)),
                ('rewards_awarded', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
