# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminledger',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Related transaction if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_ledger', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='adminledger',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who generated this profit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_profits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminledger',
            name='withdrawal',
            field=models.ForeignKey(blank=True, help_text='Withdrawal request that generated fee profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profits', to='wallet.withdrawalrequest'),
        ),
        migrations.AddIndex(
            model_name='mastertask',
            index=models.Index(fields=['system_type', 'is_active'], name='tasks_maste_system__0ba873_idx'),
        ),
        migrations.AddIndex(
            model_name='mastertask',
            index=models.Index(fields=['category', 'is_active'], name='tasks_maste_categor_88c4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='mastertask',
            index=models.Index(fields=['available_from', 'available_until'], name='tasks_maste_availab_ff9828_idx'),
        ),
        migrations.AddIndex(
            model_name='mastertask',
            index=models.Index(fields=['-created_at'], name='tasks_maste_created_962abe_idx'),
        ),
        migrations.AddIndex(
            model_name='mastertask',
            index=models.Index(fields=['task_id'], name='tasks_maste_task_id_9052ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastertask',
            unique_together={('task_id',)},
        ),
        migrations.AddField(
            model_name='adminledger',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task that generated this profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profits', to='tasks.mastertask'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.mastertask'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminledger',
            name='completion',
            field=models.ForeignKey(blank=True, help_text='Task completion that generated this profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profits', to='tasks.usertaskcompletion'),
        ),
        migrations.AddIndex(
            model_name='usertaskcompletion',
            index=models.Index(fields=['user', 'status'], name='tasks_usert_user_id_a26d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='usertaskcompletion',
            index=models.Index(fields=['completed_at'], name='tasks_usert_complet_eb6aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='usertaskcompletion',
            index=models.Index(fields=['user', '-started_at'], name='tasks_usert_user_id_4bde68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertaskcompletion',
            unique_together={('user', 'task', 'started_at')},
        ),
        migrations.AddIndex(
            model_name='adminledger',
            index=models.Index(fields=['source', '-created_at'], name='tasks_admin_source_da3f22_idx'),
        ),
        migrations.AddIndex(
            model_name='adminledger',
            index=models.Index(fields=['source_type', '-created_at'], name='tasks_admin_source__fac235_idx'),
        ),
        migrations.AddIndex(
            model_name='adminledger',
            index=models.Index(fields=['-created_at'], name='tasks_admin_created_f12961_idx'),
        ),
        migrations.AddIndex(
            model_name='adminledger',
            index=models.Index(fields=['task', 'user'], name='tasks_admin_task_id_bb70e0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminledger',
            index=models.Index(fields=['created_at'], name='tasks_admin_created_695cff_idx'),
        ),
    ]
