# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_source_created_at_1751',
            old_name='tasks_admin_source_da3f22_idx',
        ),
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_source_type_created_at_1752',
            old_name='tasks_admin_source__fac235_idx',
        ),
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_created_at_1753',
            old_name='tasks_admin_created_f12961_idx',
        ),
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_task_user_1754',
            old_name='tasks_admin_task_id_bb70e0_idx',
        ),
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_created_at_1755',
            old_name='tasks_admin_created_695cff_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_system_type_is_active_1743',
            old_name='tasks_maste_system__0ba873_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_category_is_active_1744',
            old_name='tasks_maste_categor_88c4ac_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_available_from_available_until_1745',
            old_name='tasks_maste_availab_ff9828_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_created_at_1746',
            old_name='tasks_maste_created_962abe_idx',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_task_id_1747',
            old_name='tasks_maste_task_id_9052ce_idx',
        ),
        migrations.RenameIndex(
            model_name='usertaskcompletion',
            new_name='idx_user_status_1748',
            old_name='tasks_usert_user_id_a26d4b_idx',
        ),
        migrations.RenameIndex(
            model_name='usertaskcompletion',
            new_name='idx_completed_at_1749',
            old_name='tasks_usert_complet_eb6aa1_idx',
        ),
        migrations.RenameIndex(
            model_name='usertaskcompletion',
            new_name='idx_user_started_at_1750',
            old_name='tasks_usert_user_id_4bde68_idx',
        ),
    ]
