# Generated by Django 5.0.11 on 2026-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskcompletion',
            name='admin_revenue_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
