# Generated by Django 5.0.11 on 2026-03-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_usertaskcompletion_admin_revenue_received'),
        ('tenants', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminledger',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mastertask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='adminledger',
            name='completion',
            field=models.ForeignKey(blank=True, help_text='Task completion that generated this profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tasks.usertaskcompletion'),
        ),
        migrations.AlterField(
            model_name='adminledger',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task that generated this profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tasks.mastertask'),
        ),
        migrations.AlterField(
            model_name='adminledger',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Related transaction if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='wallet.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='adminledger',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who generated this profit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_adminledger_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminledger',
            name='withdrawal',
            field=models.ForeignKey(blank=True, help_text='Withdrawal request that generated fee profit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='wallet.withdrawalrequest'),
        ),
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='tasks.mastertask'),
        ),
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_usertaskcompletion_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
