# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_tasks_admin_source_da3f22_idx_idx_source_created_at_1751_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminledger',
            new_name='idx_source_type_created_at_683',
            old_name='idx_source_type_created_at_1752',
        ),
        migrations.RenameIndex(
            model_name='mastertask',
            new_name='idx_available_from_availab_47f',
            old_name='idx_available_from_available_until_1745',
        ),
    ]
