# api/payment_gateways/reports/models.py
from django.db import models
from decimal import Decimal
from core.models import TimeStampedModel


class ReconciliationReport(TimeStampedModel):
    """
    Nightly reconciliation report.
    Stores the summary data generated by ReconciliationService.
    """
    report_date  = models.DateField(unique=True)
    data         = models.JSONField(default=dict,
                    help_text='Full reconciliation summary: totals, mismatches, discrepancies')
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name        = 'Reconciliation Report'
        verbose_name_plural = 'Reconciliation Reports'
        ordering            = ['-report_date']

    def __str__(self):
        return f'Reconciliation Report {self.report_date}'

    @property
    def total_matched(self) -> int:
        return self.data.get('total_matched', 0)

    @property
    def total_mismatched(self) -> int:
        return self.data.get('total_mismatched', 0)

    @property
    def discrepancy_amount(self) -> Decimal:
        return Decimal(str(self.data.get('discrepancy_amount', '0')))


class DailyPaymentSummary(TimeStampedModel):
    """
    Pre-aggregated daily payment summary for fast reporting.
    One row per date per gateway per transaction_type.
    Updated by analytics_tasks.py every hour.
    """
    date             = models.DateField()
    gateway          = models.CharField(max_length=20)
    transaction_type = models.CharField(max_length=20)
    currency         = models.CharField(max_length=5, default='BDT')

    total_count      = models.IntegerField(default=0)
    success_count    = models.IntegerField(default=0)
    failed_count     = models.IntegerField(default=0)
    total_amount     = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0'))
    total_fees       = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0'))
    avg_amount       = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0'))
    success_rate     = models.DecimalField(max_digits=6, decimal_places=4, default=Decimal('0'))

    class Meta:
        verbose_name    = 'Daily Payment Summary'
        unique_together = ['date', 'gateway', 'transaction_type', 'currency']
        ordering        = ['-date', 'gateway']

    def __str__(self):
        return f'{self.date} | {self.gateway} | {self.transaction_type} | count={self.total_count}'
