# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_networks', '0002_initial'),
        ('publisher_tools', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_app_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_app_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='publisher_tools.app', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='headerbiddingconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_headerbiddingconfig_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryverification',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='publisher_tools.app', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='inventoryverification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_inventoryverification_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mediationgroup',
            name='ad_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediation_group', to='publisher_tools.adunit', verbose_name='Ad Unit'),
        ),
        migrations.AddField(
            model_name='mediationgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_mediationgroup_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='headerbiddingconfig',
            name='mediation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_bidding_configs', to='publisher_tools.mediationgroup', verbose_name='Mediation Group'),
        ),
        migrations.AddField(
            model_name='payoutthreshold',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_payoutthreshold_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_publisher_tenant', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='payoutthreshold',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_thresholds', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='inventoryverification',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='app',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='ad_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='publisher_tools.adunit', verbose_name='Ad Unit'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='publisher_tools.app', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_earnings', to='ad_networks.adnetwork', verbose_name='Ad Network'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_publisherearning_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publisherinvoice',
            name='payout_threshold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='publisher_tools.payoutthreshold', verbose_name='Payment Method Used'),
        ),
        migrations.AddField(
            model_name='publisherinvoice',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_invoice_processed_by', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='publisherinvoice',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publisherinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_publisherinvoice_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='site',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_site_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='site',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_site_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publisherearning',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='publisher_tools.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='inventoryverification',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='publisher_tools.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='publisher_tools.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='sitequalitymetric',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='publisher_tools.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='sitequalitymetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_sitequalitymetric_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='action_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_traffic_actions', to=settings.AUTH_USER_MODEL, verbose_name='Action Taken By'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='ad_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_safety_logs', to='publisher_tools.adunit', verbose_name='Ad Unit'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_safety_logs', to='publisher_tools.app', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_safety_logs', to='publisher_tools.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_safety_logs', to='publisher_tools.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='trafficsafetylog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_trafficsafetylog_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='waterfallitem',
            name='mediation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_items', to='publisher_tools.mediationgroup', verbose_name='Mediation Group'),
        ),
        migrations.AddField(
            model_name='waterfallitem',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_tools_waterfall_items', to='ad_networks.adnetwork', verbose_name='Ad Network'),
        ),
        migrations.AddField(
            model_name='waterfallitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_tools_waterfallitem_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='adplacement',
            index=models.Index(fields=['ad_unit', 'is_active'], name='publisher_t_ad_unit_1650a3_idx'),
        ),
        migrations.AddIndex(
            model_name='adplacement',
            index=models.Index(fields=['position'], name='publisher_t_positio_a083ca_idx'),
        ),
        migrations.AddIndex(
            model_name='adunittargeting',
            index=models.Index(fields=['ad_unit'], name='publisher_t_ad_unit_d57b70_idx'),
        ),
        migrations.AddIndex(
            model_name='adunittargeting',
            index=models.Index(fields=['device_type'], name='publisher_t_device__ebb7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='mediationgroup',
            index=models.Index(fields=['ad_unit'], name='publisher_t_ad_unit_d7f243_idx'),
        ),
        migrations.AddIndex(
            model_name='mediationgroup',
            index=models.Index(fields=['mediation_type', 'is_active'], name='publisher_t_mediati_073c59_idx'),
        ),
        migrations.AddIndex(
            model_name='headerbiddingconfig',
            index=models.Index(fields=['mediation_group', 'status'], name='publisher_t_mediati_f3d436_idx'),
        ),
        migrations.AddIndex(
            model_name='headerbiddingconfig',
            index=models.Index(fields=['bidder_name'], name='publisher_t_bidder__940fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='headerbiddingconfig',
            unique_together={('mediation_group', 'bidder_name')},
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['publisher_id'], name='publisher_t_publish_fe3018_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['status'], name='publisher_t_status_12bde2_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['country'], name='publisher_t_country_a0e511_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['tier'], name='publisher_t_tier_852dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['is_kyc_verified'], name='publisher_t_is_kyc__0e7113_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutthreshold',
            index=models.Index(fields=['publisher', 'payment_method'], name='publisher_t_publish_657871_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutthreshold',
            index=models.Index(fields=['is_primary'], name='publisher_t_is_prim_c56ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['app_id'], name='publisher_t_app_id_7efbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['package_name'], name='publisher_t_package_ef7b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['publisher', 'status'], name='publisher_t_publish_6cb614_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['platform', 'category'], name='publisher_t_platfor_8fd013_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['quality_score'], name='publisher_t_quality_3357c6_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherinvoice',
            index=models.Index(fields=['publisher', 'status'], name='publisher_t_publish_6b0589_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherinvoice',
            index=models.Index(fields=['invoice_number'], name='publisher_t_invoice_e39339_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherinvoice',
            index=models.Index(fields=['period_start', 'period_end'], name='publisher_t_period__33a034_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherinvoice',
            index=models.Index(fields=['status', 'due_date'], name='publisher_t_status_30fb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['site_id'], name='publisher_t_site_id_fd91c4_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['domain'], name='publisher_t_domain_3abd76_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['publisher', 'status'], name='publisher_t_publish_101ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['category'], name='publisher_t_categor_c1fc10_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['quality_score'], name='publisher_t_quality_2c8f10_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['publisher', 'date'], name='publisher_t_publish_cff468_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['publisher', 'date', 'granularity'], name='publisher_t_publish_408483_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['date', 'country'], name='publisher_t_date_c65cff_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['ad_unit', 'date'], name='publisher_t_ad_unit_49ac25_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['status'], name='publisher_t_status_9c476b_idx'),
        ),
        migrations.AddIndex(
            model_name='publisherearning',
            index=models.Index(fields=['earning_type'], name='publisher_t_earning_036527_idx'),
        ),
        migrations.AddConstraint(
            model_name='publisherearning',
            constraint=models.UniqueConstraint(condition=models.Q(('ad_unit__isnull', False)), fields=('publisher', 'ad_unit', 'date', 'hour', 'country', 'earning_type'), name='unique_publisher_earning_record'),
        ),
        migrations.AddIndex(
            model_name='inventoryverification',
            index=models.Index(fields=['publisher', 'status'], name='publisher_t_publish_3f75c4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryverification',
            index=models.Index(fields=['verification_token'], name='publisher_t_verific_f504c0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryverification',
            index=models.Index(fields=['method', 'status'], name='publisher_t_method_74d553_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['unit_id'], name='publisher_t_unit_id_294d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['publisher', 'status'], name='publisher_t_publish_932a09_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['format'], name='publisher_t_format_43488b_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['inventory_type'], name='publisher_t_invento_902b55_idx'),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['floor_price'], name='publisher_t_floor_p_94a527_idx'),
        ),
        migrations.AddIndex(
            model_name='sitequalitymetric',
            index=models.Index(fields=['site', 'date'], name='publisher_t_site_id_142bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='sitequalitymetric',
            index=models.Index(fields=['overall_quality_score'], name='publisher_t_overall_6e3d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sitequalitymetric',
            index=models.Index(fields=['content_quality'], name='publisher_t_content_775ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='sitequalitymetric',
            index=models.Index(fields=['has_alerts'], name='publisher_t_has_ale_77bb19_idx'),
        ),
        migrations.AddIndex(
            model_name='sitequalitymetric',
            index=models.Index(fields=['viewability_rate'], name='publisher_t_viewabi_babd0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitequalitymetric',
            unique_together={('site', 'date')},
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['publisher', 'detected_at'], name='publisher_t_publish_594ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['traffic_type', 'severity'], name='publisher_t_traffic_0b1cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['ip_address'], name='publisher_t_ip_addr_6179e7_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['fraud_score'], name='publisher_t_fraud_s_44e7df_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['action_taken'], name='publisher_t_action__36c1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsafetylog',
            index=models.Index(fields=['is_false_positive'], name='publisher_t_is_fals_88df09_idx'),
        ),
        migrations.AddIndex(
            model_name='waterfallitem',
            index=models.Index(fields=['mediation_group', 'priority', 'status'], name='publisher_t_mediati_8578d2_idx'),
        ),
        migrations.AddIndex(
            model_name='waterfallitem',
            index=models.Index(fields=['network'], name='publisher_t_network_51567d_idx'),
        ),
        migrations.AddIndex(
            model_name='waterfallitem',
            index=models.Index(fields=['floor_ecpm'], name='publisher_t_floor_e_5b8491_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waterfallitem',
            unique_together={('mediation_group', 'priority')},
        ),
    ]
