# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_tools', '0003_rename_publisher_t_ad_unit_1650a3_idx_idx_ad_unit_is_active_1499_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='headerbiddingconfig',
            new_name='idx_mediation_group_status_fd2',
            old_name='idx_mediation_group_status_1508',
        ),
        migrations.RenameIndex(
            model_name='mediationgroup',
            new_name='idx_mediation_type_is_acti_bb6',
            old_name='idx_mediation_type_is_active_1504',
        ),
        migrations.RenameIndex(
            model_name='payoutthreshold',
            new_name='idx_publisher_payment_meth_455',
            old_name='idx_publisher_payment_method_1516',
        ),
        migrations.RenameIndex(
            model_name='publisherearning',
            new_name='idx_publisher_date_granula_843',
            old_name='idx_publisher_date_granularity_1511',
        ),
        migrations.RenameIndex(
            model_name='publisherinvoice',
            new_name='idx_period_start_period_en_9f0',
            old_name='idx_period_start_period_end_1520',
        ),
        migrations.RenameIndex(
            model_name='waterfallitem',
            new_name='idx_mediation_group_priori_362',
            old_name='idx_mediation_group_priority_statu_1505',
        ),
    ]
