# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiratelimit',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_rate_limits', to='auth.group'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoblockrule',
            name='user_groups',
            field=models.ManyToManyField(related_name='auto_block_rules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the click', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_trackers', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='EnhancedClickTracker',
            fields=[
            ],
            options={
                'verbose_name': 'Enhanced Click Tracker',
                'verbose_name_plural': 'Enhanced Click Trackers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('security.clicktracker',),
        ),
        migrations.AddField(
            model_name='countryblockrule',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_rules', to='security.country'),
        ),
        migrations.AddField(
            model_name='countryblockrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='geolocationlog',
            index=models.Index(fields=['ip_address', 'queried_at'], name='security_ge_ip_addr_5c50e3_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationlog',
            index=models.Index(fields=['country_code'], name='security_ge_country_012744_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationlog',
            index=models.Index(fields=['is_vpn', 'is_proxy'], name='security_ge_is_vpn_c8a05e_idx'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='User who reported this IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ips', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AddField(
            model_name='maintenancemode',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Initiated By'),
        ),
        migrations.AddField(
            model_name='passwordattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='rate_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='security.apiratelimit'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_rate_limit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='parent_config',
            field=models.ForeignKey(blank=True, help_text='Parent configuration this was based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_configs', to='security.securityconfig', verbose_name='Parent Configuration'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_security_configs', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='security.deviceinfo'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitynotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorattempt',
            name='device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.deviceinfo'),
        ),
        migrations.AddField(
            model_name='twofactorattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactormethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorattempt',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='security.twofactormethod'),
        ),
        migrations.AddField(
            model_name='twofactorrecoverycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(help_text='The user who is banned', on_delete=django.db.models.deletion.CASCADE, related_name='security_bans', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='EnhancedUserBan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('security.userban',),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='security.deviceinfo'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='security.geolocationlog'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='security.usersession'),
        ),
        migrations.AddField(
            model_name='withdrawalprotection',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this protection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_withdrawal_protections', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='withdrawalprotection',
            name='user',
            field=models.ForeignKey(help_text='User associated with withdrawal protection', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_protections', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['version_code', 'is_active'], name='security_ap_version_305516_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['release_type', 'release_date'], name='security_ap_release_85b0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['is_mandatory'], name='security_ap_is_mand_2900e2_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', 'created_at'], name='security_au_user_id_9073bf_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['model_name', 'object_id'], name='security_au_model_n_1f2369_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action_type', 'created_at'], name='security_au_action__a0fc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='clicktracker',
            index=models.Index(fields=['user', 'clicked_at'], name='security_cl_user_id_4f4a54_idx'),
        ),
        migrations.AddIndex(
            model_name='clicktracker',
            index=models.Index(fields=['action_type', 'clicked_at'], name='security_cl_action__39c0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='clicktracker',
            index=models.Index(fields=['ip_address', 'clicked_at'], name='security_cl_ip_addr_fc59d6_idx'),
        ),
        migrations.AddIndex(
            model_name='clicktracker',
            index=models.Index(fields=['is_suspicious'], name='security_cl_is_susp_7b36f1_idx'),
        ),
        migrations.AddIndex(
            model_name='clicktracker',
            index=models.Index(fields=['session_id'], name='security_cl_session_0b5220_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['device_id_hash', 'user'], name='security_de_device__0fd5de_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['risk_score', '-last_activity'], name='security_de_risk_sc_9e3911_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['is_rooted', 'is_emulator', 'is_vpn'], name='security_de_is_root_1d6203_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceinfo',
            constraint=models.UniqueConstraint(fields=('user', 'device_id_hash'), name='unique_user_device'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['ip_address', 'is_active'], name='security_ip_ip_addr_e6acc0_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['threat_level', 'is_active'], name='security_ip_threat__42f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['threat_type', 'is_active'], name='security_ip_threat__99bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['country_code', 'is_active'], name='security_ip_country_edb577_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['first_seen'], name='security_ip_first_s_fa6915_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['last_attempt'], name='security_ip_last_at_ccf271_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['is_permanent', 'blocked_until'], name='security_ip_is_perm_1c0f40_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemode',
            index=models.Index(fields=['is_active', 'status'], name='security_ma_is_acti_9fce32_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemode',
            index=models.Index(fields=['start_time', 'estimated_end_time'], name='security_ma_start_t_752187_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemode',
            index=models.Index(fields=['maintenance_type'], name='security_ma_mainten_38e3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordattempt',
            index=models.Index(fields=['user', 'attempted_at'], name='security_pa_user_id_64d0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordattempt',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='security_pa_ip_addr_bbd0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['user', 'created_at'], name='security_ra_user_id_a2de2f_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='security_ra_ip_addr_7bdb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['limit_exceeded'], name='security_ra_limit_e_0f1b22_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['user', 'current_score'], name='security_ri_user_id_669d73_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['current_score'], name='security_ri_current_9a3fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfig',
            index=models.Index(fields=['name', 'is_active'], name='security_se_name_0406ae_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfig',
            index=models.Index(fields=['config_type', 'is_active'], name='security_se_config__7c6c79_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfig',
            index=models.Index(fields=['effective_from', 'effective_until'], name='security_se_effecti_fb5308_idx'),
        ),
        migrations.AddIndex(
            model_name='securityconfig',
            index=models.Index(fields=['is_default'], name='security_se_is_defa_147d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('config_type', 'is_default'), name='unique_default_per_type'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['security_type'], name='security_lo_securit_a4c788_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['severity'], name='security_lo_severit_3e72cc_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address'], name='security_lo_ip_addr_9afb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['created_at'], name='security_lo_created_9079c7_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynotification',
            index=models.Index(fields=['user', 'status'], name='security_se_user_id_4f7e52_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynotification',
            index=models.Index(fields=['priority', 'created_at'], name='security_se_priorit_f8be6e_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynotification',
            index=models.Index(fields=['sent_at'], name='security_se_sent_at_404a56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='twofactormethod',
            unique_together={('user', 'method_type')},
        ),
        migrations.AddIndex(
            model_name='twofactorattempt',
            index=models.Index(fields=['user', 'successful'], name='security_tw_user_id_da2471_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorattempt',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='security_tw_ip_addr_7e3cab_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_active_ban'], name='security_us_user_id_da839e_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['banned_until'], name='security_us_banned__345136_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['banned_at'], name='security_us_banned__ab9eb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userban',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_ban', True)), fields=('user', 'is_active_ban'), name='unique_active_ban_per_user'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='security_us_user_id_9aa362_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='security_us_session_cd98d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='security_us_expires_f5812f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'activity_type'], name='security_se_session_e8e832_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['created_at'], name='security_se_created_c85a34_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalprotection',
            index=models.Index(fields=['user', 'is_active'], name='security_wi_user_id_9e54ec_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalprotection',
            index=models.Index(fields=['protection_level', 'is_active'], name='security_wi_protect_488e82_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalprotection',
            index=models.Index(fields=['risk_level'], name='security_wi_risk_le_b79861_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalprotection',
            index=models.Index(fields=['created_at'], name='security_wi_created_1b9362_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalprotection',
            index=models.Index(fields=['updated_at'], name='security_wi_updated_e63bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalprotection',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_active_protection_per_user'),
        ),
    ]
