# Generated by Django 5.0.14 on 2026-02-17 06:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'ordering': ['-last_activity', '-created_at'], 'verbose_name': 'Device Information', 'verbose_name_plural': 'Device Information'},
        ),
        migrations.RemoveIndex(
            model_name='deviceinfo',
            name='security_de_device__884a84_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceinfo',
            name='security_de_user_id_a15b8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceinfo',
            name='security_de_last_ip_35dea1_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceinfo',
            name='security_de_risk_sc_1dacc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceinfo',
            name='security_de_is_trus_f05828_idx',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='is_emulator',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='is_proxy',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='is_rooted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='is_trusted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='is_vpn',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='risk_score',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='trust_level',
            field=models.IntegerField(choices=[(1, 'Low Trust'), (2, 'Medium Trust'), (3, 'High Trust')], db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['device_id_hash', 'user'], name='security_de_device__0fd5de_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['risk_score', '-last_activity'], name='security_de_risk_sc_9e3911_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinfo',
            index=models.Index(fields=['is_rooted', 'is_emulator', 'is_vpn'], name='security_de_is_root_1d6203_idx'),
        ),
    ]
