# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_rename_security_ap_version_305516_idx_idx_version_code_is_active_1718_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appversion',
            new_name='idx_version_code_is_active_394',
            old_name='idx_version_code_is_active_1718',
        ),
        migrations.RenameIndex(
            model_name='appversion',
            new_name='idx_release_type_release_d_fdd',
            old_name='idx_release_type_release_date_1719',
        ),
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='idx_action_type_created_at_5ce',
            old_name='idx_action_type_created_at_1689',
        ),
        migrations.RenameIndex(
            model_name='deviceinfo',
            new_name='idx_risk_score_last_activi_154',
            old_name='idx_risk_score_last_activity_1673',
        ),
        migrations.RenameIndex(
            model_name='deviceinfo',
            new_name='idx_is_rooted_is_emulator__fbe',
            old_name='idx_is_rooted_is_emulator_is_vpn_1674',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_threat_level_is_active_437',
            old_name='idx_threat_level_is_active_1722',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_country_code_is_active_4e0',
            old_name='idx_country_code_is_active_1724',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_is_permanent_blocked_u_dc4',
            old_name='idx_is_permanent_blocked_until_1727',
        ),
        migrations.RenameIndex(
            model_name='maintenancemode',
            new_name='idx_start_time_estimated_e_46e',
            old_name='idx_start_time_estimated_end_time_1712',
        ),
        migrations.RenameIndex(
            model_name='passwordattempt',
            new_name='idx_ip_address_attempted_a_56c',
            old_name='idx_ip_address_attempted_at_1700',
        ),
        migrations.RenameIndex(
            model_name='securityconfig',
            new_name='idx_effective_from_effecti_dc3',
            old_name='idx_effective_from_effective_until_1716',
        ),
        migrations.RenameIndex(
            model_name='twofactorattempt',
            new_name='idx_ip_address_attempted_a_883',
            old_name='idx_ip_address_attempted_at_1707',
        ),
        migrations.RenameIndex(
            model_name='withdrawalprotection',
            new_name='idx_protection_level_is_ac_f0d',
            old_name='idx_protection_level_is_active_1729',
        ),
    ]
