# Generated by Django 5.0.11 on 2026-03-01 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_deviceinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.deviceinfo'),
        ),
    ]
