# Generated by Django 5.0.11 on 2026-03-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_securitylog_resolved_securitylog_resolved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Action taken in response to this security event', null=True, verbose_name='Action Taken'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Whether this security event has been resolved', verbose_name='Resolved'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
    ]
