# Generated by Django 5.0.11 on 2026-04-09 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_securitylog_action_taken_alter_securitylog_resolved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawalprotection',
            name='unique_active_protection_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='withdrawalprotection',
            name='daily_limit_lte_weekly_limit',
        ),
        migrations.RemoveConstraint(
            model_name='withdrawalprotection',
            name='weekly_limit_lte_monthly_limit',
        ),
        migrations.RemoveConstraint(
            model_name='withdrawalprotection',
            name='single_transaction_limit_lte_daily_limit',
        ),
        migrations.RemoveConstraint(
            model_name='withdrawalprotection',
            name='min_withdrawal_amount_lte_single_transaction_limit',
        ),
        migrations.AlterField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_rate_limit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='withdrawalprotection',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_active_protection_per_user'),
        ),
    ]
