# Generated by Django 5.0.11 on 2026-04-12 10:25

import api.subscription.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(choices=[('feature', 'Feature Access'), ('limit', 'Usage Limit'), ('discount', 'Discount'), ('priority', 'Priority Access'), ('storage', 'Storage'), ('api_calls', 'API Calls'), ('support', 'Support Level'), ('custom', 'Custom')], db_index=True, default='feature', max_length=30, verbose_name='benefit type')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('value', models.CharField(blank=True, help_text='Numeric limit, feature key, or descriptive string.', max_length=200, verbose_name='value')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show prominently on pricing pages.', verbose_name='highlighted')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'membership benefit',
                'verbose_name_plural': 'membership benefits',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('other', 'Other')], default='credit_card', max_length=30, verbose_name='payment method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[api.subscription.validators.validate_payment_amount], verbose_name='amount')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BDT', 'Bangladeshi Taka'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3, verbose_name='currency')),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='amount refunded')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='discount amount')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Raw payment gateway response payload.', verbose_name='gateway response')),
                ('invoice_url', models.URLField(blank=True, verbose_name='invoice URL')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='billing period start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='billing period end')),
                ('failure_code', models.CharField(blank=True, max_length=100, verbose_name='failure code')),
                ('failure_message', models.TextField(blank=True, verbose_name='failure message')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
            ],
            options={
                'verbose_name': 'subscription payment',
                'verbose_name_plural': 'subscription payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='plan name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[api.subscription.validators.validate_positive_price], verbose_name='price')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BDT', 'Bangladeshi Taka'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3, verbose_name='currency')),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20, verbose_name='billing interval')),
                ('interval_count', models.PositiveSmallIntegerField(default=1, help_text='Number of intervals between billings, e.g. every 3 months.', verbose_name='interval count')),
                ('trial_period_days', models.PositiveSmallIntegerField(default=0, validators=[api.subscription.validators.validate_trial_days], verbose_name='trial period (days)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[api.subscription.validators.validate_discount_percent], verbose_name='discount percent')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='one-time setup fee')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True, verbose_name='max users')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='period start')),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='period end')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='trial start')),
                ('trial_end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='trial end')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('too_expensive', 'Too Expensive'), ('not_using', 'Not Using Enough'), ('missing_features', 'Missing Features'), ('found_alternative', 'Found Alternative'), ('technical_issues', 'Technical Issues'), ('customer_service', 'Poor Customer Service'), ('other', 'Other')], max_length=30, verbose_name='cancellation reason')),
                ('cancellation_comment', models.TextField(blank=True, verbose_name='cancellation comment')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If True, subscription stays active until end of billing period.', verbose_name='cancel at period end')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='paused at')),
                ('pause_resumes_at', models.DateTimeField(blank=True, null=True, verbose_name='pause resumes at')),
                ('external_subscription_id', models.CharField(blank=True, db_index=True, help_text='Stripe / PayPal / gateway subscription ID.', max_length=255, verbose_name='external subscription ID')),
                ('payment_retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='payment retry count')),
                ('renewal_count', models.PositiveSmallIntegerField(default=0, verbose_name='renewal count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Case-insensitive coupon code users enter at checkout.', max_length=50, unique=True, verbose_name='coupon code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed amount depending on discount_type.', max_digits=10, verbose_name='discount value')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BDT', 'Bangladeshi Taka'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', help_text="Only used when discount_type is 'fixed'.", max_length=3, verbose_name='currency')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum plan price required to use this coupon.', max_digits=10, null=True, verbose_name='minimum order amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True, verbose_name='max uses')),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1, help_text='How many times a single user can use this coupon.', verbose_name='max uses per user')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='times used')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Actual amount discounted at time of use.', max_digits=10, verbose_name='discount applied')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscription.coupon', verbose_name='coupon')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
