# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='idx_code_1740',
            old_name='subscriptio_code_e4d590_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='idx_is_active_valid_until_1741',
            old_name='subscriptio_is_acti_f3c0d3_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='idx_coupon_user_1742',
            old_name='subscriptio_coupon__6e6897_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionpayment',
            new_name='idx_status_created_at_1738',
            old_name='subscriptio_status_17faa4_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionpayment',
            new_name='idx_transaction_id_1739',
            old_name='subscriptio_transac_f2e0b4_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionplan',
            new_name='idx_status_price_1733',
            old_name='subscriptio_status_8dce47_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionplan',
            new_name='idx_slug_1734',
            old_name='subscriptio_slug_77d806_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_user_status_1735',
            old_name='subscriptio_user_id_eb5f24_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_status_current_period_end_1736',
            old_name='subscriptio_status_6a1745_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_external_subscription_id_1737',
            old_name='subscriptio_externa_bfb447_idx',
        ),
    ]
