# Generated by Django 5.0.11 on 2026-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_coupon_couponusage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='subscriptio_code_e4d590_idx',
            old_name='sub_coupon_code_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='subscriptio_is_acti_f3c0d3_idx',
            old_name='sub_coupon_active_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='subscriptio_coupon__6e6897_idx',
            old_name='sub_couponusage_idx',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow on all plans.', related_name='coupons', to='subscription.subscriptionplan', verbose_name='applicable plans'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Case-insensitive coupon code users enter at checkout.', max_length=50, unique=True, verbose_name='coupon code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BDT', 'Bangladeshi Taka'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='USD', help_text="Only used when discount_type is 'fixed'.", max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed amount depending on discount_type.', max_digits=10, verbose_name='discount value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True, verbose_name='max uses'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times a single user can use this coupon.', verbose_name='max uses per user'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum plan price required to use this coupon.', max_digits=10, null=True, verbose_name='minimum order amount'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, help_text='Actual amount discounted at time of use.', max_digits=10, verbose_name='discount applied'),
        ),
    ]
