# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_subscriptio_code_e4d590_idx_idx_code_1740_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_status_current_period__3fe',
            old_name='idx_status_current_period_end_1736',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_external_subscription__efe',
            old_name='idx_external_subscription_id_1737',
        ),
    ]
