# Generated by Django 5.0.11 on 2026-04-12 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(blank=True, default='#007bff', max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, default='#6c757d', max_length=7, null=True)),
                ('plan', models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20, null=True)),
                ('max_users', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_billing',
            },
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, default='unpaid', max_length=20, null=True)),
                ('due_date', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_invoices',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, default='EarningApp', max_length=100, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('privacy_policy_url', models.URLField(blank=True, null=True)),
                ('terms_url', models.URLField(blank=True, null=True)),
                ('enable_referral', models.BooleanField(default=True)),
                ('enable_offerwall', models.BooleanField(default=True)),
                ('enable_kyc', models.BooleanField(default=True)),
                ('enable_leaderboard', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=False)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('min_withdrawal', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=10, null=True)),
                ('withdrawal_fee_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('android_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ios_bundle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('firebase_server_key', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
    ]
