# Generated by Django 5.0.11 on 2026-03-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='EarningApp', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('terms_url', models.URLField(blank=True)),
                ('enable_referral', models.BooleanField(default=True)),
                ('enable_offerwall', models.BooleanField(default=True)),
                ('enable_kyc', models.BooleanField(default=True)),
                ('enable_leaderboard', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=False)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('android_package_name', models.CharField(blank=True, max_length=255)),
                ('ios_bundle_id', models.CharField(blank=True, max_length=255)),
                ('firebase_server_key', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
    ]
