# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_planfeature_planquota_planupgrade_planusage_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='planusage',
            new_name='idx_tenant_period_period_s_001',
            old_name='idx_tenant_period_period_s_64c',
        ),
        migrations.RenameIndex(
            model_name='tenantbilling',
            new_name='idx_stripe_subscription_id_001',
            old_name='idx_stripe_subscription_id_e2e',
        ),
    ]
