# Generated by Django 5.0 - Fixed Version
from django.db import migrations, models
import django.db.models.deletion
from django.db.utils import ProgrammingError

def migrate_tenant_plans(apps, schema_editor):
    """Migrate old plan structure to new improved models."""
    try:
        Tenant = apps.get_model('tenants', 'Tenant')
        Plan = apps.get_model('tenants', 'Plan')
        
        for tenant in Tenant.objects.all():
            if hasattr(tenant, "old_plan_name") and not tenant.plan:
                plan, created = Plan.objects.get_or_create(
                    name=getattr(tenant, 'old_plan_name', 'Free'),
                    defaults={'is_default': True, 'price': 0, 'currency': 'USD'}
                )
                tenant.plan = plan
                tenant.save(update_fields=['plan'])
        
        print(f"[OK] Migrated plans for {Tenant.objects.count()} tenants")
    except LookupError as e:
        print(f"[SKIP] Plan migration skipped: {e}")
    except Exception as e:
        print(f"[WARNING] Plan migration error: {e}")

def migrate_tenant_features(apps, schema_editor):
    """Migrate tenant feature flags to new JSONField."""
    try:
        Tenant = apps.get_model('tenants', 'Tenant')
        
        for tenant in Tenant.objects.all():
            if not hasattr(tenant, 'features'):
                continue
                
            features = getattr(tenant, 'features', {})
            if isinstance(features, dict) and features:
                continue
                
            new_features = {
                'analytics': getattr(tenant, 'has_analytics', False),
                'api_access': getattr(tenant, 'has_api_access', False),
                'custom_domain': getattr(tenant, 'has_custom_domain', False),
                'white_label': getattr(tenant, 'has_white_label', False),
            }
            tenant.features = new_features
            tenant.save(update_fields=['features'])
        
        print(f"[OK] Migrated features for {Tenant.objects.count()} tenants")
    except LookupError as e:
        print(f"[SKIP] Feature migration skipped: {e}")
    except Exception as e:
        print(f"[WARNING] Feature migration error: {e}")

def reverse_migrate_tenant_plans(apps, schema_editor):
    """Reverse migration - no-op for safety."""
    print("[OK] Reverse migration - no action taken")

def reverse_migrate_tenant_features(apps, schema_editor):
    """Reverse migration - no-op for safety."""
    print("[OK] Reverse migration - no action taken")

class Migration(migrations.Migration):
    atomic = False


    dependencies = [
        ('tenants', '0004_rename_idx_tenant_period_period_s_64c_idx_tenant_period_period_s_001_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_tenant_plans,
            reverse_migrate_tenant_plans
        ),
        migrations.RunPython(
            migrate_tenant_features,
            reverse_migrate_tenant_features
        ),
    ]
