# Generated by Django 5.0.11 on 2026-03-07 03:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Under Dispute'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('reward_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bonus_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
                'db_table': 'task_submission',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing unique ID', unique=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(blank=True, default='')),
                ('target_url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('total_budget_usd', models.DecimalField(decimal_places=2, help_text='মোট বাজেট USD তে', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('spent_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Admin profit percentage (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('total_slots', models.PositiveIntegerField(help_text='কতজন worker কাজ করতে পারবে', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('filled_slots', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Advertiser')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(32), django.core.validators.RegexValidator('^[a-f0-9]+$', 'Lowercase hex hash দিন')])),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('os_version', models.CharField(blank=True, default='', max_length=30)),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('browser_version', models.CharField(blank=True, default='', max_length=20)),
                ('screen_resolution', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+x\\d+$', 'Format: WxH, e.g. 1920x1080')])),
                ('user_timezone', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('linked_account_count', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'db_table': 'device_fingerprint',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='কেন রিজেক্ট সঠিক নয় তার বিস্তারিত কারণ', validators=[django.core.validators.MinLengthValidator(20)])),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_approved', 'Resolved — Approved'), ('resolved_rejected', 'Resolved — Rejected')], db_index=True, default='open', max_length=25)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'db_table': 'dispute',
            },
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fraud_type', models.CharField(choices=[('fake_screenshot', 'Fake Screenshot'), ('vpn_detected', 'VPN / Proxy Detected'), ('bot_activity', 'Bot / Automated Activity'), ('duplicate_submission', 'Duplicate Submission'), ('account_farming', 'Multiple Account Farming'), ('emulator_detected', 'Emulator Detected'), ('click_fraud', 'Click Fraud')], db_index=True, max_length=30)),
                ('ai_model_version', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='AI এর detected features, signals ইত্যাদি')),
                ('action_taken', models.CharField(choices=[('flagged', 'Flagged for Review'), ('warned', 'Warning Issued'), ('banned', 'Account Banned'), ('ignored', 'Ignored / False Positive')], default='flagged', max_length=10)),
                ('admin_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Fraud Report',
                'verbose_name_plural': 'Fraud Reports',
                'db_table': 'fraud_report',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('play_store', 'Google Play Store'), ('app_store', 'Apple App Store'), ('twitter', 'Twitter / X'), ('other', 'Other')], max_length=50, unique=True)),
                ('base_url', models.URLField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'db_table': 'platform',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('social', 'Social Media'), ('apps', 'Mobile Apps'), ('web', 'Web Tasks'), ('surveys', 'Surveys')], max_length=50, unique=True, verbose_name='ক্যাটেগরি নাম')),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Promotion Category',
                'verbose_name_plural': 'Promotion Categories',
                'db_table': 'promotion_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reward', 'Task Reward'), ('commission', 'Admin Commission'), ('referral', 'Referral Commission'), ('refund', 'Refund'), ('escrow_lock', 'Escrow Lock'), ('escrow_release', 'Escrow Release'), ('bonus', 'Bonus Payment'), ('penalty', 'Fraud Penalty')], db_index=True, max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=6, help_text='সবসময় positive amount — type দিয়ে direction বোঝা যাবে', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('currency_code', models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'ISO 4217 code দিন')])),
                ('amount_local', models.DecimalField(blank=True, decimal_places=4, help_text='স্থানীয় মুদ্রায় equivalent amount', max_digits=18, null=True)),
                ('balance_after', models.DecimalField(decimal_places=6, help_text='Transaction এর পরে user এর balance', max_digits=14)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, help_text='submission_id বা অন্য সংশ্লিষ্ট রেকর্ডের ID', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('is_reversed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Promotion Transaction',
                'verbose_name_plural': 'Promotion Transactions',
                'db_table': 'promotion_transaction',
            },
        ),
        migrations.CreateModel(
            name='ReferralCommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Level-1 = direct referral, Level-2 = indirect', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commission_usd', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('50'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Referral Commission Log',
                'verbose_name_plural': 'Referral Commission Logs',
                'db_table': 'referral_commission_log',
            },
        ),
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g. US, BD, IN)', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'ISO 3166-1 alpha-2 কোড দিন (যেমন: US, BD)')])),
                ('rate_usd', models.DecimalField(decimal_places=4, help_text='USD তে পার-ট্র্যাক রেট', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('min_payout_usd', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reward Policy',
                'verbose_name_plural': 'Reward Policies',
                'db_table': 'reward_policy',
                'ordering': ['country_code', 'category'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('link', 'Link / URL'), ('text', 'Text Answer'), ('video', 'Screen Recording')], max_length=15)),
                ('content', models.TextField(help_text='URL (screenshot/link/video) অথবা টেক্সট উত্তর', validators=[django.core.validators.MinLengthValidator(1)])),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10240)])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Submission Proof',
                'verbose_name_plural': 'Submission Proofs',
                'db_table': 'submission_proof',
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('instruction', models.TextField(help_text='ইউজারকে কী করতে হবে তার বিস্তারিত নির্দেশনা', validators=[django.core.validators.MinLengthValidator(10)])),
                ('proof_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('link', 'Link / URL'), ('text', 'Text Answer'), ('video', 'Screen Recording')], max_length=15)),
                ('is_required', models.BooleanField(default=True)),
                ('hint_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Task Step',
                'verbose_name_plural': 'Task Steps',
                'db_table': 'task_step',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reputation', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('disputed_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('trust_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_verified_worker', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Reputation',
                'verbose_name_plural': 'User Reputations',
                'db_table': 'user_reputation',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(choices=[('ai', 'AI System'), ('admin', 'Admin'), ('system', 'Auto System')], max_length=10)),
                ('ai_model_version', models.CharField(blank=True, default='', help_text='AI verify করলে model version লগ করুন', max_length=100)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('escalate', 'Escalate to Human')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'db_table': 'verification_log',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminCommissionLog',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='commission_log', serialize=False, to='promotions.tasksubmission')),
                ('gross_amount_usd', models.DecimalField(decimal_places=6, help_text='Advertiser মোট কত দিল', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('worker_reward_usd', models.DecimalField(decimal_places=6, help_text='Worker কত পেল', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('commission_usd', models.DecimalField(decimal_places=6, help_text='Admin এর নিট লাভ', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Admin Commission Log',
                'verbose_name_plural': 'Admin Commission Logs',
                'db_table': 'admin_commission_log',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('user', 'User Account'), ('ip', 'IP Address'), ('device', 'Device Fingerprint'), ('channel_url', 'YouTube / Social Channel'), ('email_domain', 'Email Domain'), ('phone', 'Phone Number')], db_index=True, max_length=15)),
                ('value', models.CharField(help_text='IP, user_id, domain, channel URL ইত্যাদি', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('reason', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('severity', models.CharField(choices=[('warn', 'Warning Only'), ('temp_ban', 'Temporary Ban'), ('permanent', 'Permanent Ban')], default='permanent', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='শুধু temp_ban এর জন্য', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist Entry',
                'verbose_name_plural': 'Blacklist Entries',
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='schedule', serialize=False, to='promotions.campaign')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='pytz timezone string, e.g. Asia/Dhaka', max_length=50)),
                ('auto_pause_on_budget_exhaust', models.BooleanField(default=True, help_text='বাজেট শেষ হলে অটোমেটিক pause হবে কিনা')),
                ('daily_budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='প্রতিদিন সর্বোচ্চ কত USD খরচ হতে পারবে', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active_hours_start', models.TimeField(blank=True, help_text='কোন সময় থেকে কাজ নেওয়া যাবে', null=True)),
                ('active_hours_end', models.TimeField(blank=True, help_text='কোন সময়ের পরে কাজ নেওয়া যাবে না', null=True)),
            ],
            options={
                'verbose_name': 'Campaign Schedule',
                'verbose_name_plural': 'Campaign Schedules',
                'db_table': 'campaign_schedule',
            },
        ),
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='escrow', serialize=False, to='promotions.campaign')),
                ('locked_amount_usd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('released_amount_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('partially_released', 'Partially Released'), ('fully_released', 'Fully Released'), ('refunded', 'Refunded to Advertiser')], db_index=True, default='locked', max_length=25)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escrow Wallet',
                'verbose_name_plural': 'Escrow Wallets',
                'db_table': 'escrow_wallet',
            },
        ),
        migrations.CreateModel(
            name='TargetingCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='targeting', serialize=False, to='promotions.campaign')),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO alpha-2 country codes. e.g. ["US","BD","IN"]')),
                ('devices', models.JSONField(blank=True, default=list, help_text='["mobile","desktop","tablet"]')),
                ('os_types', models.JSONField(blank=True, default=list, help_text='["android","ios","windows","macos"]')),
                ('min_user_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_user_level', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_reputation_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Targeting Condition',
                'verbose_name_plural': 'Targeting Conditions',
                'db_table': 'targeting_condition',
            },
        ),
        migrations.CreateModel(
            name='TaskLimit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='limits', serialize=False, to='promotions.campaign')),
                ('max_per_ip', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_per_device', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_per_user', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=24, help_text='পরবর্তী submission এর আগে কতক্ষণ অপেক্ষা করতে হবে', validators=[django.core.validators.MaxValueValidator(8760)])),
            ],
            options={
                'verbose_name': 'Task Limit',
                'verbose_name_plural': 'Task Limits',
                'db_table': 'task_limit',
            },
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='promotions.campaign'),
        ),
        migrations.CreateModel(
            name='BonusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_type', models.CharField(choices=[('approval_rate', 'Approval Rate'), ('speed', 'Completion Speed'), ('streak', 'Consecutive Approvals')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='যেমন: 95 মানে ৯৫% approval rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bonus_percent', models.DecimalField(decimal_places=2, help_text='Base reward এর উপর কত % বোনাস দেওয়া হবে', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('200'))])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_policies', to='promotions.campaign')),
            ],
            options={
                'verbose_name': 'Bonus Policy',
                'verbose_name_plural': 'Bonus Policies',
                'db_table': 'bonus_policy',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('banner', 'Banner')], max_length=10)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('duration_sec', models.PositiveIntegerField(blank=True, help_text='শুধু ভিডিওর জন্য, সেকেন্ডে', null=True, validators=[django.core.validators.MaxValueValidator(3600)])),
                ('is_approved', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='promotions.campaign')),
            ],
            options={
                'verbose_name': 'Ad Creative',
                'verbose_name_plural': 'Ad Creatives',
                'db_table': 'ad_creative',
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('disputed_count', models.PositiveIntegerField(default=0)),
                ('fraud_detected', models.PositiveIntegerField(default=0)),
                ('total_spent_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('admin_commission_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avg_completion_time_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('unique_countries', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Analytics',
                'verbose_name_plural': 'Campaign Analytics',
                'db_table': 'campaign_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'ISO 4217 currency code দিন (e.g. USD)')])),
                ('to_currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'ISO 4217 currency code দিন (e.g. BDT)')])),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('source', models.CharField(choices=[('open_exchange_rates', 'Open Exchange Rates'), ('fixer', 'Fixer.io'), ('manual', 'Manual Entry')], default='open_exchange_rates', max_length=30)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'db_table': 'currency_rate',
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-fetched_at'], name='currency_ra_from_cu_cdb18a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.CheckConstraint(check=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='chk_currency_rate_different_currencies'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='device_fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='promotions.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_device_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_fraud_reports', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_fraud_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='promotions.platform'),
        ),
        migrations.AddField(
            model_name='promotioncategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='promotions.promotioncategory'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_transactions', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='reversed_by_tx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='promotions.promotiontransaction'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='referred',
            field=models.ForeignKey(help_text='যাকে রেফার করা হয়েছে', on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='referrer',
            field=models.ForeignKey(help_text='যে রেফার করেছে', on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='source_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='rewardpolicy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_policies', to='promotions.promotioncategory'),
        ),
        migrations.AddField(
            model_name='submissionproof',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='submissionproof',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='promotions.taskstep'),
        ),
        migrations.AddConstraint(
            model_name='userreputation',
            constraint=models.CheckConstraint(check=models.Q(('approved_count__lte', models.F('total_submissions')), ('rejected_count__lte', models.F('total_submissions'))), name='chk_reputation_counts_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='userreputation',
            constraint=models.CheckConstraint(check=models.Q(('trust_score__gte', 0), ('trust_score__lte', 100)), name='chk_reputation_trust_score_range'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='verifier_admin',
            field=models.ForeignKey(blank=True, help_text='verified_by=admin হলে কোন Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincommissionlog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_logs', to='promotions.campaign'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['type', 'value', 'is_active'], name='blacklist_type_a0cad0_idx'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('type', 'value'), name='uq_active_blacklist_type_value'),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='targetingcondition',
            constraint=models.CheckConstraint(check=models.Q(('min_user_level__lte', models.F('max_user_level'))), name='chk_targeting_user_level_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='bonuspolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('campaign', 'condition_type'), name='uq_active_bonus_policy_per_campaign_condition'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['campaign', 'type'], name='ad_creative_campaig_af5212_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignanalytics',
            index=models.Index(fields=['campaign', '-date'], name='campaign_an_campaig_07d268_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='uq_campaign_analytics_per_day'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.CheckConstraint(check=models.Q(('approved_count__lte', models.F('total_submissions'))), name='chk_analytics_approved_not_exceed_submissions'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.CheckConstraint(check=models.Q(('total_clicks__lte', models.F('total_views'))), name='chk_analytics_clicks_not_exceed_views'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['worker', 'campaign'], name='task_submis_worker__6662ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='task_submis_status_ee04e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['campaign', 'status'], name='task_submis_campaig_d28456_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['ip_address'], name='task_submis_ip_addr_8971aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(check=models.Q(('bonus_usd__gte', 0)), name='chk_submission_bonus_non_negative'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['user', '-last_seen'], name='device_fing_user_id_db7673_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['is_flagged'], name='device_fing_is_flag_1c1cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='dispute_status_25c644_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['user', 'fraud_type'], name='fraud_repor_user_id_0155d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['action_taken', 'created_at'], name='fraud_repor_action__164e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', 'status'], name='campaign_adverti_fe208a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaign_status_2c0066_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('spent_usd__lte', models.F('total_budget_usd'))), name='chk_campaign_spent_not_exceed_budget'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('filled_slots__lte', models.F('total_slots'))), name='chk_campaign_filled_not_exceed_total_slots'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('total_budget_usd__gt', 0)), name='chk_campaign_budget_positive'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['user', '-created_at'], name='promotion_t_user_id_d06803_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['campaign', 'type'], name='promotion_t_campaig_56704a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['type', '-created_at'], name='promotion_t_type_a98ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionlog',
            index=models.Index(fields=['referrer', 'status'], name='referral_co_referre_30faf9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionlog',
            index=models.Index(fields=['referred', 'level'], name='referral_co_referre_1bcf18_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcommissionlog',
            constraint=models.CheckConstraint(check=models.Q(('referrer', models.F('referred')), _negated=True), name='chk_referral_referrer_not_same_as_referred'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('country_code', 'category'), name='uq_active_reward_policy_per_country_category'),
        ),
        migrations.AddConstraint(
            model_name='taskstep',
            constraint=models.UniqueConstraint(fields=('campaign', 'step_order'), name='uq_task_step_order_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='submissionproof',
            constraint=models.UniqueConstraint(fields=('submission', 'step'), name='uq_proof_per_submission_step'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['submission', '-verified_at'], name='verificatio_submiss_da2e3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='admincommissionlog',
            constraint=models.CheckConstraint(check=models.Q(('commission_usd__lte', models.F('gross_amount_usd'))), name='chk_commission_not_exceed_gross'),
        ),
        migrations.AddConstraint(
            model_name='admincommissionlog',
            constraint=models.CheckConstraint(check=models.Q(('worker_reward_usd__gte', 0), ('commission_usd__gte', 0), ('gross_amount_usd__gte', 0)), name='chk_commission_all_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='escrowwallet',
            constraint=models.CheckConstraint(check=models.Q(('released_amount_usd__lte', models.F('locked_amount_usd'))), name='chk_escrow_released_not_exceed_locked'),
        ),
        migrations.AddConstraint(
            model_name='escrowwallet',
            constraint=models.CheckConstraint(check=models.Q(('locked_amount_usd__gt', 0)), name='chk_escrow_locked_positive'),
        ),
    ]
