# Generated by Django 5.0.11 on 2026-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bonus_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='campaign',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('SAFE', 'Safe'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sparkline_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='yield_optimization',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
