# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reputation', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('disputed_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('trust_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_verified_worker', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Reputation',
                'verbose_name_plural': 'User Reputations',
                'db_table': 'user_reputation',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.CharField(blank=True, choices=[('ai', 'AI System'), ('admin', 'Admin'), ('system', 'Auto System')], max_length=10, null=True)),
                ('ai_model_version', models.CharField(blank=True, default='', help_text='AI verify করলে model version লগ করুন', max_length=100)),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject'), ('escalate', 'Escalate to Human')], max_length=10, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'db_table': 'verification_log',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(blank=True, default='Coins', max_length=30, null=True)),
                ('currency_icon', models.CharField(blank=True, default='🪙', max_length=10, null=True)),
                ('usd_to_vc_rate', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12)),
                ('min_payout_vc', models.PositiveIntegerField(default=100)),
                ('rounding', models.CharField(choices=[('floor', 'Floor'), ('ceil', 'Ceil'), ('round', 'Round')], default='floor', max_length=10)),
                ('postback_url', models.URLField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Virtual Currency Config',
                'db_table': 'virtual_currency_config',
            },
        ),
        migrations.CreateModel(
            name='WebhookConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=6)),
                ('secret_key', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fired', models.DateTimeField(blank=True, null=True)),
                ('total_fires', models.PositiveIntegerField(default=0)),
                ('last_status_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'db_table': 'webhook_config',
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, default='', null=True)),
                ('primary_color', models.CharField(blank=True, default='#6C63FF', max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, default='#FF6584', max_length=7, null=True)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('show_powered_by', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'White Label Config',
                'db_table': 'white_label_config',
            },
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikeymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='escrow', serialize=False, to='promotions.campaign')),
                ('locked_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('released_amount_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('partially_released', 'Partially Released'), ('fully_released', 'Fully Released'), ('refunded', 'Refunded to Advertiser')], db_index=True, default='locked', max_length=25)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escrow Wallet',
                'verbose_name_plural': 'Escrow Wallets',
                'db_table': 'escrow_wallet',
            },
        ),
        migrations.CreateModel(
            name='TargetingCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='targeting', serialize=False, to='promotions.campaign')),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO alpha-2 country codes. e.g. ["US","BD","IN"]')),
                ('devices', models.JSONField(default=list, help_text='["mobile","desktop","tablet"]')),
                ('os_types', models.JSONField(default=list, help_text='["android","ios","windows","macos"]')),
                ('min_user_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_user_level', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_reputation_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Targeting Condition',
                'verbose_name_plural': 'Targeting Conditions',
                'db_table': 'targeting_condition',
            },
        ),
        migrations.CreateModel(
            name='TaskLimit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='limits', serialize=False, to='promotions.campaign')),
                ('max_per_ip', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_per_device', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_per_user', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=24, help_text='পরবর্তী submission এর আগে কতক্ষণ অপেক্ষা করতে হবে', validators=[django.core.validators.MaxValueValidator(8760)])),
            ],
            options={
                'verbose_name': 'Task Limit',
                'verbose_name_plural': 'Task Limits',
                'db_table': 'task_limit',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Advertiser'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonuspolicy',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_policies', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='admincommissionlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_logs', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='campaignanalytics',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='campaignbid',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignbid',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='contentlockmodel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpccampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpiappcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpi_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['from_currency', 'to_currency', '-fetched_at'], name='currency_ra_from_cu_cdb18a_idx'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_device_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsubmitcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsubmitconversion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='promotions.emailsubmitcampaign'),
        ),
        migrations.AddField(
            model_name='emailsubmitconversion',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_fraud_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipblacklistmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='promotions.platform'),
        ),
        migrations.AddField(
            model_name='promotioncategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='promotions.promotioncategory'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_transactions', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='reversed_by_tx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='promotions.promotiontransaction'),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='referred',
            field=models.ForeignKey(help_text='যাকে রেফার করা হয়েছে', on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='যে রেফার করেছে', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardpolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_policies', to='promotions.promotioncategory'),
        ),
        migrations.AddField(
            model_name='smartlinkconfig',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_smartlinks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subidclick',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subid_clicks', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='subidclick',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subid_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='submissionproof',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='promotions.taskstep'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='promotions.campaign'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='device_fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='promotions.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionproof',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='referralcommissionlog',
            name='source_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_fraud_reports', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='admincommissionlog',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_log', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='trackingdomain',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='promotions.tasksubmission'),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='verifier_admin',
            field=models.ForeignKey(blank=True, help_text='verified_by=admin হলে কোন Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualcurrencyconfig',
            name='publisher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookconfigmodel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whitelabelconfig',
            name='publisher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_label', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['type', 'value', 'is_active'], name='blacklist_type_a0cad0_idx'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('type', 'value'), name='uq_active_blacklist_type_value'),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bonuspolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('campaign', 'condition_type'), name='uq_active_bonus_policy_per_campaign_condition'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['campaign', 'type'], name='ad_creative_campaig_af5212_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignanalytics',
            index=models.Index(fields=['campaign', '-date'], name='campaign_an_campaig_07d268_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='uq_campaign_analytics_per_day'),
        ),
        migrations.AddIndex(
            model_name='campaignbid',
            index=models.Index(fields=['campaign', 'status'], name='campaign_bi_campaig_8dc01d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbid',
            index=models.Index(fields=['advertiser', '-bid_at'], name='campaign_bi_adverti_93f5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['user', '-last_seen'], name='device_fing_user_id_db7673_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['is_flagged'], name='device_fing_is_flag_1c1cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', 'status'], name='campaign_adverti_fe208a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaign_status_2c0066_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['user', '-created_at'], name='promotion_t_user_id_d06803_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['campaign', 'type'], name='promotion_t_campaig_56704a_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontransaction',
            index=models.Index(fields=['type', '-created_at'], name='promotion_t_type_a98ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('country_code', 'category'), name='uq_active_reward_policy_per_country_category'),
        ),
        migrations.AddIndex(
            model_name='subidclick',
            index=models.Index(fields=['publisher', 'created_at'], name='subid_click_publish_42ab45_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskstep',
            constraint=models.UniqueConstraint(fields=('campaign', 'step_order'), name='uq_task_step_order_per_campaign'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['worker', 'campaign'], name='task_submis_worker__6662ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='task_submis_status_ee04e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['campaign', 'status'], name='task_submis_campaig_d28456_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['ip_address'], name='task_submis_ip_addr_8971aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionproof',
            constraint=models.UniqueConstraint(fields=('submission', 'step'), name='uq_proof_per_submission_step'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionlog',
            index=models.Index(fields=['referrer', 'status'], name='referral_co_referre_30faf9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommissionlog',
            index=models.Index(fields=['referred', 'level'], name='referral_co_referre_1bcf18_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['user', 'fraud_type'], name='fraud_repor_user_id_0155d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['action_taken', 'created_at'], name='fraud_repor_action__164e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='dispute_status_25c644_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['submission', '-verified_at'], name='verificatio_submiss_da2e3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookconfigmodel',
            unique_together={('publisher', 'event')},
        ),
    ]
