# Generated by Django 5.0.11 on 2026-03-10 10:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_campaign_bonus_rate_campaign_risk_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('floor_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('final_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('auction_type', models.CharField(choices=[('gsp', 'Generalized Second Price'), ('first_price', 'First Price')], default='gsp', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('bid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_bids', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='promotions.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Bid',
                'verbose_name_plural': 'Campaign Bids',
                'db_table': 'campaign_bid',
                'ordering': ['-bid_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_bi_campaig_8dc01d_idx'), models.Index(fields=['advertiser', '-bid_at'], name='campaign_bi_adverti_93f5ba_idx')],
            },
        ),
    ]
