# Generated by Django 5.0.11 on 2026-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_campaignbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='promo_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('yield', 'Yield'), ('fraud', 'Fraud'), ('seasonal', 'Seasonal'), ('referral', 'Referral')], default='bonus', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='traffic_monitor',
            field=models.BooleanField(default=True),
        ),
    ]
