# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_rename_ad_creative_campaig_af5212_idx_idx_campaign_type_1411_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyrate',
            new_name='idx_from_currency_to_curre_728',
            old_name='idx_from_currency_to_currency_fetc_1412',
        ),
        migrations.RenameIndex(
            model_name='fraudreport',
            new_name='idx_action_taken_created_a_4eb',
            old_name='idx_action_taken_created_at_1427',
        ),
        migrations.RenameIndex(
            model_name='verificationlog',
            new_name='idx_submission_verified_at_141',
            old_name='idx_submission_verified_at_1419',
        ),
    ]
