# Generated by Django 5.0.11 on 2026-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_campaign_promo_type_campaign_traffic_monitor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='admincommissionlog',
            name='chk_commission_not_exceed_gross',
        ),
        migrations.RemoveConstraint(
            model_name='admincommissionlog',
            name='chk_commission_all_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='campaign',
            name='chk_campaign_spent_not_exceed_budget',
        ),
        migrations.RemoveConstraint(
            model_name='campaign',
            name='chk_campaign_filled_not_exceed_total_slots',
        ),
        migrations.RemoveConstraint(
            model_name='campaign',
            name='chk_campaign_budget_positive',
        ),
        migrations.RemoveConstraint(
            model_name='campaignanalytics',
            name='chk_analytics_approved_not_exceed_submissions',
        ),
        migrations.RemoveConstraint(
            model_name='campaignanalytics',
            name='chk_analytics_clicks_not_exceed_views',
        ),
        migrations.RemoveConstraint(
            model_name='currencyrate',
            name='chk_currency_rate_different_currencies',
        ),
        migrations.RemoveConstraint(
            model_name='escrowwallet',
            name='chk_escrow_released_not_exceed_locked',
        ),
        migrations.RemoveConstraint(
            model_name='escrowwallet',
            name='chk_escrow_locked_positive',
        ),
        migrations.RemoveConstraint(
            model_name='referralcommissionlog',
            name='chk_referral_referrer_not_same_as_referred',
        ),
        migrations.RemoveConstraint(
            model_name='targetingcondition',
            name='chk_targeting_user_level_range_valid',
        ),
        migrations.RemoveConstraint(
            model_name='tasksubmission',
            name='chk_submission_bonus_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='userreputation',
            name='chk_reputation_counts_not_exceed_total',
        ),
        migrations.RemoveConstraint(
            model_name='userreputation',
            name='chk_reputation_trust_score_range',
        ),
    ]
