# Generated migration for new models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0005_remove_admincommissionlog_chk_commission_not_exceed_gross_and_more'),
    ]

    operations = [
        # PublisherProfile
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_url', models.URLField(blank=True, default='')),
                ('traffic_source', models.CharField(blank=True, default='', max_length=50)),
                ('monthly_traffic', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('niche', models.CharField(blank=True, default='', max_length=50)),
                ('tier', models.CharField(choices=[('starter','Starter'),('bronze','Bronze'),('silver','Silver'),('gold','Gold'),('platinum','Platinum')], default='starter', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending','Pending'),('approved','Approved'),('rejected','Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('device_token_fcm', models.CharField(blank=True, default='', max_length=200)),
                ('device_token_apns', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('telegram_id', models.CharField(blank=True, default='', max_length=50)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'publisher_profile', 'verbose_name': 'Publisher Profile'},
        ),
        # AdvertiserProfile
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('website_url', models.URLField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('billing_email', models.EmailField(blank=True, default='')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'advertiser_profile', 'verbose_name': 'Advertiser Profile'},
        ),
        # APIKeyModel
        migrations.CreateModel(
            name='APIKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('permissions', models.JSONField(default=list)),
                ('rate_limit', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'publisher_api_key', 'verbose_name': 'API Key'},
        ),
        # WebhookConfigModel
        migrations.CreateModel(
            name='WebhookConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(choices=[('GET','GET'),('POST','POST')], default='GET', max_length=6)),
                ('secret_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fired', models.DateTimeField(blank=True, null=True)),
                ('total_fires', models.PositiveIntegerField(default=0)),
                ('last_status_code', models.SmallIntegerField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'webhook_config', 'verbose_name': 'Webhook Config', 'unique_together': {('publisher', 'event')}},
        ),
        # VirtualCurrencyConfig
        migrations.CreateModel(
            name='VirtualCurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(default='Coins', max_length=30)),
                ('currency_icon', models.CharField(default='🪙', max_length=10)),
                ('usd_to_vc_rate', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12)),
                ('min_payout_vc', models.PositiveIntegerField(default=100)),
                ('rounding', models.CharField(choices=[('floor','Floor'),('ceil','Ceil'),('round','Round')], default='floor', max_length=10)),
                ('postback_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vc_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'virtual_currency_config'},
        ),
        # WhiteLabelConfig
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#6C63FF', max_length=7)),
                ('secondary_color', models.CharField(default='#FF6584', max_length=7)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=100)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('show_powered_by', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white_label', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'white_label_config'},
        ),
        # EmailSubmitCampaign
        migrations.CreateModel(
            name='EmailSubmitCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(max_length=200)),
                ('opt_in_type', models.CharField(choices=[('SOI','Single Opt-in'),('DOI','Double Opt-in')], default='SOI', max_length=3)),
                ('payout', models.DecimalField(decimal_places=4, max_digits=8)),
                ('niche', models.CharField(default='general', max_length=50)),
                ('target_countries', models.JSONField(default=list)),
                ('daily_cap', models.PositiveIntegerField(default=5000)),
                ('today_submits', models.PositiveIntegerField(default=0)),
                ('total_submits', models.PositiveIntegerField(default=0)),
                ('redirect_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active','Active'),('paused','Paused'),('completed','Completed')], default='active', max_length=20)),
                ('total_spent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'email_submit_campaign'},
        ),
        # EmailSubmitConversion
        migrations.CreateModel(
            name='EmailSubmitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('subid', models.CharField(blank=True, max_length=64)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='promotions.emailsubmitcampaign')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'email_submit_conversion'},
        ),
        # CPCCampaign
        migrations.CreateModel(
            name='CPCCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('destination_url', models.URLField()),
                ('payout_us', models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=8)),
                ('payout_gb', models.DecimalField(decimal_places=4, default=Decimal('0.28'), max_digits=8)),
                ('payout_ca', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=8)),
                ('payout_au', models.DecimalField(decimal_places=4, default=Decimal('0.22'), max_digits=8)),
                ('payout_other', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=8)),
                ('daily_cap', models.PositiveIntegerField(default=10000)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('today_clicks', models.PositiveIntegerField(default=0)),
                ('dedup_window_sec', models.PositiveIntegerField(default=3600)),
                ('status', models.CharField(choices=[('active','Active'),('paused','Paused'),('completed','Completed')], default='active', max_length=20)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpc_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'cpc_campaign'},
        ),
        # CPIAppCampaign
        migrations.CreateModel(
            name='CPIAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=200)),
                ('bundle_id', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('android','Android'),('ios','iOS'),('both','Both')], max_length=10)),
                ('app_store_url', models.URLField()),
                ('payout_per_install', models.DecimalField(decimal_places=4, max_digits=8)),
                ('mmp_provider', models.CharField(choices=[('appsflyer','AppsFlyer'),('adjust','Adjust'),('firebase','Firebase'),('branch','Branch'),('kochava','Kochava')], default='appsflyer', max_length=20)),
                ('mmp_app_id', models.CharField(blank=True, max_length=200)),
                ('target_countries', models.JSONField(default=list)),
                ('target_os_version', models.CharField(blank=True, max_length=20)),
                ('daily_cap', models.PositiveIntegerField(default=1000)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_installs', models.PositiveIntegerField(default=0)),
                ('today_installs', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('active','Active'),('paused','Paused'),('completed','Completed')], default='active', max_length=20)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpi_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'cpi_app_campaign'},
        ),
        # QuizCampaign
        migrations.CreateModel(
            name='QuizCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('quiz_type', models.CharField(choices=[('personality','Personality'),('trivia','Trivia'),('survey','Survey'),('sweepstakes','Sweepstakes'),('iq','IQ Test')], default='personality', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('lead_form_fields', models.JSONField(default=list)),
                ('payout', models.DecimalField(decimal_places=4, max_digits=8)),
                ('target_countries', models.JSONField(default=list)),
                ('daily_cap', models.PositiveIntegerField(default=2000)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('today_completions', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('active','Active'),('paused','Paused'),('completed','Completed')], default='active', max_length=20)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'quiz_campaign'},
        ),
        # SmartLinkConfig
        migrations.CreateModel(
            name='SmartLinkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('link_hash', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'smartlink_config'},
        ),
        # ContentLockModel
        migrations.CreateModel(
            name='ContentLockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_type', models.CharField(choices=[('link','Link'),('file','File'),('content','Content')], max_length=10)),
                ('lock_token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('destination_url', models.URLField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('required_offers', models.PositiveSmallIntegerField(default=1)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_unlocks', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'content_lock'},
        ),
        # SubIDClick
        migrations.CreateModel(
            name='SubIDClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('s1', models.CharField(blank=True, db_index=True, max_length=64)),
                ('s2', models.CharField(blank=True, db_index=True, max_length=64)),
                ('s3', models.CharField(blank=True, max_length=64)),
                ('s4', models.CharField(blank=True, max_length=64)),
                ('s5', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('payout', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subid_clicks', to='promotions.campaign')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subid_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'subid_click', 'indexes': [models.Index(fields=['publisher', 'created_at'], name='subid_pub_date_idx')]},
        ),
        # PayoutBatch
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('paypal','PayPal'),('payoneer','Payoneer'),('wire','Wire'),('ach','ACH'),('usdt_trc20','USDT TRC20'),('usdt_erc20','USDT ERC20'),('usdt_bep20','USDT BEP20'),('btc','Bitcoin')], max_length=30)),
                ('method_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending','Pending'),('processing','Processing'),('completed','Completed'),('failed','Failed'),('cancelled','Cancelled')], default='pending', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'payout_batch', 'ordering': ['-created_at']},
        ),
        # IPBlacklistModel
        migrations.CreateModel(
            name='IPBlacklistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('cidr', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('warn','Warn'),('temp_ban','Temp Ban'),('permanent','Permanent')], default='permanent', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'ip_blacklist'},
        ),
        # TrackingDomain
        migrations.CreateModel(
            name='TrackingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=200, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('dns_target', models.CharField(blank=True, max_length=200)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'tracking_domain'},
        ),
        # SystemConfig
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string','String'),('integer','Integer'),('decimal','Decimal'),('boolean','Boolean'),('json','JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'system_config'},
        ),
    ]
