# Generated by Django 5.0.11 on 2026-04-10 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_new_offer_types_and_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentlockmodel',
            options={'verbose_name': 'Content Lock'},
        ),
        migrations.AlterModelOptions(
            name='cpccampaign',
            options={'verbose_name': 'CPC Campaign'},
        ),
        migrations.AlterModelOptions(
            name='cpiappcampaign',
            options={'verbose_name': 'CPI App Campaign'},
        ),
        migrations.AlterModelOptions(
            name='emailsubmitcampaign',
            options={'verbose_name': 'Email Submit Campaign'},
        ),
        migrations.AlterModelOptions(
            name='emailsubmitconversion',
            options={'verbose_name': 'Email Submit Conversion'},
        ),
        migrations.AlterModelOptions(
            name='ipblacklistmodel',
            options={'verbose_name': 'IP Blacklist'},
        ),
        migrations.AlterModelOptions(
            name='payoutbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payout Batch'},
        ),
        migrations.AlterModelOptions(
            name='quizcampaign',
            options={'verbose_name': 'Quiz Campaign'},
        ),
        migrations.AlterModelOptions(
            name='smartlinkconfig',
            options={'verbose_name': 'SmartLink Config'},
        ),
        migrations.AlterModelOptions(
            name='subidclick',
            options={'verbose_name': 'SubID Click'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'System Config'},
        ),
        migrations.AlterModelOptions(
            name='trackingdomain',
            options={'verbose_name': 'Tracking Domain'},
        ),
        migrations.AlterModelOptions(
            name='virtualcurrencyconfig',
            options={'verbose_name': 'Virtual Currency Config'},
        ),
        migrations.AlterModelOptions(
            name='whitelabelconfig',
            options={'verbose_name': 'White Label Config'},
        ),
        migrations.RenameIndex(
            model_name='subidclick',
            new_name='subid_click_publish_42ab45_idx',
            old_name='subid_pub_date_idx',
        ),
        migrations.AlterField(
            model_name='advertiserprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikeymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentlockmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cpccampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cpiappcampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailsubmitcampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailsubmitconversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipblacklistmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizcampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smartlinkconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subidclick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackingdomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='virtualcurrencyconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookconfigmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whitelabelconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='admincommissionlog',
            constraint=models.CheckConstraint(check=models.Q(commission_usd__lte=models.F('gross_amount_usd')), name='chk_commission_not_exceed_gross'),
        ),
        migrations.AddConstraint(
            model_name='admincommissionlog',
            constraint=models.CheckConstraint(check=models.Q(worker_reward_usd__gte=0) & models.Q(commission_usd__gte=0) & models.Q(gross_amount_usd__gte=0), name='chk_commission_all_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(spent_usd__lte=models.F('total_budget_usd')), name='chk_campaign_spent_not_exceed_budget'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(filled_slots__lte=models.F('total_slots')), name='chk_campaign_filled_not_exceed_total_slots'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(total_budget_usd__gt=0), name='chk_campaign_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.CheckConstraint(check=models.Q(approved_count__lte=models.F('total_submissions')), name='chk_analytics_approved_not_exceed_submissions'),
        ),
        migrations.AddConstraint(
            model_name='campaignanalytics',
            constraint=models.CheckConstraint(check=models.Q(total_clicks__lte=models.F('total_views')), name='chk_analytics_clicks_not_exceed_views'),
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.CheckConstraint(check=models.Q(from_currency__ne=models.F('to_currency')), name='chk_currency_rate_different_currencies'),
        ),
        migrations.AddConstraint(
            model_name='escrowwallet',
            constraint=models.CheckConstraint(check=models.Q(released_amount_usd__lte=models.F('locked_amount_usd')), name='chk_escrow_released_not_exceed_locked'),
        ),
        migrations.AddConstraint(
            model_name='escrowwallet',
            constraint=models.CheckConstraint(check=models.Q(locked_amount_usd__gt=0), name='chk_escrow_locked_positive'),
        ),
        migrations.AddConstraint(
            model_name='referralcommissionlog',
            constraint=models.CheckConstraint(check=models.Q(referrer__ne=models.F('referred')), name='chk_referral_referrer_not_same_as_referred'),
        ),
        migrations.AddConstraint(
            model_name='targetingcondition',
            constraint=models.CheckConstraint(check=models.Q(min_user_level__lte=models.F('max_user_level')), name='chk_targeting_user_level_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(check=models.Q(bonus_usd__gte=0), name='chk_submission_bonus_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userreputation',
            constraint=models.CheckConstraint(check=models.Q(approved_count__lte=models.F('total_submissions')) & models.Q(rejected_count__lte=models.F('total_submissions')), name='chk_reputation_counts_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='userreputation',
            constraint=models.CheckConstraint(check=models.Q(trust_score__gte=0) & models.Q(trust_score__lte=100), name='chk_reputation_trust_score_range'),
        ),
    ]
