# Generated by Django 5.0.11 on 2026-04-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_alter_contentlockmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartlinkconfig',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_smartlinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
