# Generated by Django 5.0.11 on 2026-03-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_fix_endpoint_toggle_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpointtoggle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='endpointtoggle',
            name='path',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
