# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerwall', '0002_initial'),
        ('tenants', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconversion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerwall_offerconversion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerprovider',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offerprovider'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offercategory'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offerprovider'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['offer', 'user'], name='offerwall_o_offer_i_851b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['click_id'], name='offerwall_o_click_i_da8ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['user', '-clicked_at'], name='offerwall_o_user_id_1cab64_idx'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['is_converted'], name='offerwall_o_is_conv_5257ac_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['offer', 'user'], name='offerwall_o_offer_i_674543_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['user', 'status'], name='offerwall_o_user_id_c59b56_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['status', '-converted_at'], name='offerwall_o_status_44f18d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['external_WalletTransaction_id'], name='offerwall_o_externa_eaa9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='offerprovider',
            index=models.Index(fields=['provider_type', 'status'], name='offerwall_o_provide_bb0f45_idx'),
        ),
        migrations.AddIndex(
            model_name='offerprovider',
            index=models.Index(fields=['status'], name='offerwall_o_status_e736b3_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['provider', 'external_offer_id'], name='offerwall_o_provide_b0c6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'platform'], name='offerwall_o_status_99d19d_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['category', 'status'], name='offerwall_o_categor_21444c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'status'], name='offerwall_o_offer_t_8e5d89_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['-reward_amount', 'status'], name='offerwall_o_reward__edf054_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured', 'status'], name='offerwall_o_is_feat_3ab00b_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['end_date'], name='offerwall_o_end_dat_11cd10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('provider', 'external_offer_id')},
        ),
    ]
