# Generated by Django 5.0.11 on 2026-03-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0002_initial'),
        ('tenants', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offercategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerclick',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerconversion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerprovider',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerwall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offercategory'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offerprovider'),
        ),
        migrations.AlterField(
            model_name='offerclick',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offer'),
        ),
        migrations.AlterField(
            model_name='offerclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerwall_offerclick_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerwall_offerconversion_click', to='offerwall.offerclick'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offer'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='wallet.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerwall_offerconversion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerconversion',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offercategory'),
        ),
        migrations.AlterField(
            model_name='offerwall',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_tenant', to='offerwall.offerprovider'),
        ),
    ]
