# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_provider_external_offer_id_1155',
            old_name='offerwall_o_provide_b0c6ae_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_status_platform_1156',
            old_name='offerwall_o_status_99d19d_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_category_status_1157',
            old_name='offerwall_o_categor_21444c_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_offer_type_status_1158',
            old_name='offerwall_o_offer_t_8e5d89_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_reward_amount_status_1159',
            old_name='offerwall_o_reward__edf054_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_is_featured_status_1160',
            old_name='offerwall_o_is_feat_3ab00b_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_end_date_1161',
            old_name='offerwall_o_end_dat_11cd10_idx',
        ),
        migrations.RenameIndex(
            model_name='offerclick',
            new_name='idx_offer_user_1162',
            old_name='offerwall_o_offer_i_851b9e_idx',
        ),
        migrations.RenameIndex(
            model_name='offerclick',
            new_name='idx_click_id_1163',
            old_name='offerwall_o_click_i_da8ad9_idx',
        ),
        migrations.RenameIndex(
            model_name='offerclick',
            new_name='idx_user_clicked_at_1164',
            old_name='offerwall_o_user_id_1cab64_idx',
        ),
        migrations.RenameIndex(
            model_name='offerclick',
            new_name='idx_is_converted_1165',
            old_name='offerwall_o_is_conv_5257ac_idx',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='idx_offer_user_1166',
            old_name='offerwall_o_offer_i_674543_idx',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='idx_user_status_1167',
            old_name='offerwall_o_user_id_c59b56_idx',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='idx_status_converted_at_1168',
            old_name='offerwall_o_status_44f18d_idx',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='idx_external_WalletTransaction_id_1169',
            old_name='offerwall_o_externa_eaa9ea_idx',
        ),
        migrations.RenameIndex(
            model_name='offerprovider',
            new_name='idx_provider_type_status_1153',
            old_name='offerwall_o_provide_bb0f45_idx',
        ),
        migrations.RenameIndex(
            model_name='offerprovider',
            new_name='idx_status_1154',
            old_name='offerwall_o_status_e736b3_idx',
        ),
    ]
