# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0004_rename_offerwall_o_provide_b0c6ae_idx_idx_provider_external_offer_id_1155_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_provider_external_offe_507',
            old_name='idx_provider_external_offer_id_1155',
        ),
        migrations.RenameIndex(
            model_name='offerconversion',
            new_name='idx_external_WalletTransac_243',
            old_name='idx_external_WalletTransaction_id_1169',
        ),
    ]
