# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / User Message')),
                ('platforms', models.JSONField(default=list, help_text="List of platform strings, e.g. ['ios', 'android']. Empty = all.", verbose_name='Affected Platforms')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16, verbose_name='Status')),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled Start')),
                ('scheduled_end', models.DateTimeField(db_index=True, verbose_name='Scheduled End')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Actual End')),
                ('bypass_token', models.CharField(default='', help_text='If set, requests carrying this token in X-Maintenance-Bypass header will not receive 503 responses.', max_length=128, verbose_name='Bypass Token')),
                ('notify_users', models.BooleanField(default=True, help_text='Send push notifications to affected platforms before start.', verbose_name='Notify Users?')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformRedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], db_index=True, max_length=16, null=True, unique=True, verbose_name='Platform')),
                ('redirect_type', models.CharField(choices=[('store', 'App Store / Play Store'), ('web', 'Web URL'), ('download', 'Direct Download'), ('custom', 'Custom')], default='store', max_length=16, verbose_name='Redirect Type')),
                ('url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Redirect URL')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Platform Redirect',
                'verbose_name_plural': 'Platform Redirects',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUpdatePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], db_index=True, max_length=16, null=True, verbose_name='Platform')),
                ('min_version', models.CharField(help_text="Inclusive lower bound. e.g. '1.0.0'", max_length=32, validators=[django.core.validators.RegexValidator(message='Version must follow semver format: MAJOR.MINOR.PATCH[-prerelease][+build]', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Minimum Affected Version')),
                ('max_version', models.CharField(blank=True, default='', help_text='Exclusive upper bound. Leave blank to match all versions above min.', max_length=32, validators=[django.core.validators.RegexValidator(message='max_version must follow semver format.', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Maximum Affected Version')),
                ('target_version', models.CharField(blank=True, help_text='The version users should upgrade to.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Version must follow semver format: MAJOR.MINOR.PATCH[-prerelease][+build]', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Target Version')),
                ('update_type', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('critical', 'Critical (Blocking)')], db_index=True, default='optional', max_length=16, verbose_name='Update Type')),
                ('release_notes', models.TextField(blank=True, default='', help_text='Markdown-formatted release notes shown in-app.', verbose_name='Release Notes')),
                ('release_notes_url', models.URLField(default='', max_length=2048, verbose_name='Release Notes URL')),
                ('force_update_after', models.DateTimeField(blank=True, help_text='If set, optional updates become required after this datetime.', null=True, verbose_name='Force Update After')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16, verbose_name='Policy Status')),
                ('metadata', models.JSONField(default=dict, help_text='Extra key-value data for downstream consumers.', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_update_policies', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'App Update Policy',
                'verbose_name_plural': 'App Update Policies',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['platform', 'status'], name='version_con_platfor_08510a_idx'), models.Index(fields=['update_type', 'status'], name='version_con_update__29e4f8_idx'), models.Index(fields=['target_version'], name='version_con_target__9156b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appupdatepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('platform', 'min_version', 'target_version'), name='unique_active_policy_per_platform_version'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['status', 'scheduled_start'], name='version_con_status_93c132_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='version_con_schedul_df4614_idx'),
        ),
        migrations.AddIndex(
            model_name='platformredirect',
            index=models.Index(fields=['platform', 'is_active'], name='version_con_platfor_91189c_idx'),
        ),
    ]
