# Generated by Django 5.0.11 on 2026-03-07 02:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='version_con_platfor_08510a_idx',
            old_name='vc_aup_plat_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='version_con_update__29e4f8_idx',
            old_name='vc_aup_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='version_con_target__9156b9_idx',
            old_name='vc_aup_target_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='version_con_status_93c132_idx',
            old_name='vc_ms_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='version_con_schedul_df4614_idx',
            old_name='vc_ms_window_idx',
        ),
        migrations.RenameIndex(
            model_name='platformredirect',
            new_name='version_con_platfor_91189c_idx',
            old_name='vc_pr_plat_active_idx',
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_update_policies', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='force_update_after',
            field=models.DateTimeField(blank=True, help_text='If set, optional updates become required after this datetime.', null=True, verbose_name='Force Update After'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='max_version',
            field=models.CharField(blank=True, default='', help_text='Exclusive upper bound. Leave blank to match all versions above min.', max_length=32, validators=[django.core.validators.RegexValidator(message='max_version must follow semver format.', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Maximum Affected Version'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra key-value data for downstream consumers.', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='min_version',
            field=models.CharField(help_text="Inclusive lower bound. e.g. '1.0.0'", max_length=32, validators=[django.core.validators.RegexValidator(message='Version must follow semver format: MAJOR.MINOR.PATCH[-prerelease][+build]', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Minimum Affected Version'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='release_notes',
            field=models.TextField(blank=True, default='', help_text='Markdown-formatted release notes shown in-app.', verbose_name='Release Notes'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='release_notes_url',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='Release Notes URL'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16, verbose_name='Policy Status'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='target_version',
            field=models.CharField(help_text='The version users should upgrade to.', max_length=32, validators=[django.core.validators.RegexValidator(message='Version must follow semver format: MAJOR.MINOR.PATCH[-prerelease][+build]', regex='^\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9._-]+)?(\\+[a-zA-Z0-9._-]+)?$')], verbose_name='Target Version'),
        ),
        migrations.AlterField(
            model_name='appupdatepolicy',
            name='update_type',
            field=models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('critical', 'Critical (Blocking)')], db_index=True, default='optional', max_length=16, verbose_name='Update Type'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual End'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Start'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='bypass_token',
            field=models.CharField(blank=True, default='', help_text='If set, requests carrying this token in X-Maintenance-Bypass header will not receive 503 responses.', max_length=128, verbose_name='Bypass Token'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description / User Message'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='notify_users',
            field=models.BooleanField(default=True, help_text='Send push notifications to affected platforms before start.', verbose_name='Notify Users?'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='platforms',
            field=models.JSONField(default=list, help_text="List of platform strings, e.g. ['ios', 'android']. Empty = all.", verbose_name='Affected Platforms'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='scheduled_end',
            field=models.DateTimeField(db_index=True, verbose_name='Scheduled End'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='scheduled_start',
            field=models.DateTimeField(db_index=True, verbose_name='Scheduled Start'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='platformredirect',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='platformredirect',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], db_index=True, max_length=16, unique=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='platformredirect',
            name='redirect_type',
            field=models.CharField(choices=[('store', 'App Store / Play Store'), ('web', 'Web URL'), ('download', 'Direct Download'), ('custom', 'Custom')], default='store', max_length=16, verbose_name='Redirect Type'),
        ),
        migrations.AlterField(
            model_name='platformredirect',
            name='url',
            field=models.URLField(max_length=2048, verbose_name='Redirect URL'),
        ),
    ]
