# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='idx_platform_status_1881',
            old_name='version_con_platfor_08510a_idx',
        ),
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='idx_update_type_status_1882',
            old_name='version_con_update__29e4f8_idx',
        ),
        migrations.RenameIndex(
            model_name='appupdatepolicy',
            new_name='idx_target_version_1883',
            old_name='version_con_target__9156b9_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='idx_status_scheduled_start_1884',
            old_name='version_con_status_93c132_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='idx_scheduled_start_scheduled_end_1885',
            old_name='version_con_schedul_df4614_idx',
        ),
        migrations.RenameIndex(
            model_name='platformredirect',
            new_name='idx_platform_is_active_1886',
            old_name='version_con_platfor_91189c_idx',
        ),
    ]
