# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_rename_version_con_platfor_08510a_idx_idx_platform_status_1881_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='idx_status_scheduled_start_b46',
            old_name='idx_status_scheduled_start_1884',
        ),
        migrations.RenameIndex(
            model_name='maintenanceschedule',
            new_name='idx_scheduled_start_schedu_5c3',
            old_name='idx_scheduled_start_scheduled_end_1885',
        ),
    ]
