# Generated by Django 5.0.14 on 2026-02-16 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_secret', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gateway Configuration',
                'verbose_name_plural': 'Gateway Configurations',
            },
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('bonus', 'Bonus')], max_length=20)),
                ('gateway', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gateway Transaction',
                'verbose_name_plural': 'Gateway Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('sslcommerz', 'SSLCommerz'), ('amarpay', 'AmarPay'), ('upay', 'Upay'), ('shurjopay', 'ShurjoPay')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('merchant_key', models.CharField(blank=True, max_length=500, null=True)),
                ('merchant_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('callback_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('supports_deposit', models.BooleanField(default=True)),
                ('supports_withdrawal', models.BooleanField(default=True)),
                ('supported_currencies', models.CharField(default='BDT,USD', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gateway_logos/')),
                ('color_code', models.CharField(default='#0066CC', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('config_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gateway', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment Gateway Method',
                'verbose_name_plural': 'Payment Gateway Methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gateway', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('headers', models.TextField(default='{}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Webhook Log',
                'verbose_name_plural': 'Payment Gateway Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
