# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_gateways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaytransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='payment_gateways.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymentgatewaymethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_gateways.paymentgatewaymethod'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gatewayconfig',
            unique_together={('gateway', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewaymethod',
            unique_together={('user', 'gateway', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['reference_id'], name='payment_gat_referen_4dc6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['status'], name='payment_gat_status_e38533_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['user', 'status'], name='payment_gat_user_id_33f150_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status'], name='payment_gat_status_f4f9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='payment_gat_user_id_335841_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['reference_id'], name='payment_gat_referen_01de71_idx'),
        ),
    ]
