# Generated by Django 5.0.11 on 2026-03-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaytransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways_gatewaytransaction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentgatewaymethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways_paymentgatewaymethod_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateways_payoutrequest_processed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways_payoutrequest_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
