# migrations/0006_deposit_withdrawal_gateway_config.py
# Migration for new models: DepositRequest, DepositCallback, DepositVerification,
# DepositRefund, WithdrawalGatewayRequest, WithdrawalGatewayCallback,
# WithdrawalReceipt, WithdrawalFailure, GatewayCredential, GatewayWebhookConfig,
# GatewayLimit, GatewayFeeRule, GatewayHealthLog,
# ReconciliationBatch, ReconciliationMismatch, GatewayStatement, PaymentAnalytics

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment_gateways', '0005_add_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        # ── DepositRequest ────────────────────────────────────────────────────
        migrations.CreateModel(name='DepositRequest', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('gateway', models.CharField(max_length=20)),
            ('amount', models.DecimalField(max_digits=12, decimal_places=2)),
            ('fee', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'))),
            ('net_amount', models.DecimalField(max_digits=12, decimal_places=2)),
            ('currency', models.CharField(max_length=5, default='BDT')),
            ('status', models.CharField(max_length=15, default='initiated')),
            ('reference_id', models.CharField(max_length=100, unique=True)),
            ('gateway_ref', models.CharField(max_length=200, blank=True)),
            ('payment_url', models.URLField(max_length=2000, blank=True)),
            ('session_key', models.CharField(max_length=200, blank=True)),
            ('initiated_at', models.DateTimeField(auto_now_add=True)),
            ('completed_at', models.DateTimeField(null=True, blank=True)),
            ('expires_at', models.DateTimeField(null=True, blank=True)),
            ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
            ('user_agent', models.TextField(blank=True)),
            ('gateway_response', models.JSONField(default=dict, blank=True)),
            ('callback_data', models.JSONField(default=dict, blank=True)),
            ('metadata', models.JSONField(default=dict, blank=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                     related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
        ], options={'verbose_name': 'Deposit Request', 'ordering': ['-initiated_at']}),
        migrations.AddIndex(model_name='depositrequest',
            index=models.Index(fields=['user', 'status'], name='dep_user_status_idx')),
        migrations.AddIndex(model_name='depositrequest',
            index=models.Index(fields=['reference_id'], name='dep_ref_idx')),

        # ── DepositCallback ───────────────────────────────────────────────────
        migrations.CreateModel(name='DepositCallback', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('gateway', models.CharField(max_length=20)),
            ('raw_payload', models.JSONField()),
            ('raw_body', models.TextField(blank=True)),
            ('headers', models.JSONField(default=dict, blank=True)),
            ('signature', models.CharField(max_length=500, blank=True)),
            ('is_valid', models.BooleanField(default=False)),
            ('processed', models.BooleanField(default=False)),
            ('processed_at', models.DateTimeField(null=True, blank=True)),
            ('event_type', models.CharField(max_length=100, blank=True)),
            ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
            ('processing_error', models.TextField(blank=True)),
            ('deposit', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL,
                        related_name='callbacks', to='payment_gateways.depositrequest')),
        ], options={'verbose_name': 'Deposit Callback', 'ordering': ['-created_at']}),

        # ── DepositVerification ───────────────────────────────────────────────
        migrations.CreateModel(name='DepositVerification', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('verification_method', models.CharField(max_length=20, default='auto_webhook')),
            ('verified_at', models.DateTimeField(null=True, blank=True)),
            ('is_verified', models.BooleanField(default=False)),
            ('gateway_txn_id', models.CharField(max_length=200, blank=True)),
            ('verified_amount', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
            ('notes', models.TextField(blank=True)),
            ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                        related_name='verification', to='payment_gateways.depositrequest')),
            ('verified_by', models.ForeignKey(null=True, blank=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name='verified_deposits', to=settings.AUTH_USER_MODEL)),
        ], options={'verbose_name': 'Deposit Verification'}),

        # ── DepositRefund ─────────────────────────────────────────────────────
        migrations.CreateModel(name='DepositRefund', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('refund_amount', models.DecimalField(max_digits=12, decimal_places=2)),
            ('reason', models.CharField(max_length=30, default='customer_request')),
            ('reason_detail', models.TextField(blank=True)),
            ('status', models.CharField(max_length=15, default='requested')),
            ('gateway_refund_id', models.CharField(max_length=200, blank=True)),
            ('refunded_at', models.DateTimeField(null=True, blank=True)),
            ('rejection_reason', models.TextField(blank=True)),
            ('metadata', models.JSONField(default=dict, blank=True)),
            ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='refunds', to='payment_gateways.depositrequest')),
            ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                             related_name='deposit_refund_requests', to=settings.AUTH_USER_MODEL)),
        ], options={'verbose_name': 'Deposit Refund', 'ordering': ['-created_at']}),

        # ── GatewayCredential ─────────────────────────────────────────────────
        migrations.CreateModel(name='GatewayCredential', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('label', models.CharField(max_length=100, default='default')),
            ('merchant_id', models.CharField(max_length=500, blank=True)),
            ('api_key', models.TextField(blank=True)),
            ('api_secret', models.TextField(blank=True)),
            ('webhook_secret', models.TextField(blank=True)),
            ('extra_fields', models.JSONField(default=dict, blank=True)),
            ('is_test_mode', models.BooleanField(default=True)),
            ('is_active', models.BooleanField(default=True)),
            ('expires_at', models.DateTimeField(null=True, blank=True)),
            ('last_verified', models.DateTimeField(null=True, blank=True)),
            ('is_verified', models.BooleanField(default=False)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='credentials', to='payment_gateways.paymentgateway')),
            ('tenant', models.ForeignKey(null=True, blank=True,
                       on_delete=django.db.models.deletion.CASCADE,
                       related_name='gateway_credentials', to=settings.AUTH_USER_MODEL)),
        ], options={'verbose_name': 'Gateway Credential'}),

        # ── GatewayHealthLog ──────────────────────────────────────────────────
        migrations.CreateModel(name='GatewayHealthLog', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('status', models.CharField(max_length=10)),
            ('response_time_ms', models.IntegerField(default=0)),
            ('http_status_code', models.IntegerField(null=True, blank=True)),
            ('error', models.TextField(blank=True)),
            ('checked_at', models.DateTimeField(auto_now_add=True)),
            ('is_test_mode', models.BooleanField(default=True)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='health_logs', to='payment_gateways.paymentgateway')),
        ], options={'verbose_name': 'Gateway Health Log', 'ordering': ['-checked_at']}),
        migrations.AddIndex(model_name='gatewayhealthlog',
            index=models.Index(fields=['gateway', 'checked_at'], name='health_gw_time_idx')),

        # ── GatewayFeeRule ────────────────────────────────────────────────────
        migrations.CreateModel(name='GatewayFeeRule', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('transaction_type', models.CharField(max_length=20, default='deposit')),
            ('fee_type', models.CharField(max_length=15, default='percentage')),
            ('fee_value', models.DecimalField(max_digits=7, decimal_places=4)),
            ('fixed_component', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'))),
            ('min_fee', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'))),
            ('max_fee', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
            ('currency', models.CharField(max_length=5, default='BDT')),
            ('tiers', models.JSONField(default=list, blank=True)),
            ('is_active', models.BooleanField(default=True)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='fee_rules', to='payment_gateways.paymentgateway')),
        ], options={'verbose_name': 'Gateway Fee Rule'}),

        # ── GatewayLimit ──────────────────────────────────────────────────────
        migrations.CreateModel(name='GatewayLimit', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('transaction_type', models.CharField(max_length=20, default='deposit')),
            ('min_amount', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('1'))),
            ('max_amount', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('50000'))),
            ('daily_limit', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
            ('monthly_limit', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
            ('currency', models.CharField(max_length=5, default='BDT')),
            ('is_active', models.BooleanField(default=True)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='limits', to='payment_gateways.paymentgateway')),
        ], options={'verbose_name': 'Gateway Limit'}),

        # ── ReconciliationBatch ───────────────────────────────────────────────
        migrations.CreateModel(name='ReconciliationBatch', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('date', models.DateField()),
            ('status', models.CharField(max_length=10, default='pending')),
            ('started_at', models.DateTimeField(null=True, blank=True)),
            ('completed_at', models.DateTimeField(null=True, blank=True)),
            ('total_our_records', models.IntegerField(default=0)),
            ('total_gateway_records', models.IntegerField(default=0)),
            ('total_matched', models.IntegerField(default=0)),
            ('total_mismatched', models.IntegerField(default=0)),
            ('our_total_amount', models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0'))),
            ('gateway_total_amount', models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0'))),
            ('discrepancy_amount', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0'))),
            ('notes', models.TextField(blank=True)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='reconciliation_batches', to='payment_gateways.paymentgateway')),
        ], options={'verbose_name': 'Reconciliation Batch', 'ordering': ['-date']}),

        # ── PaymentAnalytics ──────────────────────────────────────────────────
        migrations.CreateModel(name='PaymentAnalytics', fields=[
            ('id', models.BigAutoField(primary_key=True)),
            ('date', models.DateField()),
            ('transaction_type', models.CharField(max_length=20, default='deposit')),
            ('currency', models.CharField(max_length=5, default='BDT')),
            ('success_count', models.IntegerField(default=0)),
            ('failed_count', models.IntegerField(default=0)),
            ('pending_count', models.IntegerField(default=0)),
            ('total_count', models.IntegerField(default=0)),
            ('total_amount', models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0'))),
            ('total_fees', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0'))),
            ('avg_amount', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0'))),
            ('success_rate', models.DecimalField(max_digits=6, decimal_places=4, default=Decimal('0'))),
            ('failure_rate', models.DecimalField(max_digits=6, decimal_places=4, default=Decimal('0'))),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='analytics', to='payment_gateways.paymentgateway')),
        ], options={'verbose_name': 'Payment Analytics', 'ordering': ['-date']}),
        migrations.AlterUniqueTogether(name='paymentanalytics',
            unique_together={('date', 'gateway', 'transaction_type', 'currency')}),

        # ── New fields on PaymentGateway ──────────────────────────────────────
        migrations.AddField(model_name='paymentgateway', name='region',
            field=models.CharField(max_length=10, default='BD')),
        migrations.AddField(model_name='paymentgateway', name='supports_refund',
            field=models.BooleanField(default=True)),
        migrations.AddField(model_name='paymentgateway', name='daily_limit',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
        migrations.AddField(model_name='paymentgateway', name='health_status',
            field=models.CharField(max_length=10, default='unknown')),
        migrations.AddField(model_name='paymentgateway', name='last_health_check',
            field=models.DateTimeField(null=True, blank=True)),
        migrations.AddField(model_name='paymentgateway', name='avg_response_time_ms',
            field=models.IntegerField(default=0)),

        # ── New fields on GatewayTransaction ─────────────────────────────────
        migrations.AddField(model_name='gatewaytransaction', name='currency',
            field=models.CharField(max_length=5, default='BDT')),
        migrations.AddField(model_name='gatewaytransaction', name='ip_address',
            field=models.GenericIPAddressField(null=True, blank=True)),
        migrations.AddField(model_name='gatewaytransaction', name='device_type',
            field=models.CharField(max_length=20, blank=True)),
    ]
