# Generated by Django 5.0.11 on 2026-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0007_advertiserprofile_advertisertrackerintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='476a70ef9ac241d08dd8d1786b29f848', max_length=64),
        ),
    ]
