# Generated by Django 5.0.11 on 2026-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0009_alter_advertisertrackerintegration_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='3bcec3104853480683b9126372412738', max_length=64),
        ),
    ]
