# Generated by Django 5.0.11 on 2026-04-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('offers', '__first__'),  # removed - app not installed
        ('payment_gateways', '0010_alter_lockersession_session_id'),
        # ('tracking', '__first__'),  # removed - app not installed
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisertrackerintegration',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_integration', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='click',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='offers.campaign'),
        ),
        migrations.AlterField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='contentlocker',
            name='require_specific_offer',
            field=models.ForeignKey(blank=True, help_text='Force a specific offer (null = show best available)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='offers.campaign'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='lockersession',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.conversion'),
        ),
        migrations.AlterField(
            model_name='lockersession',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Offer shown to this visitor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='f766a7845dac4fd88282f4eba7842645', max_length=64),
        ),
        migrations.AlterField(
            model_name='offerqualityscore',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='postbacklog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_logs', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='publisherdailystats',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='smartlink',
            name='manual_offers',
            field=models.ManyToManyField(blank=True, help_text='Specific offers to include (empty = auto-select all eligible)', related_name='smart_links', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='smartlinkrotation',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='trafficblacklist',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Specific offer to apply to (null = all offers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='virtualreward',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.conversion'),
        ),
        migrations.AlterField(
            model_name='virtualreward',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
    ]
