# Generated by Django 5.0.11 on 2026-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0011_alter_advertisertrackerintegration_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='bddd32d893d641b09d74c299996e7ef8', max_length=64),
        ),
    ]
