# Generated by Django 5.0.11 on 2026-04-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0012_alter_lockersession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='e9b80768c89946f9be197d26343f5b37', max_length=64),
        ),
    ]
