# Generated by Django 5.0.11 on 2026-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0014_alter_advertisertrackerintegration_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='6dd82ab8deef46f59f51f43ea23cb7b3', max_length=64),
        ),
    ]
