# Generated by Django 5.0.11 on 2026-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0015_alter_lockersession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockersession',
            name='session_id',
            field=models.CharField(db_index=True, default='cb4d6601dd43464aa2e1e9fd37be222e', max_length=64),
        ),
    ]
