# Generated by Django 5.0.11 on 2026-03-31 14:32

import api.webhooks.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhooks_we_endpoin_692e83_idx',
            old_name='webhook_log_endpoint_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhooks_we_event_t_8503e6_idx',
            old_name='webhook_log_event_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhooks_we_status_c13112_idx',
            old_name='webhook_log_status_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhooks_we_deliver_1bc221_idx',
            old_name='webhook_log_delivery_id_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='webhooks_we_owner_i_017843_idx',
            old_name='webhook_end_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='webhooks_we_tenant__8ad610_idx',
            old_name='webhook_end_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksubscription',
            new_name='webhooks_we_event_t_0aba44_idx',
            old_name='webhook_sub_event_active_idx',
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='delivery_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID sent as X-Webhook-Delivery-ID header.', unique=True, verbose_name='Delivery ID'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='event_type',
            field=models.CharField(choices=[('payout.success', 'Payout Success'), ('payout.failed', 'Payout Failed'), ('payout.pending', 'Payout Pending'), ('payout.reversed', 'Payout Reversed'), ('payout.scheduled', 'Payout Scheduled'), ('wallet.credited', 'Wallet Credited'), ('wallet.debited', 'Wallet Debited'), ('wallet.frozen', 'Wallet Frozen'), ('wallet.threshold_hit', 'Wallet Threshold Hit'), ('user.registered', 'User Registered'), ('user.verified', 'User Verified (KYC)'), ('user.suspended', 'User Suspended'), ('user.deleted', 'User Deleted'), ('user.profile_updated', 'User Profile Updated'), ('user.password_changed', 'User Password Changed'), ('offer.completed', 'Offer Completed'), ('offer.credited', 'Offer Credited'), ('offer.reversed', 'Offer Reversed'), ('offer.flagged', 'Offer Flagged — Suspicious'), ('ad.impression', 'Ad Impression'), ('ad.click', 'Ad Click'), ('ad.reward_granted', 'Ad Reward Granted'), ('ad.network_connected', 'Ad Network Connected'), ('ad.network_disconnected', 'Ad Network Disconnected'), ('referral.signup', 'Referral Signup'), ('referral.commission', 'Referral Commission Earned'), ('subscription.activated', 'Subscription Activated'), ('subscription.cancelled', 'Subscription Cancelled'), ('subscription.renewed', 'Subscription Renewed'), ('subscription.expired', 'Subscription Expired'), ('fraud.alert_raised', 'Fraud Alert Raised'), ('fraud.account_blocked', 'Fraud — Account Blocked'), ('fraud.ip_blacklisted', 'Fraud — IP Blacklisted'), ('kyc.submitted', 'KYC Submitted'), ('kyc.approved', 'KYC Approved'), ('kyc.rejected', 'KYC Rejected'), ('system.maintenance_start', 'System Maintenance Started'), ('system.maintenance_end', 'System Maintenance Ended'), ('system.alert', 'System Alert'), ('webhook.test', 'Webhook Test Ping')], db_index=True, max_length=80, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='response_body',
            field=models.TextField(blank=True, default='', help_text='First 4096 chars of the response body.', verbose_name='Response Body'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='custom_headers',
            field=models.JSONField(blank=True, default=api.webhooks.models._empty_dict, help_text='Additional HTTP headers injected into every dispatch request.', verbose_name='Custom Headers'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='label',
            field=models.CharField(help_text='Human-readable name for this endpoint.', max_length=120, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret_key',
            field=models.CharField(default=api.webhooks.models._generate_secret_key, editable=False, help_text='HMAC-SHA256 secret auto-generated per endpoint. Sent as X-Webhook-Signature on every dispatch.', max_length=128, verbose_name='Signing Secret'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='target_url',
            field=models.URLField(help_text='The HTTPS endpoint that will receive dispatched payloads.', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])], verbose_name='Target URL'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='filters',
            field=models.JSONField(blank=True, default=api.webhooks.models._empty_dict, help_text='Optional key-value pairs to filter dispatches. Example: {"currency": "BDT", "amount_gte": 100}', verbose_name='Payload Filters'),
        ),
    ]
