# Generated by Django 5.0.11 on 2026-04-16 10:00

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_path', models.CharField(help_text='Dot-separated path to the field (e.g., user.email)', max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('not_equals', 'Not Equals'), ('not_contains', 'Not Contains')], default='equals', max_length=20)),
                ('value', models.TextField(help_text='Value to compare against')),
                ('is_active', models.BooleanField(default=True)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='filters', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Filter',
                'verbose_name_plural': 'Webhook Filters',
                'ordering': ['field_path'],
            },
        ),
        migrations.CreateModel(
            name='WebhookBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(help_text='Unique identifier for this batch', max_length=100, unique=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='batches', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Batch',
                'verbose_name_plural': 'Webhook Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(help_text='Position within the batch')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='items', to='webhooks.webhookbatch')),
                ('delivery_log', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='batch_items', to='webhooks.webhookdeliverylog')),
            ],
            options={
                'verbose_name': 'Webhook Batch Item',
                'verbose_name_plural': 'Webhook Batch Items',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WebhookTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable name for this template', max_length=255)),
                ('event_type', models.CharField(help_text='Event type this template applies to', max_length=80)),
                ('payload_template', models.TextField(help_text='Jinja2 template for payload transformation')),
                ('transform_rules', models.JSONField(blank=True, default=dict, help_text='Transformation rules for payload')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Template',
                'verbose_name_plural': 'Webhook Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_hash', models.CharField(help_text='Hashed version of the secret', max_length=256)),
                ('expires_at', models.DateTimeField(blank=True, null=True, help_text='When this secret expires')),
                ('is_active', models.BooleanField(default=True)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='secrets', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Secret',
                'verbose_name_plural': 'Webhook Secrets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookfilter',
            index=models.Index(fields=['endpoint', 'is_active'], name='webhooks_we_endpoin_4a5b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookfilter',
            index=models.Index(fields=['field_path', 'operator'], name='webhooks_we_field_p_7d8e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatch',
            index=models.Index(fields=['endpoint', 'status'], name='webhooks_we_endpoin_0a1b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatch',
            index=models.Index(fields=['batch_id'], name='webhooks_we_batch_i_3d4e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatch',
            index=models.Index(fields=['status', 'created_at'], name='webhooks_we_status_6f7g8h_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatchitem',
            index=models.Index(fields=['batch', 'position'], name='webhooks_we_batch__9i0j1k_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatchitem',
            index=models.Index(fields=['delivery_log'], name='webhooks_we_deliver_2l3m4n_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooktemplate',
            index=models.Index(fields=['event_type', 'is_active'], name='webhooks_we_event_t_5o6p7q_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksecret',
            index=models.Index(fields=['endpoint', 'is_active'], name='webhooks_we_endpoin_8r9s0t_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksecret',
            index=models.Index(fields=['expires_at'], name='webhooks_we_expires_1u2v3w_idx'),
        ),
    ]
