# Generated by Django 5.0.11 on 2026-04-16 10:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0002_advanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('url_token', models.CharField(help_text='Unique token for webhook URL', max_length=100, unique=True)),
                ('secret', models.CharField(help_text='Secret for signature verification', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_inbound_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbound Webhook',
                'verbose_name_plural': 'Inbound Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField(help_text='Raw webhook payload received')),
                ('headers', models.JSONField(help_text='HTTP headers received')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the sender')),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('inbound', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='logs', to='webhooks.inboundwebhook')),
            ],
            options={
                'verbose_name': 'Inbound Webhook Log',
                'verbose_name_plural': 'Inbound Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_pattern', models.CharField(help_text='Pattern to match webhook events', max_length=255)),
                ('handler_function', models.CharField(help_text='Function to handle the webhook', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('inbound', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='routes', to='webhooks.inboundwebhook')),
            ],
            options={
                'verbose_name': 'Inbound Webhook Route',
                'verbose_name_plural': 'Inbound Webhook Routes',
                'ordering': ['event_pattern'],
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_type', models.CharField(choices=[('validation_error', 'Validation Error'), ('network_error', 'Network Error'), ('timeout_error', 'Timeout Error'), ('authentication_error', 'Authentication Error'), ('authorization_error', 'Authorization Error'), ('rate_limit_error', 'Rate Limit Error'), ('server_error', 'Server Error'), ('unknown_error', 'Unknown Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('log', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='errors', to='webhooks.inboundwebhooklog')),
            ],
            options={
                'verbose_name': 'Inbound Webhook Error',
                'verbose_name_plural': 'Inbound Webhook Errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundwebhook',
            index=models.Index(fields=['source', 'is_active'], name='webhooks_in_source_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhook',
            index=models.Index(fields=['url_token'], name='webhooks_in_url_tok_4d5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['inbound', 'processed'], name='webhooks_in_inbound_7g8h9i_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['signature_valid', 'processed'], name='webhooks_in_signat_0j1k2l_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['ip_address'], name='webhooks_in_ip_addr_3m4n5o_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookroute',
            index=models.Index(fields=['inbound', 'is_active'], name='webhooks_in_inbound_6p7q8r_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookerror',
            index=models.Index(fields=['log', 'error_type'], name='webhooks_in_log_err_9s0t1u_idx'),
        ),
    ]
