# Generated by Django 5.0.11 on 2026-04-16 10:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0003_inbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date for these analytics')),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='analytics', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Analytics',
                'verbose_name_plural': 'Webhook Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebhookHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(help_text='When the health check was performed')),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='health_logs', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Health Log',
                'verbose_name_plural': 'Webhook Health Logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date for these statistics')),
                ('event_type', models.CharField(help_text='Event type', max_length=80)),
                ('fired_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_event_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Event Stat',
                'verbose_name_plural': 'Webhook Event Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebhookRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_seconds', models.PositiveIntegerField(default=60)),
                ('max_requests', models.PositiveIntegerField(default=1000)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='rate_limits', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Rate Limit',
                'verbose_name_plural': 'Webhook Rate Limits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookRetryAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('avg_attempts_before_success', models.FloatField(default=0.0)),
                ('exhausted_count', models.PositiveIntegerField(default=0)),
                ('endpoint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='retry_analyses', to='webhooks.webhookendpoint')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_retry_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Retry Analysis',
                'verbose_name_plural': 'Webhook Retry Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookanalytics',
            index=models.Index(fields=['endpoint', 'date'], name='webhooks_we_endpoin_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookanalytics',
            index=models.Index(fields=['date'], name='webhooks_we_date_4d5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookhealthlog',
            index=models.Index(fields=['endpoint', 'checked_at'], name='webhooks_we_endpoin_7g8h9i_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookhealthlog',
            index=models.Index(fields=['is_healthy', 'checked_at'], name='webhooks_we_is_hea_0j1k2l_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventstat',
            index=models.Index(fields=['event_type', 'date'], name='webhooks_we_event_t_3m4n5o_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventstat',
            index=models.Index(fields=['date'], name='webhooks_we_date_6p7q8r_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookratelimit',
            index=models.Index(fields=['endpoint', 'reset_at'], name='webhooks_we_endpoin_9s0t1u_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookretryanalysis',
            index=models.Index(fields=['endpoint', 'period'], name='webhooks_we_endpoin_2v3w4x_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookretryanalysis',
            index=models.Index(fields=['period'], name='webhooks_we_period_5y6z7a_idx'),
        ),
    ]
