# Generated by Django 5.0.11 on 2026-04-16 10:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0004_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookReplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for replay')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_log', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='replays', to='webhooks.webhookdeliverylog')),
                ('replayed_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='replays_made', to=settings.AUTH_USER_MODEL)),
                ('new_log', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='original_replays', to='webhooks.webhookdeliverylog')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_replays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Replay',
                'verbose_name_plural': 'Webhook Replays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReplayBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(help_text='Unique identifier for this replay batch', max_length=100, unique=True)),
                ('event_type', models.CharField(help_text='Event type being replayed', max_length=80)),
                ('date_from', models.DateField(help_text='Start date for replay')),
                ('date_to', models.DateField(help_text='End date for replay')),
                ('count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='created_replay_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Replay Batch',
                'verbose_name_plural': 'Webhook Replay Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReplayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='items', to='webhooks.webhookreplaybatch')),
                ('original_log', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='replay_items', to='webhooks.webhookdeliverylog')),
                ('new_log', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='replay_items', to='webhooks.webhookdeliverylog')),
                ('replay', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='replay_items', to='webhooks.webhookreplay')),
            ],
            options={
                'verbose_name': 'Webhook Replay Item',
                'verbose_name_plural': 'Webhook Replay Items',
                'ordering': ['batch', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookreplay',
            index=models.Index(fields=['original_log', 'status'], name='webhooks_we_origin_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplay',
            index=models.Index(fields=['replayed_by', 'status'], name='webhooks_we_replay_4d5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplay',
            index=models.Index(fields=['status', 'created_at'], name='webhooks_we_status_7g8h9i_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplaybatch',
            index=models.Index(fields=['batch_id'], name='webhooks_we_batch_0j1k2l_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplaybatch',
            index=models.Index(fields=['event_type', 'status'], name='webhooks_we_event_t_3m4n5o_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplaybatch',
            index=models.Index(fields=['status', 'created_at'], name='webhooks_we_status_6p7q8r_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplayitem',
            index=models.Index(fields=['batch', 'status'], name='webhooks_we_batch__9s0t1u_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplayitem',
            index=models.Index(fields=['original_log'], name='webhooks_we_origin_2v3w4x_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplayitem',
            index=models.Index(fields=['replay'], name='webhooks_we_replay_5y6z7a_idx'),
        ),
    ]
