# Generated by Django 5.0.11 on 2026-04-17 06:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_replay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundwebhook',
            options={'verbose_name': 'Inbound Webhook', 'verbose_name_plural': 'Inbound Webhooks'},
        ),
        migrations.AlterModelOptions(
            name='inboundwebhookerror',
            options={'verbose_name': 'Inbound Webhook Error', 'verbose_name_plural': 'Inbound Webhook Errors'},
        ),
        migrations.AlterModelOptions(
            name='inboundwebhooklog',
            options={'verbose_name': 'Inbound Webhook Log', 'verbose_name_plural': 'Inbound Webhook Logs'},
        ),
        migrations.AlterModelOptions(
            name='inboundwebhookroute',
            options={'verbose_name': 'Inbound Webhook Route', 'verbose_name_plural': 'Inbound Webhook Routes'},
        ),
        migrations.AlterModelOptions(
            name='webhookanalytics',
            options={'verbose_name': 'Webhook Analytics', 'verbose_name_plural': 'Webhook Analytics'},
        ),
        migrations.AlterModelOptions(
            name='webhookbatch',
            options={'verbose_name': 'Webhook Batch', 'verbose_name_plural': 'Webhook Batches'},
        ),
        migrations.AlterModelOptions(
            name='webhookbatchitem',
            options={'verbose_name': 'Webhook Batch Item', 'verbose_name_plural': 'Webhook Batch Items'},
        ),
        migrations.AlterModelOptions(
            name='webhookdeliverylog',
            options={'ordering': ['-dispatched_at'], 'verbose_name': 'Webhook Delivery Log', 'verbose_name_plural': 'Webhook Delivery Logs'},
        ),
        migrations.AlterModelOptions(
            name='webhookeventstat',
            options={'verbose_name': 'Webhook Event Stat', 'verbose_name_plural': 'Webhook Event Stats'},
        ),
        migrations.AlterModelOptions(
            name='webhookfilter',
            options={'verbose_name': 'Webhook Filter', 'verbose_name_plural': 'Webhook Filters'},
        ),
        migrations.AlterModelOptions(
            name='webhookhealthlog',
            options={'verbose_name': 'Webhook Health Log', 'verbose_name_plural': 'Webhook Health Logs'},
        ),
        migrations.AlterModelOptions(
            name='webhookratelimit',
            options={'verbose_name': 'Webhook Rate Limit', 'verbose_name_plural': 'Webhook Rate Limits'},
        ),
        migrations.AlterModelOptions(
            name='webhookreplay',
            options={'verbose_name': 'Webhook Replay', 'verbose_name_plural': 'Webhook Replays'},
        ),
        migrations.AlterModelOptions(
            name='webhookreplaybatch',
            options={'verbose_name': 'Webhook Replay Batch', 'verbose_name_plural': 'Webhook Replay Batches'},
        ),
        migrations.AlterModelOptions(
            name='webhookreplayitem',
            options={'verbose_name': 'Webhook Replay Item', 'verbose_name_plural': 'Webhook Replay Items'},
        ),
        migrations.AlterModelOptions(
            name='webhookretryanalysis',
            options={'verbose_name': 'Webhook Retry Analysis', 'verbose_name_plural': 'Webhook Retry Analyses'},
        ),
        migrations.AlterModelOptions(
            name='webhooksecret',
            options={'verbose_name': 'Webhook Secret', 'verbose_name_plural': 'Webhook Secrets'},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Subscription', 'verbose_name_plural': 'Webhook Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='webhooktemplate',
            options={'verbose_name': 'Webhook Template', 'verbose_name_plural': 'Webhook Templates'},
        ),
        migrations.RemoveIndex(
            model_name='inboundwebhooklog',
            name='webhooks_in_inbound_7g8h9i_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboundwebhooklog',
            name='webhooks_in_signat_0j1k2l_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookanalytics',
            name='webhooks_we_endpoin_1a2b3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookbatch',
            name='webhooks_we_status_6f7g8h_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookdeliverylog',
            name='webhooks_we_event_t_8503e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookdeliverylog',
            name='webhooks_we_status_c13112_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookdeliverylog',
            name='webhooks_we_deliver_1bc221_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookendpoint',
            name='webhooks_we_tenant__8ad610_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookeventstat',
            name='webhooks_we_event_t_3m4n5o_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookeventstat',
            name='webhooks_we_date_6p7q8r_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookfilter',
            name='webhooks_we_field_p_7d8e9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookhealthlog',
            name='webhooks_we_is_hea_0j1k2l_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookreplay',
            name='webhooks_we_replay_4d5e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookreplaybatch',
            name='webhooks_we_batch_0j1k2l_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookreplaybatch',
            name='webhooks_we_event_t_3m4n5o_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookreplayitem',
            name='webhooks_we_replay_5y6z7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhooksubscription',
            name='webhooks_we_event_t_0aba44_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundwebhook',
            new_name='iw_source_active_idx',
            old_name='webhooks_in_source_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundwebhook',
            new_name='iw_url_token_idx',
            old_name='webhooks_in_url_tok_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundwebhookerror',
            new_name='iwe_log_error_idx',
            old_name='webhooks_in_log_err_9s0t1u_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundwebhooklog',
            new_name='iwl_ip_address_idx',
            old_name='webhooks_in_ip_addr_3m4n5o_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundwebhookroute',
            new_name='iwr_inbound_active_idx',
            old_name='webhooks_in_inbound_6p7q8r_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookanalytics',
            new_name='wa_date_idx',
            old_name='webhooks_we_date_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookbatch',
            new_name='wb_batch_id_idx',
            old_name='webhooks_we_batch_i_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookbatch',
            new_name='wb_endpoint_status_idx',
            old_name='webhooks_we_endpoin_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookbatchitem',
            new_name='wbi_batch_position_idx',
            old_name='webhooks_we_batch__9i0j1k_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookbatchitem',
            new_name='wbi_delivery_log_idx',
            old_name='webhooks_we_deliver_2l3m4n_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='idx_endpoint_status_1911',
            old_name='webhooks_we_endpoin_692e83_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='idx_owner_status_1905',
            old_name='webhooks_we_owner_i_017843_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookfilter',
            new_name='wf_endpoint_active_idx',
            old_name='webhooks_we_endpoin_4a5b6c_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookhealthlog',
            new_name='whl_endpoint_checked_idx',
            old_name='webhooks_we_endpoin_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookratelimit',
            new_name='wrl_endpoint_reset_idx',
            old_name='webhooks_we_endpoin_9s0t1u_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookreplay',
            new_name='wr_original_status_idx',
            old_name='webhooks_we_origin_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookreplay',
            new_name='wr_status_created_idx',
            old_name='webhooks_we_status_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookreplaybatch',
            new_name='wrb_status_created_idx',
            old_name='webhooks_we_status_6p7q8r_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookreplayitem',
            new_name='wri_batch_status_idx',
            old_name='webhooks_we_batch__9s0t1u_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookreplayitem',
            new_name='wri_original_log_idx',
            old_name='webhooks_we_origin_2v3w4x_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookretryanalysis',
            new_name='wra_endpoint_period_idx',
            old_name='webhooks_we_endpoin_2v3w4x_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookretryanalysis',
            new_name='wra_period_idx',
            old_name='webhooks_we_period_5y6z7a_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksecret',
            new_name='ws_endpoint_active_idx',
            old_name='webhooks_we_endpoin_8r9s0t_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksecret',
            new_name='ws_expires_at_idx',
            old_name='webhooks_we_expires_1u2v3w_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooktemplate',
            new_name='wt_event_active_idx',
            old_name='webhooks_we_event_t_5o6p7q_idx',
        ),
        migrations.RemoveField(
            model_name='inboundwebhookerror',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inboundwebhooklog',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='webhookanalytics',
            unique_together={('date', 'endpoint')},
        ),
        migrations.RemoveField(
            model_name='webhookbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookbatch',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='webhookbatchitem',
            unique_together={('batch', 'delivery_log')},
        ),
        migrations.RemoveField(
            model_name='webhookdeliverylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookdeliverylog',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='webhookdeliverylog',
            name='response_time_ms',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='custom_headers',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='failed_deliveries',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='success_deliveries',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='target_url',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='total_deliveries',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='webhookeventstat',
            unique_together={('date', 'event_type')},
        ),
        migrations.RemoveField(
            model_name='webhookfilter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookhealthlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookhealthlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookhealthlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='webhookratelimit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookratelimit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookreplay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookreplaybatch',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='webhookreplaybatch',
            name='completed_at',
        ),
        migrations.AlterUniqueTogether(
            name='webhookreplayitem',
            unique_together={('batch', 'original_log')},
        ),
        migrations.AlterUniqueTogether(
            name='webhookretryanalysis',
            unique_together={('endpoint', 'period')},
        ),
        migrations.RemoveField(
            model_name='webhooksecret',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhooksecret',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='webhooksubscription',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='webhooktemplate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='inboundwebhookerror',
            name='stack_trace',
            field=models.TextField(blank=True, default='', help_text='Full stack trace for debugging', verbose_name='Stack Trace'),
        ),
        migrations.AddField(
            model_name='inboundwebhooklog',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if processing failed', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='inboundwebhookroute',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers have higher priority', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Duration of the webhook request in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom headers to include in webhook requests'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='ip_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses for webhook requests'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='payload_template',
            field=models.ForeignKey(blank=True, help_text='Template to use for payload transformation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='webhooks.webhooktemplate'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='rate_limit_per_min',
            field=models.IntegerField(default=60, help_text='Rate limit per minute for this endpoint'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='timeout_seconds',
            field=models.IntegerField(default=30, help_text='Timeout in seconds for webhook requests'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Webhook URL to send events to', max_length=2048),
        ),
        migrations.AddField(
            model_name='webhookretryanalysis',
            name='success_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Success Rate (%)'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='filter_config',
            field=models.JSONField(blank=True, default=dict, help_text='Filter configuration for conditional event delivery'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inbound_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='secret',
            field=models.CharField(help_text='Secret key for signature verification', max_length=255, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='source',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('custom', 'Custom')], help_text='Payment gateway or external system', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhook',
            name='url_token',
            field=models.CharField(help_text='Unique token for webhook URL', max_length=255, unique=True, verbose_name='URL Token'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookerror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookerror',
            name='error_message',
            field=models.TextField(help_text='Detailed error description', verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookerror',
            name='error_type',
            field=models.CharField(choices=[('validation_error', 'Validation Error'), ('signature_error', 'Signature Error'), ('timeout_error', 'Timeout Error'), ('network_error', 'Network Error'), ('system_error', 'System Error'), ('unknown_error', 'Unknown Error')], max_length=50, verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookerror',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookerror',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='webhooks.inboundwebhooklog', verbose_name='Webhook Log'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP headers from webhook request', verbose_name='Headers'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhooks.inboundwebhook', verbose_name='Inbound Webhook'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of webhook sender', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether webhook has been processed', verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When webhook was processed', null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='raw_payload',
            field=models.JSONField(help_text='Original webhook payload as received', verbose_name='Raw Payload'),
        ),
        migrations.AlterField(
            model_name='inboundwebhooklog',
            name='signature_valid',
            field=models.BooleanField(default=False, help_text='Whether webhook signature was valid', verbose_name='Signature Valid'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='event_pattern',
            field=models.CharField(help_text='Regex or pattern to match events', max_length=255, verbose_name='Event Pattern'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='handler_function',
            field=models.CharField(help_text='Python function to handle matching events', max_length=255, verbose_name='Handler Function'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='webhooks.inboundwebhook', verbose_name='Inbound Webhook'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='inboundwebhookroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='avg_latency_ms',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average Latency (ms)'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='date',
            field=models.DateField(help_text='Date for these analytics', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Failed Count'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='success_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Success Count'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='success_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Success Rate (%)'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='total_sent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Sent'),
        ),
        migrations.AlterField(
            model_name='webhookanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='batch_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Batch ID'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='event_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Event Count'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webhookbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webhooks.webhookbatch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='webhookbatchitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookbatchitem',
            name='delivery_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='webhooks.webhookdeliverylog', verbose_name='Delivery Log'),
        ),
        migrations.AlterField(
            model_name='webhookbatchitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookbatchitem',
            name='position',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Current attempt number'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the delivery was completed', null=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='dispatched_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the webhook was dispatched'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='endpoint',
            field=models.ForeignKey(help_text='Webhook endpoint that received the delivery', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='webhooks.webhookendpoint'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if delivery failed'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='event_type',
            field=models.CharField(help_text='Type of event that was delivered', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='http_status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code returned by the endpoint', null=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for next retry attempt', null=True),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='payload',
            field=models.JSONField(help_text='Payload that was sent in the webhook request'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Headers sent with the webhook request'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='response_body',
            field=models.TextField(blank=True, help_text='Response body returned by the endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='signature',
            field=models.CharField(blank=True, help_text='Signature used for webhook request', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('expired', 'Expired')], default='pending', help_text='Current status of the delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='description',
            field=models.TextField(blank=True, help_text="Description of the endpoint's purpose"),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', help_text='HTTP method to use for webhook requests', max_length=10),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='label',
            field=models.CharField(help_text='Human-readable label for the endpoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retry attempts'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this webhook endpoint', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret_key',
            field=models.CharField(help_text='Secret key for signing webhook payloads', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='active', help_text='Current status of the webhook endpoint', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Whether to verify SSL certificates'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='date',
            field=models.DateField(help_text='Date for these event statistics', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Delivered Count'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='event_type',
            field=models.CharField(help_text='Type of event tracked', max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Failed Count'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='fired_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fired Count'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookeventstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='field_path',
            field=models.CharField(help_text='JSON field path to filter (e.g., "user.email", "amount")', max_length=255, verbose_name='Field Path'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('in', 'In'), ('not_in', 'Not In'), ('exists', 'Exists'), ('not_exists', 'Not Exists')], default='equals', max_length=20, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookfilter',
            name='value',
            field=models.JSONField(help_text='Filter value (supports strings, numbers, arrays)', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Checked At'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='error',
            field=models.TextField(blank=True, default='', verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='is_healthy',
            field=models.BooleanField(default=True, verbose_name='Is Healthy'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Response Time (ms)'),
        ),
        migrations.AlterField(
            model_name='webhookhealthlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(599)], verbose_name='Status Code'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='current_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Count'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='max_requests',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum requests allowed in the time window', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Requests'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='reset_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the counter will reset', verbose_name='Reset At'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookratelimit',
            name='window_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='Time window for rate limiting in seconds', validators=[django.core.validators.MinValueValidator(60)], verbose_name='Window Seconds'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='new_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_source', to='webhooks.webhookdeliverylog', verbose_name='New Log'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='original_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='webhooks.webhookdeliverylog', verbose_name='Original Log'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='reason',
            field=models.TextField(help_text='Reason for replay (debug, error recovery, etc.)', verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='replayed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Replayed At'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='replayed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Replayed By'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webhookreplay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='count',
            field=models.PositiveIntegerField(help_text='Number of events replayed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='date_from',
            field=models.DateField(help_text='Start date for event replay', verbose_name='Date From'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='date_to',
            field=models.DateField(help_text='End date for event replay', verbose_name='Date To'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='event_type',
            field=models.CharField(help_text='Type of events to replay', max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webhookreplaybatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webhooks.webhookreplaybatch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='new_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_batch_new_logs', to='webhooks.webhookdeliverylog', verbose_name='New Log'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='original_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_batch_items', to='webhooks.webhookdeliverylog', verbose_name='Original Log'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webhookreplayitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='avg_attempts_before_success',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avg Attempts Before Success'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_analyses', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='exhausted_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times retry limit was exhausted', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Exhausted Count'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='period',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='webhookretryanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='webhooks.webhookendpoint', verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this secret expires (for rotation)', null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='webhooksecret',
            name='secret_hash',
            field=models.CharField(help_text='Hashed version of the webhook secret', max_length=255, verbose_name='Secret Hash'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='endpoint',
            field=models.ForeignKey(help_text='Webhook endpoint to send events to', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='webhooks.webhookendpoint'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_type',
            field=models.CharField(help_text='Event type to subscribe to', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this subscription is active'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='event_type',
            field=models.CharField(help_text='Event type this template applies to', max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='payload_template',
            field=models.TextField(help_text='Jinja2 template for payload transformation', verbose_name='Payload Template'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='transform_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSON transformation rules applied before template', verbose_name='Transform Rules'),
        ),
        migrations.AlterField(
            model_name='webhooktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhook',
            index=models.Index(fields=['created_at'], name='iw_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookerror',
            index=models.Index(fields=['error_type'], name='iwe_error_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookerror',
            index=models.Index(fields=['created_at'], name='iwe_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['inbound', 'created_at'], name='iwl_inbound_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['signature_valid'], name='iwl_signature_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhooklog',
            index=models.Index(fields=['processed'], name='iwl_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookroute',
            index=models.Index(fields=['priority'], name='iwr_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookroute',
            index=models.Index(fields=['event_pattern'], name='iwr_event_pattern_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookanalytics',
            index=models.Index(fields=['date', 'endpoint'], name='wa_date_endpoint_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookbatch',
            index=models.Index(fields=['created_at'], name='wb_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['event_type'], name='idx_event_type_1912'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['status'], name='idx_status_1913'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['dispatched_at'], name='idx_dispatched_at_1914'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['next_retry_at'], name='idx_next_retry_at_1915'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['status'], name='idx_status_1906'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['created_at'], name='idx_created_at_1907'),
        ),
        migrations.AddIndex(
            model_name='webhookeventstat',
            index=models.Index(fields=['date', 'event_type'], name='wes_date_event_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventstat',
            index=models.Index(fields=['event_type'], name='wes_event_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookfilter',
            index=models.Index(fields=['field_path'], name='wf_field_path_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookhealthlog',
            index=models.Index(fields=['checked_at'], name='whl_checked_at_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookhealthlog',
            index=models.Index(fields=['is_healthy'], name='whl_healthy_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookratelimit',
            index=models.Index(fields=['reset_at'], name='wrl_reset_at_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplay',
            index=models.Index(fields=['replayed_by', 'replayed_at'], name='wr_replayed_by_at_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplaybatch',
            index=models.Index(fields=['created_by', 'status'], name='wrb_created_by_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplaybatch',
            index=models.Index(fields=['event_type'], name='wrb_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreplayitem',
            index=models.Index(fields=['new_log'], name='wri_new_log_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['endpoint', 'is_active'], name='idx_endpoint_is_active_1908'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['event_type'], name='idx_event_type_1909'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['is_active'], name='idx_is_active_1910'),
        ),
        migrations.AddIndex(
            model_name='webhooktemplate',
            index=models.Index(fields=['name'], name='wt_name_idx'),
        ),
        migrations.AlterModelTable(
            name='webhookdeliverylog',
            table='webhook_delivery_logs',
        ),
        migrations.AlterModelTable(
            name='webhookendpoint',
            table='webhook_endpoints',
        ),
        migrations.AlterModelTable(
            name='webhooksubscription',
            table='webhook_subscriptions',
        ),
        migrations.RemoveField(
            model_name='webhookanalytics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookbatchitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='webhookbatchitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='webhookeventstat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webhookreplayitem',
            name='replay',
        ),
        migrations.RemoveField(
            model_name='webhookretryanalysis',
            name='created_by',
        ),
    ]
