# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, default='GET', max_length=10, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('exceeded', 'Exceeded')], max_length=10, null=True)),
                ('requests_count', models.IntegerField(default=1)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('suspicion_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRateLimitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('custom_daily_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('custom_hourly_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_usage', models.IntegerField(default=0)),
                ('daily_usage', models.IntegerField(default=0)),
                ('hourly_usage', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('blocked_requests', models.IntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('api_health_score', models.IntegerField(default=100)),
                ('endpoint_health', models.JSONField(blank=True, default=dict)),
                ('suspicion_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('rate_limit_type', models.CharField(blank=True, choices=[('user', 'User-based'), ('ip', 'IP-based'), ('endpoint', 'Endpoint-based'), ('global', 'Global'), ('referral', 'Referral-based'), ('task', 'Task-based')], max_length=20, null=True)),
                ('requests_per_unit', models.IntegerField(default=100)),
                ('time_unit', models.CharField(blank=True, choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], default='hour', max_length=10, null=True)),
                ('time_value', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('task_type', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_wall', models.CharField(blank=True, max_length=100, null=True)),
                ('whitelist', models.JSONField(blank=True, default=list)),
                ('blacklist', models.JSONField(blank=True, default=list)),
                ('bypass_keys', models.JSONField(blank=True, default=list)),
                ('hit_count', models.IntegerField(default=0)),
                ('block_count', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
