# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_limit', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimitconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate_limit.ratelimitconfig'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userratelimitprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userratelimitprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_userratelimitprofile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratelimitconfig',
            index=models.Index(fields=['rate_limit_type', 'is_active'], name='rate_limit__rate_li_3ca09f_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitconfig',
            index=models.Index(fields=['endpoint'], name='rate_limit__endpoin_f1ece4_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitconfig',
            index=models.Index(fields=['ip_address'], name='rate_limit__ip_addr_f27084_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['timestamp'], name='rate_limit__timesta_73354e_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['user', 'status'], name='rate_limit__user_id_5f19a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='rate_limit__ip_addr_78f2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['endpoint', 'timestamp'], name='rate_limit__endpoin_5632f4_idx'),
        ),
    ]
