# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_limit', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimitconfig',
            new_name='idx_rate_limit_type_is_active_1660',
            old_name='rate_limit__rate_li_3ca09f_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitconfig',
            new_name='idx_endpoint_1661',
            old_name='rate_limit__endpoin_f1ece4_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitconfig',
            new_name='idx_ip_address_1662',
            old_name='rate_limit__ip_addr_f27084_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitlog',
            new_name='idx_timestamp_1663',
            old_name='rate_limit__timesta_73354e_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitlog',
            new_name='idx_user_status_1664',
            old_name='rate_limit__user_id_5f19a5_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitlog',
            new_name='idx_ip_address_timestamp_1665',
            old_name='rate_limit__ip_addr_78f2cf_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitlog',
            new_name='idx_endpoint_timestamp_1666',
            old_name='rate_limit__endpoin_5632f4_idx',
        ),
    ]
