# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_limit', '0003_rename_rate_limit__rate_li_3ca09f_idx_idx_rate_limit_type_is_active_1660_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimitconfig',
            new_name='idx_rate_limit_type_is_act_c12',
            old_name='idx_rate_limit_type_is_active_1660',
        ),
    ]
