# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_url', models.URLField(max_length=2048, verbose_name='Page URL')),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='Duration (seconds)')),
                ('is_active_time', models.BooleanField(default=True, help_text='False when the tab was hidden/backgrounded for most of the duration.', verbose_name='Is Active Time?')),
                ('scroll_depth_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Scroll Depth (%)')),
            ],
            options={
                'verbose_name': 'Stay Time',
                'verbose_name_plural': 'Stay Times',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, help_text='Frontend-generated session identifier (UUID v4 recommended).', max_length=128, verbose_name='Session ID')),
                ('nodes', models.JSONField(default=list, help_text='Ordered list of navigation node objects.', verbose_name='Path Nodes')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='Device Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('bounced', 'Bounced'), ('expired', 'Expired')], db_index=True, default='active', max_length=16, verbose_name='Session Status')),
                ('entry_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='Entry URL')),
                ('exit_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='Exit URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'User Path',
                'verbose_name_plural': 'User Paths',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClickMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_url', models.URLField(help_text='The page where the click occurred.', max_length=2048, verbose_name='Page URL')),
                ('element_selector', models.CharField(blank=True, default='', help_text='CSS selector of the clicked element.', max_length=512, verbose_name='CSS Selector')),
                ('element_text', models.CharField(blank=True, default='', max_length=256, verbose_name='Element Text')),
                ('category', models.CharField(choices=[('navigation', 'Navigation'), ('cta', 'Call-to-Action'), ('link', 'Hyperlink'), ('button', 'Button'), ('form', 'Form Element'), ('media', 'Media Control'), ('other', 'Other')], db_index=True, default='other', max_length=16, verbose_name='Click Category')),
                ('x_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='X Position (px)')),
                ('y_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y Position (px)')),
                ('viewport_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(db_index=True, help_text='Client-side timestamp of the click event.', verbose_name='Clicked At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Extra Metadata')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Click Metric',
                'verbose_name_plural': 'Click Metrics',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Engagement Score')),
                ('tier', models.CharField(choices=[('low', 'Low (0–30)'), ('medium', 'Medium (31–60)'), ('high', 'High (61–85)'), ('elite', 'Elite (86–100)')], db_index=True, default='low', max_length=8, verbose_name='Engagement Tier')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
                ('total_stay_sec', models.PositiveIntegerField(default=0, verbose_name='Total Stay (s)')),
                ('path_depth', models.PositiveSmallIntegerField(default=0, verbose_name='Path Depth')),
                ('return_visits', models.PositiveSmallIntegerField(default=0, verbose_name='Return Visits')),
                ('breakdown_json', models.JSONField(blank=True, default=dict, help_text='Per-component weighted contribution to the final score.', verbose_name='Score Breakdown')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Engagement Score',
                'verbose_name_plural': 'Engagement Scores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
