# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior_analytics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_scores', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='staytime',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userpath',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_paths', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='staytime',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_times', to='behavior_analytics.userpath', verbose_name='User Path'),
        ),
        migrations.AddField(
            model_name='clickmetric',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_metrics', to='behavior_analytics.userpath', verbose_name='User Path'),
        ),
        migrations.AddIndex(
            model_name='engagementscore',
            index=models.Index(fields=['user', 'date'], name='behavior_an_user_id_b369f7_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementscore',
            index=models.Index(fields=['tier', 'date'], name='behavior_an_tier_79c55b_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementscore',
            index=models.Index(fields=['score'], name='behavior_an_score_123291_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagementscore',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_engagement'),
        ),
        migrations.AddIndex(
            model_name='userpath',
            index=models.Index(fields=['user', 'session_id'], name='behavior_an_user_id_99e1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userpath',
            index=models.Index(fields=['status', 'created_at'], name='behavior_an_status_b3982d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpath',
            index=models.Index(fields=['device_type'], name='behavior_an_device__3b1f31_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpath',
            constraint=models.UniqueConstraint(fields=('user', 'session_id'), name='unique_user_session_path'),
        ),
        migrations.AddIndex(
            model_name='staytime',
            index=models.Index(fields=['path', 'created_at'], name='behavior_an_path_id_66eeb0_idx'),
        ),
        migrations.AddIndex(
            model_name='staytime',
            index=models.Index(fields=['page_url'], name='behavior_an_page_ur_4abf46_idx'),
        ),
        migrations.AddIndex(
            model_name='staytime',
            index=models.Index(fields=['duration_seconds'], name='behavior_an_duratio_dbc121_idx'),
        ),
        migrations.AddIndex(
            model_name='clickmetric',
            index=models.Index(fields=['path', 'clicked_at'], name='behavior_an_path_id_e4042a_idx'),
        ),
        migrations.AddIndex(
            model_name='clickmetric',
            index=models.Index(fields=['category', 'clicked_at'], name='behavior_an_categor_2a3b63_idx'),
        ),
        migrations.AddIndex(
            model_name='clickmetric',
            index=models.Index(fields=['page_url'], name='behavior_an_page_ur_82957a_idx'),
        ),
    ]
