# Generated by Django 5.0.11 on 2026-03-07 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='behavior_an_path_id_e4042a_idx',
            old_name='ba_cm_path_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='behavior_an_categor_2a3b63_idx',
            old_name='ba_cm_cat_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='behavior_an_page_ur_82957a_idx',
            old_name='ba_cm_url_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='behavior_an_user_id_b369f7_idx',
            old_name='ba_es_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='behavior_an_tier_79c55b_idx',
            old_name='ba_es_tier_date_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='behavior_an_score_123291_idx',
            old_name='ba_es_score_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='behavior_an_path_id_66eeb0_idx',
            old_name='ba_st_path_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='behavior_an_page_ur_4abf46_idx',
            old_name='ba_st_url_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='behavior_an_duratio_dbc121_idx',
            old_name='ba_st_dur_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='behavior_an_user_id_99e1fc_idx',
            old_name='ba_up_user_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='behavior_an_status_b3982d_idx',
            old_name='ba_up_status_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='behavior_an_device__3b1f31_idx',
            old_name='ba_up_device_idx',
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='clicked_at',
            field=models.DateTimeField(db_index=True, help_text='Client-side timestamp of the click event.', verbose_name='Clicked At'),
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='element_selector',
            field=models.CharField(blank=True, default='', help_text='CSS selector of the clicked element.', max_length=512, verbose_name='CSS Selector'),
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra Metadata'),
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='page_url',
            field=models.URLField(help_text='The page where the click occurred.', max_length=2048, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='x_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='X Position (px)'),
        ),
        migrations.AlterField(
            model_name='clickmetric',
            name='y_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Y Position (px)'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='breakdown_json',
            field=models.JSONField(blank=True, default=dict, help_text='Per-component weighted contribution to the final score.', verbose_name='Score Breakdown'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Click Count'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='path_depth',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Path Depth'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='return_visits',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Return Visits'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='tier',
            field=models.CharField(choices=[('low', 'Low (0–30)'), ('medium', 'Medium (31–60)'), ('high', 'High (61–85)'), ('elite', 'Elite (86–100)')], db_index=True, default='low', max_length=8, verbose_name='Engagement Tier'),
        ),
        migrations.AlterField(
            model_name='engagementscore',
            name='total_stay_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Stay (s)'),
        ),
        migrations.AlterField(
            model_name='staytime',
            name='is_active_time',
            field=models.BooleanField(default=True, help_text='False when the tab was hidden/backgrounded for most of the duration.', verbose_name='Is Active Time?'),
        ),
        migrations.AlterField(
            model_name='staytime',
            name='scroll_depth_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Scroll Depth (%)'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='entry_url',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='Entry URL'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='exit_url',
            field=models.URLField(blank=True, default='', max_length=2048, verbose_name='Exit URL'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='nodes',
            field=models.JSONField(default=list, help_text='Ordered list of navigation node objects.', verbose_name='Path Nodes'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='session_id',
            field=models.CharField(db_index=True, help_text='Frontend-generated session identifier (UUID v4 recommended).', max_length=128, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User Agent'),
        ),
    ]
