# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analytics', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='idx_path_clicked_at_876',
            old_name='behavior_an_path_id_e4042a_idx',
        ),
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='idx_category_clicked_at_877',
            old_name='behavior_an_categor_2a3b63_idx',
        ),
        migrations.RenameIndex(
            model_name='clickmetric',
            new_name='idx_page_url_878',
            old_name='behavior_an_page_ur_82957a_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='idx_user_date_882',
            old_name='behavior_an_user_id_b369f7_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='idx_tier_date_883',
            old_name='behavior_an_tier_79c55b_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementscore',
            new_name='idx_score_884',
            old_name='behavior_an_score_123291_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='idx_path_created_at_879',
            old_name='behavior_an_path_id_66eeb0_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='idx_page_url_880',
            old_name='behavior_an_page_ur_4abf46_idx',
        ),
        migrations.RenameIndex(
            model_name='staytime',
            new_name='idx_duration_seconds_881',
            old_name='behavior_an_duratio_dbc121_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='idx_user_session_id_873',
            old_name='behavior_an_user_id_99e1fc_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='idx_status_created_at_874',
            old_name='behavior_an_status_b3982d_idx',
        ),
        migrations.RenameIndex(
            model_name='userpath',
            new_name='idx_device_type_875',
            old_name='behavior_an_device__3b1f31_idx',
        ),
    ]
