# Generated by Django 5.0.11 on 2026-03-07 05:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Batch Name')),
                ('gateway', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('BANK', 'Bank Transfer'), ('MANUAL', 'Manual')], db_index=True, max_length=10, verbose_name='Payment Gateway')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', max_length=25, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=10, verbose_name='Priority')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount (BDT)')),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Fee (BDT)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Net Amount (BDT)')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='Item Count')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success Count')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Failure Count')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when processing begins. Cleared on completion or failure.', null=True, verbose_name='Locked At')),
                ('locked_by', models.CharField(blank=True, default='', help_text='Worker ID or task ID holding the processing lock.', max_length=255, verbose_name='Locked By')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('note', models.TextField(blank=True, default='', max_length=2000, verbose_name='Note')),
                ('error_summary', models.TextField(blank=True, default='', max_length=4096, verbose_name='Error Summary')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Payout Batch',
                'verbose_name_plural': 'Payout Batches',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkProcessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], db_index=True, max_length=10, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', help_text='Celery task UUID for log correlation.', max_length=255, verbose_name='Task ID')),
                ('items_attempted', models.PositiveIntegerField(default=0, verbose_name='Items Attempted')),
                ('items_succeeded', models.PositiveIntegerField(default=0, verbose_name='Items Succeeded')),
                ('items_failed', models.PositiveIntegerField(default=0, verbose_name='Items Failed')),
                ('items_skipped', models.PositiveIntegerField(default=0, verbose_name='Items Skipped')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount Processed (BDT)')),
                ('error_summary', models.TextField(blank=True, default='', max_length=4096, verbose_name='Error Summary')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Arbitrary audit data (gateway responses, retry counts, etc.).', verbose_name='Extra Data')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_process_logs', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_logs', to='payout_queue.payoutbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Bulk Process Log',
                'verbose_name_plural': 'Bulk Process Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=15, verbose_name='Status')),
                ('gateway', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('BANK', 'Bank Transfer'), ('MANUAL', 'Manual')], db_index=True, max_length=10, verbose_name='Gateway')),
                ('account_number', models.CharField(help_text='Mobile wallet number or bank account number.', max_length=50, verbose_name='Recipient Account Number')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gross Amount (BDT)')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fee Amount (BDT)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Net Amount (BDT)')),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', help_text='Transaction ID returned by the payment gateway.', max_length=255, verbose_name='Gateway Reference')),
                ('internal_reference', models.CharField(blank=True, db_index=True, default='', help_text='Unique idempotency key for this payout item.', max_length=255, unique=True, verbose_name='Internal Reference')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Retry Count')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next Retry At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, default='', max_length=4096, verbose_name='Error Message')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
                ('note', models.TextField(blank=True, default='', max_length=2000, verbose_name='Note')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payout_queue.payoutbatch', verbose_name='Batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payout Item',
                'verbose_name_plural': 'Payout Items',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, max_length=10, verbose_name='Priority')),
                ('previous_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='', max_length=10, verbose_name='Previous Priority')),
                ('reason', models.CharField(choices=[('USER_REQUEST', 'User Request'), ('SLA_BREACH', 'SLA Breach'), ('VIP_USER', 'VIP User'), ('ADMIN_OVERRIDE', 'Admin Override'), ('SYSTEM', 'System')], max_length=20, verbose_name='Reason')),
                ('reason_note', models.TextField(blank=True, default='', max_length=2000, verbose_name='Reason Note')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, this priority override expires at this time.', null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_withdrawal_priorities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('payout_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_records', to='payout_queue.payoutitem', verbose_name='Payout Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_priorities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal Priority',
                'verbose_name_plural': 'Withdrawal Priorities',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['status', 'priority', 'scheduled_at'], name='pq_pb_status_pri_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['gateway', 'status'], name='pq_pb_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['created_by', 'status'], name='pq_pb_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['locked_at'], name='pq_pb_locked_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatch',
            constraint=models.CheckConstraint(check=models.Q(('total_fee__lte', models.F('total_amount')), ('total_amount', Decimal('0')), _connector='OR'), name='pq_pb_fee_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatch',
            constraint=models.CheckConstraint(check=models.Q(('success_count__lte', models.F('item_count'))), name='pq_pb_success_lte_items'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatch',
            constraint=models.CheckConstraint(check=models.Q(('failure_count__lte', models.F('item_count'))), name='pq_pb_failure_lte_items'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatch',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0'))), name='pq_pb_non_negative_total'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['batch', 'created_at'], name='pq_bpl_batch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['status', 'created_at'], name='pq_bpl_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['task_id'], name='pq_bpl_task_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkprocesslog',
            constraint=models.CheckConstraint(check=models.Q(('items_succeeded__lte', models.F('items_attempted'))), name='pq_bpl_succeeded_lte_attempted'),
        ),
        migrations.AddConstraint(
            model_name='bulkprocesslog',
            constraint=models.CheckConstraint(check=models.Q(('items_failed__lte', models.F('items_attempted'))), name='pq_bpl_failed_lte_attempted'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['batch', 'status'], name='pq_pi_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['user', 'status', 'created_at'], name='pq_pi_user_status_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['gateway', 'status'], name='pq_pi_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['next_retry_at', 'status'], name='pq_pi_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['gateway_reference'], name='pq_pi_gw_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(check=models.Q(('fee_amount__lte', models.F('gross_amount'))), name='pq_pi_fee_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(check=models.Q(('gross_amount__gt', Decimal('0'))), name='pq_pi_positive_gross'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', Decimal('0'))), name='pq_pi_non_negative_net'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(check=models.Q(('retry_count__lte', 3)), name='pq_pi_max_retries'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['user', 'is_active', 'priority'], name='pq_wp_user_active_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['payout_item', 'is_active'], name='pq_wp_item_active_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['expires_at', 'is_active'], name='pq_wp_exp_active_idx'),
        ),
    ]
