# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payout_queue', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkprocesslog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_process_logs', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By'),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bulkprocesslog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_logs', to='payout_queue.payoutbatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payout_queue.payoutbatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='withdrawalpriority',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_withdrawal_priorities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='withdrawalpriority',
            name='payout_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_records', to='payout_queue.payoutitem', verbose_name='Payout Item'),
        ),
        migrations.AddField(
            model_name='withdrawalpriority',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='withdrawalpriority',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_priorities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['status', 'priority', 'scheduled_at'], name='pq_pb_status_pri_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['gateway', 'status'], name='pq_pb_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['created_by', 'status'], name='pq_pb_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['locked_at'], name='pq_pb_locked_at_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['batch', 'created_at'], name='pq_bpl_batch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['status', 'created_at'], name='pq_bpl_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkprocesslog',
            index=models.Index(fields=['task_id'], name='pq_bpl_task_id_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['batch', 'status'], name='pq_pi_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['user', 'status', 'created_at'], name='pq_pi_user_status_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['gateway', 'status'], name='pq_pi_gateway_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['next_retry_at', 'status'], name='pq_pi_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['gateway_reference'], name='pq_pi_gw_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['user', 'is_active', 'priority'], name='pq_wp_user_active_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['payout_item', 'is_active'], name='pq_wp_item_active_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalpriority',
            index=models.Index(fields=['expires_at', 'is_active'], name='pq_wp_exp_active_idx'),
        ),
    ]
