# Generated by Django 5.0.11 on 2026-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payout_queue', '0002_bulkprocesslog_tenant_payoutbatch_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bulkprocesslog',
            name='pq_bpl_succeeded_lte_attempted',
        ),
        migrations.RemoveConstraint(
            model_name='bulkprocesslog',
            name='pq_bpl_failed_lte_attempted',
        ),
        migrations.RemoveConstraint(
            model_name='payoutbatch',
            name='pq_pb_fee_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='payoutbatch',
            name='pq_pb_success_lte_items',
        ),
        migrations.RemoveConstraint(
            model_name='payoutbatch',
            name='pq_pb_failure_lte_items',
        ),
        migrations.RemoveConstraint(
            model_name='payoutbatch',
            name='pq_pb_non_negative_total',
        ),
        migrations.RemoveConstraint(
            model_name='payoutitem',
            name='pq_pi_fee_lte_gross',
        ),
        migrations.RemoveConstraint(
            model_name='payoutitem',
            name='pq_pi_positive_gross',
        ),
        migrations.RemoveConstraint(
            model_name='payoutitem',
            name='pq_pi_non_negative_net',
        ),
        migrations.RemoveConstraint(
            model_name='payoutitem',
            name='pq_pi_max_retries',
        ),
    ]
