# Generated by Django 5.0.11 on 2026-03-07 05:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(blank=True, default='', help_text='Optional name for group chats. Leave blank for direct messages.', max_length=255, verbose_name='Chat Name')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is Group Chat')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Updated whenever a new message is sent. Used for inbox ordering.', null=True, verbose_name='Last Message At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Internal Chat',
                'verbose_name_plural': 'Internal Chats',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='MEMBER', max_length=10, verbose_name='Role')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Timestamp of last message the user has seen in this chat.', null=True, verbose_name='Last Read At')),
                ('is_muted', models.BooleanField(default=False, help_text='User will not receive push notifications for this chat.', verbose_name='Is Muted')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined At')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.internalchat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.TextField(blank=True, default='', max_length=10000, verbose_name='Content')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('SYSTEM', 'System')], db_index=True, default='TEXT', max_length=10, verbose_name='Message Type')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], db_index=True, default='SENT', max_length=10, verbose_name='Status')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment dicts: {url, filename, mimetype, size_bytes}.', verbose_name='Attachments')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.chatmessage', verbose_name='Reply To')),
                ('sender', models.ForeignKey(blank=True, help_text='NULL for SYSTEM messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.internalchat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10, verbose_name='Priority')),
                ('last_reply_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Reply At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('agent_note', models.TextField(blank=True, default='', help_text='Internal note visible only to support agents.', max_length=5000, verbose_name='Agent Note')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Support Thread',
                'verbose_name_plural': 'Support Threads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.TextField(max_length=10000, verbose_name='Content')),
                ('is_agent_reply', models.BooleanField(db_index=True, default=False, help_text='True if sent by a support agent, False if by the user.', verbose_name='Is Agent Reply')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('is_internal_note', models.BooleanField(default=False, help_text='Internal notes are visible only to agents.', verbose_name='Is Internal Note')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.supportthread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item_type', models.CharField(choices=[('CHAT_MESSAGE', 'Chat Message'), ('BROADCAST', 'Broadcast'), ('SUPPORT_REPLY', 'Support Reply'), ('SYSTEM', 'System Notification')], db_index=True, max_length=20, verbose_name='Item Type')),
                ('source_id', models.UUIDField(blank=True, db_index=True, help_text='PK of the source object (ChatMessage, AdminBroadcast, or SupportMessage).', null=True, verbose_name='Source ID')),
                ('title', models.CharField(blank=True, default='', help_text='Denormalized title shown in the inbox list.', max_length=255, verbose_name='Title')),
                ('preview', models.CharField(blank=True, default='', help_text='Short content preview.', max_length=200, verbose_name='Preview')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Is Archived')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Inbox Item',
                'verbose_name_plural': 'User Inbox Items',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(help_text='Markdown or plain text body of the broadcast.', max_length=50000, verbose_name='Body')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15, verbose_name='Status')),
                ('audience_type', models.CharField(choices=[('ALL_USERS', 'All Users'), ('ACTIVE_USERS', 'Active Users'), ('SPECIFIC_USERS', 'Specific Users'), ('USER_GROUP', 'User Group')], default='ALL_USERS', max_length=20, verbose_name='Audience Type')),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text='Optional filter criteria for ACTIVE_USERS or USER_GROUP audience types.', verbose_name='Audience Filter')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, the broadcast will be sent at this UTC datetime.', null=True, verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Snapshot of delivery target count at send time.', verbose_name='Recipient Count')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Delivered Count')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Admin Broadcast',
                'verbose_name_plural': 'Admin Broadcasts',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='msg_ab_status_sched_idx'), models.Index(fields=['created_by', 'status'], name='msg_ab_creator_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='adminbroadcast',
            constraint=models.CheckConstraint(check=models.Q(('delivered_count__lte', models.F('recipient_count')), ('recipient_count', 0), _connector='OR'), name='msg_ab_delivered_lte_rcpt'),
        ),
        migrations.AddIndex(
            model_name='internalchat',
            index=models.Index(fields=['status', 'last_message_at'], name='msg_ic_status_lma_idx'),
        ),
        migrations.AddIndex(
            model_name='internalchat',
            index=models.Index(fields=['created_by', 'status'], name='msg_ic_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'chat'], name='msg_cp_user_chat_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='msg_cp_unique_chat_user'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='msg_cm_chat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='msg_cm_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status', 'created_at'], name='msg_cm_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('message_type', 'TEXT'), _negated=True), ('content__gt', ''), _connector='OR'), name='msg_cm_text_needs_content'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['user', 'status'], name='msg_st_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', 'priority'], name='msg_st_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['assigned_agent', 'status'], name='msg_st_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['last_reply_at'], name='msg_st_last_reply_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='msg_sm_thread_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='msg_ui_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['user', 'item_type', 'created_at'], name='msg_ui_user_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['source_id', 'item_type'], name='msg_ui_source_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinbox',
            constraint=models.CheckConstraint(check=models.Q(('is_read', False), ('read_at__isnull', False), _connector='OR'), name='msg_ui_read_needs_read_at'),
        ),
    ]
