# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbroadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='adminbroadcast',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='affiliateconversationthread',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_threads', to=settings.AUTH_USER_MODEL, verbose_name='Affiliate'),
        ),
        migrations.AddField(
            model_name='affiliateconversationthread',
            name='last_message_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_sent_in_threads', to=settings.AUTH_USER_MODEL, verbose_name='Last Message By'),
        ),
        migrations.AddField(
            model_name='affiliateconversationthread',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_threads', to=settings.AUTH_USER_MODEL, verbose_name='Account Manager'),
        ),
        migrations.AddField(
            model_name='affiliateconversationthread',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='announcementchannel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_channels', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='announcementchannel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bots', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='botresponse',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='messaging.botconfig', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='botresponse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL, verbose_name='Caller'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='call_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.announcementchannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chatmention',
            name='mentioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Mentioned By'),
        ),
        migrations.AddField(
            model_name='chatmention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Mentioned User'),
        ),
        migrations.AddField(
            model_name='chatmention',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_instances', to='messaging.chatmessage', verbose_name='Forwarded From'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.chatmessage', verbose_name='Reply To'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chatmention',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_records', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='botresponse',
            name='sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_sent_response', to='messaging.chatmessage', verbose_name='Sent Message'),
        ),
        migrations.AddField(
            model_name='botresponse',
            name='trigger_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_trigger_responses', to='messaging.chatmessage', verbose_name='Trigger Message'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cpabroadcast',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpa_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cpabroadcast',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cpanotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpa_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='cpanotification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='disappearingmessageconfig',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disappearing_configs_set', to=settings.AUTH_USER_MODEL, verbose_name='Enabled By'),
        ),
        migrations.AddField(
            model_name='disappearingmessageconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='internalchat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalchat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='disappearingmessageconfig',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disappearing_config', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='chatmention',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='messaging.internalchat', verbose_name='Related Chat'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='chat',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global bot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='affiliateconversationthread',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_thread', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_records', to='messaging.chatmessage', verbose_name='Associated Message'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='messageedithistory',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_edits', to=settings.AUTH_USER_MODEL, verbose_name='Edited By'),
        ),
        migrations.AddField(
            model_name='messageedithistory',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messageedithistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagelinkpreview',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_previews', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagelinkpreview',
            name='preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='messaging.linkpreview', verbose_name='Link Preview'),
        ),
        migrations.AddField(
            model_name='messagelinkpreview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='pinned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Pinned By'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.chatmessage', verbose_name='Reported Message'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagesearchindex',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='messagesearchindex',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagesearchindex',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cpabroadcast',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='messaging.messagetemplate', verbose_name='Template Used'),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagingwebhook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='messagingwebhook',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.cpabroadcast', verbose_name='Broadcast'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='messaging.chatmessage', verbose_name='Poll Message'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='Voter'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='messaging.internalchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_scheduled_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_origin', to='messaging.chatmessage', verbose_name='Sent Message'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='storyhighlight',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='storyhighlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_highlights', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL, verbose_name='Viewer'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Agent'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.supportthread', verbose_name='Thread'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Blocked User'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='Blocker'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userinbox',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userinbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='messaging.userstory', verbose_name='Story'),
        ),
        migrations.AddField(
            model_name='storyhighlight',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='highlights', to='messaging.userstory', verbose_name='Stories'),
        ),
        migrations.AddField(
            model_name='voicemessagetranscription',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='messaging.chatmessage', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='voicemessagetranscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='messaging.messagingwebhook', verbose_name='Webhook'),
        ),
        migrations.AddIndex(
            model_name='adminbroadcast',
            index=models.Index(fields=['status', 'scheduled_at'], name='msg_ab_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='adminbroadcast',
            index=models.Index(fields=['created_by', 'status'], name='msg_ab_creator_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminbroadcast',
            constraint=models.CheckConstraint(check=models.Q(('delivered_count__lte', models.F('recipient_count')), ('recipient_count', 0), _connector='OR'), name='msg_ab_delivered_lte_rcpt'),
        ),
        migrations.AddIndex(
            model_name='announcementchannel',
            index=models.Index(fields=['channel_type', 'subscriber_count'], name='msg_ac_type_subs_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementchannel',
            index=models.Index(fields=['slug'], name='msg_ac_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelmember',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='msg_cm_unique_channel_user'),
        ),
        migrations.AddIndex(
            model_name='cpanotification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='msg_cpan_rcpt_read_idx'),
        ),
        migrations.AddIndex(
            model_name='cpanotification',
            index=models.Index(fields=['recipient', 'notification_type'], name='msg_cpan_rcpt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cpanotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='msg_cpan_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cpanotification',
            index=models.Index(fields=['object_type', 'object_id'], name='msg_cpan_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'platform', 'is_active'], name='msg_dt_user_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='internalchat',
            index=models.Index(fields=['status', 'last_message_at'], name='msg_ic_status_lma_idx'),
        ),
        migrations.AddIndex(
            model_name='internalchat',
            index=models.Index(fields=['created_by', 'status'], name='msg_ic_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'chat'], name='msg_cp_user_chat_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='msg_cp_unique_chat_user'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='msg_cm_chat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='msg_cm_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status', 'created_at'], name='msg_cm_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread_id'], name='msg_cm_thread_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('message_type', 'TEXT'), _negated=True), ('content__gt', ''), _connector='OR'), name='msg_cm_text_needs_content'),
        ),
        migrations.AddIndex(
            model_name='chatmention',
            index=models.Index(fields=['mentioned_user', 'is_read'], name='msg_cm2_user_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmention',
            constraint=models.UniqueConstraint(fields=('message', 'mentioned_user'), name='msg_cm2_unique_msg_user'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', 'created_at'], name='msg_cs_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['initiated_by', 'status'], name='msg_cs_caller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['room_id'], name='msg_cs_room_idx'),
        ),
        migrations.AddIndex(
            model_name='botconfig',
            index=models.Index(fields=['trigger_type', 'is_active'], name='msg_bc_trigger_active_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversationthread',
            index=models.Index(fields=['manager', 'status'], name='msg_act_manager_status_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversationthread',
            index=models.Index(fields=['last_message_at'], name='msg_act_last_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='affiliateconversationthread',
            constraint=models.UniqueConstraint(fields=('affiliate',), name='msg_act_unique_affiliate'),
        ),
        migrations.AddIndex(
            model_name='linkpreview',
            index=models.Index(fields=['domain'], name='msg_lp_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['uploaded_by', 'status'], name='msg_ma_uploader_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['message', 'status'], name='msg_ma_message_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['mimetype', 'status'], name='msg_ma_mime_status_idx'),
        ),
        migrations.AddIndex(
            model_name='messageedithistory',
            index=models.Index(fields=['message', 'created_at'], name='msg_meh_msg_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagelinkpreview',
            constraint=models.UniqueConstraint(fields=('message', 'preview'), name='msg_mlp_unique_msg_preview'),
        ),
        migrations.AddConstraint(
            model_name='messagepin',
            constraint=models.UniqueConstraint(fields=('chat', 'message'), name='msg_mp_unique_chat_message'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='msg_mr_msg_emoji_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='msg_mr_unique_message_user_emoji'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', 'created_at'], name='msg_mrpt_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['reason', 'status'], name='msg_mrpt_reason_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('message', 'reported_by'), name='msg_mr2_unique_msg_reporter'),
        ),
        migrations.AddIndex(
            model_name='messagesearchindex',
            index=models.Index(fields=['chat', 'indexed_at'], name='msg_msi_chat_indexed_idx'),
        ),
        migrations.AddIndex(
            model_name='cpabroadcast',
            index=models.Index(fields=['status', 'scheduled_at'], name='msg_cpab_status_sched_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagetranslation',
            constraint=models.UniqueConstraint(fields=('message', 'target_language'), name='msg_mt_unique_msg_lang'),
        ),
        migrations.AddIndex(
            model_name='messagingwebhook',
            index=models.Index(fields=['is_active', 'created_at'], name='msg_wh_active_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('broadcast', 'user'), name='msg_nr_unique_broadcast_user'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'option_id'), name='msg_pv_unique_msg_user_opt'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='msg_schm_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['sender', 'status'], name='msg_schm_sender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['user', 'status'], name='msg_st_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', 'priority'], name='msg_st_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['assigned_agent', 'status'], name='msg_st_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['last_reply_at'], name='msg_st_last_reply_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='msg_sm_thread_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='msg_ub_unique_blocker_blocked'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='msg_ud_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['last_active_at'], name='msg_ud_last_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='msg_ud_unique_user_device'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='msg_ui_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['user', 'item_type', 'created_at'], name='msg_ui_user_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userinbox',
            index=models.Index(fields=['source_id', 'item_type'], name='msg_ui_source_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinbox',
            constraint=models.CheckConstraint(check=models.Q(('is_read', False), ('read_at__isnull', False), _connector='OR'), name='msg_ui_read_needs_read_at'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['status', 'last_seen_at'], name='msg_up_status_lastseen_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='msg_us_user_active_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['expires_at', 'is_active'], name='msg_us_exp_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyview',
            constraint=models.UniqueConstraint(fields=('story', 'viewer'), name='msg_sv_unique_story_viewer'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'is_successful'], name='msg_wd_wh_success_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['next_retry_at', 'is_successful'], name='msg_wd_retry_idx'),
        ),
    ]
