# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
        ('tenants', '0003_planfeature_planquota_planupgrade_planusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatmessage',
            name='msg_cm_text_needs_content',
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(check=models.Q(('message_type', 'TEXT'), ('content__gt', ''), _connector='OR'), name='msg_cm_text_needs_content'),
        ),
    ]
