# Generated by Django 5.0.11 on 2026-04-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_adminbroadcast_tenant_chatmessage_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminbroadcast',
            name='msg_ab_delivered_lte_rcpt',
        ),
        migrations.RemoveConstraint(
            model_name='chatmessage',
            name='msg_cm_text_needs_content',
        ),
        migrations.RemoveConstraint(
            model_name='userinbox',
            name='msg_ui_read_needs_read_at',
        ),
    ]
