# Generated by Django 5.0.11 on 2026-04-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_adminbroadcast_msg_ab_delivered_lte_rcpt_and_more'),
        ('messaging', '0004_all_remaining_models'),
    ]

    operations = [
    ]
