# Generated by Django 5.0.11 on 2026-03-07 02:41

import api.postback.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPostbackConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='network name')),
                ('network_key', models.CharField(db_index=True, help_text='Unique slug used in the postback URL: /api/postback/{network_key}/', max_length=64, unique=True, validators=[api.postback.validators.validate_network_key_format], verbose_name='network key')),
                ('network_type', models.CharField(choices=[('cpa', 'CPA Network'), ('cpl', 'CPL Network'), ('cpi', 'CPI Network'), ('affiliate', 'Affiliate Network'), ('direct', 'Direct Advertiser'), ('internal', 'Internal System')], default='cpa', max_length=20, verbose_name='network type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing Mode')], db_index=True, default='testing', max_length=20, verbose_name='status')),
                ('secret_key', models.CharField(help_text='Shared HMAC secret. Store encrypted at rest.', max_length=512, verbose_name='secret key')),
                ('signature_algorithm', models.CharField(choices=[('hmac_sha256', 'HMAC-SHA256'), ('hmac_sha512', 'HMAC-SHA512'), ('md5', 'MD5 (Legacy)'), ('none', 'No Signature (IP-only)')], default='hmac_sha256', max_length=20, verbose_name='signature algorithm')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses / CIDR ranges. Empty = allow all.', validators=[api.postback.validators.validate_ip_whitelist], verbose_name='IP whitelist')),
                ('trust_forwarded_for', models.BooleanField(default=False, help_text='Only enable if behind a trusted reverse proxy.', verbose_name='trust X-Forwarded-For')),
                ('require_nonce', models.BooleanField(default=True, help_text='Require X-Postback-Nonce header to prevent replay attacks.', verbose_name='require nonce')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Map standard field names to network-specific param names. e.g. {"lead_id": "click_id", "offer_id": "campaign_id"}', validators=[api.postback.validators.validate_field_mapping], verbose_name='field mapping')),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='List of field names that MUST be present in the postback payload.', verbose_name='required fields')),
                ('dedup_window', models.CharField(choices=[('1h', '1 Hour'), ('1d', '1 Day'), ('7d', '7 Days'), ('30d', '30 Days'), ('forever', 'Forever (No Repeat)')], default='forever', max_length=10, verbose_name='deduplication window')),
                ('reward_rules', models.JSONField(blank=True, default=dict, help_text='Per-offer reward configuration. e.g. {"offer_123": {"points": 500, "item_id": "<uuid>"}}', validators=[api.postback.validators.validate_reward_rules], verbose_name='reward rules')),
                ('default_reward_points', models.PositiveIntegerField(default=0, help_text='Points awarded when no specific offer rule matches.', verbose_name='default reward points')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=1000, verbose_name='rate limit (per minute)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'network postback config',
                'verbose_name_plural': 'network postback configs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['network_key', 'status'], name='postback_ne_network_5c51fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadValidator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('validator_type', models.CharField(choices=[('field_present', 'Field Present'), ('field_regex', 'Field Regex Match'), ('payout_range', 'Payout Range'), ('offer_whitelist', 'Offer Whitelist'), ('user_must_exist', 'User Must Exist'), ('ip_reputation', 'IP Reputation Check'), ('custom_expression', 'Custom Expression')], max_length=30, verbose_name='validator type')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Type-specific parameters as a JSON object.', verbose_name='params')),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, a failure rejects the postback. If False, only logs a warning.', verbose_name='is blocking')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('failure_reason', models.CharField(choices=[('invalid_signature', 'Invalid Signature'), ('ip_not_whitelisted', 'IP Not Whitelisted'), ('duplicate_lead', 'Duplicate Lead'), ('missing_fields', 'Missing Required Fields'), ('invalid_offer', 'Invalid Offer ID'), ('fraud_detected', 'Fraud Detected'), ('rate_limited', 'Rate Limited'), ('signature_expired', 'Signature Expired'), ('user_not_found', 'User Not Found'), ('offer_inactive', 'Offer Inactive'), ('payout_limit_exceeded', 'Payout Limit Exceeded'), ('blacklisted', 'Blacklisted Source'), ('schema_validation', 'Schema Validation Error'), ('internal_error', 'Internal Processing Error')], default='schema_validation', max_length=40, verbose_name='failure rejection reason')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_validators', to='postback.networkpostbackconfig', verbose_name='network')),
            ],
            options={
                'verbose_name': 'lead validator',
                'verbose_name_plural': 'lead validators',
                'ordering': ['network', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PostbackLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('validated', 'Validated'), ('rewarded', 'Rewarded'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('pending_review', 'Pending Review')], db_index=True, default='received', max_length=20, verbose_name='status')),
                ('raw_payload', models.JSONField(help_text='Original request payload as received – never modified.', verbose_name='raw payload')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP method')),
                ('query_string', models.TextField(blank=True, verbose_name='query string')),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Sanitised headers – secrets stripped before storage.', verbose_name='request headers')),
                ('lead_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='lead ID')),
                ('offer_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='offer ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='transaction ID')),
                ('payout', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='payout')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='currency')),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='source IP')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='signature verified')),
                ('ip_whitelisted', models.BooleanField(default=False, verbose_name='IP whitelisted')),
                ('rejection_reason', models.CharField(blank=True, choices=[('invalid_signature', 'Invalid Signature'), ('ip_not_whitelisted', 'IP Not Whitelisted'), ('duplicate_lead', 'Duplicate Lead'), ('missing_fields', 'Missing Required Fields'), ('invalid_offer', 'Invalid Offer ID'), ('fraud_detected', 'Fraud Detected'), ('rate_limited', 'Rate Limited'), ('signature_expired', 'Signature Expired'), ('user_not_found', 'User Not Found'), ('offer_inactive', 'Offer Inactive'), ('payout_limit_exceeded', 'Payout Limit Exceeded'), ('blacklisted', 'Blacklisted Source'), ('schema_validation', 'Schema Validation Error'), ('internal_error', 'Internal Processing Error')], max_length=40, verbose_name='rejection reason')),
                ('rejection_detail', models.TextField(blank=True, verbose_name='rejection detail')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='retry count')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next retry at')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='points awarded')),
                ('inventory_id', models.UUIDField(blank=True, db_index=True, help_text='UserInventory UUID if an item was awarded.', null=True, verbose_name='inventory ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postback_logs', to='postback.networkpostbackconfig', verbose_name='network')),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_logs', to=settings.AUTH_USER_MODEL, verbose_name='resolved user')),
            ],
            options={
                'verbose_name': 'postback log',
                'verbose_name_plural': 'postback logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateLeadCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_id', models.CharField(db_index=True, max_length=255, verbose_name='lead ID')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='first seen at')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_checks', to='postback.networkpostbackconfig', verbose_name='network')),
                ('postback_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_check', to='postback.postbacklog', verbose_name='original postback log')),
            ],
            options={
                'verbose_name': 'duplicate lead check',
                'verbose_name_plural': 'duplicate lead checks',
            },
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['network', 'status', 'received_at'], name='postback_po_network_54e228_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['lead_id', 'network'], name='postback_po_lead_id_cab1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['status', 'next_retry_at'], name='postback_po_status_33053b_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['source_ip', 'received_at'], name='postback_po_source__3b6a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicateleadcheck',
            index=models.Index(fields=['network', 'lead_id'], name='postback_du_network_b424e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicateleadcheck',
            unique_together={('network', 'lead_id')},
        ),
    ]
