# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postback', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postbacklog',
            name='resolved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postback_logs', to=settings.AUTH_USER_MODEL, verbose_name='resolved user'),
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='duplicateleadcheck',
            name='postback_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_check', to='postback.postbacklog', verbose_name='original postback log'),
        ),
        migrations.AddIndex(
            model_name='networkpostbackconfig',
            index=models.Index(fields=['network_key', 'status'], name='postback_ne_network_5c51fe_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['network', 'status', 'received_at'], name='postback_po_network_54e228_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['lead_id', 'network'], name='postback_po_lead_id_cab1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['status', 'next_retry_at'], name='postback_po_status_33053b_idx'),
        ),
        migrations.AddIndex(
            model_name='postbacklog',
            index=models.Index(fields=['source_ip', 'received_at'], name='postback_po_source__3b6a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicateleadcheck',
            index=models.Index(fields=['network', 'lead_id'], name='postback_du_network_b424e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicateleadcheck',
            unique_together={('network', 'lead_id')},
        ),
    ]
