# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postback', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='duplicateleadcheck',
            new_name='idx_network_lead_id_1367',
            old_name='postback_du_network_b424e5_idx',
        ),
        migrations.RenameIndex(
            model_name='networkpostbackconfig',
            new_name='idx_network_key_status_1362',
            old_name='postback_ne_network_5c51fe_idx',
        ),
        migrations.RenameIndex(
            model_name='postbacklog',
            new_name='idx_network_status_received_at_1363',
            old_name='postback_po_network_54e228_idx',
        ),
        migrations.RenameIndex(
            model_name='postbacklog',
            new_name='idx_lead_id_network_1364',
            old_name='postback_po_lead_id_cab1a8_idx',
        ),
        migrations.RenameIndex(
            model_name='postbacklog',
            new_name='idx_status_next_retry_at_1365',
            old_name='postback_po_status_33053b_idx',
        ),
        migrations.RenameIndex(
            model_name='postbacklog',
            new_name='idx_source_ip_received_at_1366',
            old_name='postback_po_source__3b6a0a_idx',
        ),
    ]
