# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postback', '0003_rename_postback_du_network_b424e5_idx_idx_network_lead_id_1367_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postbacklog',
            new_name='idx_network_status_receive_127',
            old_name='idx_network_status_received_at_1363',
        ),
    ]
