# Generated by Django 5.0.11 on 2026-03-07 02:41

import api.inventory.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('item_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product'), ('voucher', 'Voucher / Gift Card'), ('experience', 'Experience / Event'), ('subscription', 'Subscription'), ('points', 'Points / Credits'), ('nft', 'NFT / Digital Collectible')], db_index=True, default='digital', max_length=30, verbose_name='item type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30, verbose_name='status')),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points required to redeem this item. 0 = free.', validators=[api.inventory.validators.validate_positive_points_cost], verbose_name='points cost')),
                ('cash_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Real-world monetary value for accounting purposes.', max_digits=10, verbose_name='cash value')),
                ('current_stock', models.IntegerField(db_index=True, default=0, help_text='Use -1 for unlimited stock.', validators=[api.inventory.validators.validate_non_negative_stock], verbose_name='current stock')),
                ('total_redeemed', models.PositiveIntegerField(default=0, verbose_name='total redeemed')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('manual', 'Manual Fulfillment'), ('api', 'API Callback'), ('physical_shipment', 'Physical Shipment')], default='email', max_length=30, verbose_name='delivery method')),
                ('delivery_template', models.TextField(blank=True, help_text='Jinja2 template for email/SMS delivery body.', verbose_name='delivery template')),
                ('delivery_callback_url', models.URLField(blank=True, help_text='For API delivery method: POST to this URL on fulfilment.', verbose_name='delivery callback URL')),
                ('max_per_user', models.PositiveSmallIntegerField(default=1, help_text='Maximum times a single user can redeem this item.', verbose_name='max per user')),
                ('is_transferable', models.BooleanField(default=False, verbose_name='transferable')),
                ('requires_shipping_address', models.BooleanField(default=False, verbose_name='requires shipping address')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='thumbnail URL')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'reward item',
                'verbose_name_plural': 'reward items',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['status', 'item_type'], name='inventory_r_status_01e669_idx'), models.Index(fields=['status', 'current_stock'], name='inventory_r_status_cb69ac_idx'), models.Index(fields=['slug'], name='inventory_r_slug_aebe21_idx')],
            },
        ),
        migrations.CreateModel(
            name='RedemptionCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='code')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('voided', 'Voided'), ('failed', 'Failed Delivery')], db_index=True, default='available', max_length=20, verbose_name='status')),
                ('batch_id', models.CharField(blank=True, db_index=True, help_text='Group identifier for bulk-imported codes.', max_length=100, verbose_name='batch ID')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, validators=[api.inventory.validators.validate_future_expiry_date], verbose_name='expires at')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('reserved_until', models.DateTimeField(blank=True, help_text='Temporary reservation expiry during checkout.', null=True, verbose_name='reserved until')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL, verbose_name='redeemed by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_codes', to='inventory.rewarditem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'redemption code',
                'verbose_name_plural': 'redemption codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('initial', 'Initial Stock'), ('restock', 'Restock'), ('sale', 'Sale / Redemption'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('expired', 'Expired / Written Off'), ('reserved', 'Reserved'), ('released', 'Reservation Released')], db_index=True, max_length=30, verbose_name='event type')),
                ('quantity_delta', models.IntegerField(help_text='Positive = added, negative = removed.', verbose_name='quantity delta')),
                ('stock_before', models.IntegerField(verbose_name='stock before')),
                ('stock_after', models.IntegerField(verbose_name='stock after')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='UserInventory UUID, order ID, or other reference.', max_length=255, verbose_name='reference ID')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_events', to='inventory.rewarditem', verbose_name='item')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_events', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'stock event',
                'verbose_name_plural': 'stock events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=10, validators=[api.inventory.validators.validate_low_stock_threshold], verbose_name='low-stock threshold')),
                ('critical_stock_threshold', models.PositiveSmallIntegerField(default=3, validators=[api.inventory.validators.validate_low_stock_threshold], verbose_name='critical-stock threshold')),
                ('alert_level', models.CharField(choices=[('none', 'No Alert'), ('low', 'Low Stock'), ('critical', 'Critical Stock'), ('depleted', 'Depleted')], db_index=True, default='none', max_length=20, verbose_name='alert level')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='alert sent')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='alert sent at')),
                ('reorder_quantity', models.PositiveIntegerField(default=100, help_text='Suggested restock quantity when low-stock alert fires.', verbose_name='reorder quantity')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_manager', to='inventory.rewarditem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'stock manager',
                'verbose_name_plural': 'stock managers',
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Delivery'), ('delivered', 'Delivered'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('failed', 'Delivery Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('manual', 'Manual Fulfillment'), ('api', 'API Callback'), ('physical_shipment', 'Physical Shipment')], default='email', max_length=30, verbose_name='delivery method')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='claimed at')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='delivery attempts')),
                ('last_delivery_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last delivery attempt at')),
                ('delivery_error', models.TextField(blank=True, verbose_name='delivery error')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next retry at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='revocation reason')),
                ('awarded_by_postback', models.CharField(blank=True, db_index=True, help_text='Postback log ID or campaign reference that triggered this award.', max_length=255, verbose_name='postback reference')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_inventories', to='inventory.rewarditem', verbose_name='item')),
                ('redemption_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inventory', to='inventory.redemptioncode', verbose_name='redemption code')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_inventories', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user inventory',
                'verbose_name_plural': 'user inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['item', 'status'], name='inventory_r_item_id_41d63c_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['code'], name='inventory_r_code_85acb9_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['batch_id'], name='inventory_r_batch_i_7ace3b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['item', 'event_type', 'created_at'], name='inventory_s_item_id_d6a4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'status'], name='inventory_u_user_id_a1b336_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'item'], name='inventory_u_user_id_2edeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['status', 'next_retry_at'], name='inventory_u_status_6fd57b_idx'),
        ),
    ]
