# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncode',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL, verbose_name='redeemed by'),
        ),
        migrations.AddField(
            model_name='redemptioncode',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='redemptioncode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_codes', to='inventory.rewarditem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='stockevent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_events', to='inventory.rewarditem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='stockevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_events', to=settings.AUTH_USER_MODEL, verbose_name='performed by'),
        ),
        migrations.AddField(
            model_name='stockevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockmanager',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_manager', to='inventory.rewarditem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='stockmanager',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_inventories', to='inventory.rewarditem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='redemption_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inventory', to='inventory.redemptioncode', verbose_name='redemption code'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_inventories', to=settings.AUTH_USER_MODEL, verbose_name='revoked by'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='rewarditem',
            index=models.Index(fields=['status', 'item_type'], name='inventory_r_status_01e669_idx'),
        ),
        migrations.AddIndex(
            model_name='rewarditem',
            index=models.Index(fields=['status', 'current_stock'], name='inventory_r_status_cb69ac_idx'),
        ),
        migrations.AddIndex(
            model_name='rewarditem',
            index=models.Index(fields=['slug'], name='inventory_r_slug_aebe21_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['item', 'status'], name='inventory_r_item_id_41d63c_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['code'], name='inventory_r_code_85acb9_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['batch_id'], name='inventory_r_batch_i_7ace3b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockevent',
            index=models.Index(fields=['item', 'event_type', 'created_at'], name='inventory_s_item_id_d6a4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'status'], name='inventory_u_user_id_a1b336_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'item'], name='inventory_u_user_id_2edeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['status', 'next_retry_at'], name='inventory_u_status_6fd57b_idx'),
        ),
    ]
