# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='redemptioncode',
            new_name='idx_item_status_1017',
            old_name='inventory_r_item_id_41d63c_idx',
        ),
        migrations.RenameIndex(
            model_name='redemptioncode',
            new_name='idx_code_1018',
            old_name='inventory_r_code_85acb9_idx',
        ),
        migrations.RenameIndex(
            model_name='redemptioncode',
            new_name='idx_batch_id_1019',
            old_name='inventory_r_batch_i_7ace3b_idx',
        ),
        migrations.RenameIndex(
            model_name='rewarditem',
            new_name='idx_status_item_type_1013',
            old_name='inventory_r_status_01e669_idx',
        ),
        migrations.RenameIndex(
            model_name='rewarditem',
            new_name='idx_status_current_stock_1014',
            old_name='inventory_r_status_cb69ac_idx',
        ),
        migrations.RenameIndex(
            model_name='rewarditem',
            new_name='idx_slug_1015',
            old_name='inventory_r_slug_aebe21_idx',
        ),
        migrations.RenameIndex(
            model_name='stockevent',
            new_name='idx_item_event_type_created_at_1016',
            old_name='inventory_s_item_id_d6a4c5_idx',
        ),
        migrations.RenameIndex(
            model_name='userinventory',
            new_name='idx_user_status_1020',
            old_name='inventory_u_user_id_a1b336_idx',
        ),
        migrations.RenameIndex(
            model_name='userinventory',
            new_name='idx_user_item_1021',
            old_name='inventory_u_user_id_2edeaf_idx',
        ),
        migrations.RenameIndex(
            model_name='userinventory',
            new_name='idx_status_next_retry_at_1022',
            old_name='inventory_u_status_6fd57b_idx',
        ),
    ]
