# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_r_item_id_41d63c_idx_idx_item_status_1017_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockevent',
            new_name='idx_item_event_type_create_629',
            old_name='idx_item_event_type_created_at_1016',
        ),
    ]
