# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy_intelligence', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_api_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_api_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clickfraudrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_fraud_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clickfraudrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_frauds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_device_fingerprints', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_device_fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_resolved_frauds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_fraud_attempts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_fraud_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_fraud_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_integration_credentials', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_blacklisted_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_ip_blacklists', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ipintelligence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_intelligences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_whitelisted_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipwhitelist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_ip_whitelists', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodelmetadata',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='anomalydetectionlog',
            name='detected_by_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_detections', to='proxy_intelligence.mlmodelmetadata'),
        ),
        migrations.AddField(
            model_name='multiaccountlink',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_account_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiaccountlink',
            name='primary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_account_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiaccountlink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_account_links', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proxydetectionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_detection_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proxydetectionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskscorehistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_score_histories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='riskscorehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemaudittrail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_audit_trails', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='systemaudittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_audit_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maliciousipdatabase',
            name='threat_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malicious_ips', to='proxy_intelligence.threatfeedprovider'),
        ),
        migrations.AddField(
            model_name='userriskprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi_user_risk_profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='userriskprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pi_risk_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='velocitymetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='velocity_metrics', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='velocitymetric',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='velocity_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vpndetectionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_detection_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vpndetectionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='proxy_intel_ip_addr_a3576c_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['endpoint', 'status_code'], name='proxy_intel_endpoin_bafac0_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['fingerprint_hash', 'tenant'], name='proxy_intel_fingerp_e32165_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['user', 'last_seen'], name='proxy_intel_user_id_50c54c_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattempt',
            index=models.Index(fields=['ip_address', 'fraud_type'], name='proxy_intel_ip_addr_4ebf22_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudattempt',
            index=models.Index(fields=['status', 'created_at'], name='proxy_intel_status_40d927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationcredential',
            unique_together={('tenant', 'service')},
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['ip_address', 'is_active'], name='proxy_intel_ip_addr_e9e8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ipblacklist',
            index=models.Index(fields=['tenant', 'is_active'], name='proxy_intel_tenant__f86976_idx'),
        ),
        migrations.AddIndex(
            model_name='ipintelligence',
            index=models.Index(fields=['ip_address', 'tenant'], name='proxy_intel_ip_addr_d9da01_idx'),
        ),
        migrations.AddIndex(
            model_name='ipintelligence',
            index=models.Index(fields=['risk_score'], name='proxy_intel_risk_sc_e52fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ipintelligence',
            index=models.Index(fields=['is_vpn', 'is_proxy', 'is_tor'], name='proxy_intel_is_vpn_f106ac_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionlog',
            index=models.Index(fields=['anomaly_type', 'anomaly_score'], name='proxy_intel_anomaly_a33437_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multiaccountlink',
            unique_together={('primary_user', 'linked_user', 'link_type')},
        ),
        migrations.AddIndex(
            model_name='riskscorehistory',
            index=models.Index(fields=['user', 'created_at'], name='proxy_intel_user_id_4e3f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaudittrail',
            index=models.Index(fields=['user', 'action', 'created_at'], name='proxy_intel_user_id_a0c0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaudittrail',
            index=models.Index(fields=['model_name', 'object_id'], name='proxy_intel_model_n_704b5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maliciousipdatabase',
            unique_together={('ip_address', 'threat_type', 'threat_feed')},
        ),
        migrations.AddIndex(
            model_name='userriskprofile',
            index=models.Index(fields=['overall_risk_score', 'is_high_risk'], name='proxy_intel_overall_513bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='velocitymetric',
            index=models.Index(fields=['ip_address', 'action_type', 'window_start'], name='proxy_intel_ip_addr_b1712a_idx'),
        ),
        migrations.AddIndex(
            model_name='vpndetectionlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='proxy_intel_ip_addr_efe6cc_idx'),
        ),
    ]
