# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_intelligence', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anomalydetectionlog',
            new_name='idx_anomaly_type_anomaly_score_1471',
            old_name='proxy_intel_anomaly_a33437_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='idx_ip_address_created_at_1472',
            old_name='proxy_intel_ip_addr_a3576c_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='idx_endpoint_status_code_1473',
            old_name='proxy_intel_endpoin_bafac0_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_fingerprint_hash_tenant_1464',
            old_name='proxy_intel_fingerp_e32165_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_user_last_seen_1465',
            old_name='proxy_intel_user_id_50c54c_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_ip_address_fraud_type_1462',
            old_name='proxy_intel_ip_addr_4ebf22_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudattempt',
            new_name='idx_status_created_at_1463',
            old_name='proxy_intel_status_40d927_idx',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_ip_address_is_active_1467',
            old_name='proxy_intel_ip_addr_e9e8a4_idx',
        ),
        migrations.RenameIndex(
            model_name='ipblacklist',
            new_name='idx_tenant_is_active_1468',
            old_name='proxy_intel_tenant__f86976_idx',
        ),
        migrations.RenameIndex(
            model_name='ipintelligence',
            new_name='idx_ip_address_tenant_1458',
            old_name='proxy_intel_ip_addr_d9da01_idx',
        ),
        migrations.RenameIndex(
            model_name='ipintelligence',
            new_name='idx_risk_score_1459',
            old_name='proxy_intel_risk_sc_e52fd1_idx',
        ),
        migrations.RenameIndex(
            model_name='ipintelligence',
            new_name='idx_is_vpn_is_proxy_is_tor_1460',
            old_name='proxy_intel_is_vpn_f106ac_idx',
        ),
        migrations.RenameIndex(
            model_name='riskscorehistory',
            new_name='idx_user_created_at_1470',
            old_name='proxy_intel_user_id_4e3f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='systemaudittrail',
            new_name='idx_user_action_created_at_1474',
            old_name='proxy_intel_user_id_a0c0ac_idx',
        ),
        migrations.RenameIndex(
            model_name='systemaudittrail',
            new_name='idx_model_name_object_id_1475',
            old_name='proxy_intel_model_n_704b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='userriskprofile',
            new_name='idx_overall_risk_score_is_high_ris_1469',
            old_name='proxy_intel_overall_513bd2_idx',
        ),
        migrations.RenameIndex(
            model_name='velocitymetric',
            new_name='idx_ip_address_action_type_window__1466',
            old_name='proxy_intel_ip_addr_b1712a_idx',
        ),
        migrations.RenameIndex(
            model_name='vpndetectionlog',
            new_name='idx_ip_address_created_at_1461',
            old_name='proxy_intel_ip_addr_efe6cc_idx',
        ),
    ]
