# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_intelligence', '0003_rename_proxy_intel_anomaly_a33437_idx_idx_anomaly_type_anomaly_score_1471_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anomalydetectionlog',
            new_name='idx_anomaly_type_anomaly_s_992',
            old_name='idx_anomaly_type_anomaly_score_1471',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_fingerprint_hash_tenan_491',
            old_name='idx_fingerprint_hash_tenant_1464',
        ),
        migrations.RenameIndex(
            model_name='ipintelligence',
            new_name='idx_is_vpn_is_proxy_is_tor_fb7',
            old_name='idx_is_vpn_is_proxy_is_tor_1460',
        ),
        migrations.RenameIndex(
            model_name='systemaudittrail',
            new_name='idx_user_action_created_at_492',
            old_name='idx_user_action_created_at_1474',
        ),
        migrations.RenameIndex(
            model_name='userriskprofile',
            new_name='idx_overall_risk_score_is__140',
            old_name='idx_overall_risk_score_is_high_ris_1469',
        ),
        migrations.RenameIndex(
            model_name='velocitymetric',
            new_name='idx_ip_address_action_type_b1d',
            old_name='idx_ip_address_action_type_window__1466',
        ),
    ]
