# Generated by Django 5.0.11 on 2026-04-12 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_coins_earned', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('reward_coins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='SpinWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_won', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('total_spins', models.IntegerField(default=0)),
                ('total_won', models.IntegerField(default=0)),
                ('last_spin', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('coins_earned', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10, null=True)),
                ('consecutive_days', models.IntegerField(default=1)),
                ('bonus_claimed', models.BooleanField(default=False)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
