# Generated by Django 5.0.14 on 2026-02-16 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('coins_earned', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('consecutive_days', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_coins_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('reward_coins', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='SpinWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
