# Generated by Django 5.0.11 on 2026-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='bonus_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spinwheel',
            name='last_spin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spinwheel',
            name='total_spins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spinwheel',
            name='total_won',
            field=models.IntegerField(default=0),
        ),
    ]
