# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('columns', models.JSONField(default=list)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Audit Dashboards',
                'db_table': 'audit_dashboards',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('anonymous_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('WALLET_TRANSFER', 'Wallet Transfer'), ('OFFER_VIEW', 'Offer View'), ('OFFER_CLICK', 'Offer Click'), ('OFFER_COMPLETE', 'Offer Complete'), ('OFFER_REJECT', 'Offer Rejection'), ('USER_BAN', 'User Ban'), ('USER_UNBAN', 'User Unban'), ('MANUAL_CREDIT', 'Manual Credit'), ('MANUAL_DEBIT', 'Manual Debit'), ('SYSTEM_ALERT', 'System Alert'), ('BACKUP', 'Database Backup'), ('MAINTENANCE', 'System Maintenance'), ('SUSPICIOUS_LOGIN', 'Suspicious Login'), ('BRUTE_FORCE_ATTEMPT', 'Brute Force Attempt'), ('IP_BLOCK', 'IP Blocked'), ('KYC_SUBMIT', 'KYC Submission'), ('KYC_APPROVE', 'KYC Approval'), ('KYC_REJECT', 'KYC Rejection'), ('REFERRAL_SIGNUP', 'Referral Signup'), ('REFERRAL_BONUS', 'Referral Bonus'), ('API_CALL', 'API Call'), ('RATE_LIMIT', 'Rate Limit Exceeded')], max_length=50)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security')], default='INFO', max_length=10)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True, null=True)),
                ('request_params', models.JSONField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retention_days', models.IntegerField(default=365)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_data', models.BinaryField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_logs', models.IntegerField()),
                ('compressed_size_mb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_size_mb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compression_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('storage_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log_archives',
            },
        ),
        migrations.CreateModel(
            name='AuditLogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security')], default='INFO', max_length=10)),
                ('log_request_body', models.BooleanField(default=True)),
                ('log_response_body', models.BooleanField(default=True)),
                ('log_headers', models.BooleanField(default=False)),
                ('retention_days', models.IntegerField(default=365)),
                ('notify_admins', models.BooleanField(default=False)),
                ('notify_users', models.BooleanField(default=False)),
                ('email_template', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log Configuration',
                'verbose_name_plural': 'Audit Log Configurations',
                'db_table': 'audit_log_configs',
            },
        ),
        migrations.CreateModel(
            name='AuditAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.JSONField()),
                ('action', models.CharField(choices=[('EMAIL', 'Send Email'), ('SMS', 'Send SMS'), ('WEBHOOK', 'Call Webhook'), ('CREATE_TICKET', 'Create Support Ticket'), ('BLOCK_USER', 'Block User'), ('FLAG_TRANSACTION', 'Flag Transaction')], max_length=50)),
                ('action_config', models.JSONField()),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security')], default='WARNING', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=5)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'audit_alert_rules',
                'unique_together': {('name', 'condition')},
            },
        ),
    ]
