# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_action_timestamp_809',
            old_name='audit_logs_action_474804_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_user_id_timestamp_810',
            old_name='audit_logs_user_id_88267f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_resource_type_resource_id_811',
            old_name='audit_logs_resourc_bda8a6_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_correlation_id_812',
            old_name='audit_logs_correla_953e51_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_user_ip_timestamp_813',
            old_name='audit_logs_user_ip_df8ea7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_level_timestamp_814',
            old_name='audit_logs_level_41a7b2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_created_at_815',
            old_name='audit_logs_created_262184_idx',
        ),
    ]
