# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_rename_audit_logs_action_474804_idx_idx_action_timestamp_809_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_resource_type_resource_fd0',
            old_name='idx_resource_type_resource_id_811',
        ),
    ]
