# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('offerwall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.alertrule'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='funnelanalytics',
            index=models.Index(fields=['funnel_type', 'period', 'period_start'], name='analytics_f_funnel__d3d1df_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelanalytics',
            index=models.Index(fields=['conversion_rate'], name='analytics_f_convers_94e6dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funnelanalytics',
            unique_together={('funnel_type', 'period', 'period_start')},
        ),
        migrations.AddField(
            model_name='offerperformanceanalytics',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='offerwall.offer'),
        ),
        migrations.AddIndex(
            model_name='realtimemetric',
            index=models.Index(fields=['metric_type', 'metric_time'], name='analytics_r_metric__f769f8_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimemetric',
            index=models.Index(fields=['metric_time'], name='analytics_r_metric__980ad6_idx'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='retentionanalytics',
            index=models.Index(fields=['cohort_type', 'cohort_date'], name='analytics_r_cohort__5a0511_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionanalytics',
            index=models.Index(fields=['retention_day_7'], name='analytics_r_retenti_970c0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionanalytics',
            unique_together={('cohort_type', 'cohort_date')},
        ),
        migrations.AddIndex(
            model_name='revenueanalytics',
            index=models.Index(fields=['period', 'period_start'], name='analytics_r_period_89debe_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueanalytics',
            index=models.Index(fields=['revenue_total'], name='analytics_r_revenue_2ebaad_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueanalytics',
            index=models.Index(fields=['profit_margin'], name='analytics_r_profit__faa877_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenueanalytics',
            unique_together={('period', 'period_start')},
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['rule', 'triggered_at'], name='analytics_a_rule_id_3f3396_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['is_resolved', 'triggered_at'], name='analytics_a_is_reso_870b42_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'event_time'], name='analytics_a_event_t_91adb3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'event_time'], name='analytics_a_user_id_dcd448_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['country', 'event_time'], name='analytics_a_country_45b149_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['device_type', 'event_time'], name='analytics_a_device__d07b67_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id'], name='analytics_a_session_8757e5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformanceanalytics',
            index=models.Index(fields=['offer', 'period', 'period_start'], name='analytics_o_offer_i_49c9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformanceanalytics',
            index=models.Index(fields=['completion_rate'], name='analytics_o_complet_56900c_idx'),
        ),
        migrations.AddIndex(
            model_name='offerperformanceanalytics',
            index=models.Index(fields=['roi'], name='analytics_o_roi_1dd592_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'generated_at'], name='analytics_r_report__094ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'generated_at'], name='analytics_r_generat_eaae1b_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user', 'period', 'period_start'], name='analytics_u_user_id_3986ad_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['period', 'period_start'], name='analytics_u_period_d0628a_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['earnings_total'], name='analytics_u_earning_3804db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranalytics',
            unique_together={('user', 'period', 'period_start')},
        ),
    ]
