# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_analytics_a_rule_id_3f3396_idx_idx_rule_triggered_at_807_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='idx_is_resolved_triggered__ebb',
            old_name='idx_is_resolved_triggered_at_808',
        ),
        migrations.RenameIndex(
            model_name='funnelanalytics',
            new_name='idx_funnel_type_period_per_c06',
            old_name='idx_funnel_type_period_period_star_799',
        ),
        migrations.RenameIndex(
            model_name='offerperformanceanalytics',
            new_name='idx_offer_period_period_st_a27',
            old_name='idx_offer_period_period_start_796',
        ),
        migrations.RenameIndex(
            model_name='realtimemetric',
            new_name='idx_metric_type_metric_tim_672',
            old_name='idx_metric_type_metric_time_805',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='idx_report_type_generated__deb',
            old_name='idx_report_type_generated_at_803',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='idx_generated_by_generated_1b0',
            old_name='idx_generated_by_generated_at_804',
        ),
        migrations.RenameIndex(
            model_name='retentionanalytics',
            new_name='idx_cohort_type_cohort_dat_9c1',
            old_name='idx_cohort_type_cohort_date_801',
        ),
        migrations.RenameIndex(
            model_name='useranalytics',
            new_name='idx_user_period_period_sta_416',
            old_name='idx_user_period_period_start_790',
        ),
    ]
