# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconversionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyformat',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_formats', to='localization.country'),
        ),
        migrations.AddField(
            model_name='currencyformat',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='datetimeformat',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datetime_formats', to='localization.country'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='exchangerateprovider',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_base', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='exchangerateprovider',
            name='supported_currencies',
            field=models.ManyToManyField(blank=True, related_name='supported_by_providers', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='geoinsight',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_insights', to='localization.country'),
        ),
        migrations.AddField(
            model_name='geoipmapping',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_ip_mappings', to='localization.country'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_active'], name='localizatio_is_acti_cf0e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_default', 'is_active'], name='localizatio_is_defa_4f93f3_idx'),
        ),
        migrations.AddField(
            model_name='geoinsight',
            name='top_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_insights_top', to='localization.language'),
        ),
        migrations.AddField(
            model_name='datetimeformat',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_formats', to='localization.language'),
        ),
        migrations.AddField(
            model_name='currencyformat',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_formats', to='localization.language'),
        ),
        migrations.AddField(
            model_name='countrylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_languages', to='localization.language'),
        ),
        migrations.AddField(
            model_name='contentlocalemapping',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_mappings', to='localization.language'),
        ),
        migrations.AddField(
            model_name='contentlocalemapping',
            name='redirect_to_language',
            field=models.ForeignKey(blank=True, help_text='Redirect to this language if not available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_mappings', to='localization.language'),
        ),
        migrations.AddField(
            model_name='languageusagestat',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_default', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_default', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='fallback_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_fallback', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='supported_currencies',
            field=models.ManyToManyField(blank=True, related_name='tenant_configs', to='localization.currency'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='supported_languages',
            field=models.ManyToManyField(blank=True, related_name='tenant_configs', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizationinsight',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='localization.country'),
        ),
        migrations.AddField(
            model_name='localizationinsight',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizedcontent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localizedcontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_content', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizedcontent',
            name='source_locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_source', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizedimage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localized_images', to='localization.country'),
        ),
        migrations.AddField(
            model_name='localizedimage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localized_images', to='localization.language'),
        ),
        migrations.AddField(
            model_name='localizedseo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_seo', to='localization.language'),
        ),
        migrations.AddField(
            model_name='missingtranslation',
            name='language',
            field=models.ForeignKey(help_text='Language where translation is missing', on_delete=django.db.models.deletion.CASCADE, to='localization.language'),
        ),
        migrations.AddField(
            model_name='missingtranslation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_missing_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingtranslation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numberformat',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_formats', to='localization.country'),
        ),
        migrations.AddField(
            model_name='numberformat',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_formats', to='localization.language'),
        ),
        migrations.AddField(
            model_name='phoneformat',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_format', to='localization.country'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='localization.country'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='localization.region'),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['is_active'], name='localizatio_is_acti_7baac2_idx'),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['name'], name='localizatio_name_978f97_idx'),
        ),
        migrations.AddField(
            model_name='region',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='localization.timezone'),
        ),
        migrations.AddField(
            model_name='localizationconfig',
            name='default_timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_default', to='localization.timezone'),
        ),
        migrations.AddField(
            model_name='geoipmapping',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_ip_mappings', to='localization.timezone'),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(blank=True, help_text='Timezone of the city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.timezone'),
        ),
        migrations.AddField(
            model_name='translation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this translation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(help_text='Target language', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.language'),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['expires_at'], name='localizatio_expires_9354e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together={('language_code', 'cache_key')},
        ),
        migrations.AddField(
            model_name='translationcoverage',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_stat', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationglossary',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_glossary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationglossary',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_source', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationglossaryentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_glossary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationglossaryentry',
            name='glossary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='localization.translationglossary'),
        ),
        migrations.AddField(
            model_name='translationglossaryentry',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_entries', to='localization.language'),
        ),
        migrations.AddIndex(
            model_name='translationkey',
            index=models.Index(fields=['category'], name='localizatio_categor_070d8b_idx'),
        ),
        migrations.AddField(
            model_name='translation',
            name='key',
            field=models.ForeignKey(help_text='Translation key', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.translationkey'),
        ),
        migrations.AddField(
            model_name='translationmemory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationmemory',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_source', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationmemory',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_target', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_translation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='glossary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_requests', to='localization.translationglossary'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_requests_source', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='target_languages',
            field=models.ManyToManyField(related_name='translation_requests_target', to='localization.language'),
        ),
        migrations.AddField(
            model_name='translationscreenshot',
            name='translation_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='localization.translationkey'),
        ),
        migrations.AddField(
            model_name='translationscreenshot',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_screenshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationversion',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='localization.translation'),
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='content_language',
            field=models.ForeignKey(blank=True, help_text='Content language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_users', to='localization.language'),
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='preferred_languages',
            field=models.ManyToManyField(blank=True, help_text='Preferred languages', related_name='preferred_users', to='localization.language'),
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='primary_language',
            field=models.ForeignKey(blank=True, help_text='Primary language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='localization.language'),
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='ui_language',
            field=models.ForeignKey(blank=True, help_text='UI language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_users', to='localization.language'),
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='user',
            field=models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='localization.webhookregistration'),
        ),
        migrations.AddIndex(
            model_name='countrycurrency',
            index=models.Index(fields=['country', 'is_primary'], name='localizatio_country_6bf640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countrycurrency',
            unique_together={('country', 'currency')},
        ),
        migrations.AddIndex(
            model_name='currencyconversionlog',
            index=models.Index(fields=['from_currency', 'to_currency', 'created_at'], name='localizatio_from_cu_8e9308_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyconversionlog',
            index=models.Index(fields=['user', 'created_at'], name='localizatio_user_id_85a6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyconversionlog',
            index=models.Index(fields=['created_at'], name='localizatio_created_f62730_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'date'], name='localizatio_from_cu_0f6ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['date'], name='localizatio_date_28b62d_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['source'], name='localizatio_source_15b016_idx'),
        ),
        migrations.AddIndex(
            model_name='geoinsight',
            index=models.Index(fields=['date'], name='localizatio_date_72d49c_idx'),
        ),
        migrations.AddIndex(
            model_name='geoinsight',
            index=models.Index(fields=['country', 'date'], name='localizatio_country_f5a305_idx'),
        ),
        migrations.AddIndex(
            model_name='geoinsight',
            index=models.Index(fields=['country_code'], name='localizatio_country_ca2a58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geoinsight',
            unique_together={('date', 'country', 'region_name', 'city_name')},
        ),
        migrations.AlterUniqueTogether(
            name='datetimeformat',
            unique_together={('language', 'country', 'calendar_system')},
        ),
        migrations.AlterUniqueTogether(
            name='currencyformat',
            unique_together={('currency', 'language', 'country')},
        ),
        migrations.AddIndex(
            model_name='countrylanguage',
            index=models.Index(fields=['country', 'is_official'], name='localizatio_country_379b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='countrylanguage',
            index=models.Index(fields=['language'], name='localizatio_languag_40963f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countrylanguage',
            unique_together={('country', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='contentlocalemapping',
            unique_together={('content_type', 'object_id', 'language')},
        ),
        migrations.AddIndex(
            model_name='languageusagestat',
            index=models.Index(fields=['date', 'language'], name='localizatio_date_e3ade7_idx'),
        ),
        migrations.AddIndex(
            model_name='languageusagestat',
            index=models.Index(fields=['language', 'dau'], name='localizatio_languag_5afdbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='languageusagestat',
            unique_together={('date', 'language')},
        ),
        migrations.AddIndex(
            model_name='localizationinsight',
            index=models.Index(fields=['date'], name='localizatio_date_078931_idx'),
        ),
        migrations.AddIndex(
            model_name='localizationinsight',
            index=models.Index(fields=['language', 'date'], name='localizatio_languag_5feb41_idx'),
        ),
        migrations.AddIndex(
            model_name='localizationinsight',
            index=models.Index(fields=['country', 'date'], name='localizatio_country_a0017c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localizationinsight',
            unique_together={('date', 'language', 'country')},
        ),
        migrations.AddIndex(
            model_name='localizedcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='localizatio_content_7387e1_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedcontent',
            index=models.Index(fields=['language', 'is_approved'], name='localizatio_languag_6fca32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localizedcontent',
            unique_together={('content_type', 'object_id', 'language', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='localizedimage',
            index=models.Index(fields=['content_type', 'object_id'], name='localizatio_content_5ae8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedimage',
            index=models.Index(fields=['language'], name='localizatio_languag_a87fee_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedseo',
            index=models.Index(fields=['content_type', 'object_id'], name='localizatio_content_9858ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localizedseo',
            unique_together={('content_type', 'object_id', 'language')},
        ),
        migrations.AddIndex(
            model_name='missingtranslation',
            index=models.Index(fields=['key'], name='localizatio_key_1b573b_idx'),
        ),
        migrations.AddIndex(
            model_name='missingtranslation',
            index=models.Index(fields=['language', 'resolved'], name='localizatio_languag_732803_idx'),
        ),
        migrations.AddIndex(
            model_name='missingtranslation',
            index=models.Index(fields=['created_at'], name='localizatio_created_9e10ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='numberformat',
            unique_together={('language', 'country')},
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['region_type', 'is_active'], name='localizatio_region__fdd4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country', 'region_type'], name='localizatio_country_4b4afb_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='localizatio_code_a20156_idx'),
        ),
        migrations.AddIndex(
            model_name='geoipmapping',
            index=models.Index(fields=['ip_start_int', 'ip_end_int'], name='localizatio_ip_star_5e435b_idx'),
        ),
        migrations.AddIndex(
            model_name='geoipmapping',
            index=models.Index(fields=['country_code'], name='localizatio_country_efc366_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='localizatio_is_acti_a6ca71_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'is_active'], name='localizatio_country_ee3085_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='translationcoverage',
            index=models.Index(fields=['coverage_percent'], name='localizatio_coverag_09de4a_idx'),
        ),
        migrations.AddIndex(
            model_name='translationglossary',
            index=models.Index(fields=['source_term', 'source_language'], name='localizatio_source__fc5844_idx'),
        ),
        migrations.AddIndex(
            model_name='translationglossary',
            index=models.Index(fields=['domain'], name='localizatio_domain_4c793f_idx'),
        ),
        migrations.AddIndex(
            model_name='translationglossary',
            index=models.Index(fields=['is_do_not_translate'], name='localizatio_is_do_n_958553_idx'),
        ),
        migrations.AddIndex(
            model_name='translationglossary',
            index=models.Index(fields=['is_brand_term'], name='localizatio_is_bran_1da788_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationglossaryentry',
            unique_together={('glossary', 'language')},
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['language', 'is_approved'], name='localizatio_languag_1f0585_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['key', 'language', 'is_approved'], name='localizatio_key_id_b51497_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('key', 'language')},
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['source_hash', 'source_language', 'target_language'], name='localizatio_source__b8de96_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['domain'], name='localizatio_domain_41d70c_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['is_approved'], name='localizatio_is_appr_4eb8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['status', 'priority'], name='localizatio_status_4d8930_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrequest',
            index=models.Index(fields=['due_date'], name='localizatio_due_dat_f6d244_idx'),
        ),
        migrations.AddIndex(
            model_name='translationversion',
            index=models.Index(fields=['translation', 'version_number'], name='localizatio_transla_f87b15_idx'),
        ),
        migrations.AddIndex(
            model_name='translationversion',
            index=models.Index(fields=['created_at'], name='localizatio_created_cb5d68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationversion',
            unique_together={('translation', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['webhook', 'delivered', 'created_at'], name='localizatio_webhook_3b7fdd_idx'),
        ),
    ]
