# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0003_rename_localizatio_is_acti_a6ca71_idx_idx_is_active_1078_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyconversionlog',
            new_name='idx_from_currency_to_curre_0cf',
            old_name='idx_from_currency_to_currency_crea_1086',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='idx_from_currency_to_curre_e02',
            old_name='idx_from_currency_to_currency_date_1083',
        ),
        migrations.RenameIndex(
            model_name='geoipmapping',
            new_name='idx_ip_start_int_ip_end_in_bec',
            old_name='idx_ip_start_int_ip_end_int_1095',
        ),
        migrations.RenameIndex(
            model_name='localizedcontent',
            new_name='idx_content_type_object_id_d48',
            old_name='idx_content_type_object_id_1063',
        ),
        migrations.RenameIndex(
            model_name='localizedimage',
            new_name='idx_content_type_object_id_ba2',
            old_name='idx_content_type_object_id_1065',
        ),
        migrations.RenameIndex(
            model_name='localizedseo',
            new_name='idx_content_type_object_id_c6d',
            old_name='idx_content_type_object_id_1067',
        ),
        migrations.RenameIndex(
            model_name='translation',
            new_name='idx_key_language_is_approv_9d4',
            old_name='idx_key_language_is_approved_1082',
        ),
        migrations.RenameIndex(
            model_name='translationglossary',
            new_name='idx_source_term_source_lan_015',
            old_name='idx_source_term_source_language_1105',
        ),
        migrations.RenameIndex(
            model_name='translationmemory',
            new_name='idx_source_hash_source_lan_f2f',
            old_name='idx_source_hash_source_language_ta_1102',
        ),
        migrations.RenameIndex(
            model_name='translationversion',
            new_name='idx_translation_version_nu_5d9',
            old_name='idx_translation_version_number_1109',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='idx_webhook_delivered_crea_2f2',
            old_name='idx_webhook_delivered_created_at_1097',
        ),
    ]
