# Generated by Django 5.0.11 on 2026-04-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0003_placeholder'),
        ('localization', '0004_placeholder'),
        ('localization', '0007_placeholder'),
        ('localization', '0008_performance_indexes'),
    ]

    operations = [
    ]
