# Generated by Django 5.0.14 on 2026-02-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_number', models.CharField(help_text='bKash/Nagad number', max_length=20)),
                ('payment_method', models.CharField(default='bkash', max_length=20)),
                ('address_line', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_submitted', max_length=20)),
                ('is_name_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_payment_verified', models.BooleanField(default=False)),
                ('document_type', models.CharField(blank=True, choices=[('nid', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='kyc/documents/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/documents/')),
                ('selfie_photo', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('is_face_verified', models.BooleanField(default=False)),
                ('extracted_name', models.CharField(blank=True, max_length=200)),
                ('extracted_dob', models.DateField(blank=True, null=True)),
                ('extracted_nid', models.CharField(blank=True, max_length=50)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100')),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='kyc.kyc')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC Records',
                'db_table': 'kyc',
            },
        ),
    ]
