# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_kyc_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyc',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycadminnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycadminnote',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_note_list', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycanalyticssnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycaudittrail',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycaudittrail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycblacklist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycblacklist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycbulkactionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycbulkactionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycdevicefingerprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycduplicategroup',
            name='kyc_records',
            field=models.ManyToManyField(related_name='duplicate_groups', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycduplicategroup',
            name='primary_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_duplicate_group', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycduplicategroup',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycexportjob',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycexportjob',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycfacematchresult',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_match_results', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycfeatureflag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycfeatureflag',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyciptracker',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_logs', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kyciptracker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_ip_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycnotificationlog',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycnotificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycocrresult',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycotplog',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycotplog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_otp_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycrejectiontemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycriskprofile',
            name='kyc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyctenantconfig',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycverificationlog',
            name='kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tenant', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycverificationlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverificationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycverificationstep',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_steps', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='kycwebhookendpoint',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_webhooks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycwebhookdeliverylog',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='kyc.kycwebhookendpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='kycanalyticssnapshot',
            unique_together={('tenant', 'period', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['entity_type', 'entity_id'], name='kyc_audit_t_entity__575adf_idx'),
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['actor', 'created_at'], name='kyc_audit_t_actor_i_8a0387_idx'),
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['tenant', 'created_at'], name='kyc_audit_t_tenant__2ae4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='kycblacklist',
            index=models.Index(fields=['type', 'value', 'is_active'], name='kyc_blackli_type_e889d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycblacklist',
            unique_together={('type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='kycdevicefingerprint',
            unique_together={('user', 'fingerprint')},
        ),
        migrations.AlterUniqueTogether(
            name='kycfeatureflag',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='kyciptracker',
            index=models.Index(fields=['ip_address', 'created_at'], name='kyc_ip_trac_ip_addr_aee331_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['user', 'created_at'], name='kyc_submiss_user_id_100045_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['user', 'status'], name='kyc_submiss_user_id_2baadb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycverificationstep',
            unique_together={('kyc', 'step')},
        ),
    ]
