# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycaudittrail',
            new_name='idx_entity_type_entity_id_1027',
            old_name='kyc_audit_t_entity__575adf_idx',
        ),
        migrations.RenameIndex(
            model_name='kycaudittrail',
            new_name='idx_actor_created_at_1028',
            old_name='kyc_audit_t_actor_i_8a0387_idx',
        ),
        migrations.RenameIndex(
            model_name='kycaudittrail',
            new_name='idx_tenant_created_at_1029',
            old_name='kyc_audit_t_tenant__2ae4ff_idx',
        ),
        migrations.RenameIndex(
            model_name='kycblacklist',
            new_name='idx_type_value_is_active_1025',
            old_name='kyc_blackli_type_e889d2_idx',
        ),
        migrations.RenameIndex(
            model_name='kyciptracker',
            new_name='idx_ip_address_created_at_1026',
            old_name='kyc_ip_trac_ip_addr_aee331_idx',
        ),
        migrations.RenameIndex(
            model_name='kycsubmission',
            new_name='idx_user_created_at_1023',
            old_name='kyc_submiss_user_id_100045_idx',
        ),
        migrations.RenameIndex(
            model_name='kycsubmission',
            new_name='idx_user_status_1024',
            old_name='kyc_submiss_user_id_2baadb_idx',
        ),
    ]
