# Generated by Django 5.0.11 on 2026-03-31 14:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kyc_tenant_kycverificationlog_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('verification_progress', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('document_type', models.CharField(choices=[('nid', 'NID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], db_index=True, max_length=30)),
                ('document_number', models.CharField(db_index=True, max_length=50)),
                ('nid_front', models.ImageField(upload_to='kyc/nid/front/')),
                ('nid_back', models.ImageField(upload_to='kyc/nid/back/')),
                ('selfie_with_note', models.ImageField(upload_to='kyc/selfie/')),
                ('image_clarity_score', models.FloatField(default=0.0)),
                ('document_matching_score', models.FloatField(default=0.0)),
                ('face_liveness_check', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'db_table': 'kyc_submissions',
                'indexes': [models.Index(fields=['user', 'created_at'], name='kyc_submiss_user_id_100045_idx'), models.Index(fields=['user', 'status'], name='kyc_submiss_user_id_2baadb_idx')],
            },
        ),
    ]
