# kyc/migrations/0006_world1_v2_aml_compliance_liveness_kyb.py
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_world1_new_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # AML Screening
        migrations.CreateModel(
            name='PEPSanctionsScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30, default='mock')),
                ('status', models.CharField(max_length=20, default='pending', db_index=True)),
                ('reference_id', models.CharField(max_length=100, blank=True)),
                ('screened_name', models.CharField(max_length=200)),
                ('screened_dob', models.DateField(null=True, blank=True)),
                ('screened_country', models.CharField(max_length=100, blank=True)),
                ('screened_nid', models.CharField(max_length=50, blank=True)),
                ('is_pep', models.BooleanField(default=False, db_index=True)),
                ('is_sanctioned', models.BooleanField(default=False, db_index=True)),
                ('is_adverse_media', models.BooleanField(default=False)),
                ('match_count', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('matches', models.JSONField(default=list, blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict, blank=True)),
                ('error', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_review_at', models.DateTimeField(null=True, blank=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_screenings', to='kyc.kyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_screenings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('reviewed_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_aml_screenings', 'verbose_name': 'AML/PEP Screening', 'ordering': ['-screened_at']},
        ),
        migrations.CreateModel(
            name='SanctionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=10, db_index=True)),
                ('list_name', models.CharField(max_length=200)),
                ('entry_name', models.CharField(max_length=500, db_index=True)),
                ('aliases', models.JSONField(default=list, blank=True)),
                ('dob', models.CharField(max_length=50, blank=True)),
                ('nationality', models.CharField(max_length=100, blank=True)),
                ('entity_type', models.CharField(max_length=50, blank=True)),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('listed_date', models.DateField(null=True, blank=True)),
                ('delisted_date', models.DateField(null=True, blank=True)),
                ('external_id', models.CharField(max_length=100, blank=True, db_index=True)),
                ('additional_info', models.JSONField(default=dict, blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'kyc_sanctions_list', 'verbose_name': 'Sanctions List Entry'},
        ),
        migrations.CreateModel(
            name='PEPDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=300, db_index=True)),
                ('aliases', models.JSONField(default=list, blank=True)),
                ('category', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100, db_index=True)),
                ('position', models.CharField(max_length=300, blank=True)),
                ('party', models.CharField(max_length=200, blank=True)),
                ('dob', models.CharField(max_length=20, blank=True)),
                ('is_current', models.BooleanField(default=True, db_index=True)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('source', models.CharField(max_length=100, blank=True)),
                ('external_id', models.CharField(max_length=100, blank=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'kyc_pep_database', 'verbose_name': 'PEP Entry'},
        ),
        migrations.CreateModel(
            name='AMLAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=30, db_index=True)),
                ('status', models.CharField(max_length=15, default='open', db_index=True)),
                ('severity', models.CharField(max_length=10, default='medium')),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict, blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('sar_filed', models.BooleanField(default=False)),
                ('sar_reference', models.CharField(max_length=100, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(null=True, blank=True)),
                ('kyc', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts', to='kyc.kyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('assigned_to', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_aml_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_aml_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_aml_alerts', 'verbose_name': 'AML Alert', 'ordering': ['-created_at']},
        ),
        # GDPR
        migrations.CreateModel(
            name='GDPRDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=20, db_index=True)),
                ('status', models.CharField(max_length=15, default='pending', db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('data_export_file', models.FileField(null=True, blank=True, upload_to='compliance/gdpr_exports/')),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_gdpr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_gdpr_requests', 'verbose_name': 'GDPR Data Request', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(max_length=25, db_index=True)),
                ('is_given', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=20, default='1.0')),
                ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('text_shown', models.TextField(blank=True)),
                ('withdrawn_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_consent_logs', 'verbose_name': 'Consent Log', 'ordering': ['-created_at']},
        ),
        # Liveness
        migrations.CreateModel(
            name='LivenessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=20, default='passive')),
                ('provider', models.CharField(max_length=20, default='mock')),
                ('result', models.CharField(max_length=10, default='pending', db_index=True)),
                ('liveness_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_deepfake', models.BooleanField(default=False, db_index=True)),
                ('is_print_attack', models.BooleanField(default=False)),
                ('is_screen_attack', models.BooleanField(default=False)),
                ('is_mask_attack', models.BooleanField(default=False)),
                ('is_injection_attack', models.BooleanField(default=False)),
                ('media_integrity_score', models.FloatField(default=0.0)),
                ('texture_score', models.FloatField(default=0.0)),
                ('depth_score', models.FloatField(default=0.0)),
                ('session_id', models.CharField(max_length=100, blank=True)),
                ('attempts', models.IntegerField(default=1)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_checks', to='kyc.kyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_liveness_checks', 'verbose_name': 'Liveness Check', 'ordering': ['-created_at']},
        ),
        # KYB
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=300, db_index=True)),
                ('entity_type', models.CharField(max_length=25)),
                ('trade_license_no', models.CharField(max_length=100, blank=True, db_index=True)),
                ('tin_number', models.CharField(max_length=50, blank=True)),
                ('bin_number', models.CharField(max_length=50, blank=True)),
                ('registration_no', models.CharField(max_length=100, blank=True)),
                ('incorporation_date', models.DateField(null=True, blank=True)),
                ('country_of_incorporation', models.CharField(max_length=100, default='Bangladesh')),
                ('registered_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=20, blank=True)),
                ('email', models.EmailField(blank=True)),
                ('status', models.CharField(max_length=15, default='not_submitted', db_index=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=10, default='low')),
                ('trade_license_doc', models.FileField(null=True, blank=True, upload_to='kyb/trade_license/')),
                ('incorporation_doc', models.FileField(null=True, blank=True, upload_to='kyb/incorporation/')),
                ('moa_doc', models.FileField(null=True, blank=True, upload_to='kyb/moa/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(null=True, blank=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_verifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('reviewed_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyb_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyb_business_verifications', 'verbose_name': 'Business Verification (KYB)', 'ordering': ['-created_at']},
        ),
        # Transaction Monitoring Rules
        migrations.CreateModel(
            name='TransactionMonitoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(max_length=20, db_index=True)),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('threshold_amount', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                ('threshold_count', models.IntegerField(null=True, blank=True)),
                ('time_window_hours', models.IntegerField(default=24)),
                ('currency', models.CharField(max_length=5, default='BDT')),
                ('action', models.CharField(max_length=10, default='alert')),
                ('severity', models.CharField(max_length=10, default='medium')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_tm_rules', 'verbose_name': 'Transaction Monitoring Rule'},
        ),
    ]
