# kyc/migrations/0007_world1_v3_billing_sandbox_behavioral_video.py
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_world1_v2_aml_compliance_liveness_kyb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # KYCPlan
        migrations.CreateModel(
            name='KYCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_price_bdt', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('monthly_price_usd', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('per_kyc_price_bdt', models.DecimalField(max_digits=8, decimal_places=2, default=0)),
                ('per_aml_price_bdt', models.DecimalField(max_digits=8, decimal_places=2, default=0)),
                ('per_video_kyc_bdt', models.DecimalField(max_digits=8, decimal_places=2, default=0)),
                ('monthly_kyc_limit', models.IntegerField(default=0)),
                ('monthly_aml_limit', models.IntegerField(default=0)),
                ('max_tenants', models.IntegerField(default=1)),
                ('api_rate_limit', models.IntegerField(default=100)),
                ('data_retention_days', models.IntegerField(default=365)),
                ('features', models.JSONField(default=list, blank=True)),
                ('kyb_enabled', models.BooleanField(default=False)),
                ('video_kyc_enabled', models.BooleanField(default=False)),
                ('aml_enabled', models.BooleanField(default=False)),
                ('perpetual_kyc_enabled', models.BooleanField(default=False)),
                ('behavioral_enabled', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('dedicated_support', models.BooleanField(default=False)),
                ('sla_hours', models.IntegerField(default=72)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'kyc_plans', 'verbose_name': 'KYC Plan', 'ordering': ['sort_order']},
        ),
        # KYCSubscription
        migrations.CreateModel(
            name='KYCSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15, default='trial', db_index=True)),
                ('billing_cycle_start', models.DateField()),
                ('billing_cycle_end', models.DateField()),
                ('next_billing_date', models.DateField(null=True, blank=True, db_index=True)),
                ('trial_ends_at', models.DateTimeField(null=True, blank=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('custom_kyc_price', models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)),
                ('custom_limit', models.IntegerField(null=True, blank=True)),
                ('discount_pct', models.IntegerField(default=0)),
                ('billing_email', models.EmailField(blank=True)),
                ('billing_name', models.CharField(max_length=200, blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(null=True, blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_subscription', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='kyc.kycplan')),
            ],
            options={'db_table': 'kyc_subscriptions', 'verbose_name': 'KYC Subscription'},
        ),
        # KYCUsageRecord
        migrations.CreateModel(
            name='KYCUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('usage_type', models.CharField(max_length=25, db_index=True)),
                ('unit_price_bdt', models.DecimalField(max_digits=8, decimal_places=4, default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('total_bdt', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('kyc_id', models.IntegerField(null=True, blank=True)),
                ('user_id', models.IntegerField(null=True, blank=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('billed', models.BooleanField(default=False, db_index=True)),
                ('invoice_id', models.IntegerField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('subscription', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.kycsubscription')),
            ],
            options={'db_table': 'kyc_usage_records', 'verbose_name': 'Usage Record', 'ordering': ['-created_at']},
        ),
        # KYCInvoice
        migrations.CreateModel(
            name='KYCInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=15, default='draft', db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal_bdt', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('discount_bdt', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('vat_bdt', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('total_bdt', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('line_items', models.JSONField(default=list, blank=True)),
                ('issued_at', models.DateTimeField(null=True, blank=True)),
                ('due_date', models.DateField(null=True, blank=True)),
                ('paid_at', models.DateTimeField(null=True, blank=True)),
                ('payment_reference', models.CharField(max_length=100, blank=True)),
                ('payment_method', models.CharField(max_length=50, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(null=True, blank=True, upload_to='kyc/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_invoices', to='tenants.tenant')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.kycsubscription')),
            ],
            options={'db_table': 'kyc_invoices', 'verbose_name': 'Invoice', 'ordering': ['-created_at']},
        ),
        # APIKey
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_type', models.CharField(max_length=15, default='test')),
                ('key_prefix', models.CharField(max_length=10, db_index=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('permissions', models.JSONField(default=list, blank=True)),
                ('ip_whitelist', models.JSONField(default=list, blank=True)),
                ('last_used_at', models.DateTimeField(null=True, blank=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('revoked_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_api_keys', to='tenants.tenant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'kyc_api_keys', 'verbose_name': 'API Key', 'ordering': ['-created_at']},
        ),
        # BehavioralSession
        migrations.CreateModel(
            name='BehavioralSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True, db_index=True)),
                ('avg_typing_speed_wpm', models.FloatField(default=0.0)),
                ('keystroke_intervals', models.JSONField(default=list, blank=True)),
                ('backspace_ratio', models.FloatField(default=0.0)),
                ('copy_paste_detected', models.BooleanField(default=False)),
                ('avg_mouse_speed', models.FloatField(default=0.0)),
                ('total_session_ms', models.IntegerField(default=0)),
                ('form_fill_time_ms', models.IntegerField(default=0)),
                ('idle_time_ms', models.IntegerField(default=0)),
                ('tab_switches', models.IntegerField(default=0)),
                ('device_type', models.CharField(max_length=20, blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_level', models.CharField(max_length=10, default='low', db_index=True)),
                ('bot_probability', models.FloatField(default=0.0)),
                ('automation_detected', models.BooleanField(default=False, db_index=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('anomaly_flags', models.JSONField(default=list, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_sessions', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavioral_sessions', to='kyc.kyc')),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_behavioral_sessions', 'verbose_name': 'Behavioral Session', 'ordering': ['-created_at']},
        ),
        # VideoKYCSession
        migrations.CreateModel(
            name='VideoKYCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('room_id', models.CharField(max_length=100, blank=True, db_index=True)),
                ('status', models.CharField(max_length=20, default='scheduled', db_index=True)),
                ('outcome', models.CharField(max_length=25, blank=True)),
                ('scheduled_at', models.DateTimeField(null=True, blank=True)),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('ended_at', models.DateTimeField(null=True, blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('face_verified_during_call', models.BooleanField(default=False)),
                ('document_captured', models.BooleanField(default=False)),
                ('liveness_confirmed', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('video_quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_kyc_sessions', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_sessions', to='kyc.kyc')),
                ('agent', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_video_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_video_sessions', 'verbose_name': 'Video KYC Session', 'ordering': ['-created_at']},
        ),
        # KYCMonitoringProfile
        migrations.CreateModel(
            name='KYCMonitoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('monitoring_level', models.CharField(max_length=15, default='standard', db_index=True)),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('current_risk_score', models.IntegerField(default=0)),
                ('current_risk_level', models.CharField(max_length=10, default='low', db_index=True)),
                ('risk_trend', models.CharField(max_length=10, default='stable')),
                ('last_review_at', models.DateTimeField(null=True, blank=True)),
                ('next_review_at', models.DateTimeField(null=True, blank=True, db_index=True)),
                ('rekyc_required', models.BooleanField(default=False, db_index=True)),
                ('rekyc_reason', models.TextField(blank=True)),
                ('total_triggers', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(null=True, blank=True)),
                ('last_trigger_type', models.CharField(max_length=50, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_monitoring', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_monitoring_profiles', 'verbose_name': 'KYC Monitoring Profile'},
        ),
        # SandboxConfig
        migrations.CreateModel(
            name='SandboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_sandbox_mode', models.BooleanField(default=False, db_index=True)),
                ('sandbox_api_key', models.CharField(max_length=100, blank=True)),
                ('auto_approve_all', models.BooleanField(default=False)),
                ('auto_reject_pattern', models.CharField(max_length=50, blank=True)),
                ('ocr_confidence_override', models.FloatField(default=0.95)),
                ('face_match_override', models.FloatField(default=0.92)),
                ('liveness_override', models.CharField(max_length=10, default='success')),
                ('pep_test_names', models.JSONField(default=list, blank=True)),
                ('sanctions_test_names', models.JSONField(default=list, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_config', to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_sandbox_configs', 'verbose_name': 'Sandbox Config'},
        ),
        # BatchVerificationJob
        migrations.CreateModel(
            name='BatchVerificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=20, default='api_bulk')),
                ('status', models.CharField(max_length=15, default='pending', db_index=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('input_file', models.FileField(null=True, blank=True, upload_to='kyc/batch/input/')),
                ('result_file', models.FileField(null=True, blank=True, upload_to='kyc/batch/output/')),
                ('error_log', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, blank=True)),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={'db_table': 'kyc_batch_jobs', 'verbose_name': 'Batch Verification Job', 'ordering': ['-created_at']},
        ),
    ]
