# Generated by Django 5.0.11 on 2026-04-10 04:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_world1_v3_billing_sandbox_behavioral_video'),
        ('tenants', '0003_alter_tenant_max_users_tenantbilling_tenantinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amlalert',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='amlalert',
            name='kyc',
        ),
        migrations.RemoveField(
            model_name='amlalert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='amlalert',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='amlalert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='batchverificationjob',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='batchverificationjob',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='behavioralsession',
            name='kyc',
        ),
        migrations.RemoveField(
            model_name='behavioralsession',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='behavioralsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='businessverification',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='businessverification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='businessverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consentlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gdprdatarequest',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='gdprdatarequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kycinvoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='kycinvoice',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='kycmonitoringprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='kycmonitoringprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kycsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='kycsubscription',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='kycusagerecord',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='kycusagerecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='livenesscheck',
            name='kyc',
        ),
        migrations.RemoveField(
            model_name='livenesscheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='PEPDatabase',
        ),
        migrations.RemoveField(
            model_name='pepsanctionsscreening',
            name='kyc',
        ),
        migrations.RemoveField(
            model_name='pepsanctionsscreening',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='pepsanctionsscreening',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pepsanctionsscreening',
            name='user',
        ),
        migrations.DeleteModel(
            name='SanctionsList',
        ),
        migrations.RemoveField(
            model_name='sandboxconfig',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='transactionmonitoringrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='videokycsession',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='videokycsession',
            name='kyc',
        ),
        migrations.RemoveField(
            model_name='videokycsession',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='videokycsession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='kycaudittrail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Trail', 'verbose_name_plural': 'Audit Trail'},
        ),
        migrations.AlterModelOptions(
            name='kycblacklist',
            options={'verbose_name': 'KYC Blacklist Entry', 'verbose_name_plural': 'KYC Blacklist'},
        ),
        migrations.AlterField(
            model_name='kycadminnote',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='User দেখতে পাবে না'),
        ),
        migrations.AlterField(
            model_name='kycanalyticssnapshot',
            name='verification_rate',
            field=models.FloatField(default=0.0, help_text='verified/total %'),
        ),
        migrations.AlterField(
            model_name='kycblacklist',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Null = permanent', null=True),
        ),
        migrations.AlterField(
            model_name='kycexportjob',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Applied filters snapshot'),
        ),
        migrations.AlterField(
            model_name='kycfacematchresult',
            name='match_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='kycfeatureflag',
            name='value',
            field=models.JSONField(blank=True, default=dict, help_text='Optional config value'),
        ),
        migrations.AlterField(
            model_name='kycocrresult',
            name='confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='kycotplog',
            name='otp_hash',
            field=models.CharField(help_text='Hashed OTP — never store plain', max_length=128),
        ),
        migrations.AlterField(
            model_name='kycriskprofile',
            name='overall_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='kyctenantconfig',
            name='allowed_document_types',
            field=models.JSONField(default=list, help_text='Empty = all allowed'),
        ),
        migrations.AlterField(
            model_name='kyctenantconfig',
            name='auto_approve_threshold',
            field=models.IntegerField(default=0, help_text='Risk score ≤ this → auto approve. 0=disabled'),
        ),
        migrations.AlterField(
            model_name='kyctenantconfig',
            name='auto_reject_threshold',
            field=models.IntegerField(default=90, help_text='Risk score ≥ this → auto reject'),
        ),
        migrations.AlterField(
            model_name='kycwebhookendpoint',
            name='events',
            field=models.JSONField(default=list, help_text="List of events e.g. ['kyc.verified','kyc.rejected']"),
        ),
        migrations.AlterField(
            model_name='kycwebhookendpoint',
            name='secret_key',
            field=models.CharField(blank=True, help_text='HMAC signing key', max_length=256),
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['entity_type', 'entity_id'], name='kyc_audit_t_entity__575adf_idx'),
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['actor', 'created_at'], name='kyc_audit_t_actor_i_8a0387_idx'),
        ),
        migrations.AddIndex(
            model_name='kycaudittrail',
            index=models.Index(fields=['tenant', 'created_at'], name='kyc_audit_t_tenant__2ae4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='kycblacklist',
            index=models.Index(fields=['type', 'value', 'is_active'], name='kyc_blackli_type_e889d2_idx'),
        ),
        migrations.AddIndex(
            model_name='kyciptracker',
            index=models.Index(fields=['ip_address', 'created_at'], name='kyc_ip_trac_ip_addr_aee331_idx'),
        ),
        migrations.DeleteModel(
            name='AMLAlert',
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.DeleteModel(
            name='BatchVerificationJob',
        ),
        migrations.DeleteModel(
            name='BehavioralSession',
        ),
        migrations.DeleteModel(
            name='BusinessVerification',
        ),
        migrations.DeleteModel(
            name='ConsentLog',
        ),
        migrations.DeleteModel(
            name='GDPRDataRequest',
        ),
        migrations.DeleteModel(
            name='KYCInvoice',
        ),
        migrations.DeleteModel(
            name='KYCMonitoringProfile',
        ),
        migrations.DeleteModel(
            name='KYCPlan',
        ),
        migrations.DeleteModel(
            name='KYCSubscription',
        ),
        migrations.DeleteModel(
            name='KYCUsageRecord',
        ),
        migrations.DeleteModel(
            name='LivenessCheck',
        ),
        migrations.DeleteModel(
            name='PEPSanctionsScreening',
        ),
        migrations.DeleteModel(
            name='SandboxConfig',
        ),
        migrations.DeleteModel(
            name='TransactionMonitoringRule',
        ),
        migrations.DeleteModel(
            name='VideoKYCSession',
        ),
    ]
