# Generated by Django 5.0.11 on 2026-04-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer_inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlink',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountlink',
            name='primary_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='activityheatmap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikeymanager',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklistedip',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blacklistedip',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bonuswallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='churnrecord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='churn_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='click',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='click',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clicksignature',
            name='click',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='offer_inventory.click'),
        ),
        migrations.AddField(
            model_name='commissiontier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='click',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion', to='offer_inventory.click'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversionreversal',
            name='conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversal', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='conversionreversal',
            name='reversed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversion',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.conversionstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together={('from_currency', 'to_currency')},
        ),
        migrations.AddField(
            model_name='dailystat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directadvertiser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='offer_inventory.directadvertiser'),
        ),
        migrations.AddField(
            model_name='dspconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='duplicateconversionfilter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudattempt',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='offer_inventory.fraudrule'),
        ),
        migrations.AddField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incentivelevel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='offer_inventory.directadvertiser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leadqualityscore',
            name='conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='loyaltylevel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='maintenancemode',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancemode',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='masterswitch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='masterswitch',
            name='toggled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_switches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='impression',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='duplicateconversionfilter',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_filters', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='click',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='bidlog',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_logs', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offercap',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caps', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offercategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offer_inventory.offercategory'),
        ),
        migrations.AddField(
            model_name='offercreative',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerdraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerinventorysource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerlandingpage',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offernetwork',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerinventorysource',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='offer_inventory.offernetwork'),
        ),
        migrations.AddField(
            model_name='offer',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offer_inventory.offernetwork'),
        ),
        migrations.AddField(
            model_name='networkstat',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='offer_inventory.offernetwork'),
        ),
        migrations.AddField(
            model_name='networkpinger',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='offer_inventory.offernetwork'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='offer_inventory.offernetwork'),
        ),
        migrations.AddField(
            model_name='offerquestionnaire',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerrating',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerschedule',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offertag',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='tags', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offervisibilityrule',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='offerwallconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['endpoint', 'recorded_at'], name='offer_inven_endpoin_17e05f_idx'),
        ),
        migrations.AddField(
            model_name='pixellog',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixel_logs', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postback_logs', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='publisherapp',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='offer_inventory.publisher'),
        ),
        migrations.AddField(
            model_name='appplacement',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='offer_inventory.publisherapp'),
        ),
        migrations.AddField(
            model_name='publisherpayout',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='offer_inventory.publisher'),
        ),
        migrations.AddField(
            model_name='publisherrevenue',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.publisherapp'),
        ),
        migrations.AddField(
            model_name='publisherrevenue',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='offer_inventory.publisher'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_inventory_rate_limit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redirectlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_inventory_redirect_logs', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referred_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='original_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueshare',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to='offer_inventory.conversion'),
        ),
        migrations.AddField(
            model_name='revenueshare',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_shares', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='s2srequest',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s2s_requests', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='smart_links', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='smartlink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='redirectlog',
            name='smart_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_inventory_redirect_logs', to='offer_inventory.smartlink'),
        ),
        migrations.AddField(
            model_name='subid',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ids', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='subid',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='click',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='offer_inventory.subid'),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingdomain',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='click',
            name='tracking_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.trackingdomain'),
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='click',
            name='traffic_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_inventory.trafficsource'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer_inventory.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='users_earned',
            field=models.ManyToManyField(blank=True, through='offer_inventory.UserAchievement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='offer_inventory.offer'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='offer_inventory.offercategory'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_pref', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='offer_inventory.loyaltylevel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='referred',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_referral_referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userriskprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userriskprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersegment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='walletaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='offer_inventory.paymentmethod'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='offer_inventory.payoutbatch'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountlink',
            unique_together={('primary_user', 'linked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='activityheatmap',
            unique_together={('user', 'day_of_week', 'hour_of_day')},
        ),
        migrations.AlterUniqueTogether(
            name='apikeymanager',
            unique_together={('tenant', 'service', 'key_name')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'model_name'], name='offer_inven_action_fbd6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='offer_inven_user_id_dd59e8_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedip',
            index=models.Index(fields=['ip_address', 'expires_at'], name='offer_inven_ip_addr_8fe841_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystat',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['fingerprint'], name='offer_inven_fingerp_095a96_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['level', 'is_resolved'], name='offer_inven_level_985b57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterswitch',
            unique_together={('tenant', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='duplicateconversionfilter',
            unique_together={('offer', 'user', 'fingerprint')},
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user'], name='conv_user_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['offer'], name='conv_offer_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['transaction_id'], name='conv_txid_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user', 'offer', 'created_at'], name='conv_user_offer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['status', 'postback_sent'], name='conv_status_postback_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['status', 'created_at'], name='conv_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['is_duplicate', 'created_at'], name='conv_dup_date_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['approved_at'], name='conv_approved_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.UniqueConstraint(condition=models.Q(('click__isnull', False)), fields=('click',), name='unique_conversion_per_click'),
        ),
        migrations.AddIndex(
            model_name='bidlog',
            index=models.Index(fields=['publisher_id', 'created_at'], name='offer_inven_publish_b01e54_idx'),
        ),
        migrations.AddIndex(
            model_name='bidlog',
            index=models.Index(fields=['is_won', 'created_at'], name='offer_inven_is_won_cce5ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offercap',
            unique_together={('offer', 'cap_type')},
        ),
        migrations.AddIndex(
            model_name='offerinventorysource',
            index=models.Index(fields=['network', 'is_enabled'], name='source_network_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'expires_at'], name='offer_inven_status_7f6caf_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['network', 'status'], name='offer_inven_network_da09c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkstat',
            unique_together={('network', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='offerrating',
            unique_together={('offer', 'user')},
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['status', 'api_key'], name='offer_inven_status_0260ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publisherapp',
            unique_together={('publisher', 'bundle_id', 'platform')},
        ),
        migrations.AddIndex(
            model_name='publisherpayout',
            index=models.Index(fields=['publisher', 'status'], name='offer_inven_publish_d0d223_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publisherrevenue',
            unique_together={('publisher', 'app', 'date')},
        ),
        migrations.AddIndex(
            model_name='subid',
            index=models.Index(fields=['s1', 'offer'], name='offer_inven_s1_6d93c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['click_token'], name='click_token_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['user'], name='click_user_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['offer'], name='click_offer_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address'], name='click_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['user', 'offer', 'created_at'], name='click_user_offer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address', 'offer', 'created_at'], name='click_ip_offer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['is_fraud', 'created_at'], name='click_fraud_date_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['converted', 'created_at'], name='click_converted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['country_code', 'created_at'], name='click_country_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['status', 'feedback_type'], name='offer_inven_status_a0358e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'category')},
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', 'tx_type', 'created_at'], name='offer_inven_user_id_ff4fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='offer_inven_user_id_984fb2_idx'),
        ),
    ]
