# Generated by Django 5.0.11 on 2026-04-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectlog',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_inventory_redirect_logs', to='offer_inventory.offer'),
        ),
        migrations.AlterField(
            model_name='redirectlog',
            name='smart_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_inventory_redirect_logs', to='offer_inventory.smartlink'),
        ),
    ]
