# Generated by Django 5.0.11 on 2026-04-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_action_model_name_1179',
            old_name='offer_inven_action_fbd6ad_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_user_created_at_1180',
            old_name='offer_inven_user_id_dd59e8_idx',
        ),
        migrations.RenameIndex(
            model_name='bidlog',
            new_name='idx_publisher_id_created_at_1182',
            old_name='offer_inven_publish_b01e54_idx',
        ),
        migrations.RenameIndex(
            model_name='bidlog',
            new_name='idx_is_won_created_at_1183',
            old_name='offer_inven_is_won_cce5ce_idx',
        ),
        migrations.RenameIndex(
            model_name='blacklistedip',
            new_name='idx_ip_address_expires_at_1173',
            old_name='offer_inven_ip_addr_8fe841_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='idx_fingerprint_1174',
            old_name='offer_inven_fingerp_095a96_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='idx_level_is_resolved_1178',
            old_name='offer_inven_level_985b57_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_status_expires_at_1170',
            old_name='offer_inven_status_7f6caf_idx',
        ),
        migrations.RenameIndex(
            model_name='offer',
            new_name='idx_network_status_1171',
            old_name='offer_inven_network_da09c0_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='idx_endpoint_recorded_at_1181',
            old_name='offer_inven_endpoin_17e05f_idx',
        ),
        migrations.RenameIndex(
            model_name='publisher',
            new_name='idx_status_api_key_1184',
            old_name='offer_inven_status_0260ac_idx',
        ),
        migrations.RenameIndex(
            model_name='publisherpayout',
            new_name='idx_publisher_status_1185',
            old_name='offer_inven_publish_d0d223_idx',
        ),
        migrations.RenameIndex(
            model_name='subid',
            new_name='idx_s1_offer_1172',
            old_name='offer_inven_s1_6d93c1_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='idx_status_feedback_type_1177',
            old_name='offer_inven_status_a0358e_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='idx_user_tx_type_created_at_1176',
            old_name='offer_inven_user_id_ff4fd6_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='idx_user_status_created_at_1175',
            old_name='offer_inven_user_id_984fb2_idx',
        ),
    ]
