# Generated by Django 5.0.11 on 2026-04-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_inventory', '0003_rename_offer_inven_action_fbd6ad_idx_idx_action_model_name_1179_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bidlog',
            new_name='idx_publisher_id_created_a_351',
            old_name='idx_publisher_id_created_at_1182',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='idx_user_tx_type_created_a_d55',
            old_name='idx_user_tx_type_created_at_1176',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='idx_user_status_created_at_b05',
            old_name='idx_user_status_created_at_1175',
        ),
    ]
